### ISSUE TITLE
能不能减少刷新

### ISSUE THREAD

**Issue by lxs-ol** [gitbobobo/StreamMusic#100]
每次打开软件都得刷新半天。这功能完全可以设置手动。如果歌曲少还好些。几万首歌曲的时候打开半天啥也干不了。

**Comment by 634225920** [comment]
附议

**Comment by gitbobobo** [comment]
等完全刷新好再退出，下次启动只要歌曲数量不变就不会重刷了

**Comment by n3taway** [comment]
建议加一个手动配置，歌多了刷新时间比较久

**Comment by gitbobobo** [comment]
下个版本自动同步试试采用增量同步的方式，应该会缓解一些

**Comment by gitbobobo** [comment]
1.2.1的自动同步已改为增量更新
