### ISSUE TITLE
Macos 进度条不动

### ISSUE THREAD

**Issue by 1013461195** [gitbobobo/StreamMusic#101]
Macos版本Monterey 12.7.1 (21G920)
软件版本 1.1.10(24)
播放音乐时能听到音乐，进度条卡住不动
![截屏2023-12-21 15 31 48](https://github.com/gitbobobo/StreamMusic/assets/23392657/1100f6ac-40a7-420c-ab38-451f12997117)

**Comment by gitbobobo** [comment]
看下文件格式，部分不支持的格式如果转码会出现这个问题
