### ISSUE TITLE
iOS客户端bug反馈

### ISSUE THREAD

**Issue by sanan2015** [gitbobobo/StreamMusic#102]
连接jellyfin，开启了边听边存
从昨天开始用
中间遇到这些bug：
1、昨天有一段时间没有显示专辑，今天打开有了
2、播放时没有显示音乐的播放时长，拖动进度条无效（可能是转码或者本地音乐，出现后不会恢复）
3、创建歌单添加到歌单后，偶现app黑屏，可以尝试多点几下能不能复现，黑屏时播放音乐正常，要恢复只能强杀0
4、多次闪退
5、歌词加载不到，无法搜索

**Comment by sanan2015** [comment]
总体来说app挺不错
界面和播放使用都挺不错的，动效时间可以短一点

作者加油，希望能做的更稳定
付费上，希望能把歌词服务作为付费项，我会付费

**Comment by gitbobobo** [comment]
目前app是还不太稳定

歌词服务可能会牵涉到版权问题，建议自己部署，目前已经有可用的开源项目了

**Comment by gitbobobo** [comment]
1.2.8已修复
