### ISSUE TITLE
安卓iOS客户端 播放m3u wav格式专辑

### ISSUE THREAD

**Issue by xiejia518** [gitbobobo/StreamMusic#103]
有进度条，无声音，需要转码
才能播放。iPhone Vivo跟小米手机都试过

**Comment by gitbobobo** [comment]
歌曲是整轨的吗？整轨应该是不支持的

**Comment by jayxuz** [comment]
> 歌曲是整轨的吗？整轨应该是不支持的
m3u+wav整轨格式 安卓有同样现象。

希望能够针对这个情况出一个选项开关或者写成整轨wav 默认转码策略
因为目前如果选择无损（不转码）的情况下，随机到整轨wav就会出现无声音。只能全局设置成转码才不会影响播放。
但是很多时候我也希望能够离线更多的无损音乐，不想设置成全局转码

**Comment by gitbobobo** [comment]
1.2.8已更换新的播放插件，可以再看看这样的问题还会不会出现。

**Comment by jayxuz** [comment]
> 1.2.8已更换新的播放插件，可以再看看这样的问题还会不会出现。

目前问题已解决，音流yyds
