### ISSUE TITLE
iOS问题反馈--NAS死机

### ISSUE THREAD

**Issue by ha0719** [gitbobobo/StreamMusic#104]
iOS在app store安装的最新版本，用了2天，其中有2次直接造成NAS死机，局域网和公网都无法访问，只能重新启动，不确定是否和音乐转码相关，作者如果需要查看什么日志，可以告诉我方法。
另外我也遇到了一些其他小问题，诸如：
1、正常播放几首歌之后，有进度条在走，没声音；
2、播放一会，app不确定是崩溃还是退出了；

总之，瑕不掩瑜，希望作者好好维护，期望一个安卓版发布，肯定会买一个支持。

**Comment by gitbobobo** [comment]
如果是在扫描歌曲期间导致的 NAS 死机就不是转码导致的，可以在音质里都改成无损看看还有没有问题（我的NAS感觉已经很残废了，运行了很多软件还没遇到过死机。。。）

后台播放时，可能会被其他app的视频广告打断，除此之外我还没遇到过音乐停止的问题。

**Comment by sanan2015** [comment]
> 如果是在扫描歌曲期间导致的 NAS 死机就不是转码导致的，可以在音质里都改成无损看看还有没有问题（我的NAS感觉已经很残废了，运行了很多软件还没遇到过死机。。。）
> 
> 后台播放时，可能会被其他app的视频广告打断，除此之外我还没遇到过音乐停止的问题。

我用Jellyfin，iOS很容易停止。
特别是网络切换，wifi到移动网络应该可以复现。除此之外，还有很多种情况自动停止。
自动停止后而且再也无法播放，只能杀掉进程重启，重启就一切正常。频率，一天可以遇到十几次。

**Comment by ha0719** [comment]
> 如果是在扫描歌曲期间导致的 NAS 死机就不是转码导致的，可以在音质里都改成无损看看还有没有问题（我的NAS感觉已经很残废了，运行了很多软件还没遇到过死机。。。）
> 
> 后台播放时，可能会被其他app的视频广告打断，除此之外我还没遇到过音乐停止的问题。

不是扫描的时候，现在就是怀疑转码导致的，群晖DS220+，MAC开了一段时间无损没发现问题。等放假在家，我再试试
