### ISSUE TITLE
[功能建议] 播放列表加个标记表示歌曲已缓存

### ISSUE THREAD

**Issue by BenzLeung** [gitbobobo/StreamMusic#106]
1. 播放列表的歌名右侧加个图标，标记歌曲是否已经缓存或已经下载，已缓存或已下载的，播放不再消耗流量。
2. 正在下载的，用小字的百分比展示下载进度。
3. 正在播放时，提前缓存接下来的n首歌曲，默认值n=3吧。
4. 正在播放的弹出列表，样式可以统一跟大列表一样，并且每一行右侧的x改成三点按钮。

参考另一个subsonic播放器（这界面比较丑，不要向这界面学习太多，那个右侧图标可以找找有没有“下载+对勾”的更好看的图标）

![IMG_20231229_073920](https://github.com/gitbobobo/StreamMusic/assets/2764768/aed9c799-5fc3-4552-ad34-8c67d6e814fa)

**Comment by gitbobobo** [comment]
嗯嗯，下个版本打算做提前缓存的功能，已下载的会有绿色对勾显示的，怕消耗流量感觉直接去本地音乐列表播放就好了

**Comment by BenzLeung** [comment]
倒不是怕消耗流量。只是觉得已经缓存了的歌曲就没必要再下载一遍了。应用场景也很常见——乘坐高铁的时候，网络不稳定，高铁钻进隧道就没有信号了，所以在进隧道之前提前缓存3-5首，避免播放中断。
