### ISSUE TITLE
【建议】使用预下载提升连续播放的流畅度

### ISSUE THREAD

**Issue by wanyunr** [gitbobobo/StreamMusic#108]
每换一首歌都要加载5-10秒，是否可以提前缓存下一首个来提升连续听歌流畅性。
（服务器宽带可以跑到单线程50M以上，歌舞都是HD，10MB左右）
软件版本：Android最新版 1.2.0
服务端：Navidrome

**Comment by gitbobobo** [comment]
重复问题，目前正在开发
#58
