### ISSUE TITLE
ios客户端使用dlna无法播放

### ISSUE THREAD

**Issue by yu929** [gitbobobo/StreamMusic#109]
版本：ios 1.2.0
服务端：群晖DS 7.1

使用dlna输出到雅马哈V6A功放进行播放，无法播放，ios端播放进度一直在0秒到1秒，然后又0秒到1秒循环。使用手机输出没有问题，用群晖的DS AUDIO dlna到功放也是正常的

**Comment by yu929** [comment]
![微信图片_20240102234819](https://github.com/gitbobobo/StreamMusic/assets/36434225/8ef49656-e96b-4f3b-9bde-bf4104656e05)
附上日志，返回了415

**Comment by gitbobobo** [comment]
1.3.1已修复dlna功能，可以试下是否有效
