### ISSUE TITLE
安卓客户端下载列表侧滑返回会退到手机主界面

### ISSUE THREAD

**Issue by realx1n** [gitbobobo/StreamMusic#112]
安卓客户端下载列表侧滑返回会退到手机主界面，正常逻辑应该是返回上一层界面

https://github.com/gitbobobo/StreamMusic/assets/25891244/ca11449f-e86f-4410-8fab-0d6846d5e4f0

**Comment by realx1n** [comment]
歌单和播放界面偶尔也会直接返回主界面，但是没有稳定复现

**Comment by gitbobobo** [comment]
1.2.1已修复

**Comment by realx1n** [comment]
安卓最新版又出现了同样的问题
