### ISSUE TITLE
Artist Listing Bug with Navidrome v0.50.2

### ISSUE THREAD

**Issue by s3rverro0m** [gitbobobo/StreamMusic#114]
Hi there! I found your app a few days ago and I am so excited to use it because it's really well made and beautiful. I linked Navidrome to it and I noticed an Artist bug. Here's an example:

Duke Dumont on Stream Music shows no albums:
![image](https://github.com/gitbobobo/StreamMusic/assets/46236585/a455aee5-7bb1-4899-afa4-a5b3521b1dbe)

But on the Navidrome website, I see an album:
![image](https://github.com/gitbobobo/StreamMusic/assets/46236585/90592ea2-5472-4ed5-b3c6-f3c0a800a79a)

If I search for the album in Stream Music, it shows up:
![image](https://github.com/gitbobobo/StreamMusic/assets/46236585/c1bce13b-6f7a-491d-b2e1-55b93ce1edf9)

This happens with a bunch of different artists. I also apologize if this bug has been mentioned already!

**Comment by gitbobobo** [comment]
Thank you for your feedback. The next version will support the `AlbumArtist` tag.

**Comment by s3rverro0m** [comment]
> Thank you for your feedback. The next version will support the `AlbumArtist` tag.
> 
> 

Amazing! Thank you so much.

**Comment by gitbobobo** [comment]
updated

**Comment by s3rverro0m** [comment]
> updated

This looks great, thank you!
