### ISSUE TITLE
希望提供“专辑艺术家”页面作为"歌手"页面来源的选项 而非仅仅只有"艺术家"作为“歌手”页面来源 (emby 服务器)

### ISSUE THREAD

**Issue by oreme2** [gitbobobo/StreamMusic#116]
似乎基于subsonic的服务器不支持"专辑艺术家" 页面；
但是emby是支持这一页面的显示。
而且现代音乐数据库网站 musicbranz vgmdb rym discogs tadb；
一般也是基于专辑艺术家进行分类。
因为大量的拼盘专辑和feat.艺术家存在可能使得"艺术家"页面过于杂乱。

**Comment by oreme2** [comment]
总体体验很好
使用过程中的几个小问题
专辑显示了封面
但专辑内部页面不显示封面
![image](https://github.com/gitbobobo/StreamMusic/assets/38098761/b58bf689-8b1a-4e80-a924-732407d22f96)

![image](https://github.com/gitbobobo/StreamMusic/assets/38098761/c25076e4-d215-474f-95aa-e33be8176a4d)

**Comment by oreme2** [comment]
emby自己创建的歌单，和m3u歌单都无法显示
![image](https://github.com/gitbobobo/StreamMusic/assets/38098761/481f9849-1b74-4a2f-9208-6dfdafc67343)

**Comment by gitbobobo** [comment]
歌曲列表页面的专辑图片不显示是因为查询的是第一首歌曲的封面，此问题在1.2.7改为统一查询专辑封面
