### ISSUE TITLE
[PC端]播放列表按顺序播放完最后一首歌后，软件崩溃关闭。

### ISSUE THREAD

**Issue by wxnode** [gitbobobo/StreamMusic#120]
我连接的自建的navidrome，用的最新版1.2.0
我试过随机专辑，或者我的最爱列表，只要播放完最后一首歌后，软件就自动关闭了。
并且播放歌曲列表时，一首歌播放完了不会自动切到下一首，如下图我已经等了几分钟了，必须手动切换才行。也是好像各种列表都有这个问题。
![屏幕截图 2024-01-12 195654](https://github.com/gitbobobo/StreamMusic/assets/4097168/236afad5-4d0e-4b16-a3ef-c80bb82c2a90)

**Comment by gitbobobo** [comment]
1.2.1已处理
