### ISSUE TITLE
【DLNA】设备征集

### ISSUE THREAD

**Issue by gitbobobo** [gitbobobo/StreamMusic#123]
目前收到一些用户反馈 DLNA 功能无法正常使用，因此想问问大家正在用的 DLNA 设备是什么，我想看看哪些设备用的人比较多，我买回来两三台用于测试（当然，不要太贵~）

我自己用的是小爱音箱pro。

如果你在使用 DLNA 功能时遇到问题，可以留下你的设备型号，遇到的问题是什么。

如果你用的设备型号已经有人发了，可以点个赞让我看到数量。

**Comment by 15823382203** [comment]
惠威M80W.无法搜索到音箱。偶尔搜索到了但只能正常播放一首歌下一首就自动异常了然后一直跳下一首

**Comment by 15823382203** [comment]
有时候莫名奇妙的搜索到了音箱但无法正常投屏，一直卡在那2秒循环播放但也没声音，也无法暂停。必须切换成本机输出声音才正常。大多数时候连音箱都搜索不出来。但网易云能搜索出并且正常投屏。

**Comment by yu929** [comment]
雅马哈的RX-V6A功放，具体表现在这个issue里：https://github.com/gitbobobo/StreamMusic/issues/109#issue-2062461643

**Comment by littlebabay** [comment]
小爱音响

**Comment by JoonKwan** [comment]
iPhone， v1.2.8， dlna 可以找到设备但选择后音乐暂停，dlna设备选择不成功。

dlna设备为：高登小夜曲。

**Comment by BlackskinLee** [comment]
音响：HUAWEI Sound X
无法链接，AIRPLAY/DLNA/UPNP 播放器。

车机Carplay，无法显示歌词，希望能改进。

**Comment by lianzhaowen** [comment]
马兰士 model 40n🤣

**Comment by szpw64** [comment]
小爱音箱pro能支持吗？我的设备是小爱音响pro，型号是LX06，在ios和mac os上试过多次找不到设备。
