### ISSUE TITLE
专辑 Albums No Data

### ISSUE THREAD

**Issue by jibwf** [gitbobobo/StreamMusic#124]
Backend: Jellyfin 10.8.13
StreamMusic: 1.2.1

Jellyfin Web里面是可以显示专辑的.
![image](https://github.com/gitbobobo/StreamMusic/assets/65640470/728dcc8d-f867-4483-ba94-1373bc96c6fb)

音流可以显示歌手，但是专辑提示没有数据。

**Comment by gitbobobo** [comment]
是全部专辑里没有数据还是某个歌手里面没有专辑数据

**Comment by jibwf** [comment]
> 是全部专辑里没有数据还是某个歌手里面没有专辑数据

全部都没有数据。首页点进去，专辑然后就是空的.
![image](https://github.com/gitbobobo/StreamMusic/assets/65640470/ec5baf31-21d2-4486-b78e-6fbb01b2be6f)

**Comment by gitbobobo** [comment]
可以邮箱或QQ群私发我一个测试账号，我看看什么原因导致的

**Comment by gitbobobo** [comment]
1.2.2已修复
