### ISSUE TITLE
【BUG】文件夹功能，显示了不存在的文件夹

### ISSUE THREAD

**Issue by happyostar** [gitbobobo/StreamMusic#125]
登录的群晖的Audio  station ，关闭了共享音乐，只保留了个人文件夹的音乐。

![IMG_1213](https://github.com/gitbobobo/StreamMusic/assets/70873293/3340ded4-a3ff-4f04-8b83-56b8ba1cbabe)

文件夹功能，除了显示我的个人文件夹，还显示了一个「镜像」，但是这个文件夹在我的NAS 中根本不存在。但是点进去，目录和文件都是镜像出了一份，不显示歌曲封面，最后点击无法播放，因为根本就不存在那个目录。

不明白为什么凭空多出一个目录，而且在我没有开通会员功能的时候，这个目录也有，因为我搜索歌曲的时候，会凭空多出来一些镜像，导致本来一首歌，都显示成两首歌，但是这些镜像无法播放，因为路径错误。

我退出账号，重新登录，重新同步数据库也不行。

**Comment by qhly2010** [comment]
同样遇到这个问题了，安卓端1.2.1版本出现多余的文件夹

**Comment by gitbobobo** [comment]
看着目录名是有区别的，是不是另一个是共享文件夹的目录

**Comment by happyostar** [comment]
> 查看目录名是有区别的，不是另一个是共享文件夹的目录

不是另外的目录，NAS中没有这个目录。

jmusics-1000012是我的用户名，AudioStation是读取这个用户的个人目录home中music的文件夹。

印象中是修改过用户名（出现jmusic-1000012可能是因为我创建这个用户的时候写的是jmusic，后来改成了jmusics。而群晖套件的数据库可能存在问题。）

**Comment by gitbobobo** [comment]
如果清除数据后登录还有这个问题，可以邮箱或QQ群私发我一个测试账号，目前猜测可能是失效的歌曲文件导致的
