### ISSUE TITLE
安卓客户端 点击歌词里面 LRC 后 之后返回会直接到系统桌面。重启客户端才行

### ISSUE THREAD

**Issue by benefit6** [gitbobobo/StreamMusic#126]
安卓客户端 点击歌词里面 LRC 后 之后返回会直接到系统桌面。重启客户端才行

音流版本： 1.2.1
设备： 小米10Pro
系统：miui14.0.4
安卓版本： 安卓13

**Comment by gitbobobo** [comment]
估计是上个版本调整返回键逻辑时漏掉了，

临时解决方案：进一个新的页面，这样就不用重启app了

**Comment by gitbobobo** [comment]
1.2.4已处理
