### ISSUE TITLE
安卓客户端1.2.1，随机播放bug

### ISSUE THREAD

**Issue by realx1n** [gitbobobo/StreamMusic#127]
随机播放，播放完一首歌切到下一首时中间会插入另一首歌的1秒钟前奏，往回且上一首歌是正常原来的歌曲，偶发性问题，无法稳定复现
歌曲已经全部下载到本地，主路线是内网，备用路线是公域名

**Comment by gitbobobo** [comment]
嗯嗯，我iOS也遇到了

**Comment by VantStark** [comment]
同安卓也遇到了，出现频率很高

**Comment by gitbobobo** [comment]
1.2.2已修复
