### ISSUE TITLE
希望可以调整播放列表内歌曲的播放顺序

### ISSUE THREAD

**Issue by Grosser-Kurfuerst** [gitbobobo/StreamMusic#128]
1. 目前无法调整播放列表内歌曲的播放顺序，希望后续版本可以支持
2. 此外，当前播放歌曲所在歌单内的所有歌曲无法设置为”下一首播放“ ，或许与1中功能有关？

**Comment by happyostar** [comment]
现在按文件名排序，数字1之后就是数字10，而不是数字2。

**Comment by 973685007** [comment]
![a1bb7c8ec7693b5b5f1772baf18724ce](https://github.com/gitbobobo/StreamMusic/assets/42867237/38f55468-9217-45bf-865f-8b5fa4d566fd)
排序不对，盼望大佬早日更新

**Comment by gitbobobo** [comment]
1.2.2按标题排序已经可以正确识别里面的数字了，播放队列中的播放顺序因为现有的逻辑并不好做动态调整的功能
