### ISSUE TITLE
[Bug反馈] 平板端ui问题

### ISSUE THREAD

**Issue by Tartarus2014** [gitbobobo/StreamMusic#129]
在安卓平板端，竖屏状态下，图标错位，跑进状态栏那了。
设备 三星tab s9
![Screenshot_20240118_000646_Stream Music](https://github.com/gitbobobo/StreamMusic/assets/39802246/51b7161c-430e-434c-b331-e472bd7ebb80)

**Comment by gitbobobo** [comment]
呀，漏掉了😭
