### ISSUE TITLE
【BUG】Windows客户端登录后依然显示离线模式，离线模式关闭也不行

### ISSUE THREAD

**Issue by happyostar** [gitbobobo/StreamMusic#130]
系统：win10
使用方式：直接解压msix运行，不用安装证书
登录：群晖 Audio Station

一开始正常运行的，买了会员之后通过邮箱验证码登上会员了。

过一天重新使用时，发现会员退出了，文件夹功能不可用。

于是又通过邮箱验证码登录。登录后，Win版客户端就不灵了，模式一直显示离线模式。（是否是会员win设备数量超限了？）

![image](https://github.com/gitbobobo/StreamMusic/assets/70873293/3830f5d7-d295-4b76-b1dc-03c50d09970f)

尝试故障排除：

- 重新登录无效。
- 打开离线模式，再关闭离线模式也无效。
- 删除解压后的程序，重新解压运行，也无效。因为发现数据库不在安装目录中，所以仅仅删除主程序并不能起到卸载的效果。（此处需要提供卸载程序，从主程序上查看到数据库什么的占用空间还挺大的，有3GB）

![image](https://github.com/gitbobobo/StreamMusic/assets/70873293/68df2a89-f47f-4d1c-9f34-04c51cfeddd7)

还需要提供会员从设备上登出的功能，因为有数量限制，一开始没有规划好在哪台设备上使用，就登录了。
或者出现关电脑后自动退出了会员的情况。
主要是不清楚怎么就算是减掉了1台设备，关闭软件算是减掉设备吗？

**Comment by gitbobobo** [comment]
新设备激活会员会自动踢掉旧设备的（如果超过数量限制的话）。

离线模式应该是软件bug，等30秒左右看看能否连接上
