### ISSUE TITLE
[BUG] 安卓端更改下载位置会导致下载失败

### ISSUE THREAD

**Issue by Grosser-Kurfuerst** [gitbobobo/StreamMusic#131]
- 设备：飞傲m11plus
- 安卓版本：10
- 音流版本：1.2.1
- 复现情况：总是
更改下载位置后可以正常加入下载队列，数秒后提示下载失败，使用默认位置（Android/data/cn.aqzscn.stream_music）则不存在此问题     
已授予文件相关权限，网络环境正常
   
或许与安卓版本有关？希望对hifi播放器这类安卓版本可能较低的设备进行支持

**Comment by gitbobobo** [comment]
1.2.3版本加入存储权限请求，可以试试看有没有用

**Comment by LamberMa** [comment]
更改下载位置是付费版的功能么？免费版我没找到呢。。
