### ISSUE TITLE
【BUG】Windows下窗口大小切换后歌词显示异常

### ISSUE THREAD

**Issue by DogeCA** [gitbobobo/StreamMusic#132]
问题复现方式：小窗口情况下，双击标题栏后拉长窗口，再双击回小窗后歌词界面变成专辑封面，点击上方的推荐来回切换一次后恢复正常。
软件版本：1.2.1
不是什么大问题，就是单纯发现了上来写个issue
![QQ截图20240118160608](https://github.com/gitbobobo/StreamMusic/assets/93893655/2335a5e8-9f07-4b6b-81fc-ca0738d8fd8f)
![QQ截图20240118160621](https://github.com/gitbobobo/StreamMusic/assets/93893655/50e5276e-e354-42c6-bef5-7202983ad204)
![QQ截图20240118160645](https://github.com/gitbobobo/StreamMusic/assets/93893655/27c09138-89a1-46fe-940d-b14ae9b239e4)

**Comment by gitbobobo** [comment]
1.2.6 使用了新的正在播放界面，因此这个问题将不会存在
