### ISSUE TITLE
专辑内空白

### ISSUE THREAD

**Issue by twister3344** [gitbobobo/StreamMusic#134]
服务器是AudioStation，音流上有一些专辑，外面显示是正常的专辑图片，点进去一首歌也没有，图片也变成了相同的图片。
![Screenshot_20240119_183328_cn aqzscn stream_music](https://github.com/gitbobobo/StreamMusic/assets/41074297/8dc9421f-dc08-4bdb-9f48-0df92bef932a)

**Comment by twister3344** [comment]
![Uploading Screenshot_20240120_000652_cn.aqzscn.stream_music.jpg…]()

**Comment by twister3344** [comment]
![Screenshot_20240120_000652_cn aqzscn stream_music](https://github.com/gitbobobo/StreamMusic/assets/41074297/a1e50cd1-f0f0-4fd0-b113-35e7c8beb9dc)

**Comment by twister3344** [comment]
从播放页面点进专辑，就是正常显示的
![Screenshot_20240120_001710_cn aqzscn stream_music_edit_11470793874008](https://github.com/gitbobobo/StreamMusic/assets/41074297/afc444df-8109-405c-b02d-4b7e53f3d1f4)

**Comment by twister3344** [comment]
已解决：专辑艺术家 标签留空，或与 艺术家 标签一致

**Comment by gitbobobo** [comment]
额，这应该算bug，找到原因了就好修复了
