### ISSUE TITLE
Navidrome 更新到 0.51.0 之后无法连接

### ISSUE THREAD

**Issue by 1wingedangel** [gitbobobo/StreamMusic#135]
IOS 客户端（1.2.1） 在 navidrome 更新到 0.51.0 之后同步无法完成。
无论主线路还是备用线路。点击同步时后台显示两个任务。
任务1 提示 正在同步歌曲数据(0)
任务2 提示 加载数据中…
navidrome服务器正常，可从桌面以及手机的浏览器直接访问并播放音乐。

**Comment by gitbobobo** [comment]
下个版本修复

**Comment by zhang080202** [comment]
原来是版本问题，我一直以为我设置不对，然后降一个版本就好了

**Comment by gitbobobo** [comment]
新版本已发布，更新后手动同步数据即可恢复
