### ISSUE TITLE
歌单内的歌曲已经缓存下载过了，每次播放还会去下载。

### ISSUE THREAD

**Issue by zjzheng666** [gitbobobo/StreamMusic#139]
如题，之前歌单内的歌曲都进行缓存过了，但每次播放都会下载。
![微信图片_20240124111619](https://github.com/gitbobobo/StreamMusic/assets/63964493/7f5242c3-d4ee-4b73-87f1-c4687511ea5e)
![微信图片_20240124111623](https://github.com/gitbobobo/StreamMusic/assets/63964493/58dc36f8-05c6-48ca-ae01-14439b93db11)

**Comment by gitbobobo** [comment]
这是软件内部的代理的网速，你可以关掉网络，看是否还有网速，和歌曲能否播放

**Comment by zjzheng666** [comment]
> 这是软件内部的代理的网速，你可以关掉网络，看是否还有网速，和歌曲能否播放
