### ISSUE TITLE
iOS Subsonic not loading songs

### ISSUE THREAD

**Issue by martinse93** [gitbobobo/StreamMusic#143]
Hello! I am using StreamMusic on iOS with Subsonic. When I sign in all of the albums, playlists, etc are there but StreamMusic isnt picking up any songs or folders. I purchased the upgrade to try to go into the settings for server URL but that wasn't able to resolve it. Currently using Play:Sub which works but the UI isn't nearly as good as StreamMusic, I would love to be able to switch to your app. Any ideas on what might be the issue?

【本文是谷歌翻译，如有翻译如有异常，敬请谅解。】

你好！ 我在 iOS 上使用 StreamMusic 和 Subsonic。 当我登录时，所有专辑、播放列表等都在那里，但 StreamMusic 没有拾取任何歌曲或文件夹。 我购买了升级程序，尝试进入服务器 URL 的设置，但无法解决该问题。 目前使用 Play:Sub 可以工作，但 UI 不如 StreamMusic，我希望能够切换到您的应用程序。 关于可能出现的问题有什么想法吗？

![unnamed](https://github.com/gitbobobo/StreamMusic/assets/157918265/e9045b34-b09f-4d98-8c20-fe45c1ebeac1)
![unnamed a](https://github.com/gitbobobo/StreamMusic/assets/157918265/08dbe7ea-103b-48e3-8d42-a6eb76fa4513)
![unnamed s](https://github.com/gitbobobo/StreamMusic/assets/157918265/bbadb8da-adb4-4e9e-a01d-b6972f762432)

**Comment by gitbobobo** [comment]
Possibly, there was an error in parsing the song data.

I conducted the testing using the Subsonic API that comes with Navidrome. You can send me a test account via email, which should help resolve the issue more quickly.

Additionally, if you need scrolling lyrics, you can consider deploying Navidrome, as it is the primary music service supported by StreamMusic at the moment.

**Comment by gfw404** [comment]
我也遇到同样问题了，只有个封面，点进去之后没有歌，一直显示正在同步歌曲数据

**Comment by gitbobobo** [comment]
> 我也遇到同样问题了，只有个封面，点进去之后没有歌，一直显示正在同步歌曲数据。我用的是Navidrome 用DS Player就没有问题 应该不是服务器的问题

目前不兼容navi0.51，新版本已经提交审核了，等通过后重新同步下数据就可以了

**Comment by xhongc** [comment]
同样我也遇到这个问题
测试环境：mac 版本 1.2.4 和 android 1.2.3
使用 subsonic 接口协议
![image](https://github.com/gitbobobo/StreamMusic/assets/29135056/51d7a4ca-232d-43e3-95f5-f78bc1b6d2e7)
![image](https://github.com/gitbobobo/StreamMusic/assets/29135056/2f9576e1-1a75-4c23-b635-375b17f22007)

点进去理论上要调用 /rest/getAlbum 来查询专辑下的歌曲， 我调试时候未发现接口调用
正常情况 在 sonixd 客户端中
<img width="1407" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/29135056/3260c0e7-80c1-4822-8dfe-c8474660262b">
![image](https://github.com/gitbobobo/StreamMusic/assets/29135056/20a21cd0-86e2-458e-a89e-ed6a00d38a68)
