### ISSUE TITLE
【BUG】锁屏状态下列表播放结束，解锁后无法播放歌曲。

### ISSUE THREAD

**Issue by rdminfo** [gitbobobo/StreamMusic#146]
环境：IOS15.6.1，版本：1.2.3。
复现步骤：
1.控制播放列表只有一首歌，然后点击播放。
2.等待播放结束或者手动拖动进度条至临近结束。
3.手机锁屏等待播放结束后再等待10s。
4.解锁手机，任何歌曲都无法播放。

**Comment by gitbobobo** [comment]
1.2.8已更换新的播放插件，可以再看看这样的问题还会不会出现。
