### ISSUE TITLE
希望添加对airsonic平台的适配支持

### ISSUE THREAD

**Issue by 5431** [gitbobobo/StreamMusic#148]
作者你好，subsonic的服务我用过一段时间后发现是付费软件就没再用了，转到navidrome项目使用，发现UI是好看也免费，但是没有subsonic的歌曲管理方便，如设定一些播放列表，以及编辑歌曲信息方面，后又找到了subsonic的完美兼容替代版 Airsonic，完美解决了我对音乐服务器的需求问题，但是像音流这样美观好用的客户端真是屈指可数，说了这么多是希望音流能对Airsonic做适配，目前通过subsonic接口可以登录进去歌单播放列表也都能正常加载，但是就是无法显示歌曲更不可能播放，再次感谢作者开发出音流这款优秀音乐软件。

**Comment by gitbobobo** [comment]
https://github.com/gitbobobo/StreamMusic/issues/274 可以关注此问题的进展，这个问题先关闭了哈
