### ISSUE TITLE
ios客户端链接Andiostation后无法播放歌曲

### ISSUE THREAD

**Issue by tropicaljungle** [gitbobobo/StreamMusic#149]
ios客户端链接Andiostation后，可以看到专辑和专辑歌曲，但是所有歌曲是灰色的，点击也无法播放。这种情况应当如何解决？谢谢。
![IMG_9834](https://github.com/gitbobobo/StreamMusic/assets/106308479/43e0a017-67f3-419f-bd6d-2eaab5c3a89b)

**Comment by gitbobobo** [comment]
灰色应该是app没连上服务器变为离线模式了，在内网环境可以播放吗

**Comment by tropicaljungle** [comment]
> 灰色应该是app没连上服务器变为离线模式了，在内网环境可以播放吗
我试了下还是不行，但是mac版本同样的服务器设置下，都是可以正常播放的。

**Comment by tropicaljungle** [comment]
> 灰色应该是app没连上服务器变为离线模式了，在内网环境可以播放吗

我试了下还是不行，但是mac版本都是可以正常播放

**Comment by tropicaljungle** [comment]
我安装了navidrome以后重新连接都没有出现这个问题。

**Comment by tropicaljungle** [comment]
这个问题通过更换为navidrome服务后解决
