### ISSUE TITLE
建议在歌曲信息界面新增一条本地缓存路径

### ISSUE THREAD

**Issue by YeiJ** [gitbobobo/StreamMusic#151]
建议在歌曲信息界面为已缓存歌曲新增一条本地缓存路径 并可以长按复制

**Comment by gitbobobo** [comment]
已经会显示已下载的歌曲的路径了，缓存文件在应用内的路径，有必要显示吗

**Comment by gitbobobo** [comment]
缓存文件名是一堆随机id，文件分享功能应该不会识别歌曲文件的id信息吧？

如果只是为了歌曲分享功能，过段时间会出创建歌曲链接的功能（现在没法测试全部种类的音乐服务，所以没出）

**Comment by gitbobobo** [comment]
1.3.1已添加
