### ISSUE TITLE
希望音流可以支持Last.FM音乐播放记录

### ISSUE THREAD

**Issue by MATRIX06060** [gitbobobo/StreamMusic#152]
第一次遇到像音流一样这样好看干净的音乐软件，用了十分钟就入手付费版
主要是搭配家里的Navidrome进行听歌，但是在音流里播放的时候似乎没有办法把播放状态同步到Navidrome上
那么，可不可以添加Last.FM的支持，直接通过音流把听歌记录同步到Last.FM上呢？
如果可以的话那就太好了

**Comment by gitbobobo** [comment]
音流有同步到服务器播放记录，但需要歌曲播放1/4之后才会触发

**Comment by MATRIX06060** [comment]
好的谢谢
