### ISSUE TITLE
ios下播放手机发热

### ISSUE THREAD

**Issue by xiaodaidi1** [gitbobobo/StreamMusic#153]
我的机型是iphone 12 pro
使用音流播放flac的时候手机发热严重

后端服务是emby 4.9

**Comment by gitbobobo** [comment]
是不是把边听边存关了？

**Comment by xiaodaidi1** [comment]
确实,开了边听边存就不热了
但是,我并不想要本地缓存数据啊,播放数据听完一首删一首都行...

**Comment by gitbobobo** [comment]
嗯，，，1.2.4已经改成这种逻辑了，关闭边听边存也会缓存，不过只保留最新5首
