### ISSUE TITLE
希望安卓和windows端能体现Navidrome原生的“收藏”和“排行榜”功能

### ISSUE THREAD

**Issue by 702781** [gitbobobo/StreamMusic#155]
试用2天，果断成为付费用户，感谢作者的辛勤付出。

Nas装了3种音乐服务器，决定主力使用Navidrome，搭建了歌词服务器后，音流工作的特别好。

目前希望安卓和windows端能实现Navidrome原生的“收藏”和“排行榜”功能，当前使用中是能收藏单曲，不能收藏歌手和专辑。

BTW：各前端刷新曲库比较慢，特别是第一次，我曲库有15万左右歌曲，用symfonium这个app可很快刷一遍，音流许要同步几遍最终才完成，不知道啥原因。

**Comment by gitbobobo** [comment]
后续会支持专辑和歌手收藏，navi有排行榜吗？没见过

**Comment by hahaha3542** [comment]
> 试用2天，果断成为付费用户，感谢作者的辛勤付出。
> 
> Nas装了3种音乐服务器，决定主力使用Navidrome，搭建了歌词服务器后，音流工作的特别好。
> 
> 目前希望安卓和windows端能实现Navidrome原生的“收藏”和“排行榜”功能，当前使用中是能收藏单曲，不能收藏歌手和专辑。
> 
> BTW：各前端刷新曲库比较慢，特别是第一次，我曲库有15万左右歌曲，用symfonium这个app可很快刷一遍，音流许要同步几遍最终才完成，不知道啥原因。

类似网易云的收藏歌单、专辑的显示逻辑？那玩意我也喜欢🤣🤣

**Comment by gitbobobo** [comment]
1.2.7 已支持专辑/歌手的收藏和评分功能
