### ISSUE TITLE
登录失败：请检查网络或者帐号密码是否正确

### ISSUE THREAD

**Issue by haha517** [gitbobobo/StreamMusic#156]
我用的是1.2.4的版本，在手机上登录是正常的，但在Android车机是就无法登录，我测试了sonic和navidrome两种都是这样的提示。

**Comment by 1003657663** [comment]
我也遇到了这个问题

1. 音流安卓app通过本地ip访问 audio station 和 navidrome 都没问题
2. 我通过frp穿透，配置了https 域名访问 audio station 和 navidrome 网页版都没问题
3. 但是通过音流安卓app访问https域名，audio station 和 navidrome 都提示 登录失败

**Comment by 96368a** [comment]
> 我用的是1.2.4的版本，在手机上登录是正常的，但在Android车机是就无法登录，我测试了sonic和navidrome两种都是这样的提示。

试试把端口号带上
