### ISSUE TITLE
更新1.2.4以后歌曲会播放途中，或拨动进度条时突然重新开始播放。

### ISSUE THREAD

**Issue by tropicaljungle** [gitbobobo/StreamMusic#157]
更新1.2.4以后歌曲会播放途中，或拨动进度条时突然重新开始播放。之前版本没有这个问题

**Comment by gitbobobo** [comment]
是安卓吗

**Comment by tropicaljungle** [comment]
是ios，ipados，以及macos，都有这个问题。

**Comment by gitbobobo** [comment]
那我倒是没遇到，服务端是什么？播放的时候开启转码了吗

**Comment by gitbobobo** [comment]
是不是播放队列只有一首歌时出现的这种情况？多个歌曲还会出现吗

**Comment by gyk001** [comment]
同遇到，歌曲播放到一半还没结束突然从头播放

**Comment by gyk001** [comment]
> 是不是播放队列只有一首歌时出现的这种情况？多个歌曲还会出现吗

确实是只有一首歌的情况，多个不清楚会不会有这个现象

**Comment by tropicaljungle** [comment]
> 那我倒是没遇到，服务端是什么？播放的时候开启转码了吗

服务端现在是navidrome，都是不转吗的。

**Comment by tropicaljungle** [comment]
> 是不是播放队列只有一首歌时出现的这种情况？多个歌曲还会出现吗

我尝试了一下，一首歌曲会出现。播放列表有多个歌曲时，列表的最后一首曲子出现这个问题的概率很高。

**Comment by niyoh120** [comment]
Android和MacOS都有这个问题， 使用navidrome网页播放没问题

**Comment by shelken** [comment]
ios emby端，遇到了，没播放完，突然从头开始播放

**Comment by hellolxc** [comment]
IOS客户端 服务端navidrome  设置的不转码，也是遇到这个问题了，复现几率很高

**Comment by Oman4** [comment]
近期遇到过，开车播放的时候，会有播放到中间的时候从头播放

**Comment by 635660902** [comment]
我也遇到了

**Comment by gitbobobo** [comment]
1.2.5 已修复

**Comment by niyoh120** [comment]
刚更新到1.2.5测试了一下，播放列表只有一首歌的情况下确实没问题了， 但当播放列表不止一首歌时，播放到最后一首歌还是会出现这个问题， 测试了macOS和Android版本，服务端是navidrome

**Comment by gitbobobo** [comment]
嗯嗯，是还有问题🫠

**Comment by wuyue92tree** [comment]
emby android 无转码 同样遇到

**Comment by wubinbin0403** [comment]
> 刚更新到1.2.5测试了一下，播放列表只有一首歌的情况下确实没问题了， 但当播放列表不止一首歌时，播放到最后一首歌(使用顺序播放模式)还是会出现这个问题， 测试了macOS和Android版本，服务端是navidrome

+1,测试了挺多专辑都是在最后一首歌的时候跳回开头，服务端同样是navidrome，无转码

**Comment by gitbobobo** [comment]
1.2.6应该修复了
