### ISSUE TITLE
本地歌曲缓存位置问题

### ISSUE THREAD

**Issue by as564335sa** [gitbobobo/StreamMusic#158]
现在在线歌曲保存位置是在缓存目录里吧，比如听了N首歌缓存下来，手机管家一清理垃圾，就没了，还得重新缓存，能不能调整下音乐保存的路径，放在数据目录中，可以像其他开源app一样增加一个缓存位置修改就好了

**Comment by gitbobobo** [comment]
缓存就是为了可以被删掉的吧

**Comment by as564335sa** [comment]
> 缓存就是为了可以被删掉的吧

我觉得缓存的歌曲不应该被手机管家清理掉，删除可以app中增加删除选项，感觉现在设置最大缓存空间就没有意义了，一个不注意就被清掉了，出门听音乐还是得重新下载，费流量的

**Comment by Steven128** [comment]
> 缓存就是为了可以被删掉的吧

+1，Android客户端的缓存每天夜间会被系统自动清理，相当于缓存功能没有用了

**Comment by tomerilery** [comment]
> > 缓存就是为了可以被删掉的吧
> 
> 我觉得缓存的歌曲不应该被手机管家清理掉，删除可以app中增加删除选项，感觉现在设置最大缓存空间就没有意义了，一个不注意就被清掉了，出门听音乐还是得重新下载，费流量的

我觉得你应该付费，就可以开通下载功能了，作者也要恰饭的，哪能一直用爱发电？
