### ISSUE TITLE
鸿蒙系统下蓝牙听歌会卡死，只能重启手机

### ISSUE THREAD

**Issue by shuer001** [gitbobobo/StreamMusic#162]
在鸿蒙系统下连接蓝牙听歌（蓝牙耳机或者车机）会造成手机卡死，只能重启手机来解决， 群里有同样问题的小伙伴， 非常影响体验（不敢用了。）
具体是：蓝牙听歌时，第三方应用打断/信号不好/带手机远离蓝牙设备等造成软件播放暂停  次数有个三四次就很大可能出现手机卡死现象。这时候只能重启手机来解决问题。
在群里也反馈过。希望大佬能优先定位解决下。。。。

**Comment by gitbobobo** [comment]
收到，，，现在还没有设备调试，等过几周我再试试看

**Comment by lmzhong** [comment]
鸿蒙4，mate60 连车机，播放基本正常，没有出现死机情况。只偶尔会出现换歌延迟较大现象

**Comment by hahaha3542** [comment]
> 收到，，，现在还没有设备调试，等过几周我再试试看

手动前往设置里的应用启动设置，手动关闭自动管理并授权应用三启动即可。

**Comment by shuer001** [comment]
最近几天  关闭：歌词设置-系统级状态栏歌词后. 暂时没有出现过卡死重启的情况。  后续再使用测试下看看~

**Comment by gitbobobo** [comment]
不知道后续还有没有这样的情况了，如果还不行，可以把音流从电池优化中移除试试。

另外，1.2.8更换了新的播放插件，可能会对这种情况有所帮助

**Comment by shuer001** [comment]
最近关闭系统状态栏歌词后，没有出现过手机卡死重启的问题了。最新的两个版本没有重新开启 测试、（怕了）、
能简单解决，大佬以后有空排再查下就行，

关闭问题了，
