### ISSUE TITLE
iOS版本更新到1.2.5后UI界面字体太大，能否在设置里加入用户自己调节字体大小的选项？

### ISSUE THREAD

**Issue by maninsz** [gitbobobo/StreamMusic#169]
作者你好！首先特别感谢你开发这款软件，有个问题向你反馈一下，iOS版本的音流更新到1.2.5版本后，整个界面的字体一下子变得好大，导致屏幕显示的内容太少了，能不能换回以前的字体大小，或者加入字体大小用户自己调节的选项，以便让界面显示更多的内容，谢谢！

**Comment by maninsz** [comment]
> 不会吧，我这里没有变化啊，你的系统字体设置的多大？可以截个图看看吗

![IMG_1932](https://github.com/gitbobobo/StreamMusic/assets/22188040/5ca6a004-4597-48a3-908a-3e14af7a941c)
收集系统字体已经调到最小了。
![IMG_1933](https://github.com/gitbobobo/StreamMusic/assets/22188040/50dc5c0b-8ae8-4a0e-b76c-d26d081d1232)
升级到1.2.5版本后音流UI界面明显比之前的版本字体要大的多，有种老年机既视感。

**Comment by gitbobobo** [comment]
1.2.6会应用缩小字体的配置
