### ISSUE TITLE
Navidrome服务默认添加5433端口导致登录不上问题

### ISSUE THREAD

**Issue by 96368a** [gitbobobo/StreamMusic#172]
地址输入为`https://music.test111.cn`时，默认会在后面添加端口5433，前面也没有相关的提示，我认为此处有可能产生误导

![login.png](https://github.com/gitbobobo/StreamMusic/assets/61831019/7e7aba66-b1b4-4aff-bffb-3bbf0578383a)

![port.png](https://github.com/gitbobobo/StreamMusic/assets/61831019/49d100eb-a62c-4b07-887e-f42597f43367)

**Comment by gitbobobo** [comment]
有道理，是不该添加的

**Comment by gitbobobo** [comment]
1.2.6如果未指名端口号，会弹框由用户选择使用哪个地址
