### ISSUE TITLE
登录navidrome的地址问题

### ISSUE THREAD

**Issue by qilinxinan** [gitbobobo/StreamMusic#173]
版本：V1.2.5
系统：安卓
使用navidrome音源的时候，怎么登都登录不上，后来发现，是因为要求填写的地址栏输入项，缺少了端口。但是使用域名的80端口和443端口是自动缺省的，这使得我尝试了很多次，一度以为app有BUG，希望作者能优化下，避免出现跟我相通遭遇的人。
例如：http://xxx.com
而实际上需要写：http://xxx.com:80 才有用

**Comment by gitbobobo** [comment]
嗯嗯,和 https://github.com/gitbobobo/StreamMusic/issues/172 是同一个问题，下个版本我处理下
