### ISSUE TITLE
python后端

### ISSUE THREAD

**Issue by LINycA** [gitbobobo/StreamMusic#176]
用python，flask框架，以navidrome的接口为原型，写了个后端，web前端暂时没有写，所以还没有开源，增加了刮削功能，还不是很完善，先插个眼，后期再来附上项目地址😁
![image](https://github.com/gitbobobo/StreamMusic/assets/40932023/ff9f18a1-7a41-421b-9590-b1135bd79bff)

**Comment by gitbobobo** [comment]
项目名不会是叫「阿童木」吧？哈哈哈
