### ISSUE TITLE
1.2.6 版本中无法播放某些特定歌曲

### ISSUE THREAD

**Issue by kierankihn** [gitbobobo/StreamMusic#181]
更新到 1.2.6 之后无法播放某些歌曲（或者说大部分歌曲？我看只有小部分专辑的第一首歌曲可以播放），无论是在专辑页面还是在所有歌曲页面，都无法播放，歌曲名显示为灰色，并且无法点击

同时在专辑页面点击 播放所有 仍然可以播放第一首歌曲，但是选择快进到下一首歌的时候会自动停止播放，而不是快进至下一首

在播放时无法在 emby 服务端看到有设备在播放，但是可以看到音流的登录记录

服务端为 emby 4.8.3.0，客户端为音流 1.2.6，操作系统为 Windows 10 22H2

**Comment by kierankihn** [comment]
我刚刚在音流客户端退出又重新登录了一遍，现在直接不显示所有歌曲了，直接提示 暂无数据 / 外星人好像来过这里，所有专辑 / 歌曲界面均如此

但是 emby 服务端仍然有刚刚音流的登录日志

**Comment by kierankihn** [comment]
音流的日志中显示

```
  ERROR 17:51:15.766 (+0:00:00.848034)
  ERROR ⛔ 初始化播放器失败：Loading interrupted
   INFO 17:51:15.766 (+0:00:00.848034)
   INFO 💡 歌曲加载状态: ProcessingState.idle
   INFO 17:51:15.766 (+0:00:00.848034)
   INFO 💡 当前播放歌曲索引：0
  DEBUG 17:51:15.766 (+0:00:00.848034)
  DEBUG 🐛 播放状态: false
WARNING 17:51:21.290 (+0:00:06.371586)
WARNING ⚠️ 同步数据任务正在进行或当前处于离线模式
WARNING 17:51:22.066 (+0:00:07.148161)
WARNING ⚠️ 同步数据任务正在进行或当前处于离线模式
WARNING 17:51:22.370 (+0:00:07.451908)
WARNING ⚠️ 同步数据任务正在进行或当前处于离线模式
WARNING 17:51:22.618 (+0:00:07.699881)
WARNING ⚠️ 同步数据任务正在进行或当前处于离线模式
WARNING 17:51:22.866 (+0:00:07.948116)
WARNING ⚠️ 同步数据任务正在进行或当前处于离线模式
```

**Comment by gitbobobo** [comment]
歌曲变灰就是进入离线模式了，另外，安全起见贴日志时最好不要带上你自己的网址

**Comment by kierankihn** [comment]
> 安全起见贴日志时最好不要带上你自己的网址

感谢提醒，我会注意的

> 歌曲变灰就是进入离线模式了

为什么会进入离线模式呢？如上文所述，我是可以成功登录的，但是根据日志来看应该是一登录就强制进入了离线模式？

**Comment by kierankihn** [comment]
今天我卸载并重新安装了一次，现在可以正常播放了，但是原因仍然未知
