### ISSUE TITLE
音流有不同步智能歌单的bug

### ISSUE THREAD

**Issue by chrisdong** [gitbobobo/StreamMusic#183]
安卓、Windows上这个bug相同，ios没测试。

我用Navidrome 智能歌单.nsp 建立的一个歌单，里面有四首歌，这4首歌我更换了3首，其中1首没动。

Navidrome刷新后，网页版里的这个歌单全都更新了，显示4首歌，而音流上的这个歌单 变成  我没改动的这一首歌，更换的3首歌不见了，音流上 已经操作 同步歌单，同步数据库。

音流退出帐号，重新登录后，这个歌单 又变成4首歌了。

退出帐号才能刷新歌单的bug能否修复一下？
我认为不是 Navidrome或者.nsp智能歌单的问题，因为网页版的没问题，歌单能更新。重新登录帐号，音流也能更新歌单。

还有能否增加 歌单自动刷新功能？

**Comment by hahaha3542** [comment]
而且文件夹选项卡内也有一样的问题，视觉上的感觉像是刷新不彻底，有些底层的东西没有刷新
