### ISSUE TITLE
希望可以优化播放模式操作

### ISSUE THREAD

**Issue by hahaha3542** [gitbobobo/StreamMusic#184]
希望循环模式按钮可以类似苹果iOS输入法切换的操作逻辑，长按然后拖动精准选择循环模式，省去来回点按切换模式的麻烦。

以及希望增加一个用于设置更换播放列表之后循环模式不变的选项，每次跑到另外一个播放列表之后都要手动调回单曲循环。

**Comment by gitbobobo** [comment]
单曲循环个人感觉只会在极个别突然发现一首好听的歌时会用，因此没有必要单独加配置。

播放模式的切换只有三种，我认为点两下比长按选择更快达到目的。

**Comment by hahaha3542** [comment]
> 单曲循环个人感觉只会在极个别突然发现一首好听的歌时会用，因此没有必要单独加配置。
> 
> 播放模式的切换只有三种，我认为点两下比长按选择更快达到目的。

emmm，上下两段是不同的诉求，第一段我承认有点自私了，但是第二点较为影响使用，我希望在更换歌单（目录、专辑）之后循环方式不变，即单曲保持单曲，随机保持随机，顺序保持顺序，而不是每次更换歌单都会变回顺序循环😂😂

**Comment by gitbobobo** [comment]
这个不知道你看过没，循环方式不变的逻辑是和这里的逻辑冲突的  https://music.aqzscn.cn/docs/guides/operations

**Comment by hahaha3542** [comment]
> 这个不知道你看过没，循环方式不变的逻辑是和这里的逻辑冲突的  https://music.aqzscn.cn/docs/guides/operations

收到了，确实在一定程度上会影响到
