### ISSUE TITLE
大佬有webdav适配计划么

### ISSUE THREAD

**Issue by emmsevenQ** [gitbobobo/StreamMusic#186]
家里的环境只能搭建得起alist了

**Comment by gitbobobo** [comment]
短期内不会适配，可以尝试其他支持webdav的播放器

**Comment by emmsevenQ** [comment]
> 短期内不会适配，可以尝试其他支持webdav的播放器

好的，谢谢大佬了

**Comment by gitbobobo** [comment]
和这个问题 https://github.com/gitbobobo/StreamMusic/issues/119 重复了，先关闭了

**Comment by tyokantei** [comment]
大佬，我有个musictagweb的作者支持了alist，支持Subsonic，支持它的webapp，你可以试试，但是用你这个音流接入，其他都OK，但是相同歌曲，只能播放一遍，第二遍就播放不了，看日志说是不支持的格式，不知道是什么问题，用其他支持subsonic的客户端是ok的
