### ISSUE TITLE
求回放增益（Replay Gains）/音量平衡功能

### ISSUE THREAD

**Issue by BenzLeung** [gitbobobo/StreamMusic#19]
如题，Navidrome 的API是有返回回放增益数据的。如下截图：

<img width="950" alt="图片" src="https://github.com/gitbobobo/StreamMusic/assets/2764768/c4038bcd-4574-45c8-b8bb-134dfc9f82d4">

建议提供个回放增益选项：无、按音轨应用增益（即使用 Track gain 值）、按专辑应用增益（即使用 Album gain 值）。

至于具体实现，可以参考我在另外一个音乐播放器仓库中发过一篇issue：
https://github.com/Moriafly/SaltPlayerSource/issues/158#issuecomment-1250657182

另外，我还找到了 ExoPlayer 的实现代码供参考：
https://github.com/google/ExoPlayer/issues/9796#issuecomment-1006761525

期待~

**Comment by gitbobobo** [comment]
嗯嗯，我先看一下，对这块不太了解，应该会晚点开发

**Comment by gitbobobo** [comment]
是否可以提供几个加了回放增益标签的歌曲文件？我自己的曲库都是 0 db的

**Comment by BenzLeung** [comment]
[我在那一角落患过伤风.mp3.gz](https://github.com/gitbobobo/StreamMusic/files/12724951/mp3.gz)

给你一个。

不是我不想多给你几个，实在是没有办法，github只能最大25MB，阿里云和百度云都不让分享（可能是检测到了版权问题）。。。

另外，使用 foobar2000 （安卓版或win版都可以）可以给曲库扫描分析并加入回放增益标签。

**Comment by gitbobobo** [comment]
foobar2000 加回放增益标签是自己分析音乐的响度，然后自动加的吗？

**Comment by BenzLeung** [comment]
对的，win版就在播放列表选中歌曲（一般直接全选），然后右键-播放增益-扫描为专辑(按标签)，然后先显示个进度条，进度条跑完就弹出扫描结果，按确认后就会自动写入标签到文件里了。

<img width="481" alt="图片" src="https://github.com/gitbobobo/StreamMusic/assets/2764768/d5d50aa2-22e9-4b4e-9089-b2f8dd29c8f1">

然后登录navidrome的pc网页版，右上角执行一下快速扫描，就能让回放增益数据录入navidrome。

<img width="296" alt="图片" src="https://github.com/gitbobobo/StreamMusic/assets/2764768/cf4574fc-49e3-44f1-afa0-1cf5cc5b7e69">

**Comment by BenzLeung** [comment]
多PS一句：如果音乐文件是从扣扣音乐或网抑云下载的，那是都不会携带回放增益数据的，都是需要自己用foobar2000扫描补充。境外的音乐网站我不清楚。

**Comment by gitbobobo** [comment]
好的，我去试试

**Comment by BenzLeung** [comment]
哇哇哇~ 😍🥰😘❤️❤️❤️
