### ISSUE TITLE
基于navidrome服务的歌词标点符号格式问题

### ISSUE THREAD

**Issue by hahaha3542** [gitbobobo/StreamMusic#190]
在部分歌曲的歌词中有中文中括号用于分辨演唱者，但是在该应用中歌词内容仅限演唱者标签，歌词本身未被正确识别![Screenshot_2024-03-21-17-32-45-307_cn.aqzscn.stream_music.jpg](https://github.com/gitbobobo/StreamMusic/assets/69064412/ac74c2be-ec37-46dd-86bd-63ff3bb95f8d)

![Screenshot_2024-03-21-17-45-10-098_cn.aqzscn.stream_music.jpg](https://github.com/gitbobobo/StreamMusic/assets/69064412/e0100b2e-eb19-40b2-a488-3a6132123a0d)

如图，我希望知晓部分常见标点符号在歌词识别方面的作用，以修正该问题

**Comment by gitbobobo** [comment]
从这个歌词格式来看，应该是【】内的内容被当作翻译了，导致后面的歌词被丢弃了。

应该可以通过优化代码正确识别这种格式的歌词。

PS：目前只有【】在歌词识别中起到区分翻译的作用，其他方面都是按照标准的lrc格式解析的

**Comment by gitbobobo** [comment]
1.2.7 已修复
