### ISSUE TITLE
能否为专辑页面添加歌手和风格标签？

### ISSUE THREAD

**Issue by beavermarine** [gitbobobo/StreamMusic#191]
当歌手名为非中、英文时输入搜索较为繁琐，希望能在专辑页面添加歌手和风格标签方便直接转到相同歌手或风格的专辑集合。

**Comment by gitbobobo** [comment]
目前暂未实现分类/风格功能，等后续实现后会添加这个快捷方式

**Comment by gitbobobo** [comment]
专辑页面已经添加对应的专辑艺术家链接，风格的话，由于服务端返回的专辑信息中不包含风格信息，此功能无法实现
