### ISSUE TITLE
为音流添加opus转码功能

### ISSUE THREAD

**Issue by GoldBro233** [gitbobobo/StreamMusic#193]
相较于aac和mp3格式来说，Opus格式在同等码率下更能保留更多频段和音频细节，更加适合网络流媒体
希望能够添加本地Opus转码功能，并适配Navidrome的Opus转码

**Comment by ljcbaby** [comment]
这要服务端支持吧

**Comment by happyTonakai** [comment]
Navidrome服务端本来就有opus转码

**Comment by happyTonakai** [comment]
你说的是解码opus能力吧，好像ios本身就不具备这个能力，只能作者去集成第三方的解码器
