### ISSUE TITLE
ios端多应用同时播放功能支持

### ISSUE THREAD

**Issue by Mrgu2** [gitbobobo/StreamMusic#199]
希望能支持此功能，打开一些软件会中断媒体内容很烦人
![IMG_7788](https://github.com/gitbobobo/StreamMusic/assets/86710948/dc4e4e0b-8d7a-413a-93d5-0f0f060a774a)
![IMG_7787](https://github.com/gitbobobo/StreamMusic/assets/86710948/5efee33c-9e6a-48ee-ab26-ff421d77e081)

**Comment by gitbobobo** [comment]
1.2.8 已添加，等审核通过后可以体验
