### ISSUE TITLE
提个可能导致没法登录的小bug

### ISSUE THREAD

**Issue by westmelom** [gitbobobo/StreamMusic#201]
navidrome在配置文件里面支持自己添加baseurl路径，虽然一般是用端口来区分不同服务而且也能在浏览器页面完成自动跳转，但是APP似乎不行，我看了半天日志发现他拼出来的URL是会自己添加固定路径好像是auth/login，但是实际的网页其实不是这个网址（虽然好像能正常登录），然后baseurl会被夹在中间。后续希望能增加一个登录时候自己能填baseurl参数的选项或者加个提示把baseurl的配置参数关掉。

**Comment by gitbobobo** [comment]
不太理解，举个例子？

**Comment by westmelom** [comment]
> 不太理解，举个例子？

这是路径参数不设置时候的跳转：http://192.168.3.62:8889/app/#/login
这是路径参数设置为example时候的跳转：http://localhost:8889/example/app/#/login
我昨天测试发现下面这种baseurl存在参数的会导致无法登录，需要在服务器端置空baseurl重启navidrome生效才能用音流登录。
PS：我用电视装了音流后也能正常登录进去，但是无法正常同步歌单，直接是0，手机端的歌单正常。

**Comment by gitbobobo** [comment]
那加了路径参数的，怎样才能正确访问呢

**Comment by westmelom** [comment]
> 那加了路径参数的，怎样才能正确访问呢

理论上应该要在端口号和你现在拼接的路径之间插入baseurl这个参数，我最近也没法测是否有效，建议是先加个提示在登录页面告知navidrome那边别开baseurl的参数
