### ISSUE TITLE
[Feature Request] 希望可以添加在切歌的时候平滑切歌的功能

### ISSUE THREAD

**Issue by kierankihn** [gitbobobo/StreamMusic#203]
希望可以添加在切换歌曲时平滑切歌的功能

例如可以直接做歌曲淡入淡出（逐渐减小音量），或者在两首歌之间添加等待时间，又或者做一个像是 spotify 的 crossfade 的功能（但是感觉这个会比较困难）

**Comment by gitbobobo** [comment]
1.2.8已添加（非交叉淡入淡出）
