### ISSUE TITLE
主题可以丰富一些

### ISSUE THREAD

**Issue by sayunchuan** [gitbobobo/StreamMusic#204]
系统：ios
建议：当前主题只有深浅与默认，是否可以考虑整体毛玻璃配合一些随机色，或者用户本地上传图片以图片或毛玻璃效果的图片作为主题？

**Comment by gitbobobo** [comment]
已经支持自定义背景图片了（需要先切换到默认主题）

**Comment by sayunchuan** [comment]
NB！！！
