### ISSUE TITLE
aduiostatiom方式登录，经常无法播放

### ISSUE THREAD

**Issue by wardwyz** [gitbobobo/StreamMusic#210]
通过audiostation方式登录，时常会出现歌曲时长0:0-0:0 无法播放，通过另一款ds player播放正常。已关闭转码。
![IMG_3550](https://github.com/gitbobobo/StreamMusic/assets/24563243/e0d66db0-682a-4ebf-93b5-cacd8608d46a)
![IMG_3551](https://github.com/gitbobobo/StreamMusic/assets/24563243/72c54590-6e8b-4e99-9941-d97e8ebdcc07)

**Comment by gitbobobo** [comment]
1.2.8已更换新的播放插件，可以再看看这样的问题还会不会出现。
