### ISSUE TITLE
时不时的程序就会无法播放

### ISSUE THREAD

**Issue by yzmninglang** [gitbobobo/StreamMusic#215]
在使用阴流的时候。服务端使用的是nav，客户端使用的是音流。有时候播放着播放着就卡住了。不管怎么拖动那个进度条。甚至换一首歌。那个进度条还是不能继续向前行动

机型：一加ace2pro

**Comment by gitbobobo** [comment]
1.2.8已更换新的播放插件，可以再看看这样的问题还会不会出现。
