### ISSUE TITLE
更新到V1.2.7专辑封面不显示了

### ISSUE THREAD

**Issue by Skinsly** [gitbobobo/StreamMusic#216]
更新到V1.2.7专辑封面不显示了

**Comment by gitbobobo** [comment]
服务端是什么

**Comment by kierankihn** [comment]
同样的问题，在 emby 4.8.3.0 上遇到了，部分歌曲无法显示封面

在 emby 上浏览元数据可以看到正确的专辑和音乐封面

**Comment by mxm012337** [comment]
> 服务端是什么

jellyfin10.8.13  
1.2.7也不显示封面  1.2.6正常

**Comment by dlovew** [comment]
> 1.2.8已修复（emby）

每日推荐还是没有封面，emby服务端，windows客户端

**Comment by dlovew** [comment]
> > 1.2.8已修复（emby）
> 
> 每日推荐还是没有封面，emby服务端，windows客户端

补充一下，我1.2.8安卓是正常的

**Comment by gitbobobo** [comment]
1.2.9 重新处理了此问题，看下还有没有问题
