### ISSUE TITLE
更新到1.2.7后，读取封面图片发生错误

### ISSUE THREAD

**Issue by ZGLinus** [gitbobobo/StreamMusic#218]
服务器是navidrome, 1.2.6版本如果碰到同一专辑的不同封面歌曲，是可以读取到不同的封面，但是1.2.7只能获取到专辑的封面了。
音流1.2.7效果
![95ce8fd08a22d1bb5e986733f3fa39fd](https://github.com/gitbobobo/StreamMusic/assets/69845097/192de4c4-01d1-4c11-b115-3960bb8ef460)
音流1.2.6效果
![图片](https://github.com/gitbobobo/StreamMusic/assets/69845097/89aa6128-2ac4-44da-aad6-3bbb29887682)

歌曲元数据
![图片](https://github.com/gitbobobo/StreamMusic/assets/69845097/16f4a323-5c78-46b4-9592-44760b38e61c)

**Comment by gitbobobo** [comment]
一般来说歌曲的封面就是专辑的封面吧，这个版本统一改为获取专辑封面，是因为一个专辑内可能有的歌曲有封面，有的歌曲没封面，所以才统一请求专辑封面的

**Comment by jpsn123** [comment]
@gitbobobo 昨天下了一堆软件，发现你做的这个还不错，但是有两个比较影响使用体验的点

1. 很多歌曲封面没有，虽然我平时都是carplay听，但是这个看上去比较难受
2. 转码的音乐没有进度，这个很多其他协议的软件也是这样，甚至不能转码，这个应该跟ios标准组件有关系，转码是很重要的功能，主要是无损不太适合移动设备，没必要也浪费空间
3. carplay直接启动会卡死，不管软件是否在后台开着，需要重启软件

![微信图片_20240411142327](https://github.com/gitbobobo/StreamMusic/assets/21193254/9d219be1-22ae-47ca-85f6-777ede5cd275)

总体来说软件还是不错，把一些小bug修复一下，就是一个完整的产品了。

我是做产品的，作者如果有需求可以交流。

**Comment by ZGLinus** [comment]
navidrome默认配置是先读取文件夹下的cover.*, folder.* 或者 front.*格式的图片，然后才是内嵌图片，我认为这一个改动似乎多此一举，因为navidrome配置得当是可以读取到专辑图片的。

**Comment by jpsn123** [comment]
我用的是emby

**Comment by 518512** [comment]
我也是Emby，1.2.7 大部分歌曲内嵌的封面都无法显示了。 1.2.6显示正常，Emby客户端显示正常。

希望修复

**Comment by gitbobobo** [comment]
1.3.1已改回歌曲封面显示逻辑
