### ISSUE TITLE
更新1.2.7后，Audio Station使用域名+端口无法登陆

### ISSUE THREAD

**Issue by ixgxgoe** [gitbobobo/StreamMusic#219]
更新1.2.7，链接Audio Station，使用域名+端口无法登陆，显示：登录失败 请检查网络或者账号密码是否正确。回退到1.26后正常登录，下方能显示http和https的选择

**Comment by ixgxgoe** [comment]
另外，希望能出个调整UI缩放的功能，我是装在安卓车机上来听歌的，用了一个多月1.2.5版本，不能调整UI大小，图标跟文字太小了。不方便。

**Comment by gitbobobo** [comment]
重新下载一下1.2.7，安装包重新上传了。

**Comment by ixgxgoe** [comment]
> 重新下载一下1.2.7，安装包重新上传了。

下方出现：请选择登录地址的选项了，但还是登录不了，提示登录失败，不知道是不是跟我修改了群晖的默认5000、5001这2个端口号有关

**Comment by ixgxgoe** [comment]
好像也不是，刚借用朋友的群晖，用QC方式+默认端口，也无法登录

**Comment by gitbobobo** [comment]
修改默认端口号的话得带上端口号，选择登录地址那个弹框里只有默认的端口

**Comment by leG09** [comment]
我也提示这个问题，1.2.6能登录 ,1.2.7无法登录。app端提示请检查网络或者账号密码是否正确。mac端提示登录失败
<img width="1000" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/35995161/beca0649-f9f4-4a58-a767-108cc7871249">
<img width="537" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/35995161/e96441ae-c611-4643-a66a-daddf29d2070">

**Comment by leG09** [comment]
> 登录 ,1.2.7无法登录。app端提示请检查



> DSM 是6.0吗？

> DSM 6.2.1-23824

**Comment by leG09** [comment]
DSM 6.2.1-23824

**Comment by a502347020** [comment]
果然不只我一个人，DSM6.2，内网地址，外网地址，无论加不加端口，全部无法登录。
官方DS audio正常，
卸载音流1.2.7，安装旧版内外网都能正常登录。

**Comment by gitbobobo** [comment]
1.2.8已修复
