### ISSUE TITLE
1.2.6 windows版本没有浮窗暂停功能，希望增加

### ISSUE THREAD

**Issue by Zhzcyborg** [gitbobobo/StreamMusic#220]
希望能增加浮窗暂停功能
如图，希望能在这个浮动窗口增加暂停，下一曲等按钮
![image](https://github.com/gitbobobo/StreamMusic/assets/81177601/ed1837ea-b76d-46af-ac83-dd419f67990c)
希望增加后效果，如sonixd一样，浮窗内有暂停按钮
![image](https://github.com/gitbobobo/StreamMusic/assets/81177601/acd57083-2bf0-40bd-9b95-40a8aac33fa4)
已入完全版支持，邮箱同我id，希望能优先考虑，thanks

**Comment by gitbobobo** [comment]
1.3.1已添加
