### ISSUE TITLE
鸿蒙4.0锁屏不显示操作按钮

### ISSUE THREAD

**Issue by taowei20** [gitbobobo/StreamMusic#222]
![91712753199_ pic](https://github.com/gitbobobo/StreamMusic/assets/62376335/3abf9279-28eb-40c3-a090-b68ea4588d5f)

**Comment by hahaha3542** [comment]
是被自动隐藏通知内容搞的，或者通知内容被认为是普通通知被收起了。作者说hmos的适配计划比较靠后，因为开发是按照谷歌框架来的。

**Comment by gitbobobo** [comment]
点下右边的下拉按钮就有了吧，现在是折叠状态

**Comment by taowei20** [comment]
> 点下右边的下拉按钮就有了吧，现在是折叠状态

没有,点下拉就提示解锁,估计是鸿蒙的问题,安卓没问题的.

**Comment by jayxuz** [comment]
> > 点下右边的下拉按钮就有了吧，现在是折叠状态
> 
> 没有,点下拉就提示解锁,估计是鸿蒙的问题,安卓没问题的.

这个状态应该是打开了通知 -> 隐藏通知内容这个选项导致的。关闭之后对于消息的隐私又产生了影响。
所以音流的控制因为是通知栏形式，被“误杀”了。

要解决这个问题，得添加对鸿蒙系统，播控中心的支持，使用系统级的组件控制
