### ISSUE TITLE
两个问题：1、有计划支持用邮箱购买和恢复吗？有计划支持安卓4.2吗？感谢作者解答

### ISSUE THREAD

**Issue by www766** [gitbobobo/StreamMusic#225]
两个问题：
1、有计划支持用邮箱购买和恢复吗？
看安卓平台软件内有说**支持邮箱恢复  在原平台购买 请问是在哪购买？支持作者劳动！**
虽然支持支付宝订单但查找麻烦，还是**习惯用主邮箱注册和绑定各类服务**，请问有什么途径购买，麻烦提供下，去支持作者。

2、有计划支持安卓4.2吗？

TV端和车机端的安卓版本较老 因为**目前这类设备社会存量还是很多的，当时购买设备价值较高，不会轻易更换**，请问作者有计划支持下吗？ 安卓老版本 v7a。

**另外问下目前APP最低适配到安卓几平台？**

**Comment by gitbobobo** [comment]
购买后可以绑定邮箱

不支持安卓4.2，最低多少我没试过，可能是5.0吧。没有计划支持低版本安卓
