### ISSUE TITLE
IOS端部分歌曲无法显示歌曲封面

### ISSUE THREAD

**Issue by JonDoe47** [gitbobobo/StreamMusic#227]
服务端为AudioStation，在服务器端可以看到专辑、歌曲的封面。在IOS端部分歌曲只有专辑封面，看不到歌曲封面。
![image](https://github.com/gitbobobo/StreamMusic/assets/127613236/13320624-a982-4965-a702-b65057036007)
![95d70f731a6b58f4da8e5967275e769](https://github.com/gitbobobo/StreamMusic/assets/127613236/904f204a-95f3-4e24-bcf9-4d6ea6c13209)

**Comment by gitbobobo** [comment]
1.2.8已修复
