### ISSUE TITLE
Plex可以支持公网DDNS域名吗？

### ISSUE THREAD

**Issue by realx1n** [gitbobobo/StreamMusic#228]
目前NAS装的Plex通过ddns映射在域名进行访问，但APP里面登录之后连接的服务器地址是公网IP，这个IP会不定时更换。
如果更换了IP，就会出现访问不上，只能重新登录再获取新的IP。
能否实现连接的服务器地址是域名呢？

**Comment by gitbobobo** [comment]
正常来说是可以自动获取到服务器IP的，等我多用一段时间看看吧

**Comment by realx1n** [comment]
第一次登录用是在内网，然后在公网使用的时候就长时间连接不上服务器，不确定是否获取有问题

**Comment by Ccnavi** [comment]
> 第一次登录用是在内网，然后在公网使用的时候就长时间连接不上服务器，不确定是否获取有问题

可以尝试 将动态域名+端口 发布到 plex

**Comment by Ccnavi** [comment]
![image](https://github.com/gitbobobo/StreamMusic/assets/80135349/cb6cb127-cb2e-4f00-881d-582ca87d6a4d)

**Comment by realx1n** [comment]
> ![image](https://private-user-images.githubusercontent.com/80135349/324330783-cb6cb127-cb2e-4f00-881d-582ca87d6a4d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM5Mjk0NDcsIm5iZiI6MTcxMzkyOTE0NywicGF0aCI6Ii84MDEzNTM0OS8zMjQzMzA3ODMtY2I2Y2IxMjctY2IyZS00ZjAwLTg4MWQtNTgyY2E4N2Q2YTRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI0VDAzMjU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0YjhhNjYxODVjZjc4NDEyMWY2OTAzNTdkOGIzYmM1NDAyYzAwMjA5MjM0YmRhNWZmY2VjYWMxMDEwZDljNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YHMi6rs389Pn-7vnxdw1aka_3ZCu98Gci5LWzaiholU)

搞定了，没想到这个设置是在【网络】里面，不在【远程访问】里，找了一圈

**Comment by TooAndy** [comment]
目前1.3.0版本，直接在 线路配置 里，添加一个DDNS域名加端口，然后拖到第一个，当成主线路就可以了。
域名是你的ddns域名，例如 www.example.com，端口是你映射到公网的端口，例如23400，就填写：
https://www.example.com:23400
