### ISSUE TITLE
充值问题

### ISSUE THREAD

**Issue by Jesae** [gitbobobo/StreamMusic#229]
你好，我今天在09:00左右安卓平板上安装app后点充值vip使用支付宝账号支付成功后，在上午11:59分居然又收到了支付宝账户正在登录的短信验证码、我可以保证我自己并没有操作，在下午15:18分收到了国家反诈短信 提示【【反诈温馨提示】您接收到来自不明多个非法IP进行了攻击以及盗刷提交了不明短信内容，请保护好个人信息，请勿点开链接，提升识骗防骗意识。】

app是在官网下载的！请知晓！

**Comment by gitbobobo** [comment]
第一次遇到这种情况，不排除音流不小心用到了什么恶意插件。

我先把这个问题置顶吧，看看有没有遇到同样情况的。

**Comment by grouse108** [comment]
今天才在安卓平台用支付宝付款，没有碰到同样问题。

这个APP配合Navidrome简直绝配，必须入正支持！为了帮大佬免了苹果税，专门转的安卓平台付款。

顺便问一下，入正以后支持几台设备？我目前用了3台

**Comment by gitbobobo** [comment]
感谢反馈～

最多可同时在6台设备使用

**Comment by gitbobobo** [comment]
目前没时间支持更多支付方式。

如果可以在国区购买也是一样的，后面通过邮箱验证码恢复购买就可以。

会员身份和订单号是绑定的，不支持其他方式购买。

**Comment by zzzwang** [comment]
请问大佬双十一有活动吗

**Comment by gitbobobo** [comment]
没有哈，音流只会在大版本更新时才会有活动

**Comment by gitbobobo** [comment]
这个问题置顶也有挺长时间了，暂时没有收到其他用户类似的反馈，我先关闭了。

过段时间还没有反馈的话再取消置顶
