### ISSUE TITLE
适配TV版

### ISSUE THREAD

**Issue by gitbobobo** [gitbobobo/StreamMusic#23]

**Comment by BenzLeung** [comment]
期待这个~ 订阅了

**Comment by lidongsun** [comment]
期待早日用上TV端

**Comment by demerzelxd** [comment]
期待，已经购买了

**Comment by XR-LM** [comment]
期待

**Comment by gitbobobo** [comment]
1.3.0 测试版（仓库说明有地址）已适配安卓TV，欢迎尝鲜～

**Comment by lmzhong** [comment]
已试用，基本能用
随机播放时，封面图有时候不能随音乐更新，停留在第一首歌的封面
界面简单够用，有点像jellyfin-tv版早期风格

**Comment by lmzhong** [comment]
> 已试用，基本能用 随机播放时，封面图有时候不能随音乐更新，停留在第一首歌的封面 界面简单够用，有点像jellyfin-tv版早期风格

补充一个bug
搜索栏调用输入法不成功后界面吊死，只能强制退出，多个机顶盒测试均如此

**Comment by gitbobobo** [comment]
1.3.0已发布

**Comment by chrisdong** [comment]
https://apps.apple.com/us/app/lmp-music-hub/id6451009326
这个AppleTV版 支持navidrome，而且界面美观，支持歌词
我已经买了音流的付费版，等不了音流 AppleTV版本了，又买了这个
建议音流作者可以参考 https://apps.apple.com/us/app/lmp-music-hub/id6451009326 这个来优化音流界面，取长补短
