### ISSUE TITLE
歌词时间格式不支持 mm:ss 格式

### ISSUE THREAD

**Issue by wanghaida** [gitbobobo/StreamMusic#230]
根据百科解释，歌词的形式有 3 种，经测试 AudioStation 支持三种，而音流只支持标准格式，其他格式①②显示但不滚动。

1、标准格式： [分钟:秒.毫秒] 歌词
2、其他格式①：[分钟:秒] 歌词
3、其他格式②：[分钟:秒:毫秒] 歌词，与标准格式相比，秒后边的点号被改成了冒号

**Comment by gitbobobo** [comment]
可以附上百科的链接吗？我参考一下。

**Comment by wanghaida** [comment]
https://baike.baidu.com/item/lrc/46935

**Comment by gitbobobo** [comment]
1.2.9可以兼容这种格式的歌词了
