### ISSUE TITLE
更新到V1.2.8播放界面的专辑图片不显示

### ISSUE THREAD

**Issue by Skinsly** [gitbobobo/StreamMusic#231]
更新到V1.2.8主页的专辑图片显示了，播放界面的专辑图片还是不显示，1.2.6版本播放界面可以显示图片，安卓和PC都这样。
服务器版本emby4.9.0.14。
![微信图片_20240418075927](https://github.com/gitbobobo/StreamMusic/assets/45187023/a12811ea-3092-45ed-9618-4f6d5927a8a5)
![微信图片_20240418075933](https://github.com/gitbobobo/StreamMusic/assets/45187023/744c6606-e3e9-41ba-98de-902095789f28)

**Comment by gitbobobo** [comment]
1.2.9 重新处理了封面问题，可以看看还有无此问题
