### ISSUE TITLE
状态栏歌词希望支持三星

### ISSUE THREAD

**Issue by djdjfjfkeocj** [gitbobobo/StreamMusic#232]
听说三星也可以有状态栏歌词，好像网易云就可以有，希望支持

**Comment by gitbobobo** [comment]
目前没有三星设备，状态栏歌词目前已知只支持魅族和部分第三方ROM

网易云的状态栏歌词长什么样？如果你确定它是状态栏歌词而非浮窗显示的话，可以留下你的机型，以后可能会考虑实现。

**Comment by djdjfjfkeocj** [comment]
好吧，我也不确定。。。。我是看b站有说

**Comment by gitbobobo** [comment]
已确定网易云状态栏歌词用的是悬浮窗显示的
