### ISSUE TITLE
播放器记忆每张专辑上次播放的进度

### ISSUE THREAD

**Issue by 18309871333** [gitbobobo/StreamMusic#234]
平时喜欢用emby放好多有声小说，emby每张专辑记忆播放位置的功能挺不错的，能继承过来吗？

**Comment by gitbobobo** [comment]
未播放过的歌曲，序号是用绿色表示的

长音频记忆播放位置的功能已经有了，不过需要会员身份。

**Comment by 18309871333** [comment]
> 未播放过的歌曲，序号是用绿色表示的
> 
> 长音频记忆播放位置的功能已经有了，不过需要会员身份。

我是会员，服务端是 plex，可以实现这个功能吗
