### ISSUE TITLE
1.2.8播放位置记忆的问题

### ISSUE THREAD

**Issue by dlovew** [gitbobobo/StreamMusic#236]
1.2.8版本不会记忆播放位置么？我设置的是打开自动播放，每次打开会继续放上次的歌，但是都是重开头放，之前是可以重中间放，也就是上次关闭前放到第几秒，下次还能重第几秒放！emby服务端！

**Comment by iNinet** [comment]
+1，Navidrome服务端，苹果和安卓都不会记忆，试了1.2.9也不行

**Comment by gitbobobo** [comment]
1.3.0已发布
