### ISSUE TITLE
魅族21后台划掉还在放音乐

### ISSUE THREAD

**Issue by mxm012337** [gitbobobo/StreamMusic#239]
魅族21最新内测版，后台自动管理，播放音乐一会就暂停了，改为允许后台运行，上滑关掉音乐后台音乐还继续在播放，重新打开在划掉也没用，不知道是系统bug还是音流bug,用喜马拉雅和其他app都没问题

**Comment by gitbobobo** [comment]
我用的魅族20，flyme 10，后台自动管理开启和关闭都试过了，划掉都是可以完全停掉的。

而且全新安装后无需任何设置，一直都是可以后台播放的。

**Comment by mxm012337** [comment]
> 我用的魅族20，flyme 10，后台自动管理开启和关闭都试过了，划掉都是可以完全停掉的。
我用的是最新版内测系统，那有可能是系统bug吧，发现其他app都没这问题

**Comment by mxm012337** [comment]
> 我用的魅族20，flyme 10，后台自动管理开启和关闭都试过了，划掉都是可以完全停掉的。

通用版允许后台播放好像可以划掉后台，v8a版划掉还有音乐在播放

**Comment by mxm012337** [comment]
> 我用的魅族20，flyme 10，后台自动管理开启和关闭都试过了，划掉都是可以完全停掉的。

老大，试了好久，v8a版本划掉后台得强行停止才可以，通用版没问题

**Comment by gitbobobo** [comment]
我这里用的也是v8a，是可以停掉的。

暂时不清楚什么原因导致的，如果通用版没问题就先用通用版吧，这个问题我得查查资料，看其他人是怎么解决的。

**Comment by mxm012337** [comment]
> 我这里用的也是v8a，是可以停掉的。
> 
> 暂时不清楚什么原因导致的，如果通用版没问题就先用通用版吧，这个问题我得查查资料，看其他人是怎么解决的。
好的👌🏻辛苦了

**Comment by gitbobobo** [comment]
1.3.0已发布
