### ISSUE TITLE
mac 上运行巨卡

### ISSUE THREAD

**Issue by 0xganz** [gitbobobo/StreamMusic#244]
![image](https://github.com/gitbobobo/StreamMusic/assets/5989219/6b82d4ae-0dfb-48ac-a8fe-5b9e6deec824)
不知道什么原因

**Comment by 0xganz** [comment]
`❯ lsof -p 55241
COMMAND    PID      USER   FD      TYPE             DEVICE  SIZE/OFF                NODE NAME
�\x9f�� 55241 xxx  cwd       DIR               1,18       640                   2 /
�\x9f�� 55241 xxx  txt       REG               1,18    304176            35691907 /Applications/音流.app/Contents/MacOS/音流
�\x9f�� 55241 xxx  txt       REG               1,18       119 1152921500312135043 /System/Library/CoreServices/SystemVersion.bundle/zh_CN.lproj/SystemVersion.strings
�\x9f�� 55241 xxx  txt       REG               1,18    237952            23757896 /private/var/db/timezone/tz/2024a.1.0/icutz/icutz44l.dat
�\x9f�� 55241 xxx  txt       REG               1,18    137016 1152921500312134679 /System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/SystemAppearance.car
�\x9f�� 55241 xxx  txt       REG               1,18    137898            36009493 /private/var/db/analyticsd/events.allowlist
�\x9f�� 55241 xxx  txt       REG               1,18      6179 1152921500312163403 /System/Library/Frameworks/AppKit.framework/Versions/C/Resources/InputManager.loctable
�\x9f�� 55241 xxx  txt       REG               1,18    281152 1152921500312512777 /usr/lib/libobjc-trampolines.dylib
�\x9f�� 55241 xxx  txt       REG               1,18     58649 1152921500312163329 /System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Common.loctable
�\x9f�� 55241 xxx  txt       REG               1,18    139224            36020551 /private/var/folders/67/pn4cb9zn7c95b0fzlmr826hm0000gn/C/com.apple.IntlDataCache.le.kbdx
�\x9f�� 55241 xxx  txt       REG               1,18    761936            35692159 /Applications/音流.app/Contents/Frameworks/Mbedtls.framework/Versions/A/Mbedtls
�\x9f�� 55241 xxx  txt       REG               1,18    448080            35691928 /Applications/音流.app/Contents/Frameworks/Avfilter.framework/Versions/A/Avfilter
�\x9f�� 55241 xxx  txt       REG               1,18   1954064            35692004 /Applications/音流.app/Contents/Frameworks/Mbedcrypto.framework/Versions/A/Mbedcrypto
�\x9f�� 55241 xxx  txt       REG               1,18    282064            35692345 /Applications/音流.app/Contents/Frameworks/connectivity_plus.framework/Versions/A/connectivity_plus
�\x9f�� 55241 xxx  txt       REG               1,18    154560            35692251 /Applications/音流.app/Contents/Frameworks/package_info_plus.framework/Versions/A/package_info_plus
�\x9f�� 55241 xxx  txt       REG               1,18    213792            35692015 /Applications/音流.app/Contents/Frameworks/audio_service.framework/Versions/A/audio_service
�\x9f�� 55241 xxx  txt       REG               1,18   1391904            35691949 /Applications/音流.app/Contents/Frameworks/Avformat.framework/Versions/A/Avformat
�\x9f�� 55241 xxx  txt       REG               1,18    362832            35692334 /Applications/音流.app/Contents/Frameworks/Mbedx509.framework/Versions/A/Mbedx509
�\x9f�� 55241 xxx  txt       REG               1,18    171808            35692289 /Applications/音流.app/Contents/Frameworks/audio_session.framework/Versions/A/audio_session
�\x9f�� 55241 xxx  txt       REG               1,18   3023696            35692170 /Applications/音流.app/Contents/Frameworks/Avcodec.framework/Versions/A/Avcodec
�\x9f�� 55241 xxx  txt       REG               1,18   1013472            35692229 /Applications/音流.app/Contents/Frameworks/Avutil.framework/Versions/A/Avutil
�\x9f�� 55241 xxx  txt       REG               1,18    252416            35692037 /Applications/音流.app/Contents/Frameworks/Swresample.framework/Versions/A/Swresample
�\x9f�� 55241 xxx  txt       REG               1,18    319632            35691994 /Applications/音流.app/Contents/Frameworks/appkit_ui_element_colors.framework/Versions/A/appkit_ui_element_colors
�\x9f�� 55241 xxx  txt       REG               1,18    309808            35692148 /Applications/音流.app/Contents/Frameworks/in_app_purchase_storekit.framework/Versions/A/in_app_purchase_storekit
�\x9f�� 55241 xxx  txt       REG               1,18    261552            35692301 /Applications/音流.app/Contents/Frameworks/macos_ui.framework/Versions/A/macos_ui
�\x9f�� 55241 xxx  txt       REG               1,18    256256            35692203 /Applications/音流.app/Contents/Frameworks/device_info_plus.framework/Versions/A/device_info_plus
�\x9f�� 55241 xxx  txt       REG               1,18    235504            35691982 /Applications/音流.app/Contents/Frameworks/dynamic_color.framework/Versions/A/dynamic_color
�\x9f�� 55241 xxx  txt       REG               1,18    216320            35692181 /Applications/音流.app/Contents/Frameworks/media_kit_libs_macos_audio.framework/Versions/A/media_kit_libs_macos_audio
�\x9f�� 55241 xxx  txt       REG               1,18    797616            35692240 /Applications/音流.app/Contents/Frameworks/Swscale.framework/Versions/A/Swscale
�\x9f�� 55241 xxx  txt       REG               1,18    288384            35692356 /Applications/音流.app/Contents/Frameworks/screen_retriever.framework/Versions/A/screen_retriever
�\x9f�� 55241 xxx  txt       REG               1,18    169200            35691961 /Applications/音流.app/Contents/Frameworks/sqlite3_flutter_libs.framework/Versions/A/sqlite3_flutter_libs
�\x9f�� 55241 xxx  txt       REG               1,18     19328             4465181 /private/var/folders/67/pn4cb9zn7c95b0fzlmr826hm0000gn/C/com.apple.scriptmanager2.le.cache
�\x9f�� 55241 xxx  txt       REG               1,18    245600            35692027 /Applications/音流.app/Contents/Frameworks/media_kit_native_event_loop.framework/Versions/A/media_kit_native_event_loop
�\x9f�� 55241 xxx  txt       REG               1,18    243072            35692219 /Applications/音流.app/Contents/Frameworks/path_provider_foundation.framework/Versions/A/path_provider_foundation
�\x9f�� 55241 xxx  txt       REG               1,18    285824            35692279 /Applications/音流.app/Contents/Frameworks/shared_preferences_foundation.framework/Versions/A/shared_preferences_foundation
�\x9f�� 55241 xxx  txt       REG               1,18    608224            35692323 /Applications/音流.app/Contents/Frameworks/macos_window_utils.framework/Versions/A/macos_window_utils
�\x9f�� 55241 xxx  txt       REG               1,18    436160            35692311 /Applications/音流.app/Contents/Frameworks/window_manager.framework/Versions/A/window_manager
�\x9f�� 55241 xxx  txt       REG               1,18    280560            35692366 /Applications/音流.app/Contents/Frameworks/url_launcher_macos.framework/Versions/A/url_launcher_macos
�\x9f�� 55241 xxx  txt       REG               1,18    496176            35692054 /Applications/音流.app/Contents/Frameworks/sqflite.framework/Versions/A/sqflite
�\x9f�� 55241 xxx  txt       REG               1,18    351136            35692263 /Applications/音流.app/Contents/Frameworks/tray_manager.framework/Versions/A/tray_manager
�\x9f�� 55241 xxx  txt       REG               1,18    238736            35692191 /Applications/音流.app/Contents/Frameworks/wakelock_macos.framework/Versions/A/wakelock_macos
�\x9f�� 55241 xxx  txt       REG               1,18   1513032 1152921500312149309 /System/Library/Extensions/AGXMetalG13X.bundle/Contents/Resources/ds.g13s
�\x9f�� 55241 xxx  txt       REG               1,18      4802 1152921500312163379 /System/Library/Frameworks/AppKit.framework/Versions/C/Resources/DictationManager.loctable
�\x9f�� 55241 xxx  txt       REG               1,18      2798 1152921500312163425 /System/Library/Frameworks/AppKit.framework/Versions/C/Resources/NSColorPanel.loctable
�\x9f�� 55241 xxx  txt       REG               1,18   2344016            35691972 /Applications/音流.app/Contents/Frameworks/sqlite3.framework/Versions/A/sqlite3
�\x9f�� 55241 xxx  txt       REG               1,18    234934 1152921500312230425 /System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/InfoPlist.loctable
�\x9f�� 55241 xxx  txt       REG               1,18   7309104            35692065 /Applications/音流.app/Contents/Frameworks/Mpv.framework/Versions/A/Mpv
�\x9f�� 55241 xxx  txt       REG               1,18   8454144            35998888 /private/var/folders/67/pn4cb9zn7c95b0fzlmr826hm0000gn/0/com.apple.LaunchServices.dv/com.apple.LaunchServices-5019-v2.csstore
�\x9f�� 55241 xxx  txt       REG               1,18   7855176 1152921500312134640 /System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Aqua.car
�\x9f�� 55241 xxx  txt       REG               1,18   2979064 1152921500312134668 /System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantLight.car
�\x9f�� 55241 xxx  txt       REG               1,18   6160456 1152921500312134693 /System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantLight.car
�\x9f�� 55241 xxx  txt       REG               1,18    146873 1152921500312163427 /System/Library/Frameworks/AppKit.framework/Versions/C/Resources/NSColorPanelExtras.loctable
�\x9f�� 55241 xxx  txt       REG               1,18    817232            35691937 /Applications/音流.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/Resources/icudtl.dat
�\x9f�� 55241 xxx  txt       REG               1,18  26447328            35691939 /Applications/音流.app/Contents/Frameworks/FlutterMacOS.framework/Versions/A/FlutterMacOS
�\x9f�� 55241 xxx  txt       REG               1,18  32986592 1152921500312521881 /usr/share/icu/icudt72l.dat
�\x9f�� 55241 xxx  txt       REG               1,18 104865480 1152921500312354983 /System/Library/PrivateFrameworks/SFSymbols.framework/Versions/A/Resources/CoreGlyphs.bundle/Contents/Resources/Assets.car
�\x9f�� 55241 xxx  txt       REG               1,18   8322880 1152921500312161516 /System/Library/Fonts/SFNS.ttf
�\x9f�� 55241 xxx  txt       REG               1,18    133757 1152921500312163409 /System/Library/Frameworks/AppKit.framework/Versions/C/Resources/MenuCommands.loctable
�\x9f�� 55241 xxx  txt       REG               1,18      6020            35692094 /Applications/音流.app/Contents/Frameworks/App.framework/Versions/A/Resources/flutter_assets/packages/cupertino_icons/assets/CupertinoIcons.ttf
�\x9f�� 55241 xxx  txt       REG               1,18   2369592 1152921500312161440 /System/Library/Fonts/Helvetica.ttc
�\x9f�� 55241 xxx  txt       REG               1,18   1455236 1152921500312230423 /System/Library/Keyboard Layouts/AppleKeyboardLayouts.bundle/Contents/Resources/AppleKeyboardLayouts-L.dat
�\x9f�� 55241 xxx  txt       REG               1,18   1305088 1152921500312163237 /System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Assets.car
�\x9f�� 55241 xxx  txt       REG               1,18   3390992 1152921500312134646 /System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/Assets.car
�\x9f�� 55241 xxx  txt       REG               1,18      3372 1152921500312174538 /System/Library/Frameworks/CoreText.framework/Versions/A/Resources/AxisNames.loctable
�\x9f�� 55241 xxx  txt       REG               1,18  23733328            35692075 /Applications/音流.app/Contents/Frameworks/App.framework/Versions/A/App
�\x9f�� 55241 xxx  txt       REG               1,18  77913936 1152921500312161490 /System/Library/Fonts/PingFang.ttc
�\x9f�� 55241 xxx  txt       REG               1,18     16448            35692114 /Applications/音流.app/Contents/Frameworks/App.framework/Versions/A/Resources/flutter_assets/fonts/MaterialIcons-Regular.otf
�\x9f�� 55241 xxx  txt       REG               1,18     36722 1152921500312163411 /System/Library/Frameworks/AppKit.framework/Versions/C/Resources/Menus.loctable
�\x9f�� 55241 xxx  txt       REG               1,18   7744568 1152921500312134652 /System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/DarkAqua.car
�\x9f�� 55241 xxx  txt       REG               1,18     73240 1152921500312134664 /System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/FauxVibrantDark.car
�\x9f�� 55241 xxx  txt       REG               1,18    999424            35692737 /private/var/folders/67/pn4cb9zn7c95b0fzlmr826hm0000gn/C/cn.aqzscn.streamMusic/com.apple.metal/32023/libraries.data
�\x9f�� 55241 xxx  txt       REG               1,18    950272            35692744 /private/var/folders/67/pn4cb9zn7c95b0fzlmr826hm0000gn/C/cn.aqzscn.streamMusic/com.apple.metal/16777235_530/functions.data
�\x9f�� 55241 xxx  txt       REG               1,18     27522 1152921500312170984 /System/Library/Frameworks/ColorSync.framework/Versions/A/Resources/InfoPlist.loctable
�\x9f�� 55241 xxx  txt       REG               1,18   6685032 1152921500312134683 /System/Library/CoreServices/SystemAppearance.bundle/Contents/Resources/VibrantDark.car
�\x9f�� 55241 xxx  txt       REG               1,18   3075344 1152921500312108403 /System/Library/Components/CoreAudio.component/Contents/MacOS/CoreAudio
�\x9f�� 55241 xxx    0r      CHR                3,2       0t0                 335 /dev/null
�\x9f�� 55241 xxx    1u      CHR                3,2     0t273                 335 /dev/null
�\x9f�� 55241 xxx    2u      CHR                3,2     0t299                 335 /dev/null
�\x9f�� 55241 xxx    3u     unix 0xcc4d77e8cd571487       0t0                     ->0xcc4d77e8ce22714f
�\x9f�� 55241 xxx    4r      REG               1,18    142209 1152921500312169814 /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/HIToolbox.rsrc
�\x9f�� 55241 xxx    5r      REG               1,18    490410 1152921500312170417 /System/Library/Frameworks/Carbon.framework/Versions/A/Frameworks/HIToolbox.framework/Versions/A/Resources/zh_CN.lproj/Localized.rsrc
�\x9f�� 55241 xxx    6   NPOLICY
�\x9f�� 55241 xxx    7r      DIR               1,18       320            35692077 /Applications/音流.app/Contents/Frameworks/App.framework/Versions/A/Resources/flutter_assets
�\x9f�� 55241 xxx    8r      DIR               1,18      6240            35692724 /Users/xxx/Library/Caches/flutter_engine/e76c956498841e1ab458577d3892003e553e4f3c/skia/e2621f417ff57ccab752a59bd8c938ade1bb9b4c
�\x9f�� 55241 xxx    9      PIPE 0x8a3706f19d2acb1c     16384                     ->0x29be46e769d90cc1
�\x9f�� 55241 xxx   10r      DIR               1,18        64            35692725 /Users/xxx/Library/Caches/flutter_engine/e76c956498841e1ab458577d3892003e553e4f3c/skia/e2621f417ff57ccab752a59bd8c938ade1bb9b4c/sksl
�\x9f�� 55241 xxx   11      PIPE 0x29be46e769d90cc1     16384                     ->0x8a3706f19d2acb1c
�\x9f�� 55241 xxx   12u   KQUEUE                                                  count=0, state=0xa
�\x9f�� 55241 xxx   13u      REG               1,18  27254784            35692750 /Users/xxx/Library/Application Support/cn.aqzscn.streamMusic/stream_music.db
�\x9f�� 55241 xxx   14u    systm 0xcc4d77e8cafd125f       0t0                     [ctl com.apple.netsrc id 7 unit 49]
�\x9f�� 55241 xxx   15u     unix 0xcc4d77e8cbee00ef       0t0                     ->0xcc4d77e8cc5581b7
�\x9f�� 55241 xxx   16u      REG               1,18      6368            36021358 /Users/xxx/Library/Saved Application State/cn.aqzscn.streamMusic.savedState/data.data
�\x9f�� 55241 xxx   17w      REG               1,18      4900            36021359 /Users/xxx/Library/Saved Application State/cn.aqzscn.streamMusic.savedState/windows.plist
�\x9f�� 55241 xxx   18u      REG               1,18    999424            35692737 /private/var/folders/67/pn4cb9zn7c95b0fzlmr826hm0000gn/C/cn.aqzscn.streamMusic/com.apple.metal/32023/libraries.data
�\x9f�� 55241 xxx   19u      REG               1,18      8724            36021142 /private/var/folders/67/pn4cb9zn7c95b0fzlmr826hm0000gn/C/cn.aqzscn.streamMusic/com.apple.metal/32023/libraries.list
�\x9f�� 55241 xxx   20u      REG               1,18    950272            35692744 /private/var/folders/67/pn4cb9zn7c95b0fzlmr826hm0000gn/C/cn.aqzscn.streamMusic/com.apple.metal/16777235_530/functions.data
�\x9f�� 55241 xxx   21u      REG               1,18     22500            36021143 /private/var/folders/67/pn4cb9zn7c95b0fzlmr826hm0000gn/C/cn.aqzscn.streamMusic/com.apple.metal/16777235_530/functions.list
�\x9f�� 55241 xxx   22u      REG               1,18   1037184            36021360 /Users/xxx/Library/Saved Application State/cn.aqzscn.streamMusic.savedState/window_1.data
�\x9f�� 55241 xxx   23u      REG               1,18   1507328            35693259 /Users/xxx/Library/Application Support/cn.aqzscn.streamMusic/sm_caches/assets.db
�\x9f�� 55241 xxx   24u      REG               1,18     12288            35693237 /Users/xxx/Library/Application Support/cn.aqzscn.streamMusic/libCachedImageData.db
�\x9f�� 55241 xxx   25u     IPv6 0xcc4d77e40279731f       0t0                 TCP localhost:64759 (LISTEN)
�\x9f�� 55241 xxx   29r      REG               1,18  32108806            36020105 /Users/xxx/Library/Caches/sm_caches/songs/61a5160b0d4cd84c67a35cd950ad6e04.flac`

**Comment by gitbobobo** [comment]
这个日志我也看不出什么，不过我一直在用m1芯片的mac，运行是很流畅的，如果你是x86架构的mac，那有可能是只打了arm架构的安装包导致的？

**Comment by 0xganz** [comment]
我是 m2 的忽略吧，偶尔出现的。但是cpu 资源占用比别的软件高
