### ISSUE TITLE
主备线路切换问题

### ISSUE THREAD

**Issue by jayxuz** [gitbobobo/StreamMusic#248]
**Describe the bug (BUG 描述)**
目前使用的群晖DSM7环境下的Audio Station, 家里没有公网v4地址，只有v6地址。使用QC登录
目前办公室wifi没有ipv6地址，但是手机流量是有v6地址的，因此在从wifi环境下离开之后，主线路（ipv4）会切换至备用线路(ipv6)。但是当从外面回到wifi环境后，由于没有ipv6地址，备用线路(ipv6)连接不上，却不会自动切换回主线路（ipv4）。只能杀掉进程，重新启动app。

**To Reproduce (复现步骤)**
1. 关闭用户端wifi路由器的ipv6开关
2. nas端关闭v4的端口转发，仅开放v6的访问
3. 使用QC连接Audio Station
4. wifi连接上时主线路为v4
5. 离开wifi环境，使用流量，自动切换至备用线路（v6）
6. 回到wifi环境，无法从备用线路切换为主线路

**Expected behavior (期望行为)**
- 提供一个手动切换主备线路的选项
- 能够在备用线路不通时自动再次尝试再次连接主线路

**Screenshots (截图)**
![Screenshot_20240425_095055](https://github.com/gitbobobo/StreamMusic/assets/15922466/7b59645c-1278-4881-aae3-22b642e55e05)

**Platform and Device Info (操作系统及设备信息)**
 - OS: 安卓
 - Version 1.2.8

**Music Server Type (音乐服务器类型)**
群晖DSM7环境下的Audio Station

**Comment by gitbobobo** [comment]
1.2.9 已发布
