### ISSUE TITLE
自定义歌词 API 失效后导致无法自动播放下一首

### ISSUE THREAD

**Issue by simpsonkoo** [gitbobobo/StreamMusic#250]
navidrome库，ios短升级128后，经常播放完当前那首歌就停了，要开屏或者手动按播放才会播下一首，是加入的淡入淡出的缘故？话说音量淡入淡出没看到选项也没听出有效果啊。还有就是打开app时是连着Wi-Fi的，过阵子离开了wifi范围，手机切换到流量了，播完当前那首歌就卡住了，要重启app才能正常播了。还有调节音量的控制条不能放在播放页么？

**Comment by gitbobobo** [comment]
iOS我没遇到自动停的问题

淡入淡出听不出效果我也没办法

备用线路目前逻辑有点问题，下个版本优化

不能

**Comment by simpsonkoo** [comment]
是自定义歌词api的原因，关了歌词就不会停止播放了

**Comment by gitbobobo** [comment]
自定义api正常来说是不会影响到播放相关的问题的

如果真是这个原因，反馈的人应该会挺多的

**Comment by greatkeke** [comment]
我也遇到这个问题了，删除重新安装也不行，各种设置都试过，没用。
不知道哪里可以把日志导出来吗？

**Comment by gitbobobo** [comment]
@simpsonkoo 似乎确实有这个问题，歌词API失效后会导致这个问题，我没部署过歌词API，你这里有可以公网访问的歌词API吗

**Comment by simpsonkoo** [comment]
https://api.lrc.cx/lyrics这个可以用 ，就是开了会播放出问题 ，现在都没用了

**Comment by gitbobobo** [comment]
1.3.0已发布
