### ISSUE TITLE
我是用Audio Station授权音流使用的，在这个场景下同样是MP3格式，部分歌曲在音流上播放不了，拖动等操作都没用，在Audio Station使用正常。

### ISSUE THREAD

**Issue by jiaobaba1027** [gitbobobo/StreamMusic#251]
我是用Audio Station授权音流使用的，在这个场景下同样是MP3格式，部分歌曲在音流上播放不了，拖动等操作都没用，在Audio Station使用正常。

https://github.com/gitbobobo/StreamMusic/assets/119810187/05c17eb2-dfc1-420e-981b-8c5b8cad5f00

https://github.com/gitbobobo/StreamMusic/assets/119810187/858de68b-ef5b-4c28-bf3d-dc15ac880396

**Comment by gitbobobo** [comment]
看下日志有什么报错

**Comment by jiaobaba1027** [comment]
963874846
***@***.***
能否加一下我的飞机，我不是专业的程序员，不知道日志在哪 
---- 回复的原邮件 ----
***@***.***>发送日期2024年4月26日 ***@***.***>***@***.***>,
***@***.***>主题Re: [gitbobobo/StreamMusic] 我是用Audio Station授权音流使用的，在这个场景下同样是MP3格式，部分歌曲在音流上播放不了，拖动等操作都没用，在Audio Station使用正常。 (Issue #251)
看下日志有什么报错

**Comment by jiaobaba1027** [comment]
我下载的是客户端 ，不知道日志在哪，怎么发

**Comment by gitbobobo** [comment]
仓库首页有说明

**Comment by jiaobaba1027** [comment]
![1](https://github.com/gitbobobo/StreamMusic/assets/119810187/2b3f0fea-0e02-49ba-965a-6f3b31cf73d4)

**Comment by gitbobobo** [comment]
清除下存储空间再试试同一首歌能否播放，目前感觉是因为歌曲因某种原因没有缓存完导致的

**Comment by jiaobaba1027** [comment]
INFO 02:41:30.130 (+0:00:00.002044)
   INFO 💡 当前版本：1.2.8，构建次数：66
   INFO 02:41:30.132 (+0:00:00.003969)
   INFO 💡 当前网络连接类型：WiFi
   INFO 02:41:30.137 (+0:00:00.009376)
   INFO 💡 数据库位置：/var/mobile/Containers/Data/Application/152A05BD-CC71-4F5C-BD46-DC5033937E09/Documents/stream_music.db
   INFO 02:41:30.145 (+0:00:00.017234)
   INFO 💡 数据库版本：15
   INFO 02:41:30.251 (+0:00:00.123112)
   INFO 💡 歌曲占用空间: 1.91 GB，元数据占用空间: 8.97 MB，系统占用空间: 1.17 MB
   INFO 02:41:30.261 (+0:00:00.132974)
   INFO 💡 应用初始化完毕
   INFO 02:41:30.587 (+0:00:00.459165)
   INFO 💡 最新版本: 1.2.7
   INFO 02:41:31.554 (+0:00:01.426553)
   INFO 💡 上次播放队列歌曲数量：439
   INFO 02:41:31.554 (+0:00:01.426654)
   INFO 💡 播放列表恢复完成
   INFO 02:41:31.571 (+0:00:01.442995)
   INFO 💡 代理服务已启动，端口号: 57947
   INFO 02:41:31.722 (+0:00:01.593955)
   INFO 💡 服务器歌曲数量：439，本地歌曲数量：439
   INFO 02:41:31.722 (+0:00:01.593975)
   INFO 💡 服务端歌曲数量少于本地歌曲数量，无需同步
   INFO 02:41:31.722 (+0:00:01.594276)
   INFO 💡 服务器数据同步完成
   INFO 02:41:41.970 (+0:00:11.842392)
   INFO 💡 跳转链接：https://music.aqzscn.cn/
   INFO 10:33:52.394 (+7:52:22.266092)
   INFO 💡 当前网络连接类型：WiFi
   INFO 10:33:52.508 (+7:52:22.380413)
   INFO 💡 歌曲占用空间: 1.91 GB，元数据占用空间: 8.97 MB，系统占用空间: 1.17 MB
   INFO 10:33:54.328 (+7:52:24.200778)
   INFO 💡 跳转链接：https://music.aqzscn.cn/
   INFO 10:34:01.409 (+7:52:31.281494)
   INFO 💡 跳转链接：https://github.com/gitbobobo/StreamMusic
   INFO 21:51:04.206 (+0:00:00.003643)
   INFO 💡 当前版本：1.2.8，构建次数：66
   INFO 21:51:04.213 (+0:00:00.010255)
   INFO 💡 当前网络连接类型：WiFi
   INFO 21:51:04.213 (+0:00:00.010448)
   INFO 💡 数据库位置：/var/mobile/Containers/Data/Application/152A05BD-CC71-4F5C-BD46-DC5033937E09/Documents/stream_music.db
   INFO 21:51:04.220 (+0:00:00.017067)
   INFO 💡 数据库版本：15
   INFO 21:51:04.313 (+0:00:00.110542)
   INFO 💡 歌曲占用空间: 1.91 GB，元数据占用空间: 8.97 MB，系统占用空间: 1.17 MB
   INFO 21:51:04.322 (+0:00:00.119718)
   INFO 💡 应用初始化完毕
   INFO 21:51:04.614 (+0:00:00.411495)
   INFO 💡 最新版本: 1.2.7
   INFO 21:51:06.185 (+0:00:01.982022)
   INFO 💡 上次播放队列歌曲数量：439
   INFO 21:51:06.185 (+0:00:01.982111)
   INFO 💡 播放列表恢复完成
   INFO 21:51:06.202 (+0:00:01.998972)
   INFO 💡 代理服务已启动，端口号: 50481
   INFO 21:51:06.310 (+0:00:02.107797)
   INFO 💡 服务器歌曲数量：439，本地歌曲数量：439
   INFO 21:51:06.310 (+0:00:02.107813)
   INFO 💡 服务端歌曲数量少于本地歌曲数量，无需同步
   INFO 21:51:06.311 (+0:00:02.108098)
   INFO 💡 服务器数据同步完成
   INFO 21:51:06.885 (+0:00:02.682207)
   INFO 💡 当前网络连接类型：WiFi
   INFO 21:51:08.763 (+0:00:04.560701)
   INFO 💡 服务器歌曲数量：439，本地歌曲数量：439
   INFO 21:51:08.763 (+0:00:04.560763)
   INFO 💡 同步歌曲数据中(id: U3wAfujiDj)
   INFO 21:51:08.763 (+0:00:04.560841)
   INFO 💡 同步专辑数据中(id: U3wAfujiDj)
   INFO 21:51:08.764 (+0:00:04.561089)
   INFO 💡 同步歌手数据中(id: U3wAfujiDj)
   INFO 21:51:09.264 (+0:00:05.061459)
   INFO 💡 歌手数据同步完成(id: U3wAfujiDj)
   INFO 21:51:09.323 (+0:00:05.120243)
   INFO 💡 专辑数据同步完成(id: U3wAfujiDj)
   INFO 21:51:09.953 (+0:00:05.750456)
   INFO 💡 歌曲数据同步完成(id: U3wAfujiDj)
   INFO 21:51:09.953 (+0:00:05.750468)
   INFO 💡 同步歌单数据中(id: U3wAfujiDj)
   INFO 21:51:10.024 (+0:00:05.821732)
   INFO 💡 歌单数据同步完成(id: U3wAfujiDj)
   INFO 21:51:10.024 (+0:00:05.821803)
   INFO 💡 服务器数据同步完成
   INFO 21:51:18.906 (+0:00:14.703265)
   INFO 💡 服务器歌曲数量：439，本地歌曲数量：439
   INFO 21:51:18.906 (+0:00:14.703323)
   INFO 💡 同步歌曲数据中(id: 1SO8fNIECX)
   INFO 21:51:18.906 (+0:00:14.703401)
   INFO 💡 同步专辑数据中(id: 1SO8fNIECX)
   INFO 21:51:18.906 (+0:00:14.703480)
   INFO 💡 同步歌手数据中(id: 1SO8fNIECX)
   INFO 21:51:19.252 (+0:00:15.049873)
   INFO 💡 歌手数据同步完成(id: 1SO8fNIECX)
   INFO 21:51:19.443 (+0:00:15.239973)
   INFO 💡 专辑数据同步完成(id: 1SO8fNIECX)
   INFO 21:51:19.947 (+0:00:15.744509)
   INFO 💡 歌曲数据同步完成(id: 1SO8fNIECX)
   INFO 21:51:19.947 (+0:00:15.744522)
   INFO 💡 同步歌单数据中(id: 1SO8fNIECX)
   INFO 21:51:20.031 (+0:00:15.827915)
   INFO 💡 歌单数据同步完成(id: 1SO8fNIECX)
   INFO 21:51:20.031 (+0:00:15.827961)
   INFO 💡 服务器数据同步完成
   INFO 21:51:25.023 (+0:00:20.820469)
   INFO 💡 歌曲占用空间: 1.91 GB，元数据占用空间: 8.78 MB，系统占用空间: 1.17 MB
  ERROR 21:51:25.079 (+0:00:20.876635)
  ERROR ⛔ 播放异常：Failed to open http://localhost:50481/MP3/webapi/AudioStation/stream.cgi?api=SYNO.AudioStation.Stream&version=2&method=stream&id=music_3346&_sid=Ks7_hOA5NhVBbnPqZOANjsEeu30VWJD7MqJA0loAB8EXbLgiMWRmOaMVw-yIHwTZPX_36Qfs0Wvx8Ox2yOUKPE.
   INFO 21:53:00.493 (+0:01:56.290583)
   INFO 💡 服务器歌曲数量：0，本地歌曲数量：439
   INFO 21:53:00.493 (+0:01:56.290629)
   INFO 💡 同步歌曲数据中(id: 3DiIigKvfy)
   INFO 21:53:00.493 (+0:01:56.290698)
   INFO 💡 同步专辑数据中(id: 3DiIigKvfy)
   INFO 21:53:00.493 (+0:01:56.290767)
   INFO 💡 同步歌手数据中(id: 3DiIigKvfy)
   INFO 21:53:00.851 (+0:01:56.648521)
   INFO 💡 专辑数据同步完成(id: 3DiIigKvfy)
   INFO 21:53:00.861 (+0:01:56.658309)
   INFO 💡 歌手数据同步完成(id: 3DiIigKvfy)
   INFO 21:53:00.884 (+0:01:56.681106)
   INFO 💡 歌曲数据同步完成(id: 3DiIigKvfy)
   INFO 21:53:00.884 (+0:01:56.681145)
   INFO 💡 同步歌单数据中(id: 3DiIigKvfy)
   INFO 21:53:00.957 (+0:01:56.754178)
   INFO 💡 歌单数据同步完成(id: 3DiIigKvfy)
   INFO 21:53:00.957 (+0:01:56.754441)
   INFO 💡 服务器数据同步完成
   INFO 21:54:45.795 (+0:03:41.592546)
   INFO 💡 服务器歌曲数量：439，本地歌曲数量：0
   INFO 21:54:45.795 (+0:03:41.592600)
   INFO 💡 同步歌曲数据中(id: GpZSr38GwF)
   INFO 21:54:45.795 (+0:03:41.592685)
   INFO 💡 同步专辑数据中(id: GpZSr38GwF)
   INFO 21:54:45.795 (+0:03:41.592756)
   INFO 💡 同步歌手数据中(id: GpZSr38GwF)
   INFO 21:54:46.122 (+0:03:41.919648)
   INFO 💡 歌手数据同步完成(id: GpZSr38GwF)
   INFO 21:54:46.171 (+0:03:41.968364)
   INFO 💡 专辑数据同步完成(id: GpZSr38GwF)
   INFO 21:54:46.805 (+0:03:42.601994)
   INFO 💡 歌曲数据同步完成(id: GpZSr38GwF)
   INFO 21:54:46.805 (+0:03:42.602007)
   INFO 💡 同步歌单数据中(id: GpZSr38GwF)
   INFO 21:54:46.876 (+0:03:42.673868)
   INFO 💡 歌单数据同步完成(id: GpZSr38GwF)
   INFO 21:54:46.877 (+0:03:42.673939)
   INFO 💡 服务器数据同步完成
   INFO 21:54:50.249 (+0:03:46.046482)
   INFO 💡 歌曲占用空间: 1.91 GB，元数据占用空间: 8.78 MB，系统占用空间: 1.17 MB
  ERROR 21:54:50.312 (+0:03:46.109811)
  ERROR ⛔ 播放异常：Failed to open http://localhost:50481/MP3/webapi/AudioStation/stream.cgi?api=SYNO.AudioStation.Stream&version=2&method=stream&id=music_3785&_sid=Ks7_hOA5NhVBbnPqZOANjsEeu30VWJD7MqJA0loAB8EXbLgiMWRmOaMVw-yIHwTZPX_36Qfs0Wvx8Ox2yOUKPE.
   INFO 21:55:01.001 (+0:03:56.798212)
   INFO 💡 歌曲占用空间: 1.92 GB，元数据占用空间: 9.00 MB，系统占用空间: 1.18 MB
  ERROR 21:55:01.049 (+0:03:56.846284)
  ERROR ⛔ 播放异常：Failed to open http://localhost:50481/MP3/webapi/AudioStation/stream.cgi?api=SYNO.AudioStation.Stream&version=2&method=stream&id=music_3810&_sid=Ks7_hOA5NhVBbnPqZOANjsEeu30VWJD7MqJA0loAB8EXbLgiMWRmOaMVw-yIHwTZPX_36Qfs0Wvx8Ox2yOUKPE.

**Comment by jiaobaba1027** [comment]
没用

**Comment by jiaobaba1027** [comment]
此bug挺影响使用的

**Comment by gitbobobo** [comment]
为什么你的播放地址后面会有 `MP3` ？正常应该是没有的，你是用地址登录的？

**Comment by jiaobaba1027** [comment]
是的，我去掉试试

**Comment by jiaobaba1027** [comment]
还真是地址的问题，已可以正常使用。是否需要我删除这个提问。

**Comment by gitbobobo** [comment]
我直接关闭吧，还有问题的话可以重新打开

**Comment by jiaobaba1027** [comment]
好的
