### ISSUE TITLE
windows安装后播放音乐报错

### ISSUE THREAD

**Issue by leG09** [gitbobobo/StreamMusic#252]
**Platform and Device Info (操作系统及设备信息)**
 - OS: Windows 10
 - Version 1.2.8

**Music Server Type (音乐服务器类型)**
DS Audio

**Additional context (额外信息)**
ERROR ⛔ 2024-04-26 14:23:14.083760	0:00:00.010623	GET	/webapi/AudioStation/stream.cgi?api=SYNO.AudioStation.Stream&version=2&method=stream&id=music_645&_sid=kCigNrgCqlkaE1780PDN809789
  ERROR ⛔ FormatException: Invalid HTTP header field value: "C:\\Users\\é¹ææ¾\\AppData\\Local\\Temp\\sm_caches\\songs\\music_645.flac" (at character 10)
  ERROR ⛔ C:\Users\é¹ææ¾\AppData\Local\Temp\sm_caches\songs\music_645.flac
  ERROR ⛔          ^
  ERROR ⛔ 
  ERROR ⛔ unparsed  *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
  ERROR ⛔ unparsed  pid: 14588, tid: 35812, name io.flutter.ui
  ERROR ⛔ unparsed  os: windows arch: x64 comp: no sim: no
  ERROR ⛔ unparsed  build_id: '8d24fa665d7126a2447c75394554b408'
  ERROR ⛔ unparsed  isolate_dso_base: 1ddd6a00000, vm_dso_base: 1ddd6a00000
  ERROR ⛔ unparsed  isolate_instructions: 1ddd6e4a600, vm_instructions: 1ddd6e44000
  ERROR ⛔ unparsed      #00 abs 000001ddd6e8a1ae virt 000000000048a1ae _kDartIsolateSnapshotInstructions+0x3fbae
  ERROR ⛔ unparsed      #01 abs 000001ddd707a9f0 virt 000000000067a9f0 _kDartIsolateSnapshotInstructions+0x2303f0
  ERROR ⛔ unparsed      #02 abs 000001ddd70831fc virt 00000000006831fc _kDartIsolateSnapshotInstructions+0x238bfc
  ERROR ⛔ unparsed      #03 abs 000001ddd718ef0b virt 000000000078ef0b _kDartIsolateSnapshotInstructions+0x34490b
  ERROR ⛔ unparsed      #04 abs 000001ddd6e710fd virt 00000000004710fd _kDartIsolateSnapshotInstructions+0x26afd
  ERROR ⛔ unparsed      #05 abs 000001ddd74cde17 virt 0000000000acde17 _kDartIsolateSnapshotInstructions+0x683817

**Comment by gitbobobo** [comment]
和这个问题 https://github.com/gitbobobo/StreamMusic/issues/242 应该是一样的，先把你的关闭了哈
