### ISSUE TITLE
已入正，车机安卓4.2，新版无法安装，请教使用历史版本，哪个版本能够稳定支持AudioStation？请作者大佬给个版本号感谢！

### ISSUE THREAD

**Issue by www766** [gitbobobo/StreamMusic#253]
已入正，车机是安卓4.2，新版无法安装，请教使用历史版本，哪个版本能够稳定支持AudioStation？请作者大佬给个版本号感谢！

**Comment by gitbobobo** [comment]
历史版本应该都不支持4.2的，稳定支持AudioStation的话，1.2.x中除了1.2.7，其他应该都可以的
