### ISSUE TITLE
DLNA 播放失败

### ISSUE THREAD

**Issue by roccox** [gitbobobo/StreamMusic#254]
DLNA设备找到的都是重复两个，但是任何一个都无法正常播放。

Android版本1.2.8中每次都可以复现，以前的版本1.2.6和1.2.7都是正常的。

服务器Navidrome

**Comment by XlangNan** [comment]
我的也失败 我的的小米音响 HD

**Comment by gitbobobo** [comment]
目前dlna兼容性不太好，预计1.3.1或1.3.2进行修复

**Comment by jasonliuspark123** [comment]
+1 dlna 更新之后就挂了

**Comment by gitbobobo** [comment]
1.3.1已修复
