### ISSUE TITLE
无法播放wav文件

### ISSUE THREAD

**Issue by RinChan520** [gitbobobo/StreamMusic#255]
**Describe the bug (BUG 描述)**
第一次可以播放，这个文件是96khz的，文件大小约185M，市场约5分钟，公网播放，上行带宽约20Mbps
在第一次播放时，需要的网络速度远超实际所需，20Mbps是完全足够满足这个码率与大小的歌曲的，但实际播放效果是播放1秒卡顿3秒。带宽方面，则是全程20Mbps吃满。在DS Audio在开始的短暂缓冲后可流畅播放，网页端亦如此。
在关闭软件重新打开后，将无法播放这首歌曲，时间显示为00:00，日志如下

**To Reproduce (复现步骤)**
如上述

**Expected behavior (期望行为)**
正常播放歌曲，并使用正常的网络带宽速率

**Screenshots (截图)**
![image](https://github.com/gitbobobo/StreamMusic/assets/46668578/3f38f3e7-a927-4ec3-ad31-11ae13e0345e)

**Platform and Device Info (操作系统及设备信息)**
 - OS: Windows 11
 - Version 1.2.8

**Music Server Type (音乐服务器类型)**
Audio Station （DSM7.2）

**Additional context (额外信息)**
INFO 💡 当前版本：1.2.8，构建次数：67
   INFO 19:28:00.629 (+0:00:00.005010)
   INFO 💡 数据库位置：C:\Users\MagicRin\AppData\Roaming\cn.aqzscn\stream_music\stream_music.db
   INFO 19:28:00.634 (+0:00:00.010524)
   INFO 💡 数据库版本：15
   INFO 19:28:00.634 (+0:00:00.010524)
   INFO 💡 恢复窗口信息：width:1350.0,height:981.0
   INFO 19:28:00.646 (+0:00:00.022048)
   INFO 💡 当前网络连接类型：以太网
   INFO 19:28:00.683 (+0:00:00.059237)
   INFO 💡 歌曲占用空间: 1.27 GB，元数据占用空间: 13.62 MB，系统占用空间: 1.51 MB
   INFO 19:28:00.683 (+0:00:00.059237)
   INFO 💡 应用初始化完毕
   INFO 19:28:01.293 (+0:00:00.669086)
   INFO 💡 上次播放队列歌曲数量：3
   INFO 19:28:01.293 (+0:00:00.669086)
   INFO 💡 播放列表恢复完成
   INFO 19:28:01.346 (+0:00:00.722123)
   INFO 💡 代理服务已启动，端口号: 54967
   INFO 19:28:01.513 (+0:00:00.889461)
   INFO 💡 最新版本: 1.2.7
   INFO 19:28:01.522 (+0:00:00.898216)
   INFO 💡 服务器歌曲数量：1859，本地歌曲数量：1859
   INFO 19:28:01.522 (+0:00:00.898216)
   INFO 💡 服务端歌曲数量少于本地歌曲数量，无需同步
   INFO 19:28:01.522 (+0:00:00.898216)
   INFO 💡 服务器数据同步完成
  ERROR 19:28:01.821 (+0:00:01.197164)
  ERROR ⛔ 播放异常：Failed to recognize file format.
   INFO 19:28:03.656 (+0:00:03.032271)
   INFO 💡 [player]开始播放

**Comment by Oman4** [comment]
我也有相同的BUG，AudioStation 群晖6.1.3 放第二次提示同样的错误
![微信图片_20240429000956](https://github.com/gitbobobo/StreamMusic/assets/11306488/e9791180-01f0-4fff-b81b-9d9cfb788692)

https://github.com/gitbobobo/StreamMusic/assets/11306488/585b1325-d2eb-47b9-900e-849285ca0b91

**Comment by MiyamuraMiyako** [comment]
遇到过类似问题：第一次播放wav没问题，只要切换到其他歌曲（不管这个wav是否被完整缓存）再切换回来必定不能播放（通知栏上有进度在走，但是主界面上的进度是0，长度也是0）
![图片](https://github.com/user-attachments/assets/3912d5d6-df62-429c-a26d-539cb3961352)
