### ISSUE TITLE
已入正plex数据库怎么选择急

### ISSUE THREAD

**Issue by yche2990** [gitbobobo/StreamMusic#259]
我登录上plex后，无法选择数据库啊，我有音乐也有戏曲，可是默认只链接了一个戏曲数据库，当有多个数据库如何自定义哪个啊，急，要不无法使用

**Comment by yche2990** [comment]
那如何自定义选择啊，重新登录界面就只能选择服务器，不能选择服务器下的哪个资料库

**Comment by gitbobobo** [comment]
等下个版本修复吧，现在是自动选择了第一个媒体库

**Comment by yche2990** [comment]
谢谢，麻烦今早修复
