### ISSUE TITLE
【bug】1.2.8安卓音流在后台放置一段时间后，无法播放

### ISSUE THREAD

**Issue by Oman4** [gitbobobo/StreamMusic#260]
**Describe the bug (BUG 描述)**
正常播放，暂停操作，放到后台不杀死，一两个小时后后台打开音流，无法播放，切音乐也无法播放，杀死程序重开后恢复正常

**To Reproduce (复现步骤)**
1. 打开音流正常播放一段时间，暂停
![微信图片_20240428174646](https://github.com/gitbobobo/StreamMusic/assets/11306488/74aa27c8-3b6c-4f33-9207-8c66e4e2f470)

2. 放置后台，不杀死
3. 一段时间后打开软件，软件无法播放
![微信图片编辑_20240428175549](https://github.com/gitbobobo/StreamMusic/assets/11306488/ca760c19-a701-47a3-92c8-72deede07d7e)

4. 切换音乐也无法播放，下面的播放时长和播放时间均为0

**Expected behavior (期望行为)**
软件可以正常播放

**Platform and Device Info (操作系统及设备信息)**
 - OS: realme GT neo 5 Android 14 RealmeUI 5.0（ColorOS） 
 - Version 1.2.8 付费

**Music Server Type (音乐服务器类型)**
autioStation 群晖6.1.3

**Additional context (额外信息)**
后台无报错日志
电池优化 关闭

**Comment by gitbobobo** [comment]
可能是登录状态过期了，试试在首页下拉刷新有没有用

**Comment by gitbobobo** [comment]
1.2.9 已优化登录过期重新登录的逻辑
