### ISSUE TITLE
[BUG,功能改进] 1.播放模式记忆 2.主副线路切换  ..

### ISSUE THREAD

**Issue by AprDeci** [gitbobobo/StreamMusic#261]
功能改进 : 

1. 希望可以记忆播放模式,不用每次重新点击,如今是切歌或者关闭APP都会变成顺序播放
2. 桌面歌词可以调整左右,不只是高度
3. 我的歌单页面能否添加创建歌单按钮
4. 在不同目录切换歌曲不会直接播放需要在播放页面再次点击,请问这是专门这么设计的吗?如果不是希望可以点击直接播放

BUG:
 系统:鸿蒙4 设备 matepad11
1. 使用一会就不会播放了，必须重开。
2. 偶尔关闭屏幕音乐暂停(已关闭电池优化),重新开启APP解决
3. 主线路ipv6,副线路ipv4,使用仅有ipv4的wifi时不会切换到副线路

**Comment by gitbobobo** [comment]
记忆播放模式的功能，可以翻下官网的文档

桌面歌词之后会增加更多自定义选项

emby直接创建空歌单会导致音流找不到刚创建的歌单，因此不能直接创建。

后台播放暂停的问题，一是要允许后台运行或关掉电池优化，若还是会暂停，找找系统设置里有没有自动限制单个应用数据流量的配置，关掉应该就可以了。

线路切换这个是有bug

**Comment by Pastechn** [comment]
同遇到了线路切换的问题
不过我这儿在都是IPv4的情况下 主线路是内网http地址 备用线路是外网https地址
在某一次使用流量的情况下 主线路无法连接的情况下（直接用浏览器访问主线路显示connection refused）一直无法切换至备用线路
而在另外一次使用流量 且主线路无法连接的情况下（直接用浏览器访问主线路显示connection timed out）则在手动刷新一次后可以切换至备用线路

**Comment by AprDeci** [comment]
> 记忆播放模式的功能，可以翻下官网的文档
> 
> 桌面歌词之后会增加更多自定义选项
> 
> emby直接创建空歌单会导致音流找不到刚创建的歌单，因此不能直接创建。
> 
> 后台播放暂停的问题，一是要允许后台运行或关掉电池优化，若还是会暂停，找找系统设置里有没有自动限制单个应用数据流量的配置，关掉应该就可以了。
> 
> 线路切换这个是有bug

感谢回复,最近用下来还有几个问题.
1. 每次手机(魅族20)/平板(matepad11)重启后初次打开APP,都会停在启动图处,需要关进程重新开启.
2. 在不同目录切换歌曲不会直接播放需要在播放页面再次点击,请问这是专门这么设计的吗?如果不是希望可以点击直接播放
3. 感觉同步还是需要很多次手动同步,要是能更丝滑点就更好了

**Comment by gitbobobo** [comment]
1.2.9 升级了线路配置功能
