### ISSUE TITLE
手机APP IPV6无法播放

### ISSUE THREAD

**Issue by bugleigt** [gitbobobo/StreamMusic#265]
手机APP IPV6无法播放的问题，请问下有解决的办法吗

**Comment by picpo** [comment]
我iOS上的最新版本，未开代理的情况下还支持本地局域网ipv6的播放。
但是开了代理就不行了，同一台机器上的其他端口的ipv6服务我能正常访问，包括直接访问网页端navidrome都行，就是音流无法连接

**Comment by gitbobobo** [comment]
需要在代理软件内排除对127.0.0.1或localhost的代理
