### ISSUE TITLE
备用线路切换

### ISSUE THREAD

**Issue by helscn** [gitbobobo/StreamMusic#266]
**Describe the bug (BUG 描述)**
购买VIP后，无法设置主、副线路。

**To Reproduce (复现步骤)**
1、打开App后，媒体界面上显示为主线路；
2、进入设置界面，找不到主、副线路地址设置选项。

**Expected behavior (期望行为)**
显示主、副线路切换设置

**Screenshots (截图)**
![Screenshot_2024-05-02-09-19-56-549_cn aqzscn stream_music](https://github.com/gitbobobo/StreamMusic/assets/6456837/25d6f782-84f0-4815-8cdf-8a4869d2e375)
![Screenshot_2024-05-02-09-42-39-144_cn aqzscn stream_music](https://github.com/gitbobobo/StreamMusic/assets/6456837/be8b331f-865e-4d85-90b2-894259addecd)

**Platform and Device Info (操作系统及设备信息)**
 - 小米10 Pro / MIUI 14.0.4 / 音流安卓版 1.2.8
 - Windows 10 22H2 / 音流Windows版 1.2.8

**Music Server Type (音乐服务器类型)**
DSM 7.2.1-69057 Update 5
DS Audio Version 7.1.0-5508

**Comment by gitbobobo** [comment]
用qc ID登录会自动选择可以连接的线路，所以没有这个选项。

若你是用地址登录的，那可能就是程序逻辑有问题了

**Comment by helscn** [comment]
没有用QC登录，不管是用内网http://192.168.31.157，还是外网域名访问，都没有出现备用线路的设置，我用苹果手机登上去后也没这个设置选项。

**Comment by littlebabay** [comment]
我这边发现设置了备用线路之后，即使主线路连不上也不会切到备用线路 @gitbobobo

**Comment by gitbobobo** [comment]
1.2.9 已升级此功能

**Comment by helscn** [comment]
感谢，测试过已经可以设置备用线路了。
