### ISSUE TITLE
希望增加一个标记不喜欢歌曲的功能，用于后续清理不喜欢的歌曲

### ISSUE THREAD

**Issue by littlebabay** [gitbobobo/StreamMusic#270]
**需求描述：**
作为NAS使用场景，我们经常会一次性加入很多首歌曲，其中肯定会有很多陌生的不喜欢的歌曲。希望增加一个“不喜欢”功能，并可设置在N次点 “不喜欢” 后，主动或被动删除该歌曲，用于清理那些听了多次仍然不喜欢的歌曲。

**操作逻辑：**
1. 在歌曲播放页面显示 “不喜欢” 图标，可以跟“喜欢”图标并列。
2. 点击一次”不喜欢“， 则标记点击次数，并在图标上叠加显示次数。
3. 可在设置页面设置是否在歌曲被点击N次”不喜欢“之后自动删除歌曲。
4. 每点击一次”喜欢“可抵消一次”不喜欢“。

**Comment by gitbobobo** [comment]
这样的操作逻辑过于复杂了，而且我希望播放界面能保持简洁，不需要太复杂的元素。

正如群里所说，这个功能完全可以通过新建一个歌单来实现，没有必要单独做个新功能，而且这个功能还无法将数据存到服务端。

清理不喜欢的歌曲这个功能，个人感觉用NAS了其实必要性就不大了，空间又不紧张，万一哪天心血来潮想听也不用重新下载。

还有，自动删除服务端歌曲可是打死也不敢做的啊，万一删错了多尴尬，不求有功，但求无过。

**Comment by littlebabay** [comment]
> 这样的操作逻辑过于复杂了，而且我希望播放界面能保持简洁，不需要太复杂的元素。
> 
> 正如群里所说，这个功能完全可以通过新建一个歌单来实现，没有必要单独做个新功能，而且这个功能还无法将数据存到服务端。
> 
> 清理不喜欢的歌曲这个功能，个人感觉用NAS了其实必要性就不大了，空间又不紧张，万一哪天心血来潮想听也不用重新下载。
> 
> 还有，自动删除服务端歌曲可是打死也不敢做的啊，万一删错了多尴尬，不求有功，但求无过。

好的，你说的有道理
