### ISSUE TITLE
1.2.8后台播放几分钟会自动暂停

### ISSUE THREAD

**Issue by zjzheng666** [gitbobobo/StreamMusic#272]
BUG ：在后台播放时，大约七八分钟会暂停，进入app像是被杀后台似的，但后台限制设置的无限制。
复现步骤：每次播放，把app放在后台播放七八分钟左右。
期望行为：后台正常播放。
音乐服务器类型：Navidrome。
操作系统与设备：小米10，Android13。xiaomi HyperOS 1.0.3.0

昨天刚升的1.2.8,。之前1.2.7版本无这个问题。
重新删除app安装，歌单同步不到了o(╥﹏╥)o

**Comment by zjzheng666** [comment]
同步问题，把增量同步关闭，然后退出app重新打开，点击立即同步可以了。

**Comment by gitbobobo** [comment]
Navidrome超过5w首歌后按添加时间排序的接口会报错，可能会导致后续步骤无法开始（歌曲同步完成后才会同步歌单）

自动暂停的问题，可以找找限制数据流量的设置

**Comment by zjzheng666** [comment]
> Navidrome超过5w首歌后按添加时间排序的接口会报错，可能会导致后续步骤无法开始（歌曲同步完成后才会同步歌单）
> 
> 自动暂停的问题，可以找找限制数据流量的设置

歌曲数量确实超过五万了。
自动暂停问题，重新安装了一遍，测试了半小时没问题了。

**Comment by zjzheng666** [comment]
1.2.9没有暂停问题了
