### ISSUE TITLE
无法使用subsonic api登录airsonic

### ISSUE THREAD

**Issue by yuygfgg** [gitbobobo/StreamMusic#274]
**Describe the bug (BUG 描述)**
无法登陆airsonic
**To Reproduce (复现步骤)**
选择subsonic，输入正确地址，用户名密码，点击登录

**Expected behavior (期望行为)**
成功登录
**Screenshots (截图)**
<img width="995" alt="截屏2024-05-08 08 30 21" src="https://github.com/gitbobobo/StreamMusic/assets/140488233/dd1806c4-a0df-4f9c-ab1c-d7a792b297e4">

**Platform and Device Info (操作系统及设备信息)**
 - OS: all（IOS, macos, windows)
 - Version latest

**Music Server Type (音乐服务器类型)**
e.g. airsonic-advanced

**Additional context (额外信息)**
应该是音流不支持老的api登录方式，所以无法登陆

```
2024-05-08 08:30:15.457  INFO --- o.a.p.s.GlobalSecurityConfig             : Login failed from [192.168.110.115]
```

**Comment by gitbobobo** [comment]
最近在开发直连模式的过程中也尝试过对 Arisonic 进行适配，但很遗憾的是，即使可以登录成功，进入软件后也有很多接口没办法使用。

所以只能给你提两个建议：

1. 切换音流支持的服务端，如 Navidrome，Gonic（Gonic将在直连模式推出后支持）
2. 使用其他支持 Arisonic 的客户端

**Comment by yuygfgg** [comment]
> 最近在开发直连模式的过程中也尝试过对 Arisonic 进行适配，但很遗憾的是，即使可以登录成功，进入软件后也有很多接口没办法使用。
> 
> 所以只能给你提两个建议：
> 
> 1. 切换音流支持的服务端，如 Navidrome，Gonic（Gonic将在直连模式推出后支持）
> 2. 使用其他支持 Arisonic 的客户端

其他使用subsonic api的软件可以很好的适配airsonic（如开源的amperfy, substreasmer)，而且只有kagemomiji/airsonic-advanced这一个服务端能够处理内嵌cue的flac，所以我没法换服务端

对了，大概一星期前我用音流登录进airsonic过，是更新之后去掉了吗

**Comment by gitbobobo** [comment]
它们能支持是因为它们没有查询全部歌曲的页面，而音流需要这个接口（可能还有其他缺失的接口）

我也是用的 airsonic-advanced 测试的，之前版本一直都不支持老的验证方式的

**Comment by yuygfgg** [comment]
> 它们能支持是因为它们没有查询全部歌曲的页面，而音流需要这个接口（可能还有其他缺失的接口）
> 
> 我也是用的 airsonic-advanced 测试的，之前版本一直都不支持老的验证方式的

这两个软件都支持查询歌曲，并且amperfy能够列出全部歌曲，所以我觉得是支持的
<img width="1025" alt="截屏2024-05-08 10 15 24" src="https://github.com/gitbobobo/StreamMusic/assets/140488233/d8220585-80e9-47ad-a1af-f775c0449371">
。

<img width="1197" alt="截屏2024-05-08 10 14 38" src="https://github.com/gitbobobo/StreamMusic/assets/140488233/2ebf710e-fea7-4344-a6bb-29e36f8baeb5">

**Comment by gitbobobo** [comment]
没用过amperfy，我去试试看。

但substreamer一定是不支持的，我的意思是直接获取全部歌曲，而不是加上搜索词搜索

**Comment by gitbobobo** [comment]
这个很明显不是全部歌曲，估计是调用的随机歌曲的接口

<img width="1015" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/100769410/d6d59767-5965-4b68-a807-65d7e1558685">

**Comment by yuygfgg** [comment]
> 这个很明显不是全部歌曲，估计是调用的随机歌曲的接口
> 
> <img alt="image" width="1015" src="https://private-user-images.githubusercontent.com/100769410/328735383-d6d59767-5965-4b68-a807-65d7e1558685.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxMzYyOTMsIm5iZiI6MTcxNTEzNTk5MywicGF0aCI6Ii8xMDA3Njk0MTAvMzI4NzM1MzgzLWQ2ZDU5NzY3LTU5NjUtNGI2OC1hODA3LTY1ZDdlMTU1ODY4NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwMjM5NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNzcwY2U1NThkNzc5MjhjNTY1ODg4YTI3OGRiNzgzNTIyZDhhMmFmNDY0NzExY2M5OTdmZGI3NDM2MmQ4ZTY1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vu6P3KOp_g8bNR5hxvrNLes9b65HXpsUePkELM7Havc">

不是的，你去settings->library，等扫描完才是全部的

amperfy估计是遍历专辑/文件夹来获取的全部音乐

**Comment by gitbobobo** [comment]
好吧，确实如此

**Comment by yuygfgg** [comment]
> 好吧，确实如此

所以音流能不能也这样workaround一下？我真的很需要一个能够显示歌词的客户端

**Comment by gitbobobo** [comment]
尽量吧，我试试看

**Comment by yuygfgg** [comment]
> 尽量吧，我试试看

谢谢，感激不尽！

**Comment by gitbobobo** [comment]
1.2.9已发布

**Comment by yuygfgg** [comment]
> 1.2.9已发布

1.2.9官网上只看见安卓和Windows版，而且windows版无法下载
![Uploading 截屏2024-05-15 20.50.57.png…]()

**Comment by gitbobobo** [comment]
检查下网址是否正确
<img width="356" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/100769410/bed586ef-7fb2-48de-a94c-337a0bc6bd09">

**Comment by yuygfgg** [comment]
> 检查下网址是否正确 <img alt="image" width="356" src="https://private-user-images.githubusercontent.com/100769410/330812469-bed586ef-7fb2-48de-a94c-337a0bc6bd09.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU3NzgyODEsIm5iZiI6MTcxNTc3Nzk4MSwicGF0aCI6Ii8xMDA3Njk0MTAvMzMwODEyNDY5LWJlZDU4NmVmLTdmYjItNDhkZS1hOTRjLTMzN2EwYmM2YmQwOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxNVQxMjU5NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00Yjg3NjAxNGU3NjBlMDY4YjkwNzJmODJlMzNlZDNkOGRhMjc4YmQyMGVlMGMyMDQ5ZDk3ZGUwNTZhYjk1YzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.AM-lpGLFwT99INWci1XU2mowuFn72-2r_O-fr74dZ4g">

music.aqzscn.cn只看见1.2.8，devmusic.aqzscn.cn无法下载，且没有mac版

**Comment by yuygfgg** [comment]
好了，估计是缓存问题
