### ISSUE TITLE
连接DS audiostation专辑详情页有概率不显示专辑图片和歌曲编码信息

### ISSUE THREAD

**Issue by yuygfgg** [gitbobobo/StreamMusic#276]
**Describe the bug (BUG 描述)**
如题，在推荐页/专辑页正常，点进去就没有图片（有时推荐页/专辑页也是空白，一般重新登录就好了）。歌曲可以正常播放，但是显示“未知时长”。歌曲信息显示大小0B但是时长正确
**To Reproduce (复现步骤)**
点进部分专辑

**Expected behavior (期望行为)**
正确显示专辑封面，歌曲信息
**Screenshots (截图)**
<img width="1010" alt="截屏2024-05-09 08 27 47" src="https://github.com/gitbobobo/StreamMusic/assets/140488233/c55576fd-a6a9-4856-bcad-909673554610">
<img width="1003" alt="截屏2024-05-09 08 35 22" src="https://github.com/gitbobobo/StreamMusic/assets/140488233/58ea681e-956d-4321-87bb-1d6bffac316e">
<img width="1006" alt="截屏2024-05-09 08 35 30" src="https://github.com/gitbobobo/StreamMusic/assets/140488233/ed2d9e63-309e-404a-8283-7bf50def3def">
<img width="1006" alt="截屏2024-05-09 08 36 00" src="https://github.com/gitbobobo/StreamMusic/assets/140488233/226ff357-dc60-4aac-946c-12a0b02471c3">

**Platform and Device Info (操作系统及设备信息)**
 - OS: macOS & IOS
 - Browser ？
 - Version: latest

**Music Server Type (音乐服务器类型)**
e.g. DS audiostation

**Additional context (额外信息)**
没有相关日志

**Comment by gitbobobo** [comment]
歌曲信息直接用的服务端返回的信息，没有就是没有，应该不会有什么问题。

歌曲列表没有封面的话，换个排序方式会有吗？因为这里的封面显示逻辑是从列表第一首歌拿的信息

**Comment by yuygfgg** [comment]
> 歌曲信息直接用的服务端返回的信息，没有就是没有，应该不会有什么问题。
> 
> 歌曲列表没有封面的话，换个排序方式会有吗？因为这里的封面显示逻辑是从列表第一首歌拿的信息

你看我截图，第一首歌的封面是有的，但是专辑封面没有

**Comment by yuygfgg** [comment]
我发现了，所有CUE文件的专辑都不行。flac分轨的就正常

**Comment by gitbobobo** [comment]
是的，确实是这个问题，因为cue分轨的，服务端返回的文件大小是 0，程序就以为没有其他信息了。

下个版本会优化此逻辑

**Comment by gitbobobo** [comment]
时长显示问题已在1.2.9修复
