### ISSUE TITLE
主副线路无法自动切换

### ISSUE THREAD

**Issue by gggcpy** [gitbobobo/StreamMusic#277]
**Describe the bug (BUG 描述)**
主副线路无法自动切换。
设置了主副线路，主线路内网地址，副线路域名地址
当处于外网环境时，主线路一直尝试连接转圈，不会自动切换到副线路。
后端不管是emby还是navidrome都不行。
如果设置主线路为域名访问，直接秒连。

**Expected behavior (期望行为)**
希望修复次问题。

**Screenshots (截图)**
![微信图片_20240509115837](https://github.com/gitbobobo/StreamMusic/assets/141815883/9e7111b6-d069-4a8d-9fc5-791c7e469660)
![微信图片_20240509115845](https://github.com/gitbobobo/StreamMusic/assets/141815883/5b4041a3-e340-4097-b3a9-d72f8781f043)

**Platform and Device Info (操作系统及设备信息)**
安卓13，IOS15.8.2
音流版本1.2.8

**Music Server Type (音乐服务器类型)**
emby 4.18.5
navidrome 0.51.1

**Comment by gitbobobo** [comment]
与此问题 https://github.com/gitbobobo/StreamMusic/issues/248 重复
