### ISSUE TITLE
音流1.2.8,无法创建歌单(群晖6.2 DS Audio )

### ISSUE THREAD

**Issue by leG09** [gitbobobo/StreamMusic#280]
**Describe the bug (BUG 描述)**
App创建歌单完成后，无反应。尝试在群晖电脑端创建歌单可以成功创建。
后通过手机抓包发现和电脑端所传参数不一致
群晖电脑端参数：
api=SYNO.AudioStation.Playlist&method=create&name=aaa&library=personal&version=2'
手机端参数：
api=SYNO.AudioStation.Playlist&method=create&name=aaa&library=personal&version=3'
经过对比是version字段所导致，麻烦处理下

**Music Server Type (音乐服务器类型)**
DS Audio.

**Additional context (额外信息)**
群晖6.2版本

**Comment by gitbobobo** [comment]
好的，下个版本可以试试有没有用

**Comment by gitbobobo** [comment]
1.2.9 已将与歌单相关的 version 调整为 2
