### ISSUE TITLE
优化启动后自动打开播放页的逻辑

### ISSUE THREAD

**Issue by helscn** [gitbobobo/StreamMusic#282]
**Describe the bug (BUG 描述)**
设置后开启【启动后自动播放】及【自动打开播放页】设置后，在开启App后，自动播放歌曲不会打开播放页

**To Reproduce (复现步骤)**
1. 开启【启动后自动播放】及【自动打开播放页】设置
2. 启动App
3. 等待歌曲自动播放，此时页面不会切换到播放页

**Expected behavior (期望行为)**
开启【启动后自动播放】及【自动打开播放页】设置后，当启动App后并开始自动播放歌曲时，可以自动切换到播放页，或者增加单独的设置选项。

**Platform and Device Info (操作系统及设备信息)**
 - 小米10 Pro / MIUI 14.0.4 / 音流安卓版 1.2.8

**Music Server Type (音乐服务器类型)**
- DS Audio Version 7.1.0-5508

**Additional context (额外信息)**
在车机互联时，会将播放器投屏到车机屏幕上，对于没有触摸屏的车机，用旋钮移动到最下侧控制栏打开播放页操作极其麻烦（显示界面不是车机界面，界面上元素太多），所以希望可以在自动播放后自动打开播放页。

**Comment by gitbobobo** [comment]
自动打开播放页的配置，本就是在用户切换到新的播放列表时触发的

如果是因为界面元素太多太麻烦的缘故的话，1.3.0会适配 TV 版，界面元素肯定会精简不少，应该能在一定程度上提升操作体验

**Comment by helscn** [comment]
好的，谢谢回复，如果能直接支持CarWith就更好了
