### ISSUE TITLE
audio station 一直卡在任务2

### ISSUE THREAD

**Issue by rcqed** [gitbobobo/StreamMusic#284]
**Describe the bug (BUG 描述)**
能连接上，但是歌曲一直加载不出来，一直卡在任务2，不知道什么原因。

**Expected behavior (期望行为)**
修复本问题

**Screenshots (截图)**
![S40512-20230657](https://github.com/gitbobobo/StreamMusic/assets/40952828/37d7f524-6f0e-4c1b-83c9-ffe6eaf2bdc0)
![S40512-20225930](https://github.com/gitbobobo/StreamMusic/assets/40952828/266905a8-5ec0-47da-8096-f326b0c68dd6)
![S40512-20231094](https://github.com/gitbobobo/StreamMusic/assets/40952828/94e0f25f-0693-4f2e-b875-b013ff383528)

**Platform and Device Info (操作系统及设备信息)**
 - OS: 安卓，ios，windows11
 - Version 1.2.8

**Music Server Type (音乐服务器类型)**
audio station

**Comment by gitbobobo** [comment]
dsm 版本多少

**Comment by rcqed** [comment]
DSM 7.2.1

**Comment by rcqed** [comment]
audio station 是 7.1.0-5508

**Comment by gitbobobo** [comment]
我也是dsm 7.2，如果版本没问题，那大概率是你的某些歌曲数据，程序转换异常导致进度卡住了

这种情况没什么好办法处理，如果可以，你可以新建一个测试账号，我这边连接测试一下。或者等其他人向我提供

**Comment by rcqed** [comment]
http://47.242.252.201:12554   账号：test1  密码：Password1

**Comment by gitbobobo** [comment]
试了下，你这个服务器感觉有点奇怪，同时发起的请求数过多会导致所有请求都收不到响应，一直卡住。

我减少了一些并发请求就可以收到。不清楚你是网络上做了特殊设置还是服务器性能的问题

**Comment by rcqed** [comment]
> 试了下，你这个服务器感觉有点奇怪，同时发起的请求数过多会导致所有请求都收不到响应，一直卡住。
> 
> 我减少了一些并发请求就可以收到。不清楚你是网络上做了特殊设置还是服务器性能的问题

谢谢，辛苦了。我刚刚去看了一下，我用的内网穿透服务限制了并发为150，因为我没有办法修改服务器，请问是否可以增加自定义并发数的功能

**Comment by gitbobobo** [comment]
我稍微降低了一些并发请求，我这里测试是可以获取到数据了。

暂时先不加这个配置了。

https://devmusic.aqzscn.cn/docs/versions/latest/

测试版你可以先试试看行不行

**Comment by rcqed** [comment]
> 我稍微降低了一些并发请求，我这里测试是可以获取到数据了。
> 
> 暂时先不加这个配置了。
> 
> https://devmusic.aqzscn.cn/docs/versions/latest/
> 
> 测试版你可以先试试看行不行

收到，感谢
