### ISSUE TITLE
能不能详细介绍一下获取歌词和确认歌词的api使用信息啊？

### ISSUE THREAD

**Issue by lee86** [gitbobobo/StreamMusic#285]
**Describe the bug (BUG 描述)**
No Bug

**To Reproduce (复现步骤)**
Nothing

**Expected behavior (期望行为)**
当前通过官网上自定义api的信息开发歌词api，无法完成确认歌词接口...通过api请求日志发现确认歌词似乎也是调用的获取歌词接口...

**Screenshots (截图)**
Nothing

**Platform and Device Info (操作系统及设备信息)**
 - OS: [macos 14.5 ，hyperOS 1，windows 11]
 - Browser [ Nothing ]
 - Version [ 1.2.8 ]

**Music Server Type (音乐服务器类型)**
Navidrome

**Additional context (额外信息)**
希望官网能补充完整自定义API的信息

**Comment by gitbobobo** [comment]
我认为这里介绍的已经很全面了 https://music.aqzscn.cn/docs/guides/interfaces#%E7%A1%AE%E8%AE%A4%E6%AD%8C%E8%AF%8D

**Comment by lee86** [comment]
主要是，在播放页面自动获取歌词是limit默认为1，切换歌词页面limit默认10？如果是那我对这一部分就没问题了
在切换歌词页面里，点击保存的业务逻辑是啥啊，发送至服务端保存嘛？

**Comment by gitbobobo** [comment]
是的，自动获取拿的数量再多也没有用

保存在应用本地，配置了歌词确认的地址，就顺便向这个地址发个请求，相当于一个web hooks

**Comment by lee86** [comment]
还有个问题，切换歌词页点击保存后，应该返回啥类型消息，结构体是什么，我看api文档那边说只要求http状态，但是点击保存后，返回200，没有立即加载歌词。。。

**Comment by gitbobobo** [comment]
返回状态码即可，没有立即加载可能是程序有问题，我待会儿试一下

**Comment by gitbobobo** [comment]
1.2.9已修复确认歌词后当前歌曲不生效的问题
