### ISSUE TITLE
[Audio Station] 支持选择转码比特率

### ISSUE THREAD

**Issue by julystars** [gitbobobo/StreamMusic#286]
非常不错，已买断支持。
1、增加在线音质调整，API接口中Query参数增加bitrate=128000/16000/192000/256000/320000等比特率参数即可
2、歌手头像和介绍建议开放自定义API接口
3、播放界面歌词Tab页能全屏，自动隐藏底部控制界面，点击界面出现控制界面，建议参照Apple Music
4、MacOS客户端播放界面，收藏和歌曲时长以及后面播放模式、列表按钮布局看着有点难受
5、播放界面歌词希望能增加左对齐

**Comment by gitbobobo** [comment]
1. 这个参数你是从哪里找的，我一直以为audio station不能调整比特率呢

2. 歌手头像和封面是同一个接口，介绍之后可能会在应用端使用lastFM的接口，因此不用添加

3. 全屏歌词有计划

4. 难受也没办法，审美不同而已

5. 可以增加左对齐的配置

**Comment by julystars** [comment]
1，反编译DS audio apk找的，转码mp3时增加这个参数即可，之前有打算开发个KMP全平台的audio station播放器的，KMP轮子太少+转行，一直耽搁了。
2，了解，其实可以把专辑封面和歌手头像分开来，自定义API优先。docker部署了lrcapi服务，加到APP里发现不生效🙈

另外audio station支持API更新音乐元数据，是否可以增加自定义API接口中获取数据来更新音乐元数据呢？

**Comment by gitbobobo** [comment]
好的，音质调整这个我有空试下。

音乐服务自带的接口，陆续都会补充上去的，不用加到自定义api，太麻烦了

**Comment by gitbobobo** [comment]
1.3.0已发布
