### ISSUE TITLE
[Audio Station] 刮削时纯音乐会被贴上歌词，会在下方的 Mini 播放条滚动播放歌词，遮挡纯音乐标题

### ISSUE THREAD

**Issue by bigshezhang** [gitbobobo/StreamMusic#287]
使用 MusicTag 对同时含有纯音乐和含有歌词的音乐进行刮削时，纯音乐也会有几行歌词，然后会在 Mini 播放器栏播放类似“作曲 XXX” 和 “纯音乐，请欣赏”，遮挡 Mini 播放栏歌曲的标题。

希望能够添加一个选项，少于 X 行（如 3 行或 5 行）的歌词不予显示（显示为无歌词）

**Comment by gitbobobo** [comment]
非常好的主意，下个版本就加上~

**Comment by gitbobobo** [comment]
1.2.9已加入此配置
