### ISSUE TITLE
JellyFin 服务端10.9版本已支持歌词，能否添加对应支持

### ISSUE THREAD

**Issue by OneEarMouse** [gitbobobo/StreamMusic#289]
JellyFin 服务端10.9版本已支持歌词，能否添加对应支持

**Comment by OneEarMouse** [comment]
大概看了一眼Jellyfin的文档。本地启动最新版本的JellyFin服务器之后，访问http://localhost:8096/api-docs/swagger/index.html。这里的​/Audio​/{itemId}​/Lyrics接口应该就是歌词相关的接口

不过我不太懂这个歌词相关的开发。作者加油

**Comment by xieyx** [comment]
+1

**Comment by hawkvan** [comment]
jellyfin目前也没法切换音乐媒体库，只能选一个

**Comment by l5oo00** [comment]
我今天试了下 iOS 客户端，链接 jelyfin  10.9.6 服务端，发现第一次同步后

**Comment by gitbobobo** [comment]
1.3.0已发布
