### ISSUE TITLE
公网下播放歌曲进度显示不正常

### ISSUE THREAD

**Issue by IvanTseLL** [gitbobobo/StreamMusic#29]
公网播放的时候歌曲进度和歌曲总时长都是0:00 但是点击暂停 进度时间又显示出来了(总时长还是0:00) 点击继续播放 又变回0:00 感觉出现的次数有点多了 内网正常 可能跟网络状态有关？但是歌曲能播放的 就是进度时长显示有问题 版本1.0.10 服务端是navidrome

**Comment by gitbobobo** [comment]
歌曲转码后会出现此问题，是播放插件的问题，这个晚点修复

**Comment by gitbobobo** [comment]
1.2.8已修复
