### ISSUE TITLE
希望可以添加 “服务器内含有 3 曲以下的专辑不在发现页和专辑页展示” 的选项

### ISSUE THREAD

**Issue by bigshezhang** [gitbobobo/StreamMusic#291]
本人已入正，感谢开发者带来这么好用的软件。

本人自己有维护一些喜欢的专辑库，但有时也会从网易云上下载别人的歌单，这些歌单里的歌来自很多专辑，但本地文件中，每个专辑可能实际上只存了一个文件。但是这些歌单里的专辑数量众多，展示在 “发现页” 和 “专辑页” 里会让我感到困惑，很难找到我自己在维护的专辑库，且大部分发现页里的专辑我也不认识（很多不是自己维护的库里的）。

希望可以添加一个选项，“专辑内文件小于 3 的专辑，不在发现页和专辑页展示”

**Comment by gitbobobo** [comment]
这个功能个人感觉不是特别合理，而且这个功能受限于服务端返回的专辑信息中是否包含歌曲数量的信息

如果你的服务端有专辑评分功能，建议为你自己专门整理的专辑加上评分，这样不止在音流可以快速找到你想要的专辑，也能在服务端或其他app上找到

**Comment by bigshezhang** [comment]
我使用的是 Audio Station，在发现页的专辑推荐里，推荐的专辑在 Nas 上实际上只有一首歌，这就导致了专辑的每日推荐和单曲的每日推荐没有太大差别。

Audio Station 里不能给专辑打评分，目前我寻找到一个专辑，除了直接搜索之外，需要进入比较深的层级才能找到（在文件夹中一级一级往下翻）

我点开那些实际只有一两首的专辑，里面确实是只有一两首，所以我觉得服务端返回的专辑信息会有歌曲数量的信息的（可能不是显式的，但只需要对 Json 遍历一遍或许就可以）

因为 Audio Station 不能给专辑打分，导致我无法排除那些 Nas 里实际上只有一首歌的专辑出现在发现页，也无法在专辑页快速排除这些专辑。

**Comment by gitbobobo** [comment]
你的需求是筛选歌曲数量小于n的专辑，单个专辑可以获取到歌曲数量，不代表专辑列表的接口可以获取到。

如果真要加此功能，只能在媒体库模式添加，直连模式大概率是做不到的
