### ISSUE TITLE
128/129 DLAN 无法播放问题

### ISSUE THREAD

**Issue by hbmask** [gitbobobo/StreamMusic#292]
IOS/安卓/鸿蒙4 使用DLAN 搜索出来设备以后,
设备无法选择,并且圈圈一直转也不报错...
推送不到任何设备上去,接收设备为Q90R 和sony x9500g/apple tv.

想确切知道,音流解析DDNS或者说域名的时候,是在登录的时候解析一次保存ip,
还是每次播放歌曲的解析一次ip...这个很重要,大家都用ddns,可能中途ip会变化..会导致用户可能重新登录导致音乐过多.加载时间特别漫长..
目前我有4万音乐库...加载要几分钟不等...(现在用直连视乎问题 没有了.)

**Comment by gitbobobo** [comment]
dlna 会在131或132开始修复

你输入的是域名，就不会管你ip变不变

**Comment by hbmask** [comment]
您的来信我已经收到，我会尽快回复你。
