### ISSUE TITLE
无法在PC断恢复购买，邮箱和订单号均不可用

### ISSUE THREAD

**Issue by asiluokegit** [gitbobobo/StreamMusic#293]
无法在PC断恢复购买，邮箱和订单号均不可用。
![微信图片_20240515144150](https://github.com/gitbobobo/StreamMusic/assets/35768010/2a56de2a-b1be-42cc-a9d5-5476222b7669)

![image](https://github.com/gitbobobo/StreamMusic/assets/35768010/ae7cb1ed-5cf3-47f8-be2f-7301cfa76d6f)

**Comment by gitbobobo** [comment]
检查下网络问题

**Comment by asiluokegit** [comment]
经测试，在家里的电脑可以激活，办公室的笔记本尝试多次均不行，操作系统是win10专业版22H2， 这里摘录了部分日志
  ERROR ⛔ 订单验证失败 DioException [unknown]: null
  ERROR ⛔ Error: HandshakeException: Handshake error in client (OS Error: 
  ERROR ⛔ 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
  ERROR 22:37:59.647 (+9:36:06.778905)
  ERROR ⛔ 订单验证失败 DioException [unknown]: null
  ERROR ⛔ Error: HandshakeException: Handshake error in client (OS Error: 
  ERROR ⛔ 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
  ERROR 22:38:01.309 (+9:36:08.440283)
  ERROR ⛔ 订单验证失败 DioException [unknown]: null
  ERROR ⛔ Error: HandshakeException: Handshake error in client (OS Error: 
  ERROR ⛔ 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
  ERROR 22:38:02.735 (+9:36:09.867004)
  ERROR ⛔ 订单验证失败 DioException [unknown]: null
  ERROR ⛔ Error: HandshakeException: Handshake error in client (OS Error: 
  ERROR ⛔ 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
  ERROR 22:38:17.453 (+9:36:24.584574)
  ERROR ⛔ 通过邮箱激活失败 DioException [unknown]: null
  ERROR ⛔ Error: HandshakeException: Handshake error in client (OS Error: 
  ERROR ⛔ 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))
  ERROR 22:38:20.231 (+9:36:27.362775)
  ERROR ⛔ 通过邮箱激活失败 DioException [unknown]: null
  ERROR ⛔ Error: HandshakeException: Handshake error in client (OS Error: 
  ERROR ⛔ 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../third_party/boringssl/src/ssl/handshake.cc:393))

**Comment by gitbobobo** [comment]
看下有没有用什么代理，报错是证书验证失败，服务端的证书肯定是没问题的

**Comment by asiluokegit** [comment]
陆陆续续尝试了好多次，关掉代理，换网络，关闭防火墙、修改本机时间等都还是不行，目前只能怀疑是本机环境问题了，哪天找到原因记得通知我下771657364@qq.com，不胜感激

**Comment by jiaoyi5551** [comment]
![IMG_20240729_013337](https://github.com/user-attachments/assets/d71cb80d-255b-40ac-b0a2-cf28fc84e722)
我也是一样问题，你解决了吗？我已经更新到1.30版本还是一样

**Comment by gitbobobo** [comment]
131测试版此问题应该已经解决

**Comment by gitbobobo** [comment]
1.3.1已修复

**Comment by BaeKey** [comment]
> 1.3.1已修复

1.3.1还是遇到了这个问题，系统版本22H2专业版。

Error: HandshakeException: Handshake error in client (OS Error: 
  ERROR ⛔ 	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(../../flutter/third_party/boringssl/src/ssl/handshake.cc:393))
