### ISSUE TITLE
连接群晖audio station 不能正常播放

### ISSUE THREAD

**Issue by tanxiaofen** [gitbobobo/StreamMusic#296]
用了最新的程序，首次登录后正常使用，但下次再用，无法播放：表现为能选择歌曲，歌词也能显示，但无法播放，只有退出登录后，再次登录才能正常使用，MAC和iPhone同样遇到，请教怎么解决？

**Comment by gitbobobo** [comment]
https://github.com/gitbobobo/StreamMusic/issues/321 应该和这个是同一个问题，可能是程序逻辑有问题了，先把这个问题关闭了
