### ISSUE TITLE
windows版1.2.9 在搜索后，点击结果页的歌曲无法播放

### ISSUE THREAD

**Issue by lee86** [gitbobobo/StreamMusic#297]
**Describe the bug (BUG 描述)**
windows版1.2.9 在搜索后，点击结果页的歌曲无法播放

**To Reproduce (复现步骤)**
- 点击搜索，输入搜索内容
- 在结果页面点击，无法正常播放，日志无异常信息

**Expected behavior (期望行为)**
搜索后能正常播放

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 - OS: windows 11
 - Browser: Nothing
 - Version: 1.2.9

**Music Server Type (音乐服务器类型)**
Navidrome

**Additional context (额外信息)**
除了搜索以外的地方好像都能正常播放

**Comment by l5oo00** [comment]
Mac  1.2.9 也有同样的问额，搜索后双击无法播放，只能添加到下一首

**Comment by gitbobobo** [comment]
1.3.0已发布
