### ISSUE TITLE
针对封面API调用的建议

### ISSUE THREAD

**Issue by YeiJ** [gitbobobo/StreamMusic#299]
**功能建议**
希望能加个开关 优先从API获取专辑/歌曲/歌手封面

目前 当服务端返回了一个默认封面时 音流不会主动从API获取正确的歌曲封面

**Comment by gitbobobo** [comment]
开关不是已经有了吗，自定义API的第一个开关

没有返回404的话，就不会认为没有获取到歌曲封面，除非专门计算一下这个默认封面的哈希值，每次获取后进行对比

**Comment by YeiJ** [comment]
> 开关不是已经有了吗，自定义API的第一个开关
> 
> 没有返回404的话，就不会认为没有获取到歌曲封面，除非专门计算一下这个默认封面的哈希值，每次获取后进行对比

我用的是群大佬的LyricsAPI的服务
在播放一些歌曲时以及专辑页面仍显示的Navidrome的默认封面
如图
我也没找到封面请求的历史信息

![Screenshot_2024-05-31-11-42-56-044_cn aqzscn stream_music](https://github.com/gitbobobo/StreamMusic/assets/63900106/8f6d6032-582b-42bf-bb2b-8826b3b3d041)

![Screenshot_2024-05-31-11-36-24-017_cn aqzscn stream_music](https://github.com/gitbobobo/StreamMusic/assets/63900106/1579ab0e-f1a2-4a93-8391-7c0ff24485b9)

**Comment by gitbobobo** [comment]
目前是没有哈希对比的逻辑的，试试关掉这个开关

<img width="1051" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/100769410/6dea575c-0361-4969-8eed-f3f28e874923">

**Comment by gitbobobo** [comment]
1.3.0已发布
