### ISSUE TITLE
win版搜索歌手后，歌手列表和专辑列表无法左右拖动

### ISSUE THREAD

**Issue by zjd309** [gitbobobo/StreamMusic#300]
**Describe the bug (BUG 描述)**
win版搜索歌手后，歌手列表和专辑列表无法左右拖动

**To Reproduce (复现步骤)**
1. 搜索歌手
2. 歌手列表和专辑列表无法左右拖动

**Expected behavior (期望行为)**
由于专辑太多，无法显示完全，希望能够左右拖动

**Screenshots (截图)**
<img width="1020" alt="1715846877514" src="https://github.com/gitbobobo/StreamMusic/assets/144345057/65d43a9f-ed03-452f-817f-b9ebc1b194fd">

**Platform and Device Info (操作系统及设备信息)**
 - OS: win10

**Music Server Type (音乐服务器类型)**
群晖DSM7.2环境下的Audio Station

**Comment by gitbobobo** [comment]
1.3.0已发布
