### ISSUE TITLE
iOS: Song sorting in albums is random

### ISSUE THREAD

**Issue by s3rverro0m** [gitbobobo/StreamMusic#301]
**Describe the bug (BUG 描述)**
When going into an album, the song sorting is either reversed (from the last song first, to the first song, last). Or the sorting order is random.

**To Reproduce (复现步骤)**
Go to any album on iOS and look at the song sorting.

**Expected behavior (期望行为)**
The song sorting in an album should be from the first track to the last one.

**Screenshots (截图)**
![image](https://github.com/gitbobobo/StreamMusic/assets/46236585/f6c96d38-7f86-46b5-affb-e61ae673a6d9)

![image](https://github.com/gitbobobo/StreamMusic/assets/46236585/97082335-2f8b-476d-a2a4-54792e534e90)

**Platform and Device Info (操作系统及设备信息)**
 - OS: iOS
 - Version: v1.2.9

**Music Server Type (音乐服务器类型)**
Navidrome 0.52.5

**Additional context (额外信息)**

**Comment by s3rverro0m** [comment]
I apologize for assigning this directly to you, GitHub on iOS automatically assigned it to you. 😣

**Comment by gitbobobo** [comment]
thanks your feedback~

**Comment by Insprill** [comment]
I hate to be that guy, but this is a pretty major issue. Are there any plans to fix it soon? Most of my library consists of live shows, so having the songs in each album sorted randomly makes the app unusable to me.

**Comment by gitbobobo** [comment]
sorry about this，but 1.3.0 still need more time to dev.

if you have vip，you can try this link https://aqzscn.cn/archives/2024-middle-summary to apply testflight

**Comment by Insprill** [comment]
I can confirm this is fixed in the latest version, thank you :)

**Comment by s3rverro0m** [comment]
Looks like this is broken again in the latest 1.3.2 TestFlight version. 😔 @gitbobobo 

![image](https://github.com/user-attachments/assets/a2e492b6-607f-4b0f-9187-0251e8ac56b0)

**Comment by gitbobobo** [comment]
sorry about this，you can try modify sort method to track number。

**Comment by s3rverro0m** [comment]
Wow, I didn't even realize it flipped the sort. Sorry about that!
