### ISSUE TITLE
歌曲排序混乱

### ISSUE THREAD

**Issue by Vincent32035** [gitbobobo/StreamMusic#303]
不用直连，专辑内排序混乱，歌单排序正常；
用了直连，专辑内排序正常，歌单排序混乱；

客户端操作系统：iOS 17.5，macOS Sonama 14.5；
音流版本：1.2.9；
服务端：Navidrome 0.51.1

**Comment by kawashiro-ryofu** [comment]
插眼，QQ群没有人回复，发现有人情况类似，遂跟一帖

![d56fd827e5a54ba143c650f42f8a726c](https://github.com/gitbobobo/StreamMusic/assets/53611149/abf527d7-e342-4bb5-b5e5-a0b2c7d0f914)

1.2.7之前，歌单“按添加时间排序”实为歌单默认排序。1.2.8后，确实根据歌曲添加时间来排序了，但是菜单中没有保留列表默认排序的选项，比较影响体验，希望能在后续版本中修正。

**Comment by Oman4** [comment]
![155c7e0548b512581fb80615560957c](https://github.com/gitbobobo/StreamMusic/assets/11306488/4ce56109-6ebf-47cf-9a71-b116f5c512c9)
![af8e35fb3995402d1555c08453e62c5](https://github.com/gitbobobo/StreamMusic/assets/11306488/a2e108b1-e47b-4b74-849e-a363f9ea846b)
![77758bea193c763d5b9bc73b8e52409](https://github.com/gitbobobo/StreamMusic/assets/11306488/ffe376fc-6eaf-4861-b52c-72dc7115a030)
按道理应该是先按照分轨号排序的吧？

**Comment by lalalamiheart** [comment]
![image](https://github.com/gitbobobo/StreamMusic/assets/166940417/46fecf2b-ef16-48c2-b877-4a6b3690997a)
顺便，提供下按音轨排序呢，我好像没法直接设置

**Comment by gitbobobo** [comment]
1.3.0已发布

**Comment by theturtle626** [comment]
iOS 1.3.0, 點選一張專輯， 還是沒有看到可以用音轨排序, 可以再確認一下嗎?
