### ISSUE TITLE
换歌专辑图没切换

### ISSUE THREAD

**Issue by jasonnmy** [gitbobobo/StreamMusic#305]
**Describe the bug (BUG 描述)**
换歌后专辑图会停留在上一首歌，但有些又会切换
**To Reproduce (复现步骤)**
切换歌
**Expected behavior (期望行为)**
换歌如果没有专辑图显示一张默认专辑图，比如poweramp那样，有的话显示，切换的时候不会卡专辑图，我记得1.2.6以前好像没碰到过
**Screenshots (截图)**
![Screenshot_2024-05-18-18-18-59-921_cn.aqzscn.stream_music-edit.jpg](https://github.com/gitbobobo/StreamMusic/assets/10269349/19d3e5cf-bd75-4934-a4fd-72a34df1971e)

![Screenshot_2024-05-18-18-19-29-007_cn.aqzscn.stream_music.jpg](https://github.com/gitbobobo/StreamMusic/assets/10269349/333d6380-8efa-4207-8a2b-aa8d77983671)

**Platform and Device Info (操作系统及设备信息)**

Android 14

**Music Server Type (音乐服务器类型)**
e.g. emby 4.17.

emby，并且还重置过一次

**Additional context (额外信息)**

**Comment by puckee** [comment]
我也碰到了同样的问题，设备为安卓，服务端为audio station。手动切歌可以自动切换封面，但是自动播放下一首的时候不会切换。

**Comment by gitbobobo** [comment]
1.3.0已发布
