### ISSUE TITLE
搜索结果点击播放没有反应

### ISSUE THREAD

**Issue by 1013461195** [gitbobobo/StreamMusic#307]
**Describe the bug (BUG 描述)**
搜索结果点击播放没有反应

**To Reproduce (复现步骤)**
从旧版本替换上来，原始版本是哪个忘了，选择直连模式链接Navidrome，然后搜索音乐点击，没有反应，经测试直连模式和关闭直连都是一样

**Expected behavior (期望行为)**
正常应该切换到新歌或者重新开始当前歌曲

**Screenshots (截图)**
![company2024-05-20 15 06 25](https://github.com/gitbobobo/StreamMusic/assets/23392657/6880de1d-36c1-4b93-9789-666331a557bd)

**Platform and Device Info (操作系统及设备信息)**
 - OS: Macos Monterey 12.7.1 (21G920)

**Music Server Type (音乐服务器类型)**
e.g. Navidrome

**Comment by gitbobobo** [comment]
与此问题 https://github.com/gitbobobo/StreamMusic/issues/297 相同
