### ISSUE TITLE
【功能需求】完全自定义API

### ISSUE THREAD

**Issue by myderr** [gitbobobo/StreamMusic#313]
以下的音乐服务我不想使用，我想自定义API来使用，
你也说了`就我个人使用体验来讲，目前并不存在完美的音乐服务，它们各有优缺点，需要根据自己的需求酌情选择。`
所有我希望能支持自定义的音乐服务，由`音源`来定义需要的数据接口和格式

例如`音源`需要歌单列表，需要根据歌单id查询歌曲列表，根据歌曲列表查询歌曲详情等等的

![7f283ca023d5198013076630027a4316](https://github.com/gitbobobo/StreamMusic/assets/26431313/e17d787a-337e-4de1-bd64-3b4937567945)

**Comment by gitbobobo** [comment]
这不是通过自定义API能完成的，那么多接口不可能全在自定义API里配置，这样做不如音流直接适配一个新的服务端。

ps：音流有开发服务端的计划，不一定是最好用的，但一定是最匹配音流app的

**Comment by myderr** [comment]
我想到了一个方法，根据[接口文档](https://music.aqzscn.cn/docs/notes/services/emby)我可以自己模拟一个服务，比如模拟一个emby的服务器，配置界面就可以直接选择emby就行了，这样好像也能达到效果。
当然，要是音流能有自己的服务端来进行处理是更好的了，期待服务端的新版本

> 这不是通过自定义API能完成的，那么多接口不可能全在自定义API里配置，这样做不如音流直接适配一个新的服务端。
> 
> ps：音流有开发服务端的计划，不一定是最好用的，但一定是最匹配音流app的
