### ISSUE TITLE
最新版windows 客户端 有一些歌曲只显示专辑 但是专辑里面无歌曲  手机端可以正常显示

### ISSUE THREAD

**Issue by XlangNan** [gitbobobo/StreamMusic#319]
![image](https://github.com/gitbobobo/StreamMusic/assets/54304073/41536c54-062a-494c-be5f-b789854a7941)
![image](https://github.com/gitbobobo/StreamMusic/assets/54304073/832d8bb5-2ca0-4e24-8d6d-d5600b826c66)

**Comment by gitbobobo** [comment]
手机和PC是相同的处理逻辑的
