### ISSUE TITLE
以 Lavf 作为编码工具的 Flac 文件无法在 1.2.9 版本播放

### ISSUE THREAD

**Issue by ZGLinus** [gitbobobo/StreamMusic#320]
**Describe the bug (BUG 描述)**
部分Flac文件不是以 Libflac 作为编码工具，而是用 libavformat(lavf) 作为编码工具，这两种 Flac 文件的区别在于前者可以被音流正常播放，后者不行。

**To Reproduce (复现步骤)**
1. 将以 libavformat(lavf) 作为编码工具的 Flac 文件放在服务器
2. 把音流和服务器连接起来
3. 不转码播放该 Flac 文件
4. 该文件无法播放

**Expected behavior (期望行为)**
正常播放以 libavformat(lavf) 作为编码工具的 Flac 文件

**Screenshots (截图)**
可以正常播放的文件信息
![图片](https://github.com/gitbobobo/StreamMusic/assets/69845097/32afeb11-edf2-4336-a0ed-1c9333acbeb9)
不能正常播放的文件信息
![图片](https://github.com/gitbobobo/StreamMusic/assets/69845097/a673135e-aff2-4a97-b2a0-5b5f99d06a8c)
![图片](https://github.com/gitbobobo/StreamMusic/assets/69845097/f4254334-5a76-4f3d-976c-0abd0d0c3a7a)

**Platform and Device Info (操作系统及设备信息)**
 - OS: Android 
 - Version: 1.2.9

**Music Server Type (音乐服务器类型)**
navidrome 0.52.5 (c5560888)

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
能提供个文件吗，如果不能上传，发到我邮箱里也行 aqzscn@qq.com

**Comment by ZGLinus** [comment]
经过测试，下面这个文件也可以正常播放，看起来是用Lavf58.29.100编码的文件在音流会无法播放，用Lavf57.71.100编码的可以正常播放。
![图片](https://github.com/gitbobobo/StreamMusic/assets/69845097/286d0b5a-c228-4318-b55b-5adb920d1d70)

**Comment by gitbobobo** [comment]
经测试，mac可以播放枕着光的她，安卓等我再测试一下

**Comment by ZGLinus** [comment]
现在这个bug在没有修改任何东西的情况下神奇地消失了
