### ISSUE TITLE
AudioStation 登录过期后无法自动恢复

### ISSUE THREAD

**Issue by AbcdefgXW** [gitbobobo/StreamMusic#321]
**Describe the bug (BUG 描述)**

> 自从更新后，iOS和安卓都只能读取列表却播放不了

**To Reproduce (复现步骤)**
打开稳定复现

**Expected behavior (期望行为)**
上个版本是正常的，期待修复

**Screenshots (截图)**
![Screenshot_20240525_161859_cn aqzscn stream_music](https://github.com/gitbobobo/StreamMusic/assets/8380778/6a2ce4d3-19ed-4d7e-98f2-bb64c413ff01)
![Screenshot_20240525_161904_cn aqzscn stream_music](https://github.com/gitbobobo/StreamMusic/assets/8380778/79db56ef-3aa2-4d81-b06d-8471cb555564)

**Platform and Device Info (操作系统及设备信息)**
iOS17.5
鸿蒙42

**Music Server Type (音乐服务器类型)**
群晖自带

**Comment by gitbobobo** [comment]
重新登录试试可以吗？看着像是登录信息失效了

**Comment by AbcdefgXW** [comment]
> 重新登录试试可以吗？看着像是登录信息失效了

欧真的可以，谢谢了

**Comment by gitbobobo** [comment]
嗯，再用一段时间试试，可能自动重新登录的逻辑没有处理好

**Comment by gitbobobo** [comment]
1.3.0已发布
