### ISSUE TITLE
没有歌曲页面的图片

### ISSUE THREAD

**Issue by q2051839** [gitbobobo/StreamMusic#323]
WIN最新版
jellyfin最新服务端10.9.2
确认其他软件都可以读取专辑图片。都是内嵌好的。
![捕获](https://github.com/gitbobobo/StreamMusic/assets/38458888/593739f2-d6b8-4809-9500-a3a378d49b74)
歌手页面是正常读取的。
![2](https://github.com/gitbobobo/StreamMusic/assets/38458888/8822d81d-08b5-485a-bee0-578eae333ee6)

**Comment by q2051839** [comment]
![image](https://github.com/gitbobobo/StreamMusic/assets/38458888/4e93e017-2886-4735-bcf4-b236fca8c8c2)

**Comment by gitbobobo** [comment]
好的，我试试看，如果你的服务可以公网访问的话，可以邮箱 aqzscn@qq.com 发我一个测试账号，这样比较容易复现问题

**Comment by q2051839** [comment]
> 好的，我试试看，如果你的服务可以公网访问的话，可以邮箱 [aqzscn@qq.com](mailto:aqzscn@qq.com) 发我一个测试账号，这样比较容易复现问题

已发送

**Comment by whtry** [comment]
我有同样的问题，还请尽快修复，谢谢

**Comment by gitbobobo** [comment]
1.3.1已更新，可以试试有无修复
