### ISSUE TITLE
希望音流能给会员 新增USB独占的功能

### ISSUE THREAD

**Issue by hbmask** [gitbobobo/StreamMusic#325]
希望音流能给会员 新增USB独占的功能

在听歌的时候,插着小尾巴,老是有其他信息老骚扰....特别烦人...

**Comment by gitbobobo** [comment]
在 1.3.x 会考虑添加，与此问题 https://github.com/gitbobobo/StreamMusic/issues/36 相同，先关闭了

**Comment by hbmask** [comment]
您的来信我已经收到，我会尽快回复你。
