### ISSUE TITLE
歌词识别

### ISSUE THREAD

**Issue by dsa14962** [gitbobobo/StreamMusic#326]
歌词识别，可以增加适配一下其他的编码格式吗，用fb2000内嵌的歌词基本上都不支持。

**Comment by gitbobobo** [comment]
目前音流能识别歌词的音乐格式比较有限，依赖开源插件的支持，所以最好是服务端能支持歌词识别。

短期内不会对此进行更多优化。

（我一般是用musictag加的标签，如果fb2000不支持的话，可以试试这个）
