### ISSUE TITLE
专辑页面下歌曲排序混乱

### ISSUE THREAD

**Issue by Melanrabbit** [gitbobobo/StreamMusic#329]
**Describe the bug (BUG 描述)**
歌曲无法按照音轨号排序

**To Reproduce (复现步骤)**
1. 进入专辑页面
2. 点进含有多首歌曲的专辑
3. 歌曲无法按照音轨号排序
4. 右上角排序方式中只有按照时间、歌曲名、专辑名排序三种

**Expected behavior (期望行为)**
希望增加按照音轨号排序

**Screenshots (截图)**
![IMG_7286](https://github.com/gitbobobo/StreamMusic/assets/170956004/58ff942d-740f-41d9-87b3-4b4c0df7716f)

**Platform and Device Info (操作系统及设备信息)**
 - OS: iOS 17.4.1, Windows11 23H2
 - Browser: Edge]
 - Version: iOS(1.2.9), Windows(1.2.9)

**Music Server Type (音乐服务器类型)**
e.g. navidrome [0.52.5]

**Additional context (额外信息)**

**Comment by lxw314** [comment]
+1，俺也是升到1.2.9就全乱了

**Comment by Blaiselux** [comment]
同样遇到这个问题，抓狂

**Comment by gitbobobo** [comment]
与此问题 https://github.com/gitbobobo/StreamMusic/issues/303 相同，在歌单页面也会有同样问题，下个版本修复
