### ISSUE TITLE
加入根据歌曲类型自动生成歌单

### ISSUE THREAD

**Issue by heihei1634** [gitbobobo/StreamMusic#33]

**Comment by gitbobobo** [comment]
在我自己的曲库中，大部分歌曲都没有类型标签，如果仅根据标签信息来生成我认为是不现实的，除非可以从某个API获取

**Comment by cfandora** [comment]
这个功能navidrome自己就有，不需要音流来实现。参考这里自己写json并导入 https://github.com/navidrome/navidrome/issues/1417

**Comment by gitbobobo** [comment]
自动生成歌单确实还是服务端实现好一点
