### ISSUE TITLE
Android 客户端 1.2.9不播放问题

### ISSUE THREAD

**Issue by lw-zg** [gitbobobo/StreamMusic#333]
环境：Android 13
客户端：1.2.9
音乐服务器：navidrome
如下视频，已经听过缓存完成的歌曲不能播放，不是全部的歌曲不能播放，缓存的歌曲有部分不能播放。
![S40529-09572484-1_小萌GIF_20240529_111634.gif](https://github.com/gitbobobo/StreamMusic/assets/19853331/120d583e-21c4-4f0c-96b8-121f72cc2faf)

**Comment by gitbobobo** [comment]
歌曲未完整缓存可能导致此问题，与此问题 https://github.com/gitbobobo/StreamMusic/issues/316 相同
