### ISSUE TITLE
emby服务器连上歌手简介显示不了

### ISSUE THREAD

**Issue by yche2990** [gitbobobo/StreamMusic#341]
**Describe the bug (BUG 描述)**

用emb连上歌手简介显示不了

**To Reproduce (复现步骤)**

**Expected behavior (期望行为)**

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**

**Music Server Type (音乐服务器类型)**
e.g. emby 4.17.

**Additional context (额外信息)**

**Comment by yche2990** [comment]
![IMG_1748](https://github.com/gitbobobo/StreamMusic/assets/48862442/b82ccdd8-5eed-4eda-a4cc-21dcefa5a638)
![IMG_1749](https://github.com/gitbobobo/StreamMusic/assets/48862442/40455fc6-cf5e-4b8d-8939-f24b4418c883)
![IMG_1750](https://github.com/gitbobobo/StreamMusic/assets/48862442/ed11c5e1-b978-4340-a20c-ed1570ec3f2b)
emby里是有介绍的，音流则看不到。

**Comment by gitbobobo** [comment]
再次确认1.3.1可以显示简介，此问题暂时关闭。

若还存在问题可重新打开此问题，最好能邮件发我一个测试账号方便我排查问题
