### ISSUE TITLE
Mac客户端（1.2.9）无法登录Emby服务器（4.8.8.0）

### ISSUE THREAD

**Issue by kele-manong** [gitbobobo/StreamMusic#343]
**Describe the bug (BUG 描述)**
Mac版本客户端（1.2.9版本）无法登录Emby服务器，但是同版本的windows客户端就可以。
Emby服务器的版本是4.8.8.0，windows安装版本。

**To Reproduce (复现步骤)**
Mac1.2.9版本，选择emby服务器登录，即可复现
（反复确认，服务器，用户名密码没有错误）

**Expected behavior (期望行为)**
应该可以正常登录，如windows那样

**Screenshots (截图)**
略，没有报出明显错误，

**Platform and Device Info (操作系统及设备信息)**
 - OS: MacOS 14.5 (23F79)
 - Version [1.2.9]

**Music Server Type (音乐服务器类型)**
emby 4.8.8.0 windows安装版

**Additional context (额外信息)**
同样服务器，windows就没问题

**Comment by gitbobobo** [comment]
登录的逻辑是一样的，我这里正常，建议检查下网络
