### ISSUE TITLE
pc客户端不放歌挂一两个小时后，不能继续播放歌曲

### ISSUE THREAD

**Issue by jehulv** [gitbobobo/StreamMusic#344]
**Describe the bug (BUG 描述)**
pc客户端不放歌挂一两个小时后，不能继续播放歌曲

**To Reproduce (复现步骤)**
1.暂停播放歌曲，然后盖上笔记本，隔一两小时后重新点播放，不能播放
2.多次关闭重启客户端后可以播放，但是不能收藏歌曲了（提示离线模式不能收藏），需要切换网络环境

**Expected behavior (期望行为)**
1.暂停播放长时间后还可以继续播放
2.只要能继续播放新歌曲，线路就没问题，应支持收藏

**Screenshots (截图)**
![image](https://github.com/gitbobobo/StreamMusic/assets/72123312/3b5d9cf7-a09b-46d8-82b5-0444cca25edb)

**Platform and Device Info (操作系统及设备信息)**
win10

**Music Server Type (音乐服务器类型)**
navidrome

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
可以尝试下测试版本 https://devmusic.aqzscn.cn/docs/versions/latest 是否还有此问题

**Comment by jehulv** [comment]
目前未复现点击播放不能播放，但还是会出现无法收藏
![image](https://github.com/gitbobobo/StreamMusic/assets/72123312/38872000-fb5d-4d0d-be3e-c821e24c8260)

**Comment by gitbobobo** [comment]
出现这种情况后点下右上角的重连按钮看看是否能恢复

**Comment by jehulv** [comment]
收藏歌曲可能和使用异地组网有关，把twingate关了，现在没出现了
