### ISSUE TITLE
ios 播放过的会无法播放

### ISSUE THREAD

**Issue by fightroad** [gitbobobo/StreamMusic#347]
iOS 16.2
1.2.9
nv 服务器
1.歌单或专辑右上角更多菜单点击里面的删除或下载 后，一直显示加载。导致无法进行操作，只能关掉进程重进。鸿蒙也一样。
2.opus 转码的音乐，发现原来播放过的歌再点击无法播放，进度条也不动。
3.dlan 无法投送 。ios 和鸿蒙测试都不能。
4. 提个建议，现在歌词界面的歌词和音量按钮感觉有点违和。调音量要进歌词界面调有点不符合操作。
希望音流越来越完善！原来一直用 play:sub 为了要好用点还专门联系作者贡献了中文翻译。后面发现提了一些问题 bug，一直没修复，迭代很慢。最近发现音流试用了下果断订阅了。主要看中了界面简洁漂亮有 和CarPlay。

**Comment by gitbobobo** [comment]
1下个版本会修复
2等我确认一下，最好还是用aac或者mp3转码
3下下个版本修复
4音量调节主要是为桌面端设计的，手机端更推荐直接用实体按键

**Comment by fightroad** [comment]
> 1下个版本会修复
> 2等我确认一下，最好还是用aac或者mp3转码
> 3下下个版本修复
> 4音量调节主要是为桌面端设计的，手机端更推荐直接用实体按键

opus 转码 安卓也是一样，该问题在其他播放器也出现过。(amperfy)

**Comment by gitbobobo** [comment]
那就不太好解决了，可能是歌曲文件经过流传输部分数据改变了，导致下次读取本地缓存播放时歌曲文件解码失败了

**Comment by gitbobobo** [comment]
1.3.2已经优化了缓存逻辑，此问题应该已经解决。还有问题可以重新开启此issue
