### ISSUE TITLE
navidrome 评分和收藏不起作用

### ISSUE THREAD

**Issue by fightroad** [gitbobobo/StreamMusic#348]
1.2.9
nv 服务器
专辑 评分和收藏不起作用
歌手 评分和收藏不起作用  搜索筛选不起作用  列出的都是全部 
歌曲 评分不起作用   收藏是起作用

**Comment by fightroad** [comment]
> 我这里都正常，是直连模式还是默认的媒体库模式？

媒体库模式

**Comment by fightroad** [comment]
> 我这里都正常，是直连模式还是默认的媒体库模式？

提示收藏成功  其实是没起作用。评分点星星没用。

**Comment by gitbobobo** [comment]
navi版本多少？似乎0.52.5会有此问题

**Comment by fightroad** [comment]
> navi版本多少？似乎0.52.5会有此问题

我用的就是最新的这个版本

**Comment by gitbobobo** [comment]
我在docker新安装了0.52.5，依旧没有复现此问题，可以尝试使用此测试版本https://devmusic.aqzscn.cn/docs/versions/latest，若还有问题，重新安装一下navi试试。

**Comment by fightroad** [comment]
> 我在docker新安装了0.52.5，依旧没有复现此问题，可以尝试使用此测试版本https://devmusic.aqzscn.cn/docs/versions/latest ，若还有问题，重新安装一下navi试试。

我是 ios 的

**Comment by fightroad** [comment]
> 我在docker新安装了0.52.5，依旧没有复现此问题，可以尝试使用此测试版本https://devmusic.aqzscn.cn/docs/versions/latest ，若还有问题，重新安装一下navi试试。

用安卓测试了下，问题出现在媒体库下。直连没有问题。媒体库下评分和收藏还是有问题。直连和媒体库模式主要是有些什么区别。

**Comment by fightroad** [comment]
> 我在docker新安装了0.52.5，依旧没有复现此问题，可以尝试使用此测试版本https://devmusic.aqzscn.cn/docs/versions/latest ，若还有问题，重新安装一下navi试试。

媒体库模式下，评分和收藏点击没反应，实际接口是成功了，但是界面没有表现感觉没起作用，同时数据也不会刷新，要点击下立即同步才会看到。直连模式没有问题，点击后是直接有反馈。

**Comment by gitbobobo** [comment]
1.3.0已发布
