### ISSUE TITLE
歌单建议增加重复检查，并支持歌单内搜索歌曲

### ISSUE THREAD

**Issue by jehulv** [gitbobobo/StreamMusic#349]
**Describe the bug (BUG 描述)**
歌单建议增加重复检查，并支持歌单内搜索歌曲

**To Reproduce (复现步骤)**
1.收藏歌曲到歌单的时候，可以重复添加到歌单，歌单里面会出现多条相同的歌曲
2.查看歌单排序，按添加时间筛选，刚新增的歌曲去到了中间位置
3.不支持歌单内搜索，只能一首一首找刚新增的歌曲位置

**Expected behavior (期望行为)**
1.收藏时增加重复检验，不能重复添加相同歌曲到歌单，如果之前已经添加到歌单的，新添加也会提示已存在
2.歌单内筛选有效
3.歌单内支持歌曲搜索
4.pc端支持展示所有歌单

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
主要是安卓客户端

**Music Server Type (音乐服务器类型)**
navidrome

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
歌单排序问题1.3.0测试版已修复。

重复检查我记得是有这个逻辑的，你是用直连模式还是默认的媒体库模式？

**Comment by jehulv** [comment]
我用的还是1.2.9，我稍后更新下。用的直连模式

**Comment by gitbobobo** [comment]
直连模式的话，重复校验不太合适，因为要从服务端查询歌曲是否在歌单中，批量操作会导致速度过慢。

这个去重工作我个人觉得最好是在服务端完成，或许给navi提个建议有可能解决？

**Comment by jehulv** [comment]
歌单添加歌曲现在到navidrome网页端确实更好些，歌单增加搜索栏可以看着安排下
