### ISSUE TITLE
加入多服务器切换功能

### ISSUE THREAD

**Issue by ZGLinus** [gitbobobo/StreamMusic#35]
我使用一个navidrome管理我的本地音乐，另外一个navidrome管理我订阅的播客内容，但是音流只支持连接到一个服务器，希望加入多服务器切换功能。

**Comment by zheyiyuezhuo** [comment]
赞同，确实可以，这样我就可以连一个navidrome和一个jellyfin了！

**Comment by itodouble** [comment]
我想的是 一个外网一个内网 不切换账号 切换链接

**Comment by gitbobobo** [comment]
1.3.0已发布
