### ISSUE TITLE
CarPlay 图标优化

### ISSUE THREAD

**Issue by fightroad** [gitbobobo/StreamMusic#350]
音流使用了几天，carplay 提几点建议，希望能采纳。
1.播放界面的收藏和循环播放按钮太小了，可以模仿下  qq 音乐的界面。
![00DC3325-D933-492B-9572-470102D5A3AE](https://github.com/gitbobobo/StreamMusic/assets/39027157/f198e428-4fe7-443b-b3e3-1e8cce717cfc)
![52694C54-DECC-49C0-812F-384E66D225EC](https://github.com/gitbobobo/StreamMusic/assets/39027157/825cd107-94a0-4364-8fb9-696049bf309b)

2.现在就听页面的本地音乐加个图标统一下 ui
![FF3DEAFB-5640-4F18-B540-AE8D994F7E72](https://github.com/gitbobobo/StreamMusic/assets/39027157/b0417441-34c0-4b4f-a8b9-659e6999159b)
3.即将播放列表只会显示当前播放音乐的封面。
![D7002BED-06BB-4FDF-A977-9C35E5250C5E](https://github.com/gitbobobo/StreamMusic/assets/39027157/06dca08c-924a-4751-b9a4-dd0000c1ebc3)

**Comment by BlackskinLee** [comment]
你好，你的carplay显示歌词吗？ios那个版本？

**Comment by fightroad** [comment]
> 你好，你的carplay显示歌词吗？ios那个版本？

不显示歌词

**Comment by BlackskinLee** [comment]
> 显示歌词需要打开 歌词 - 歌词通知

谢谢

**Comment by gitbobobo** [comment]
@fightroad 3 应该是列表中其他项目的图片正在加载中，所以没有显示，1和2我处理一下

**Comment by gitbobobo** [comment]
1.3.0已发布

**Comment by fightroad** [comment]
> 1.3.0已发布

我更新测试  发现并没有变化。
