### ISSUE TITLE
navidrome直连特殊搜索词错误

### ISSUE THREAD

**Issue by yuygfgg** [gitbobobo/StreamMusic#352]
**Describe the bug (BUG 描述)**
在搜索包含 / 的搜索词时出错
**To Reproduce (复现步骤)**
1. 输入包含 / 的搜索词
2. 按回车

**Expected behavior (期望行为)**
正确搜索
**Screenshots (截图)**
<img width="1178" alt="截屏2024-06-10 21 20 18" src="https://github.com/gitbobobo/StreamMusic/assets/140488233/4c5ead64-2539-4e54-9783-391509b8ffd3">

**Platform and Device Info (操作系统及设备信息)**
 - OS: macOS
 - Version 1.2.9

**Music Server Type (音乐服务器类型)**
e.g. navidrome latest

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
1.3.0已发布
