### ISSUE TITLE
重复下载歌曲

### ISSUE THREAD

**Issue by ilwzmf** [gitbobobo/StreamMusic#353]
Android，打开了边听边存和自动下载歌单（不确定是否这两配置影响）
手机硬盘上的歌曲下载了两份
![20240611-113109](https://github.com/gitbobobo/StreamMusic/assets/3972546/bf2cde35-4684-4523-ac9b-6270d10e9618)

**Comment by gitbobobo** [comment]
自动下载的去重机制出了问题，请等待下个版本修复

或在此 https://devmusic.aqzscn.cn/docs/versions/latest 下载测试版试用（可能需要卸载之前版本）

**Comment by gitbobobo** [comment]
1.3.0已发布
