### ISSUE TITLE
 navidrome 歌手封面返回占位符导致不会调用自定义 api 接口

### ISSUE THREAD

**Issue by fightroad** [gitbobobo/StreamMusic#355]
nv 在没有找到歌手封面的时候会默认返回五角星图片占位。配置了自定义 api 获取歌手，由于 nv  不返回空导致不会去调自定义 api.
需要音速对 nv 这种处理做下处理，如果返回是占位的五角星认为是没图像，触发去调 api.如果 api 也没有就给默认的图像或 nv 返回的占位五角星。

**Comment by gitbobobo** [comment]
1.3.0已发布
