### ISSUE TITLE
无损格式无法正常播放如AIFF和DSD

### ISSUE THREAD

**Issue by timelord2018** [gitbobobo/StreamMusic#360]
![image](https://github.com/gitbobobo/StreamMusic/assets/35413966/1d2c67dc-a093-4900-bd2f-c7dbf41d94a1)

![image](https://github.com/gitbobobo/StreamMusic/assets/35413966/fef15e98-6580-4eab-9562-3d78fffd3f51)
如图，转码成mp3可以。音乐在audio station上可以正常播放。

**Comment by timelord2018** [comment]
播放无损音乐的时候软件会卡死，无法做任何操作，也无法关闭退出。只能任务管理器强制退出。

**Comment by timelord2018** [comment]
找到原因了，应该是https加密协议的问题。改为http明文连接就好很多了

**Comment by gitbobobo** [comment]
好很多是什么意思。。是有的能播有的播不了吗
