### ISSUE TITLE
按评分筛选能增加没有评分的选项么？

### ISSUE THREAD

**Issue by sayggtome** [gitbobobo/StreamMusic#362]
![image](https://github.com/gitbobobo/StreamMusic/assets/98970107/4cc27789-cb31-4b88-a8b8-e58cc31e8dc8)
现在按评分筛选只能筛选1星到5星的歌曲，能增加一个没有评分的筛选选项么？谢谢。

**Comment by gitbobobo** [comment]
1.3.0已发布
