### ISSUE TITLE
emby同步25w以上的歌曲库会一直卡着不动

### ISSUE THREAD

**Issue by Pitaya-ligang** [gitbobobo/StreamMusic#365]
[**Describe](url) the bug (BUG 描述)**
emby同步25w以上的歌曲库会一直卡着不动

**To Reproduce (复现步骤)**

**Expected behavior (期望行为)**

**Screenshots (截图)**
![image](https://github.com/gitbobobo/StreamMusic/assets/35123309/d06c72ef-f0e3-4f72-8b5c-9d78b507f25b)

**Platform and Device Info (操作系统及设备信息)**
ios16

**Music Server Type (音乐服务器类型)**
emby 4.9.0.25

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
如果你的emby可以公网访问，可以邮件发我一个测试账号(aqzscn@qq.com)，我这边没那么多歌曲触发这个问题。

而且我觉得这个问题可能是由于数据解析失败导致同步任务卡住了

**Comment by Pitaya-ligang** [comment]
> 如果你的emby可以公网访问，可以邮件发我一个测试账号([aqzscn@qq.com](mailto:aqzscn@qq.com))，我这边没那么多歌曲触发这个问题。
> 
> 而且我觉得这个问题可能是由于数据解析失败导致同步任务卡住了

已发送

**Comment by gitbobobo** [comment]
1.3.0已发布
