### ISSUE TITLE
歌单播放列表顺序紊乱

### ISSUE THREAD

**Issue by kawashiro-ryofu** [gitbobobo/StreamMusic#367]
**Describe the bug (BUG 描述)**
歌单中的歌曲播放顺序与navidrome中不同

**To Reproduce (复现步骤)**
从1.2.7升级1.2.9后，歌单播放顺序紊乱
1.2.7版本中歌单“按添加时间排序”与navidrome歌单默认排序相同
1.2.8后歌单播放顺序紊乱

**Expected behavior (期望行为)**
添加“默认排序”的排序方式，使歌单歌曲排序与navidrome一致

**Screenshots (截图)**
*排序方式均为“按添加时间排序”*

- navidrome中，该歌单第一首歌为*I Really Want to Stay at Your House*

![navidrome中，该歌单第一首歌为*I Really Want to Stay at Your House*](https://github.com/gitbobobo/StreamMusic/assets/53611149/25aefc09-4be4-470f-834c-06f9cc588214)

- v1.2.9，同一歌单第一首歌为*アイスドロップ*

![v1.2.9，同一歌单第一首歌为*アイスドロップ*](https://github.com/gitbobobo/StreamMusic/assets/53611149/bc1470b4-a282-463b-9f40-a352568f1abf)

- v1,2,7，同一歌单第一首歌为*I Really Want to Stay at Your House*，与navidrome一致

![v1,2,7，同一歌单第一首歌为*I Really Want to Stay at Your House*](https://github.com/gitbobobo/StreamMusic/assets/53611149/46508495-4727-4dad-a1ca-d39466050d9b)

**Platform and Device Info (操作系统及设备信息)**
该issue所提出的问题与设备无关，在安卓端出现了相同的问题

**Music Server Type (音乐服务器类型)**
Navidrome v0.51.0

**Additional context (额外信息)**
该问题在[#329](https://github.com/gitbobobo/StreamMusic/issues/329)中被我提及过，并没有得到解决

**Comment by gitbobobo** [comment]
问题重复了 https://github.com/gitbobobo/StreamMusic/issues/303 ，你应该用1.3.0测试
