### ISSUE TITLE
倍速播放可自定义

### ISSUE THREAD

**Issue by liang67** [gitbobobo/StreamMusic#37]
默认的倍速播放无法满足要求，1.25倍太块，希望可以自定义。如1.1倍速 或者 1.15倍速，

**Comment by gitbobobo** [comment]
有什么使用场景吗？听歌我觉得用不着这么详细的倍速吧

**Comment by liang67** [comment]
电子书，1倍速太慢了，1.25又太快

**Comment by liang67** [comment]
![Screenshot_2023-09-15-22-07-39-152_app.symfonik.music.player-edit.jpg](https://github.com/gitbobobo/StreamMusic/assets/158511/53a5b448-1294-4aca-a47c-42ece57c80fc)

补一个symfonium软件的设置图
