### ISSUE TITLE
关于删除本地音乐问题

### ISSUE THREAD

**Issue by hyf20030316** [gitbobobo/StreamMusic#371]
**Describe the bug (BUG 描述)**
删除本地音乐成功后，删除窗口不收回，且一直显示加载中，且一直停留在加载中，不可进行其他任何操作

**To Reproduce (复现步骤)**
只要删除本地音乐百分百出现，在导入歌单的时候也会百分百出现
**Expected behavior (期望行为)**
删除本地音乐后窗口收回，且不会出现一直停留在加载中界面

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 - OS: Android 14
 - Browser
 - Version 1.2.9

**Music Server Type (音乐服务器类型)**
Navidrome 0.52.5
![Screenshot_20240620_103353](https://github.com/gitbobobo/StreamMusic/assets/61220765/743b2f49-3810-4285-baca-27ab8b366d07)
![Screenshot_20240620_103356](https://github.com/gitbobobo/StreamMusic/assets/61220765/94fcea7f-e11c-4baa-b1d1-f92c8bee9c0b)

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
安卓可以去 https://devmusic.aqzscn.cn/docs/versions/latest 安装测试版，应该已经解决了

**Comment by gitbobobo** [comment]
1.3.0已发布
