### ISSUE TITLE
期待1.3.0版本！

### ISSUE THREAD

**Issue by ersaijun** [gitbobobo/StreamMusic#374]
**Describe the bug (BUG 描述)**

**To Reproduce (复现步骤)**

**Expected behavior (期望行为)**

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**

**Music Server Type (音乐服务器类型)**
e.g. emby 4.17.

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
1.3.0已发布
