### ISSUE TITLE
password填写不校验是否填写

### ISSUE THREAD

**Issue by lalalamiheart** [gitbobobo/StreamMusic#377]
**Describe the bug (BUG 描述)**
服务器免password登录

**To Reproduce (复现步骤)**
见截图

**Expected behavior (期望行为)**
jellyfin 未设置密码的情况。

**Screenshots (截图)**
![image](https://github.com/gitbobobo/StreamMusic/assets/166940417/47db5610-8284-4efe-bd46-a43024b8cbc8)

**Comment by gitbobobo** [comment]
1.3.0已发布
