### ISSUE TITLE
这个支持emby的直链吗？

### ISSUE THREAD

**Issue by xinxuxu** [gitbobobo/StreamMusic#378]
emby弄了直链，客户端都没问题，就音流走服务器流量，是这个不支持还是我操作有问题？

**Comment by gitbobobo** [comment]
没明白，什么直链啊

**Comment by xinxuxu** [comment]
> 没明白，什么直链啊

说起来有点复杂，就是这个项目，https://github.com/bpking1/embyExternalUrl，播放的时候走网盘的流量，不走服务器的，我也向该作者反馈过这个问题https://github.com/bpking1/embyExternalUrl/issues/241

**Comment by xinxuxu** [comment]
> 没明白，什么直链啊

说起来有点复杂，就是这个项目，https://github.com/bpking1/embyExternalUrl，
播放的时候走网盘的流量，不走服务器的。


我也向该作者反馈过这个问题
https://github.com/bpking1/embyExternalUrl/issues/241

我试过其他的软件都没问题，用音流，有些歌曲就放不了

**Comment by xinxuxu** [comment]
我觉得emby和alist直链这个组合是个趋势，大佬可以考虑针对性的适配一下，歌曲本身使用的流量是不大，但如果多用户使用，直链快得多，而且一点都不卡

**Comment by xinxuxu** [comment]
我觉得emby和alist直链这个组合是个趋势，大佬可以考虑针对性的适配一下，歌曲本身使用的流量是不大，但如果多用户使用，直链快得多，而且一点都不卡，可以和亲朋好友共享音乐库，对开会员也是有利的，毕竟多端适配就仅此一家了

**Comment by gitbobobo** [comment]
看到这个issue了，我试试第二首歌晚点获取能不能解决这个问题。

**Comment by AmbitiousJun** [comment]
> 我觉得emby和alist直链这个组合是个趋势，大佬可以考虑针对性的适配一下，歌曲本身使用的流量是不大，但如果多用户使用，直链快得多，而且一点都不卡，可以和亲朋好友共享音乐库，对开会员也是有利的，毕竟多端适配就仅此一家了

还有这个问题吗，emby 直链反代仓库我有参与贡献过。
前几天我也发现这个问题了，音流走的还是服务器流量，排查了一下原因是 nginx 没有反代到音流请求的那个接口，只需要修改一下 `emby.conf` 文件，重启 docker 即可：

原始配置（片段）：
```
    # Redirect the stream to njs
    location ~* /videos/(.*)/stream {
        # Cache alist direct link
        # add_header    Cache-Control  max-age=3600;
        js_content emby2Pan.redirect2Pan;
    }
```

修改后（在下边重新加一条配置）：
```
    # Redirect the stream to njs
    location ~* /videos/(.*)/stream {
        # Cache alist direct link
        # add_header    Cache-Control  max-age=3600;
        js_content emby2Pan.redirect2Pan;
    }
    # Redirect the stream to njs
    location ~* /Audio/(.*)/stream {
        # Cache alist direct link
        # add_header    Cache-Control  max-age=3600;
        js_content emby2Pan.redirect2Pan;
    }
```
