### ISSUE TITLE
iOS版本无法按照专辑音轨顺序排序

### ISSUE THREAD

**Issue by heiway** [gitbobobo/StreamMusic#383]
**Describe the bug (BUG 描述)**
在有音轨编号的情况下，iOS版本不按照音轨编号排序。Macos版本的正确。

**To Reproduce (复现步骤)**
1. 进入专辑界面
2. 选中某个专辑
3. 歌曲排序混乱，见截图。

**Expected behavior (期望行为)**
默认按照专辑的音轨编号排序，并能够在切换排序方式后，还能主动将排序方式选择为按音轨编号排序。

**Screenshots (截图)**
![IMG_DD37C1613041-1](https://github.com/gitbobobo/StreamMusic/assets/12270764/c94fc986-86af-4220-8d15-80257831f1ed)

**Platform and Device Info (操作系统及设备信息)**
 - OS: iOS
 - Version 17.5.1

**Music Server Type (音乐服务器类型)**
navidrome 0.51.1

**Additional context (额外信息)**

**Comment by shaoxuantoo** [comment]
我以为是我手机有问题直到我用安卓备用机看到排序正常，确实，希望修复，极度影响体验

**Comment by KurumiSerori** [comment]
+1 iOS 的“按专辑名排序”似乎效果与“按添加时间倒序”排序是一致的，不知道是菜单映射有问题还是实现上有问题。

**Comment by yqsas** [comment]
+1 希望修复

**Comment by kele-manong** [comment]
不光是iOS，我mac版本也是乱序，实际上我安卓版本也是乱序。
我感觉是一旦我选过一个排序方式，就回不来了，因为没有按歌曲序号排序这个选项。

**Comment by Tom-Smithman** [comment]
+1

**Comment by gitbobobo** [comment]
1.3.0已发布
