### ISSUE TITLE
多线路切换无法成功

### ISSUE THREAD

**Issue by rfrftt** [gitbobobo/StreamMusic#387]
**Describe the bug (BUG 描述)**
IOS v1.2.9  主线路局域网地址不能访问时，无法自动切换线备用线路，

**To Reproduce (复现步骤)**
1. 配置主线路，备用线路1 备用线路2，刚配置完成能正常使用
2. 上划关闭app
3. 隔一段时间后,切换到移动网络或无法直连主线路的wifi网络 
4. 打开app,同步数据时提示认证过期(然而并没有修改密码),自动切换线路失败，手动切换所有备用线路，提示 连接中... 后连接失败
5. **Expected behavior (期望行为)**
任意可连接备用线路下正常同步数据并正确播放

**Screenshots (截图)**
![wechat](https://github.com/gitbobobo/StreamMusic/assets/30916155/4f71f934-a41d-40ef-85ff-ac234e0bdbcd)

**Platform and Device Info (操作系统及设备信息)**
 - OS: IOS
 - Version 17.4

**Music Server Type (音乐服务器类型)**
navidrome v0.52.5

**Comment by rfrftt** [comment]
重新验证，判断是线路连接性问题，另一个时间测试发现能正常切换
潜在的超时判断问题: 切换线路发生问题时，通过浏览器发起web界面的登录和播放没有问题，app内切换线路提示超时

**Comment by gitbobobo** [comment]
1.3.0已发布
