### ISSUE TITLE
多终端 播放 dsf 文件会直接卡死，只能强退

### ISSUE THREAD

**Issue by zhanguohao** [gitbobobo/StreamMusic#388]
**Describe the bug (BUG 描述)**
 播放 dsf 文件会直接卡死，只能强退

**To Reproduce (复现步骤)**

**Expected behavior (期望行为)**

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**

MacBook Pro 14.5
ios 17.5.1

**Music Server Type (音乐服务器类型)**
emby 4.8.8.0

**Additional context (额外信息)**

**Comment by cheng2004237** [comment]
是的，我也发现这个问题了~

**Comment by codermali** [comment]
同样的问题，请问解决了嘛

**Comment by gitbobobo** [comment]
我的曲库没有dsf格式的文件，谁可以邮件发我一个吗？aqzscn@qq.com

**Comment by Aiden92** [comment]
同样的问题

**Comment by gitbobobo** [comment]
1.3.2最新测试版已修复，可以先试试看有没有问题

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布
