### ISSUE TITLE
直连模式每次进入都会重新完整下载选中的音乐

### ISSUE THREAD

**Issue by sfgghtu** [gitbobobo/StreamMusic#391]
直连模式每次进入都会重新完整下载选中的音乐，在本地生成多份相同的音乐文件（ios，安卓都有这个问题），服务端用的emby

**Comment by cyril-2048** [comment]
有遇到同样问题，不管是不是直连模式，均会出现这个问题。

**Comment by gitbobobo** [comment]
1.3.0已发布
