### ISSUE TITLE
1.3.0自定义歌词接口切换歌词失效.

### ISSUE THREAD

**Issue by lee86** [gitbobobo/StreamMusic#392]
**Describe the bug (BUG 描述)**
1.3.0自定义歌词接口切换歌词失效.

**To Reproduce (复现步骤)**
1. 播放页面点击`LRC-切换歌词`
2. 点击搜索，无响应，自定义接口未收到请求
3. limit=1时，正常解析请求歌词

**Screenshots (截图)**
![image](https://github.com/gitbobobo/StreamMusic/assets/25501580/0c9f0d83-2032-411c-aa45-584b9df7e3a9)

**Platform and Device Info (操作系统及设备信息)**
 - OS: windows 11

**Additional context (额外信息)**
接口请求返回正常
![image](https://github.com/gitbobobo/StreamMusic/assets/25501580/3565fdd7-d8d2-4ac3-88df-a38fa6507ed9)
limit=10，接口返回正常
![image](https://github.com/gitbobobo/StreamMusic/assets/25501580/f96ff5d7-3807-46bf-83ef-229f733ed809)

**Comment by gitbobobo** [comment]
已更新，试试看还有没有问题

**Comment by lee86** [comment]
> 已更新，试试看还有没有问题

能正常请求了
