### ISSUE TITLE
Navidrome 使用ND_BASEURL 属性挂到子目录上时，会导致部分音乐无法播放。连时间都不显示

### ISSUE THREAD

**Issue by iamckun** [gitbobobo/StreamMusic#393]
**Describe the bug (BUG 描述)**
Navidrome 使用ND_BASEURL 属性挂到子目录上时，会导致部分音乐无法播放。连时间都不显示

**To Reproduce (复现步骤)**
1. ND_BASEURL 设置 `/music`
2. 直接点击列表音乐无法显示时常也无法播放

**Expected behavior (期望行为)**
希望使用子目录可以正常播放

**Screenshots (截图)**
![image](https://github.com/gitbobobo/StreamMusic/assets/65990499/7bd473a6-7119-4040-996e-2853cb43d848)

**Platform and Device Info (操作系统及设备信息)**
 - OS: 鸿蒙、ios、mac
 - Version 鸿蒙3.0 iOS16.7.8 Mac 14.5 (23F79)

**Music Server Type (音乐服务器类型)**
e.g. Navidrome 0.52.5

**Additional context (额外信息)**

**Comment by iamckun** [comment]
![image](https://github.com/gitbobobo/StreamMusic/assets/65990499/21cab30a-30e9-4f18-9682-68b5f2675d17)

**Comment by iamckun** [comment]
![image](https://github.com/gitbobobo/StreamMusic/assets/65990499/40b01175-4ad4-466f-a1fb-a688d64492aa)

**Comment by gitbobobo** [comment]
1.3.1已修复
