### ISSUE TITLE
通知栏不显示播放控件

### ISSUE THREAD

**Issue by kingsey** [gitbobobo/StreamMusic#394]
通知栏不显示播放控件，音流APP系统允许通知的选项打不开，
![Screenshot_20240703_212538](https://github.com/gitbobobo/StreamMusic/assets/9674563/f6c9e375-4ef4-4933-ab4f-a3e7397ea21b)
开启之后退回上一页再进来就又是关闭的了。其他APP的通知是正常的。
系统是Android14 originOS4
音流1.3.0 1.2.9都这样的

**Comment by YUNDAN21** [comment]
1.30出了吗

**Comment by kingsey** [comment]
> 1.30出了吗

没正式出，在开发频道

**Comment by Slandern** [comment]
对呀，我也是这样，android14 originOS4

**Comment by gitbobobo** [comment]
目前发现此问题都是出现在vivo系的手机上，目前我手上没有vivo的测试机，所以这个问题不会太快处理

**Comment by redfieldw** [comment]
我也是这样，我也是 OriginOS 4 手机，不止这个软件，Fintunes 和 Audiobookself 安卓端都打不开通知权限

**Comment by gitbobobo** [comment]
因为没有用到通知权限，安装包里的清单文件是没有声明这个权限的，所以无法打开此权限

**Comment by gitbobobo** [comment]
132测试版已修复

**Comment by kingsey** [comment]
> 132测试版已修复

控件已显示，控件上的上一首/下一首正常，播放/暂停 可以暂停，没法恢复播放。
