### ISSUE TITLE
Jellyfin 启用 base path 后， 偶现某些音乐无法播放

### ISSUE THREAD

**Issue by l5oo00** [gitbobobo/StreamMusic#396]
**Describe the bug (BUG 描述)**
当 jellyfin 服务启用 base path 后， 偶现某些音乐无法播放。

因为我是用 nginx 代理的 jellyfin， 查看 nginx 的日志发现一些请求 url 前缀为   /jellyfin/jellyfin/  的请求， 所以怀疑是 App 哪里有 bug 导致前缀重复了（正常应该只有一个 /jellyfin/ 前缀）。

测试发现 mac 、iOS App 均有问题。

**To Reproduce (复现步骤)**
1. Jellyfin 开启 base path <br><img width="660" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/1233234/8b487176-b47a-400a-95ea-eeab94f76762">
2. 清除 App 缓存， 重启 App
3. 重新登录后依次播放所有歌曲，部分歌曲会复现，且只有这些歌曲会复现

**Expected behavior (期望行为)**

所有音乐能正常播放。

**Screenshots (截图)**

查看 nginx 的 access 日志：

<img width="493" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/1233234/6b73fbb0-30c9-471d-9408-931257481754">

**Additional context (额外信息)**

因为使用了 nginx 代理， 所以临时加了一行规则处理了下，测试所有 App 上所有歌曲都可以正常播放了。

```nginx
rewrite ^/jellyfin/jellyfin/(.*)$ /jellyfin/$1 break;
```

**Comment by gitbobobo** [comment]
客户端你填的登录地址是什么样的？`ip:port/jellyfin/`吗

**Comment by l5oo00** [comment]
对，不带这个没法登录

**Comment by gitbobobo** [comment]
1.3.1已修复
