### ISSUE TITLE
MacOS 客户度无法连接 Jellyfin

### ISSUE THREAD

**Issue by gldsly** [gitbobobo/StreamMusic#398]
**Describe the bug (BUG 描述)**

**To Reproduce (复现步骤)**

**Expected behavior (期望行为)**

**Screenshots (截图)**
<img width="1112" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/32083698/23e503b4-7e2e-4ab5-8e02-c6c6b3bf753d">

**Platform and Device Info (操作系统及设备信息)**
 - 
<img width="392" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/32083698/e30f6561-402e-4059-b638-7ed31b3b2367">

**Music Server Type (音乐服务器类型)**
e.g. emby 4.17.

Jellyfin   :10.8.13

**Additional context (额外信息)**

使用 http 方式，在 wireshark 中，看不到  请求发出，直接提示 错误，相同的参数，IOS 客户端连接正常

**Comment by gitbobobo** [comment]
网络连接方面，所有平台的逻辑是一样的，iOS客户端正常，那可能就是你mac的网络环境有些问题

**Comment by gldsly** [comment]
> 网络连接方面，所有平台的逻辑是一样的，iOS客户端正常，那可能就是你mac的网络环境有些问题

#382  我和这个老哥是一样的问题，已经尝试 关闭代理软件，重启电脑，检查电脑的网络连接，都是正常，包括和 jellyfin 的服务器通信，都是正常，网页端能打开，infuse 也没问题，同时验证 手机（ios）的连接也正常。   网络地址使用的内网环境的地址。
走的也是 http 协议，端口号也是默认的 8096，账号密码都是直接复制 浏览器中记住的密码，反复退出登录，验证浏览器记住的密码是对的。

能不能增加一个在登录时，查看客户端和服务端建立连接的 错误日志的地方，现在不管怎么尝试都是上面的 提示，自己尝试排查错误也没个头绪，然后也无法反馈更详细的数据。

**Comment by gitbobobo** [comment]
先看下服务端有没有接收到请求吧，服务端应该是有查看日志的地方的

**Comment by yuhenghuang** [comment]
说起来我最近两周遇到了两次, 原因似乎是macos把音流访问本地网络的权限给取消了.

系统设置里面虽然看起来有访问本地网络的权限, 但是把该权限关闭再打开, 问题就解决了.

也不知道是软件问题还是系统问题...

**Comment by JackyLeeCS** [comment]
> 说起来我最近两周遇到了两次, 原因似乎是macos把音流访问本地网络的权限给取消了.
> 
> 系统设置里面虽然看起来有访问本地网络的权限, 但是把该权限关闭再打开, 问题就解决了.
> 
> 也不知道是软件问题还是系统问题...

为什么我的本地网络权限管理里面根本就没有音流的app，想开都开不了，现在其它应用都可以连上Jellyfin的app，就音流死活连不上
