### ISSUE TITLE
windows端安装报错

### ISSUE THREAD

**Issue by mufengyouyang** [gitbobobo/StreamMusic#399]
![image](https://github.com/gitbobobo/StreamMusic/assets/130118370/f9a123ee-bfb9-4e1e-ac9e-eed532b4a60b)
报错如图

**Comment by anderjgr** [comment]
Windows得先安装音流证书https://devmusic.aqzscn.cn/docs/guides/install

**Comment by anderjgr** [comment]
> ![image](https://private-user-images.githubusercontent.com/130118370/346247018-f9a123ee-bfb9-4e1e-ac9e-eed532b4a60b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzQ3NzAsIm5iZiI6MTcyMDQzNDQ3MCwicGF0aCI6Ii8xMzAxMTgzNzAvMzQ2MjQ3MDE4LWY5YTEyM2VlLWJmYjktNGUxZS1hYzllLWVlZDUzMmI0YTYwYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwOFQxMDI3NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYWFhYTNhYTg2OWViMzMxYzZiYzE2MTlmMjJjNjMzM2M5Y2YyZDg0YTNmYjZkYWU2NzQ2MzgzNGZjZGM0ZWZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZiGWwA4MTtogGgwI3Ssa-KsWcdt8AW1uuk9XrKPaSrw) 报错如图
Windows得先安装音流证书https://devmusic.aqzscn.cn/docs/guides/install
