### ISSUE TITLE
windows11 签名错误

### ISSUE THREAD

**Issue by sangxuesheng** [gitbobobo/StreamMusic#401]
**Describe the bug (BUG 描述)**
![image](https://github.com/gitbobobo/StreamMusic/assets/62563207/17efa566-5998-4f2b-a5d1-7f14f29cf528)

windows11 签名错误
**To Reproduce (复现步骤)**
恢复购买，邮箱验证码时出现

**Expected behavior (期望行为)**

**Screenshots (截图)**
![image](https://github.com/gitbobobo/StreamMusic/assets/62563207/17efa566-5998-4f2b-a5d1-7f14f29cf528)

**Platform and Device Info (操作系统及设备信息)**
windows11 

**Music Server Type (音乐服务器类型)**
Navidrome0.52.5 (c5560888)

**Comment by gitbobobo** [comment]
检查下系统时间，系统时间与服务端相差过大会出现这种情况
