### ISSUE TITLE
歌曲封面希望优先使用嵌入图片

### ISSUE THREAD

**Issue by yqsas** [gitbobobo/StreamMusic#402]
- Server: Navidrome 0.52.5
- Navidrome 有个选项设置封面优先级，Web 端是生效的，但是到音流无效。
- 目前音流内规则是相同专辑的歌曲，显示的是其中某歌曲的图片，没有使用各个歌曲文件内嵌的图片。
有些歌曲专辑信息不匹配的看着很混乱。
    > 有些歌手单曲较多的我统一改成相同专辑名称便于归类，并且每首歌曲都有内嵌封面

**Comment by gitbobobo** [comment]
嗯，目前统一用的专辑封面。后续除了Subsonic，其他服务端都会逐步改回使用歌曲封面

**Comment by gitbobobo** [comment]
1.3.1已重新使用歌曲封面
