### ISSUE TITLE
播放缓存的音乐时，时长/时间轴与源文件不符。

### ISSUE THREAD

**Issue by zhiyutan** [gitbobobo/StreamMusic#404]
**Describe the bug (BUG 描述)**

1. 播放器展示的文件时长与源文件不符，如源文件 5min，播放时只有 3min 的源文件切片。
2. 播放器展示的文件时长与源文件一致，但播放时的时间轴不一致，如缓存文件 0:00 ~ 1:00 的内容为源文件 4:00 ~ 5:00 的内容。

**To Reproduce (复现步骤)**
1. 设置[边听边存]。
2. 假设存在一个时长为 5min 的音乐文件，正常在线播放，待缓存完毕后，再次对播放该文件时随机出现，无法稳定复现。

**Expected behavior (期望行为)**

正常播放且时长/内容与源文件一致。

**Screenshots (截图)**

![截屏2024-07-10 16 57 12](https://github.com/gitbobobo/StreamMusic/assets/14798130/f0e3a213-ae31-4003-8eeb-dd279a284dfc)
![截屏2024-07-10 16 58 09](https://github.com/gitbobobo/StreamMusic/assets/14798130/c0b1cd1d-3eac-4191-8697-9eb2490ca72f)

**Platform and Device Info (操作系统及设备信息)**

 - OS: Android 12
 - Version: 1.2.9

**Music Server Type (音乐服务器类型)**

Navidrome 0.52.0

**Additional context (额外信息)**

目前只能通过清除本地所有缓存临时解决，建议增加重新缓存单个歌曲文件的功能，以便用户以更小的成本解决该问题。

P.S: 我看到[#371](https://github.com/gitbobobo/StreamMusic/issues/371)中有删除本地音乐的功能，似乎也可以解决这个问题，但我点击本地音乐中的删除文件时无任何响应，请问这是付费功能吗？

**Comment by zhiyutan** [comment]
> 删除本地音乐文件的bug在1.30版本解决了

好的，期待新版本。

**Comment by sfgghtu** [comment]
作者是不是遇啥事了，好久没更新了

**Comment by gitbobobo** [comment]
1.3.0已发布
