### ISSUE TITLE
artist的取值问题

### ISSUE THREAD

**Issue by w0330t** [gitbobobo/StreamMusic#405]
在播放专辑艺术家为Various Artists的音乐的时候，取值为专辑艺术家而并非当前曲目的艺术家，这不仅会导致给出的信息有误，同样也会导致API有概率搜不到歌词。

第二张图的tag信息如下（foobar2000复制导出）
```
Artist Name : Cynthia Harrell
Track Title : Snake Eater
Album Title : Metal Gear Solid Vocal Tracks
Date : 2015-09-02
Genre : Soundtrack
Composer : Norihiko Hibino
Performer : 
Album Artist : Various Artists
Track Number : 3
Total Tracks : 13
Disc Number : 1
Total Discs : 1
Comment : 
<ACOUSTID_ID> : 4108fa60-956a-4396-91b9-a938f0253517
<ALBUMARTISTSORT> : Various Artists
<ARTISTS> : Cynthia Harrell
<ARTISTSORT> : Harrell, Cynthia
<BARCODE> : 4988602168211
<CATALOGNUMBER> : GFCA-409
<COMPILATION> : 1
<ISRC> : JPM200400454
<LABEL> : KONAMI
<MEDIA> : CD
<MUSICBRAINZ_ALBUMARTISTID> : 89ad4ac3-39f7-470e-963a-56509c546377
<MUSICBRAINZ_ALBUMID> : 57ecc60e-4af9-48ce-8005-3281f62fa11e
<MUSICBRAINZ_ARTISTID> : eadf2016-229a-4f58-8098-7fdbaf3cc897
<MUSICBRAINZ_RELEASEGROUPID> : 8555598c-74fe-428e-a52c-d31315e5e6fe
<MUSICBRAINZ_RELEASETRACKID> : 07367ab6-e207-466c-97c9-a0145256ed5a
<MUSICBRAINZ_TRACKID> : ee13994a-c539-42cf-8366-da14b041f16e
<ORIGINALDATE> : 2015-09-02
<ORIGINALYEAR> : 2015
<RELEASECOUNTRY> : JP
<RELEASESTATUS> : official
<RELEASETYPE> : album; compilation; soundtrack
<SCRIPT> : Latn
```

我同时去查看了API的查看请求，确实是没有当前的歌曲艺术家Cynthia Harrell。
```
lyrics?title=Snake+Eater&artist=Various+Artists&album=Metal+Gear+Solid+Vocal+Tracks&offset=0&limit=10&path=%2Fmusic%2FVarious+Artists%2FMETAL+GEAR+SOLID+VOCAL+TRACKS+%282015%29%2F03.+Snake+Eater.flac&duration=178
```

![IMG_1305](https://github.com/gitbobobo/StreamMusic/assets/4970238/0b1a57b4-c6c5-44f5-971c-78f89b929feb)

![IMG_1307](https://github.com/gitbobobo/StreamMusic/assets/4970238/cc6e5920-c6c5-4393-a58f-7a6a32af1269)

**Comment by yuygfgg** [comment]
音流好像一直都是前往的专辑艺术家，单曲艺术家从来没有过。
前面subsonic api的实现有bug，是单曲艺术家，然后修了之后就变成专辑的了

**Comment by gitbobobo** [comment]
从歌曲这里跳转艺术家，确实单曲艺术家会更符合直觉一些。

之后除了subsonic，其他应该都会改回跳转单曲艺术家

**Comment by yuygfgg** [comment]
> 从歌曲这里跳转艺术家，确实单曲艺术家会更符合直觉一些。
> 
> 之后除了subsonic，其他应该都会改回跳转单曲艺术家

1. subsonic 应该也可以单曲艺术家的，用id3api 就行。https://github.com/kagemomiji/airsonic-advanced/issues/492 

> the API supports information retrieval through ID3 tags, allowing it to recognize an artist even if there is no album.

2. 现在的音流在专辑页面并不能前往专辑艺术家，到时候是不是加一个

3. 有没有支持opensubsonic api的打算？在subsonic基础上支持了歌曲/专辑多个艺术家

**Comment by yuygfgg** [comment]
> 嗯，单曲的跳转逻辑改了之后会在专辑那里加上入口的
> 
> opensubsonic api 有支持程度比较好的服务端吗？

https://github.com/epoupon/lms

**Comment by gitbobobo** [comment]
1.3.1已将歌手的取值改为艺术家的值，同时添加专辑中专辑艺术家的跳转
