### ISSUE TITLE
播放界面不显示歌曲图片

### ISSUE THREAD

**Issue by ReTiscCC** [gitbobobo/StreamMusic#406]
音乐服务器：Emby 4.8.8.0 (Docker)
音流版本：Windows 1.2.9

音流能够获取到专辑封面，但播放界面不显示，Emby网页端正常

音流播放列表
![20240712_122635](https://github.com/gitbobobo/StreamMusic/assets/49191851/cb7774c4-98a2-47e8-ade8-597f0b7fffbe)

音流播放界面
![20240712_122938](https://github.com/gitbobobo/StreamMusic/assets/49191851/9908f9c4-9453-4621-9733-8a1051870013)

Emby网页端
![20240712_122756](https://github.com/gitbobobo/StreamMusic/assets/49191851/3bd3c5e9-c78f-4e55-9713-e57a67fa691f)

**Comment by gitbobobo** [comment]
Windows端可以先试下测试版是否正常 https://devmusic.aqzscn.cn/

**Comment by ReTiscCC** [comment]
> Windows端可以先试下测试版本是否正常https://devmusic.aqzscn.cn/

正常了
