### ISSUE TITLE
后台任务缓存歌曲重复下载

### ISSUE THREAD

**Issue by w0330t** [gitbobobo/StreamMusic#407]
**Describe the bug (BUG 描述)**
缓存歌曲重复下载，同一首歌一直在0到100徘徊。

**To Reproduce (复现步骤)**
打开正在下载页面即可看到

**Screenshots (截图)**
https://github.com/user-attachments/assets/b463d379-a268-493a-843a-f4237ae39929

**Platform and Device Info (操作系统及设备信息)**
 - OS: iOS 
 - Version 17

**Music Server Type (音乐服务器类型)**
Navidorme

**Additional context (额外信息)**
有群友说是因为文件名以数字开头，但我整个曲库的数据都是曲目开头。如果有需要可以提供曲库做测试

**Comment by gitbobobo** [comment]
1.3.0已发布
