### ISSUE TITLE
Frp穿透，外部用Nginx做的代理，无法连接服务器

### ISSUE THREAD

**Issue by FasAway** [gitbobobo/StreamMusic#411]
服务端用的Navidrome
穿透方式用的http
服务器上加了层Nginx来Https访问
证书使用的ZeroSSL，内网环境使用IP可以正常，外网穿透环境没办法连接
外网穿透环境下，网页上可以直接访问Navidrome
![a91e69ec4b0010c9f4e9f9664bfcb0db](https://github.com/user-attachments/assets/3adfd97b-c047-4766-b3a0-d190460beb3b)
![2a967e6f85bfb64d5039bc47926dc2aa](https://github.com/user-attachments/assets/222c689d-2d06-4add-96a8-c53ffd5c1ba8)

**Comment by wrz-wrs** [comment]
类似的问题，Frp穿透，Navidrome服务，穿透后非默认端口号就无法登录
![067fd48468a43090e404fe1f3d687b8](https://github.com/user-attachments/assets/8d621439-fae4-487b-a058-3e7a7d7de5a4)
![20f91269d52d0968ad39a2259496088](https://github.com/user-attachments/assets/3739e75c-01d0-4f15-997d-22a0c5d41adf)

**Comment by gitbobobo** [comment]
证书不能是自签名证书，而且需要确保证书链完整

**Comment by FasAway** [comment]
> 证书不能是自签名证书，而且需要确保证书链完整

检查了下，确实是证书链的问题，Nginx只配置了自身cer没配置上层证书链，目前已解决
