### ISSUE TITLE
MacOS软件无法使用！

### ISSUE THREAD

**Issue by fgjg123000** [gitbobobo/StreamMusic#414]
<img width="513" alt="image" src="https://github.com/user-attachments/assets/d6a77722-fa31-4794-8c41-996c82f0ba33">
这是我的电脑参数，在此环境下软件打开后无法使用，具体情况如下
<img width="1036" alt="image" src="https://github.com/user-attachments/assets/b1798cd4-d11d-471c-8e2c-5061ad1412bc">
请问一下是系统原因还是软件bug

**Comment by gitbobobo** [comment]
不太清楚，15之前是能正常使用的

**Comment by xueyingsha** [comment]
遇到了同样的问题，macos版本也是升级到了“24A5289h” 这个public beta版本后出现的问题。
之前在develop beta 2的macos15中不存在问题，看起来像是系统问题

**Comment by fgjg123000** [comment]
> 遇到了同样的问题，macos版本也是升级到了“24A5289h” 这个public beta版本后出现的问题。 之前在develop beta 2的macos15中不存在问题，看起来像是系统问题

确实 我更新完bata3之后出现了打不开的问题

**Comment by fgjg123000** [comment]
> 已找到问题，音流打包时用的中文名称导致的此问题

大佬计划在哪个版本发布呀

**Comment by gitbobobo** [comment]
下个版本就发布了，可以先用测试版

**Comment by gitbobobo** [comment]
加了coming soon标签的都是已经发布在测试版的

**Comment by gitbobobo** [comment]
1.3.1已修复
