### ISSUE TITLE
手机端文件夹视图中，无法完整显示歌曲列表

### ISSUE THREAD

**Issue by YIKU-MEO** [gitbobobo/StreamMusic#416]
**Describe the bug (BUG 描述)**
在手机端文件夹视图中，无法完整显示歌曲列表。
但未显示的歌曲可以在所有歌曲中搜索到。

**To Reproduce (复现步骤)**
1. 点击文件夹按钮，到目标文件夹，发现歌曲列表不完整显示
2. 点击全部音乐按钮，发现未显示的歌曲列表可以被检索到

**Expected behavior (期望行为)**
在手机端文件夹视图下正确显示完整歌曲列表

**Screenshots (截图)**
如图
![%{UE NQ~92%11G7237$IG7L](https://github.com/user-attachments/assets/c3edfed7-e5ee-49c8-b9b9-bb7f461ca552)

https://github.com/user-attachments/assets/cd668766-03b4-4dbc-83f3-3ea1bfd7f42b

![Screenshot_2024-07-17-08-25-54-690_cn aqzscn stre](https://github.com/user-attachments/assets/712bbc58-7a8b-4d56-b30c-83912333236b)

**Platform and Device Info (操作系统及设备信息)**
安卓客户端1.2.9

**Music Server Type (音乐服务器类型)**
navidrome [0.52.5-SNAPSHOT]

**Comment by gitbobobo** [comment]
navidrome 没有文件夹接口，因此直连模式显示的是已获取过歌曲数据的文件夹结构，只有媒体库模式可以显示完整文件夹内容

**Comment by YIKU-MEO** [comment]
确实，取消了直连模式后就没问题了
