### ISSUE TITLE
建议增加排序方式

### ISSUE THREAD

**Issue by Robinghe** [gitbobobo/StreamMusic#419]
建议增加支持专辑内按**音轨号**以及**碟号**顺序排列

**Comment by gitbobobo** [comment]
这个是129版本的bug，下个版本会修复的

**Comment by gitbobobo** [comment]
1.3.0已发布

**Comment by theturtle626** [comment]
iOS 1.3.0, 點選一張專輯， 還是沒有看到可以用音轨排序, 可以再確認一下嗎?

**Comment by gitbobobo** [comment]
一个专辑内只有一个专辑名，所以按专辑名排序默认就是按碟号+音轨号排序

**Comment by theturtle626** [comment]
測試後已經正常了，非常謝謝，有些碟號是有名稱的，是否考慮也顯示出來, 如果沒有名稱, 也顯示 DISC 1, DISC 2 ....
DISC 1 - XXX
01 xxx
02 yyy ...

DISC 2 - YYY
01 xxx
02 yyy ...

**Comment by gitbobobo** [comment]
感觉没有必要，实现起来也有点复杂
