### ISSUE TITLE
Windows客户端长时间未使用后无法播放，进度条没反应，日志报错Failed to recognize file format

### ISSUE THREAD

**Issue by asiluokegit** [gitbobobo/StreamMusic#420]
版本1.29 
群晖dsm7.1

近2个周没有使用过，再次打开时无法播放，格式Mp3，重新安装无效，重新登录后正常 播放
报错日志：   
INFO 💡 歌曲占用空间: 741.00 B，元数据占用空间: 5.60 KB，系统占用空间: 2.61 MB
  ERROR 16:57:33.018 (+0:00:18.373124)
  ERROR ⛔ 播放异常：Failed to recognize file format.
   INFO 16:57:36.668 (+0:00:22.023476)
   INFO 💡 歌曲占用空间: 741.00 B，元数据占用空间: 5.60 KB，系统占用空间: 2.61 MB
  ERROR 16:57:37.833 (+0:00:23.188383)
  ERROR ⛔ 播放异常：Failed to recognize file format.

**Comment by gitbobobo** [comment]
129群晖的登录逻辑存在问题，可以先从devmusic.aqzscn.cn下载130测试版使用

**Comment by gitbobobo** [comment]
1.3.0已发布
