### ISSUE TITLE
"流派"功能异常

### ISSUE THREAD

**Issue by RuiDSaaCC** [gitbobobo/StreamMusic#422]
服务器：Emby 4.8.8.0（Docker）
音流版本：Windows 1.3.0（测试版本）

音流中"流派"功能异常，任何流派标签都会对应音乐库内全部的歌手、专辑以及歌曲，Emby网页端正常。尝试过重新同步音乐库以及关闭程序重新打开，均无法改变这一情况。

音流"流派"功能界面：
![20240721_053222](https://github.com/user-attachments/assets/3004f592-e342-4c3b-8e8d-71ec112b52db)

![20240721_053210](https://github.com/user-attachments/assets/e260fa32-1c52-4639-9f4b-1028ae86199d)

Emby网页端"流派"功能界面：
![20240721_053413](https://github.com/user-attachments/assets/5bb637d2-d614-4313-a465-99f3b1ee1a79)

![20240721_053357](https://github.com/user-attachments/assets/9e2ccdf0-ec21-4b96-bc56-b056ee02e817)

**Comment by RuiDSaaCC** [comment]
V1.3.0 (0723) 已修复

**Comment by theturtle626** [comment]
我使用 Windows 1.3.0, 此問題還是存在
