### ISSUE TITLE
曲库无法同步、歌曲无法播放

### ISSUE THREAD

**Issue by justyeh** [gitbobobo/StreamMusic#423]
**Describe the bug (BUG 描述)**
曲库无法同步、歌曲无法播放

**Expected behavior (期望行为)**
能够正常使用

**Screenshots (截图)**
播放失败  
![播放失败](https://github.com/user-attachments/assets/b1430e7d-f05c-4b08-afde-a7ca67e7da3c)
拉数据失败  
![拉数据失败](https://github.com/user-attachments/assets/9dc43458-b032-41d7-a37d-7fdb88c70a9e)

**Platform and Device Info (操作系统及设备信息)**
 - OS: iOS 16.6
 - Version: 1.2.9

**Music Server Type (音乐服务器类型)**
novidrome 0.52.5

**Additional context (额外信息)**
经常听不了歌，下载app后第一次初始化（我尝试过几次卸载重装）的时候拉取曲库正常，之后就经常发生无法同步的事情，尤其是直连由打开切换为关闭后，整个数据全部丢失！
听歌加载的比网页慢，我用music tag为资源打标签后很多歌曲播放不了

以上信息都是前提都是服务端正常在运行，web、LMP音乐这些都能正常跑

**Comment by gitbobobo** [comment]
看起来像是数据解析出问题了，如果能提供公网测试账号的话，可以邮件发到 aqzscn@qq.com 我本地调试一下

**Comment by justyeh** [comment]
> 看起来像是数据解析出问题了，如果能提供公网测试账号的话，可以邮件发到 [aqzscn@qq.com](mailto:aqzscn@qq.com) 我本地调试一下

账户信息发送邮件了

**Comment by justyeh** [comment]
自行排查就是网络问题

**Comment by gitbobobo** [comment]
好的，感谢反馈
