### ISSUE TITLE
ios端 自动下载问题

### ISSUE THREAD

**Issue by Meng-X-G** [gitbobobo/StreamMusic#425]
**Describe the bug (BUG 描述)**
设置自动下载，每次打开软件会重复下载歌曲

**To Reproduce (复现步骤)**
连接的emby服务
1.创建一个歌单，添加几首歌
2.给该歌单设置自动下载
3.重新打开软件后开始自动下载
4.全部下载完成后，再次重新打开软件，发现
又开始重复下载自己下载完成的歌曲，目前只能下载完成后手动关闭自动下载

**Expected behavior (期望行为)**
自动判断那些没有下载的歌曲进行下载，已下载的歌曲不在重复下载

**Platform and Device Info (操作系统及设备信息)**
iOS 1.2.9版本

**Music Server Type (音乐服务器类型)**
emby 4.7.14

**Comment by gitbobobo** [comment]
1.3.0已发布，应该解决了这个问题
