### ISSUE TITLE
无法匹配到任何在线歌词

### ISSUE THREAD

**Issue by ShohanPei** [gitbobobo/StreamMusic#426]
我看描述里说了有“在线歌词”这个功能，不知道入口在哪里？是不是在歌词页点击【LRC】-【切换歌词】？
这里的意思是根据歌名和作者在互联网上匹配歌词对吧？
我的所有歌都无法找到任何结果，歌名和作者都是正确的，但是永远是“没有找到歌词”
安卓版，V1.2.9（2024-05-15），使用的群晖Audio Station，用QC连接，梯子OR国内都试了

**Comment by gitbobobo** [comment]
音流本身不提供歌词刮削功能，群晖需要安装歌词插件或使用音流的自定义API

**Comment by ShohanPei** [comment]
大佬 后半句我该怎么理解呀？
