### ISSUE TITLE
希望增加plex服务端的支持

### ISSUE THREAD

**Issue by BruceSuen720** [gitbobobo/StreamMusic#43]
希望能够支持对plex服务端的支持

**Comment by gitbobobo** [comment]
1.2.7 支持连接到 Plex，但暂未适配转码播放功能，使用时请注意流量消耗（下个版本适配）

**Comment by realx1n** [comment]
> 1.2.7 支持连接到 Plex，但暂未适配转码播放功能，使用时请注意流量消耗（下个版本适配）

登陆报错，显示401
