### ISSUE TITLE
1.3.0BUG 两个

### ISSUE THREAD

**Issue by youhers** [gitbobobo/StreamMusic#433]
1.3.0下搜索歌手 
点专辑
所有的专辑都会显示出来不是针对此歌手的专辑显示
所有的歌曲也都会显示出来 
貌似搜索失效了 
2. 还有就是在IOS18的carplay播放歌曲的页面下
点击专辑名称  
此歌手下的所有歌曲都会显示出来 
而不是显示此张专辑内的歌曲

**Comment by youhers** [comment]
![Uploading 微信图片_20240725144932.png…]()

**Comment by gitbobobo** [comment]
服务端是什么

**Comment by youhers** [comment]
直链模式有问题  audio station 不是直连模式正常  刚发现

**Comment by youhers** [comment]
谢谢

**Comment by gitbobobo** [comment]
1.3.1已修复
