### ISSUE TITLE
连接群晖Audio Station无法将歌曲添加至群晖歌单

### ISSUE THREAD

**Issue by maycyc** [gitbobobo/StreamMusic#434]
**Describe the bug (BUG 描述)**
连接Audio Station后，同步的歌单可以正常显示，
但将歌曲手动添加至Audio Station歌单，App会一直显示加载中...然后界面无法操作，且所有的群晖歌单都显示只有1首歌

**Expected behavior (期望行为)**
期待可以将歌曲添加至群晖Audio Station歌单，并同步至Audio Station，可以实现音流与群晖Audio Station歌单相互同步

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 - OS: IOS 17.5.1
 - Version 1.3.0

**Music Server Type (音乐服务器类型)**
Synology Audio Station

https://github.com/user-attachments/assets/a7bdd708-d262-4280-a8e0-0dddc500dcdf

**Additional context (额外信息)**

**Comment by maycyc** [comment]
## 同步的群晖歌单包含Audio Station规则生成的智能歌单：
- 最近15天加入的歌曲
- 周杰伦
- 全部歌单


都不能将歌曲添加至Audio Station歌单

## 截图如下：
- ![image](https://github.com/user-attachments/assets/2a422adc-4c9c-43fa-865b-58f0050f4600)

- ![image](https://github.com/user-attachments/assets/b40bd59b-25e7-4c49-aed8-9525a1148a38)

**Comment by gitbobobo** [comment]
智能歌单是自动生成的，不能随意编辑里面的歌曲。

**Comment by maycyc** [comment]
> 智能歌单是自动生成的，不能随意编辑里面的歌曲。

明白
但是其它在群晖中手动创建的歌单，也无法通过音流向其添加歌曲

**Comment by maycyc** [comment]
## 还有自定义背景的问题：

- 此设置只能修改背景，但是播放页是不会同步修改的，
- 这个后续版本能否将播放页也能保持自定义背景一致


> * ![图像](https://private-user-images.githubusercontent.com/95576512/352016305-b40bd59b-25e7-4c49-aed8-9525a1148a38.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4OTc5NjAsIm5iZiI6MTcyMTg5NzY2MCwicGF0aCI6Ii85NTU3NjUxMi8zNTIwMTYzMDUtYjQwYmQ1OWItMjVlNy00YzQ5LWFlZDgtOTUyNWExMTQ4YTM4LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNVQwODU0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YjA2YTEwMmQzNzIwNTdmNDk2MTQ1OWI0ODc3NTgyMzU3YzU5MDBhZjM2YzEzMGIyYTJiNDQ0OGEzNzRjMThjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MMVXco3-37bGwuwwm9CQrMROCMZ6R-sUCOLW1V6rXGo)

**Comment by gitbobobo** [comment]
播放页同步显示当前歌曲的封面，我觉得是更合理的做法，所以不会改的。

歌单方面确实存在问题，下个版本修复一下。

**Comment by maycyc** [comment]
歌单这个真是困扰很久了，从上个版本开始使用就已经存在。

播放页一开始我以为颜色都是暗色，对比不是很明显，多播放了几首歌，仔细观察了，的确是按歌曲封面配色，这个很合理，
只是对比度是否能再调整下，不是太直观😅

**Comment by maycyc** [comment]
Uploading 2accedc72231e2134397568c81923920.mp4…
