### ISSUE TITLE
1.3.0最新版无法显示歌曲封面

### ISSUE THREAD

**Issue by YashiroKirara** [gitbobobo/StreamMusic#435]
今天下午刚更新到1.3.0，发现播放页无法显示歌曲封面。
手机是iPhone 15 pro，系统是17.5.1
服务端是Jellyfin 10.9.6
歌曲有内嵌封面，专辑文件夹下也有cover.jpg
专辑、歌单、随机推荐等页面都能显示出封面，只有播放页不显示，请问是BUG还是新版本有了什么调整吗？

![IMG_5064](https://github.com/user-attachments/assets/11f63e44-e840-4ad1-b061-8843f8187e08)
![IMG_5065](https://github.com/user-attachments/assets/ac96c440-2ddb-4649-a365-2f3825610f7a)
![IMG_5066](https://github.com/user-attachments/assets/b4b66742-fb68-4a2f-af6d-adea6b49d2eb)

**Comment by gitbobobo** [comment]
应该是新版本的调整导致了bug，不过我这里的jellyfin可以在播放时显示歌曲封面，可能你那边的数据有所不同。如果你可以建一个公网访问的测试账号的话，可以邮件发送到 aqzscn@qq.com

![IMG_7723](https://github.com/user-attachments/assets/8b4d6b68-e8ed-4bac-97ac-0c424ac02016)

**Comment by YashiroKirara** [comment]
我建了一个测试账号，发到你邮箱了，谢谢

**Comment by YashiroKirara** [comment]
不好意思，冒昧的问一下，封面这个是我这边数据的问题吗？
如果是，需要怎么处理呢？
谢谢！


| |
Yashiro Kirara
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年07月25日 22:54 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [gitbobobo/StreamMusic] 1.3.0最新版无法显示歌曲封面 (Issue #435) |

应该是新版本的调整导致了bug，不过我这里的jellyfin可以在播放时显示歌曲封面，可能你那边的数据有所不同。如果你可以建一个公网访问的测试账号的话，可以邮件发送到 ***@***.***

IMG_7723.png (view on web)

**Comment by gitbobobo** [comment]
程序问题，测试版已修复

**Comment by YashiroKirara** [comment]
多谢多谢！期待正式版发布！

**Comment by gitbobobo** [comment]
1.3.1已发布
