### ISSUE TITLE
Scrobbles don't report the actively playing song

### ISSUE THREAD

**Issue by Insprill** [gitbobobo/StreamMusic#437]
**Describe the bug (BUG 描述)**
When playing a song, Stream Music will only scrobble it as completed once you're partway though. Ideally, it would scrobble it as soon as you start playing without submitting it, so integrations like Last.FM can show the actively playing song.

From a quick look at the Navidrome docs, and by observing Amperrfy behaviour, this should be as simple as calling the scrobble endpoint with `submission=false`.

**To Reproduce (复现步骤)**
1. Setup a Navidrome server with Last.FM integration.
2. Start playing a song.
3. Once it's 1/4 the way though, it'll get added to the list as if it were finished.
4. With [Amperfy](https://github.com/BLeeEZ/amperfy), do the same.
5. Observe that once you start playing, Last.FM will show that the song is currently playing.

**Expected behavior (期望行为)**
Songs should be scrobbled while playing without submitting them.

**Platform and Device Info (操作系统及设备信息)**
 - OS: IOS v16.7.8
 - Version v1.3.0

**Music Server Type (音乐服务器类型)**
Navidrome v0.52.5

**Additional context (额外信息)**
Another IOS Subsonic client, [Amperfy](https://github.com/BLeeEZ/amperfy), does scrobble songs correctly.

**Comment by gitbobobo** [comment]
you need play a song at least 1/4 to scrobble it。this is my scrollbe record, it works well.

![IMG_7724](https://github.com/user-attachments/assets/b3063661-83c9-46ad-bbcc-11eb9d1872eb)

**Comment by Insprill** [comment]
I know that, that's not the issue. I was using the last.fm integration as a reference, and I realized my mistake. Once you're 1/4 through a song, Stream Music scrobbles it as if it were finished, and that's it. Ampery will scrobble it while it's playing, so Last.FM, and any integrations with Last.FM can see the song actively playing. I'll update the report to reflect the actual issue/feature req. Sorry about that, I should've done my due diligence.

**Comment by gitbobobo** [comment]
i see your point, thanks for feedback~

**Comment by gitbobobo** [comment]
1.3.1 has been released.
