### ISSUE TITLE
1.2.8~1.3.0 navidrome无法播放

### ISSUE THREAD

**Issue by as564335sa** [gitbobobo/StreamMusic#438]
服务端：navidrome
客户端：安卓，权限均已允许
昨天卸载旧版本安装1.3.0，绝大部分歌曲无法播放，现象是，点击播放后，没有任何反应，在本地音乐中看到，文件大小只有2k，如下图

![Q11111](https://github.com/user-attachments/assets/c17ef379-d776-4717-9a40-5eba984a75ca)
![不动](https://github.com/user-attachments/assets/f0d11cc5-db4c-42bc-819a-be59641152c9)
反复尝试都是一样的现象，经测试，1.2.8，1.2.9，1.3.0现象一样，换回1.2.7后正常

已知并实测：navierome服务无异常，web客户端正常播放，Ultrasonic播放器正常播放

**Comment by as564335sa** [comment]
是更新了缓存的问题吗，注意到1.2.7版本并没有申请文件访问权限，1.2.8以上有权限申请，已经授权始终允许了，手机是红米K30pro

**Comment by gitbobobo** [comment]
看起来是没完整缓存导致的，你的歌曲是直链吗？还是navi的路径加了baseurl。

**Comment by as564335sa** [comment]
> 看起来是没完整缓存导致的，你的歌曲是直链吗？还是navi的路径加了baseurl。

加了baseurl的

**Comment by kael-aiur** [comment]
我遇到了相同的问题

**Comment by gitbobobo** [comment]
如果可以公网访问，可以邮箱发我一个测试账号 aqzscn@qq.com

**Comment by as564335sa** [comment]
> 如果可以公网访问，可以邮箱发我一个测试账号 [aqzscn@qq.com](mailto:aqzscn@qq.com)

以发送

**Comment by gitbobobo** [comment]
已处理，等下个测试版发布可以试试看

**Comment by gitbobobo** [comment]
1.3.1已发布
