### ISSUE TITLE
随机播放总是在前400首左右里随机，后面的歌曲随机不上，基本就在一些顺序在一起的专辑里循环，能不能改一下这个随机的规则

### ISSUE THREAD

**Issue by FateMoo** [gitbobobo/StreamMusic#445]

**Comment by gitbobobo** [comment]
直连模式的随机播放是从服务端随机获取500首歌曲播放的，正常来说随机范围就是整个歌单，你用的服务端是什么

**Comment by FateMoo** [comment]
服务端是navidrome，那就能理解了，我的全部歌曲有1700多首，因为添加顺序的原因后面的歌曲大都是整张专辑



来自QQ邮箱


------------------ 原始邮件 ------------------
发件人: gitbobobo ***@***.***&gt;
发送时间: 2024年7月27日 08:34
收件人: gitbobobo/StreamMusic ***@***.***&gt;
抄送: moo ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [gitbobobo/StreamMusic] 随机播放总是在前400首左右里随机，后面的歌曲随机不上，基本就在一些顺序在一起的专辑里循环，能不能改一下这个随机的规则 (Issue #445)





 
直连模式的随机播放是从服务端随机获取500首歌曲播放的，正常来说随机范围就是整个歌单，你用的服务端是什么

**Comment by gitbobobo** [comment]
那不应该啊，我主要用的就是navi，随机范围是正常的

**Comment by gitbobobo** [comment]
或者就是你是先全部播放，然后在播放页切的随机，这种是不行的。

**Comment by FateMoo** [comment]
我就是什么干的，在车上用，没有试过其他方式，都是进了播放页才切换都随机的


------------------ 原始邮件 ------------------
发件人: gitbobobo ***@***.***&gt;
发送时间: 2024年7月27日 08:41
收件人: mooail ***@***.***&gt;
主题: Re: [gitbobobo/StreamMusic] 随机播放总是在前400首左右里随机，后面的歌曲随机不上，基本就在一些顺序在一起的专辑里循环，能不能改一下这个随机的规则 (Issue #445)





 
或者就是你是先全部播放，然后在播放页切的随机，这种是不行的。

**Comment by gitbobobo** [comment]
music.aqzscn.cn 看下使用说明

**Comment by cnitts** [comment]
为什么随机播放只能限制500首呢
