### ISSUE TITLE
TV端进不去

### ISSUE THREAD

**Issue by CharysseZ** [gitbobobo/StreamMusic#446]
TV端卡在logo界面进不去，用的当贝投影x3

**Comment by CharysseZ** [comment]
![IMG_20240726_214502](https://github.com/user-attachments/assets/52ef9e64-8e0a-4c20-a20c-661def4fcc81)

**Comment by CharysseZ** [comment]
1.3.0的每个版本都试了不行，1.2.9没问题

**Comment by gitbobobo** [comment]
是登录页面就进不去还是登录之后下次打开时进不去

**Comment by CharysseZ** [comment]
一打开就进不去了，登录页面都还没出现

**Comment by gitbobobo** [comment]
首次安装就无法进入的，应该是存在兼容性问题，可以提供下设备和系统信息，不保证能修复。

第二次使用无法进入的，目前我这里可以复现，需要再排查下问题。

**Comment by gitbobobo** [comment]
1.3.1已修复第二次可能卡在启动页的问题
