### ISSUE TITLE
Windows端是否可以支持配置代理？

### ISSUE THREAD

**Issue by Mustang0394** [gitbobobo/StreamMusic#447]
有时候需要连接到国外的服务端的时候，是否可以支持配置HTTP Proxy/Socks5 Proxy这类的代理来提升访问体验？
谢谢~

**Comment by gitbobobo** [comment]
在哪些平台有这个需求？而且一般来说代理不都是全局代理吗，感觉不是很有必要在软件里单独加这个

**Comment by Mustang0394** [comment]
> 在哪些平台有这个需求？而且一般来说代理不都是全局代理吗，感觉不是很有必要在软件里单独加这个

主要是Windows平台下，日常是会有代理的情况，一般Windows里像浏览器这些的会自动使用Windows的 `系统代理`
如果不想显式支持代理的配置的话，那是否可以检测系统本身是否有配置系统代理，如果有的话遵循使用系统代理来实现功能？

**Comment by 7ongOrz** [comment]
我也有这个需求，Windows平台请求适配一下

**Comment by zmquan** [comment]
MacOS 也有同样需求。 求代理 @gitbobobo

**Comment by gitbobobo** [comment]
1.3.1已添加
