### ISSUE TITLE
可以调整横屏界面封面的占比大小吗？

### ISSUE THREAD

**Issue by Timelesseternity** [gitbobobo/StreamMusic#448]
手边只有 Android 平板端，横屏播放时封面显示很小，不协调。可以考虑参考一下 AM 的 MAC 全屏播放界面以及 iPad 横屏播放界面调整一下吗？

![Screenshot_20240726_230349_cn aqzscn stream_music](https://github.com/user-attachments/assets/6955edd9-29da-4877-9e56-aeb08b188ccd)
上图是 Android 平板端播放界面

![image](https://github.com/user-attachments/assets/2ed078ad-e7e4-42ba-be4d-3c3e9d0091b5)
网上找的 AM 全屏播放的图片。

**Comment by gitbobobo** [comment]
有空调整下，不过不会搞这么大，操作的按钮我觉得还是有必要保留的

**Comment by Timelesseternity** [comment]
> 有空调整下，不过不会搞这么大，操作的按钮我觉得还是有必要保留的

类似iPad 也行，hhh。贴一张 iPad 的：
![image](https://github.com/user-attachments/assets/095da312-a3ea-4651-87b9-0a998ff17998)

**Comment by gitbobobo** [comment]
132测试版已更新，稍微增大了一些封面尺寸

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布
