### ISSUE TITLE
锁屏无播放控件

### ISSUE THREAD

**Issue by maycyc** [gitbobobo/StreamMusic#449]
**Describe the bug (BUG 描述)**

**早晨到现在试了几次都是这种情况**

**To Reproduce (复现步骤)**

杀后台再进还是一样

https://github.com/user-attachments/assets/7b92f176-8ec5-47dc-b880-7f8710489c45
**Platform and Device Info (操作系统及设备信息)**
 - OS: [iOS 17.5.1]
 - Version [1.3.0]

**Music Server Type (音乐服务器类型)**

Synology Audio Station

**Comment by maycyc** [comment]
设备重启后还是一样无锁屏播放控件

**Comment by gitbobobo** [comment]
请把个性化 - 与其他应用同时播放关掉，这个是iOS系统特性

**Comment by maycyc** [comment]
抱歉😢
看到回复突然想起之前看到过文档

**Comment by gitbobobo** [comment]
解决就好
