### ISSUE TITLE
点完删除后歌曲依然在列表里面服务器上也在

### ISSUE THREAD

**Issue by supersu097** [gitbobobo/StreamMusic#45]
试了删除好几次都不行哦~

**Comment by gitbobobo** [comment]
删除的只是下载到本地的文件，服务器的文件app是没有权限删除的，也不安全。

**Comment by supersu097** [comment]
> 删除的只是下载到本地的文件，服务器的文件app是没有权限删除的，也不安全。

好的，辛苦啦~
