### ISSUE TITLE
功能建议：请增加【排除】或者【不喜欢】功能

### ISSUE THREAD

**Issue by JunoSu** [gitbobobo/StreamMusic#451]
可否增加一个【排除】或者【不喜欢】这样的功能。
1，方便听歌时把一些不喜欢的歌拉进小黑屋清单，排除不听。
2，也方便后期整理歌曲，把小黑屋里那些不喜欢的歌统一删除。

**Comment by gitbobobo** [comment]
我觉得不太合理，如果服务端不支持，排除的歌曲无法做到多平台同步，意义不大。

如果只是为了后期批量删除歌曲的话，再过几个版本会出一个类似的功能（暂时保密）来解决这个问题。
