### ISSUE TITLE
支付成功后会员未到账

### ISSUE THREAD

**Issue by redfieldw** [gitbobobo/StreamMusic#453]
安卓支付后软件卡死，毫无反应，再次打开应用没有会员，想通过支付宝订单号恢复购买，但是那个按钮是灰的，没法点击。请帮我处理一下。
![IMG_20240728_004032](https://github.com/user-attachments/assets/2c7a0bc7-5084-49e3-b356-262601c36d28)

**Comment by gitbobobo** [comment]
试下输入空格再删掉是否可以，可能粘贴过去没有识别到内容改变了

**Comment by philipzou** [comment]
我也遇到同样的问题，订单号输入栏内手动输入数字也不会激活按钮

**Comment by gitbobobo** [comment]
按下回车就可以触发了，下个版本修复此问题

**Comment by gitbobobo** [comment]
1.3.1已修复
