### ISSUE TITLE
jellyfin 10.9.8 steammusic 1.3.1 download function does not work

### ISSUE THREAD

**Issue by jibwf** [gitbobobo/StreamMusic#461]
**Describe the bug (BUG 描述)**
jellyfin 10.9.8 steammusic 1.3.1 download function does not work. No any syslog on 1.3.1 even with debug level.
GUI display failed to get song info.
Play and cache function also does not work. 

**To Reproduce (复现步骤)**
1. In any page, download a song.

**Expected behavior (期望行为)**
download and cache when play

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 - OS: [e.g. iOS] MACOS 
 - Version [e.g. 22]14.5

**Music Server Type (音乐服务器类型)**
jellyfin 10.9.8
steammusic 1.3.1 dev release

**Additional context (额外信息)**

**Comment by greatkeke** [comment]
same to android app

**Comment by gitbobobo** [comment]
I cannot reproduce this issue.

**Comment by jibwf** [comment]
@gitbobobo 重试了一下，看到这种报错

DEBUG 16:33:35.942 (+0:01:59.737182)
  DEBUG 🐛 GET:https://XXXX:XXXXX/Audio/c1ac915e091681c553090c6da5aa87d4/stream?static=true
  ERROR 16:33:36.530 (+0:02:00.325353)
  ERROR ⛔ 下载歌曲失败：DioException [bad response]: This exception was thrown because the response has a status code of 404 and RequestOptions.validateStatus was configured to throw for this status code.
  ERROR ⛔ The status code of 404 has the following meaning: "Client error - the request contains bad syntax or cannot be fulfilled"
  ERROR ⛔ Read more about status codes at https://developer.mozilla.org/en-US/docs/Web/HTTP/Status
  ERROR ⛔ In order to resolve this exception you typically have either to verify and fix your request code or you have to fix the server code.
  ERROR ⛔ 
  DEBUG 16:33:40.830 (+0:02:04.625358)

**Comment by jibwf** [comment]
知道了，我这个音频文件之前改过目录名。 音流没有同步

**Comment by gitbobobo** [comment]
好的，解决就好，建议开启直连模式，这样不用同步数据
