### ISSUE TITLE
navidrome使用域名更新很慢

### ISSUE THREAD

**Issue by taiyuanhuoyandao** [gitbobobo/StreamMusic#463]
1.3.0版本通过ddns域名访问navidrome时手动同步一直不能完成同步，但是切换为内网ip时手动同步可以很快就同步完成

**Comment by gitbobobo** [comment]
这应该和软件无关吧

**Comment by taiyuanhuoyandao** [comment]
有什么好的解决方法吗?现在通过域名连接navidrome很不稳定，使用audio station 是可以正常连接的，但是因为歌曲经过刮削与分类会导致audio station出现好至少两个同名文件，其中只有一个文件能播放，导致audio station识别到的数量要比navidrome多很多。还有一个很重要的问题是audio station不能按添加时间进行排序。

**Comment by gitbobobo** [comment]
audiostation我记得是有清除失效文件的按钮的。

同步速度慢就使用直连模式
