### ISSUE TITLE
播放的歌曲不会停止缓存

### ISSUE THREAD

**Issue by 7ongOrz** [gitbobobo/StreamMusic#465]
**Describe the bug (BUG 描述)**
IOS和Windows平台下播放歌曲后在歌曲完整缓存下来之前不会停止，即使关闭了程序再打开还是会接着缓存，该行为也会导致切换歌曲后原播放歌曲还会在后台缓存。在设置中也没有开启边听边存和自动下载。

**To Reproduce (复现步骤)**
不需要特别的复现步骤，只要播放某一歌曲后缓存就不会停止。

**Expected behavior (期望行为)**
我觉得正常的情况下停止播放后应该停止缓存，切换歌曲后也要停止原歌曲的缓存，最关键的一点是关闭程序后再次打开不应该接着进行缓存。

**Music Server Type (音乐服务器类型)**
Subsonic 1.16.0

**Comment by 7ongOrz** [comment]
![image](https://github.com/user-attachments/assets/e99a5abb-3bba-44f2-9260-040f1efa7856)
![image](https://github.com/user-attachments/assets/b4999948-cb84-4f1f-bd77-ee3f3c174c79)
打开app没点播放，自动缓存了一首歌下来，边听边存也没有开启

**Comment by gitbobobo** [comment]
目前一些功能的实现必须借助于对歌曲文件的代理，所以缓存是不可避免的。而且歌曲不像电影那么大，我认为没有必要在意这一点。

之后如果播放插件实现了音流需要的功能，我就会优化此逻辑。

**Comment by 7ongOrz** [comment]
这种缓存机制可能在局域网环境没有明显感知，但在我的小带宽vps上感受是非常明显的，前一首的没缓存完的话直接切歌会导致下一首直接无法加载，前一首的加载已经占满带宽了，需等待前面的缓存完毕，并且打开app的时候会直接占满带宽，也是得等待缓存完毕才能切歌，希望后续能优化吧，感谢

**Comment by gitbobobo** [comment]
嗯，不手动立即切歌的话感觉应该还好，音流是有预缓存机制的，当前歌曲加载完成后会加载下一首歌曲
