### ISSUE TITLE
安卓版搜索歌手后专辑和歌曲数据出错

### ISSUE THREAD

**Issue by aceril** [gitbobobo/StreamMusic#467]
安卓版搜索歌手后专辑和歌曲数据出错

安卓版搜索某一位歌手后，点击进入歌手页面，展示的专辑和歌曲数据并不是该歌手的数据，而且曲库的所有专辑和所有歌曲。

 - 红米K70PRO
 - 1.3和1.31都有这个问题，1.29版本是正常的。

Audio station，直连模式，曲库上万首。

**Comment by gitbobobo** [comment]
1.3.1正式版已处理此问题
