### ISSUE TITLE
建議默認歌單封面採用較為通用的圖片

### ISSUE THREAD

**Issue by lightningken** [gitbobobo/StreamMusic#468]
Dear 開發者大大，
一直以來有一個在意的 UI 設計細節，就是默認的歌單封面是用紫色的不明圖案，因此加載前後會有很明顯的顏色跳躍，在視覺體驗方面會對用戶造成一點點困擾。在此大力建議默認封面採用較為通用的圖片（純灰色的也好），謝謝🙏
![IMG_3460](https://github.com/user-attachments/assets/f5ba4c3b-e215-4b08-8335-cd72bda40705)

**Comment by gitbobobo** [comment]
嗯，之后调整一下

**Comment by gitbobobo** [comment]
1.3.1已修改
