### ISSUE TITLE
tv端会员恢复购买，邮箱发送不了

### ISSUE THREAD

**Issue by gaoqizhong3414** [gitbobobo/StreamMusic#469]
小米电视安装1.30安卓版tv端会员恢复购买，邮箱发送不了

**Comment by gitbobobo** [comment]
已知问题，安卓版本太低，没有let's Encrypt 的证书导致的问题，下个版本修复。

顺便问下，播放功能正常吗？是否会出现播放一到两首歌就卡死的问题

**Comment by gitbobobo** [comment]
1.3.1已修复

**Comment by anwaryou** [comment]
我遇到了相同的问题，下载了最新1.3.1的版本还是无法恢复付费会员账号，扫码，输入支付宝订单号和邮箱验证都提示失败！
