### ISSUE TITLE
音流1.3.1 jellyfin10.9.6专辑内排序混乱，流派标签缺失且不起作用

### ISSUE THREAD

**Issue by beavermarine** [gitbobobo/StreamMusic#472]
**Describe the bug (BUG 描述)**
专辑内排序混乱，和jellyfin内排序不同。流派标签不全且点击后出现的是所有专辑。

**Platform and Device Info (操作系统及设备信息)**
 - OS: lg g7 安卓10 

**Music Server Type (音乐服务器类型)**
jellyfin 10.9.6

**Comment by gitbobobo** [comment]
排序问题，请将排序方式改为按专辑名排序

流派功能我试了下，可能是 Jellyfin 自身的问题，因为131音流支持选择全部分区，此时在查询数据时不会传递分区ID，此时 Jellyfin 自己似乎会返回最后一个分区的流派列表，而在指定分区之后就可以正常获取流派列表

**Comment by beavermarine** [comment]
修改为单一分区后可正常获得流派列表，但点击后仍显示为全部专辑。

**Comment by gitbobobo** [comment]
找到原因了，你用的媒体库模式吧

**Comment by beavermarine** [comment]
> 找到原因了，你用的媒体库模式吧

对，更改为直连模式后可正常筛选。

**Comment by gitbobobo** [comment]
1.3.1已修复
