### ISSUE TITLE
在线播放音质小于设定码率下无需转换等建议

### ISSUE THREAD

**Issue by sdepool** [gitbobobo/StreamMusic#474]
几个小问题，软件版本1.31，可能要求过高，看作者是否考虑改善下：

1、可不可以加个"在线播放音质在小于特定码率下无需转换"的判定？媒体库里存在无损音乐如flac，还有低码率的音乐如128k。在线播放音质如设定为320k，再转换低于320k的音质就没有必要了。这样既节省流量也节省空间。

2、安卓系统更新软件时只能重新安装么？我的手机系统是 miui12，在从1.29升级1.31时提示只能卸载重新安装，这个有没有直接更新的方法，或者是有其他原因，如我前后下的版本不一致造成的？这条主要的影响就是每次安装还要重新配置服务，重新注册购买账号，重新下歌等，比较麻烦。

3、资料库有分区功能挺好，只是有几个问题。如果我的emby库中分为“华语音乐”、”日韩音乐“、“古典音乐”等，而在音流中我想添加前两个库，不想要“古典音乐”的库，该如何添加？另外如何分别区分"华语"和"日韩"这两个区？这倒是可以用文件夹功能，但文件夹功能无法直接显示专辑等；或者想要听哪个分区时再选择特定分区，但这样选择的话我又遇到个问题，就是在设定“全部分区”时下载的华语歌曲，在设定“华语音乐”分区后消失了（在“全部分区”时，下载歌曲时曾设置过下载路径）。

4、文件夹功能只显示在emby库中设定的第一个文件夹里的内容；

5、关于双语歌词，可否调小原词和翻译词间的行间距，这样更美观更好辨认。

6、本地下载音乐的歌曲信息显示的是媒体库的音乐信息，本地歌曲的信息是否也可以加上？或者标明为原歌曲信息。这条倒无所谓，就是看起来比较别扭。

**Comment by gitbobobo** [comment]
1 我没有详细做过测试，因为我觉得服务端应该自己会处理这样的事情
2 安装不同架构的才会出现必须卸载安装的提示，测试版只提供了通用版本
3 4 如果觉得是bug可以单独提一下，目前应该是没办法同时选中两个分区的，只能单独或全部
5 之后我优化下
6 就不改了，肯定是以服务端的信息为主

**Comment by gitbobobo** [comment]
1.3.1已处理双语歌词间距问题
