### ISSUE TITLE
1.3.0添加歌词自定义api，右上角没有保存按钮，返回也不会自动保存。

### ISSUE THREAD

**Issue by yjjyjjyyjj** [gitbobobo/StreamMusic#479]
**Describe the bug (BUG 描述)**
升级到1.3.0版本更换歌词自定义api时发现无法保存。

**To Reproduce (复现步骤)**
点击设置，自定义api，填入歌词和封面接口无法保存

**Expected behavior (期望行为)**
保存成功。

**Platform and Device Info (操作系统及设备信息)**
小米10，安卓13.

**Music Server Type (音乐服务器类型)**
Navidrome 0.52.5

**Comment by gitbobobo** [comment]
按回车键保存，下个版本会把保存按钮加回来，与 https://github.com/gitbobobo/StreamMusic/issues/458 问题重复。
