### ISSUE TITLE
音流平台间同步问题

### ISSUE THREAD

**Issue by YUNDAN21** [gitbobobo/StreamMusic#480]
**Describe the bug (BUG 描述)**

在使用同步功能时候，

如果使用手机端音流开启服务，电脑端连接手机热点，

首先我发现手机端显示的地址有问题，我使用termux查询到我手机IP地址**如图一**，但是音流中显示的是172开头的那个地址，**见图二**，且无法在电脑端通过输入该ip地址加端口号连接。

其次，如果使用termux中查询到的192.168开头的那个地址，电脑端提示客户端版本过低（但是我确信我两个设备均为最新版本1.3.0），**见图三**

如果使用电脑端音流开启服务，同样是电脑连接手机热点，

手机端输入电脑端音流音流显示的地址（**见图四**）这样手机端是可以正常显示要选择的数据发送的。

下为图一：
![IMG_20240804_231201](https://github.com/user-attachments/assets/c15e4ea7-1ae6-4c56-9acc-2a63c21bde9b)

下为图二
![IMG_20240804_231240](https://github.com/user-attachments/assets/01847ddb-788d-4ee0-8224-b247f347c61d)

下为图三
![image](https://github.com/user-attachments/assets/341ae81f-a951-4e9b-a6e7-976fc3fff26f)

下为图四
![image](https://github.com/user-attachments/assets/d2740c5d-9113-4049-b8b7-8d45f3a9a36b)

**Platform and Device Info (操作系统及设备信息)**
 - OS: 手机端：Redmi K70，HyperOS 1.0.17.0.UNKCNXM，电脑端：windows11

**Music Server Type (音乐服务器类型)**
Navidrome 0.52.5

**Comment by gitbobobo** [comment]
试下测试版是否正常，已添加对多个IP地址的支持

**Comment by gitbobobo** [comment]
1.3.1已发布

**Comment by YUNDAN21** [comment]
> 1.3.1已发布

我最后一张图的问题还是存在，就是在手机端开启本地服务，在电脑端搜索框输入对应ip地址加端口号，电脑端显示当前客户端版本过低。

但是如果在电脑端开启服务，手机端扫描二维码就可以正常连接

而且我确定我两个客户端版本都是最新的1.3.1（但不知道为啥，电脑端音流检查更新显示最新版是1.3.0(83)）
