### ISSUE TITLE
媒体库模式文件夹内模糊搜索

### ISSUE THREAD

**Issue by CloudDragon3** [gitbobobo/StreamMusic#481]
安卓 V1.3.0（2024-07-25）
服务端：emby 4.8.8.0
非直连模式
有的歌曲在文件夹中直接搜索，搜不到。在首页搜索栏中可以搜到，且位置就是在对应文件夹中。

![微信图片_20240805084625](https://github.com/user-attachments/assets/ea085222-eae8-4e65-8558-fbe642f5acf8)
![微信图片_20240805084626](https://github.com/user-attachments/assets/a4de9579-9e8e-4bc3-91a2-e7a300664009)
![微信图片_20240805084628](https://github.com/user-attachments/assets/122be0e6-3a57-4391-afee-64952d4ed7d4)
![微信图片_20240805084747](https://github.com/user-attachments/assets/d943474b-1d7c-4899-930e-42612fd6feb6)

**Comment by CloudDragon3** [comment]
我知道咋回事了，文件夹内的搜索是区分大小写字母的，首页的不分。作者看看是否可以改一下，都支持模糊大小写就可以了。

**Comment by gitbobobo** [comment]
好的，应该是开发的时候忘了添加这个逻辑了

**Comment by gitbobobo** [comment]
1.3.1已修复
