### ISSUE TITLE
PC端 无法播放 版本 1.3.0

### ISSUE THREAD

**Issue by redrainy** [gitbobobo/StreamMusic#486]
环境： win11,  stream-music 1.3.0,  jellfiny 10.9.7

描述：PC端 无法播放，能显示歌曲列表，双击音乐可切换音乐，但是音乐时长为： 0/0

步骤：任意音乐双击

<img width="618" alt="微信图片_20240807094634" src="https://github.com/user-attachments/assets/f31e353a-e07d-403a-8335-339a4ac1da6e">
<img width="618" alt="微信图片_20240807094530" src="https://github.com/user-attachments/assets/f463a867-d7eb-41d6-9485-aa1dcb804768">

**Comment by Glightyyds** [comment]
同样的问题，从1.2.8开始就不能播放了，win

**Comment by gitbobobo** [comment]
看日志是404的报错，如果是媒体库模式可以尝试重新同步下数据。或更新1.3.1看看问题有没有解决

**Comment by redrainy** [comment]
> 看日志是404的报错，如果是媒体库模式可以尝试重新同步下数据。或更新1.3.1看看问题有没有解决

还是不行，应该是PC端请求路径问题，手机版本没有问题 & 手机端更新1.3.1版本后封面出问题，1.3.0版本没有问题

**Comment by tasty007** [comment]
> 看日志是404的报错，如果是媒体库模式可以尝试重新同步下数据。或更新1.3.1看看问题有没有解决

PC端,1.3.7版本遇到同样问题...
