### ISSUE TITLE
单曲循环时允许通过上一曲下一曲按钮切歌

### ISSUE THREAD

**Issue by 131CC6A** [gitbobobo/StreamMusic#487]
1.歌曲设置单曲循环时，无法通过上一首或者下一首按钮切换，这个能否改进成设置单曲循环时仍能正常切换呢？
2.同样是关于歌曲循环模式设置的问题，设置单曲循环或随机播放后，在菜单中切换别的歌曲就恢复成循环播放模式了，可以设置成不重置模式吗？
3.已购买会员，希望大大能关注我说的这两个问题

**Comment by gitbobobo** [comment]
2去官网看下使用说明。

1是可以优化一下

**Comment by gitbobobo** [comment]
这个不会做，单曲循环使用场景太少

**Comment by gitbobobo** [comment]
132测试版已添加，可以试下是否有问题

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布
