### ISSUE TITLE
CarPlay音量异常

### ISSUE THREAD

**Issue by noginger** [gitbobobo/StreamMusic#489]
**Describe the bug (BUG 描述)**
车机是福特 SYNC3，支持carplay，其他音乐app（网易云音乐、QQ音乐、包括以前用咪咕音乐）和哔哩哔哩、车机自带的FM等，音量在4～6就比较合适，但是用音流app播放，车机音量要调整到16～18才有正常的声音，4～6完全听不清，换成网易云音乐又需要把音量调低。

**To Reproduce (复现步骤)**
1. 连接CarPlay
2. 点击 播放
3. 4～6音量下无声音

**Expected behavior (期望行为)**

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**

**Music Server Type (音乐服务器类型)**
emby 4.8.3

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
看下是不是开启回放增益导致的

**Comment by noginger** [comment]
> 看下是不是开启回放增益导致的

请问一下，在哪里关闭 回放增益？音流APP的所有设置项检查了一遍，没有看到。

**Comment by noginger** [comment]
> 看下是不是开启回放增益导致的

刚又仔细阅读了一遍音流官网，发现服务端列表中写明 emby 不支持回放增益的。我的服务端就是emby，请问一下这个可能是什么原因。

**Comment by noginger** [comment]
> 建议用同类软件播放同一首歌曲，看看是否正常

你好，尝试用emby官方客户端，播放同一首歌，没有出现上述异常情况。

测试过的各种播放器合适的音量区间：
1、emby客户端+emby服务器：4～6
2、网易云音乐：4～6
3、哔哩哔哩：4～6

**4、音流+emby服务器：16～18**

**Comment by gitbobobo** [comment]
额，那应该是音流的问题，不过我这里没法复现，连接 CarPlay 模拟器的话，音量是正常的

**Comment by noginger** [comment]
> 额，那应该是音流的问题，不过我这里没法复现，连接 CarPlay 模拟器的话，音量是正常的

好的，感谢您的回复。请问一下我还可以做什么来帮助您排查这个问题。还是说这个问题无解了。

**Comment by gitbobobo** [comment]
目前确实没有办法，我这里能复现才有解决的可能

**Comment by noginger** [comment]
> 目前确实没有办法，我这里能复现才有解决的可能

终于找到原因了。原来是因为音流app中的音量设置小了（大概20%），就导致carplay必须把音量开到很大才有声音。把音流app里面的音量开到最大就正常了。

但是我有个疑问，那就是为什么网易云音乐在carplay时是无法在app中调节音量的，但是音流在链接carplay之后依然可以在app中调节音量啊。

**Comment by gitbobobo** [comment]
音流调节的是输出音量，不是系统音量

**Comment by gitbobobo** [comment]
🏷️ **Priority: P0** - 图片加载异常导致黑屏，严重影响视觉体验，问题描述清晰。
