### ISSUE TITLE
Emby的当前分区希望可以是所有

### ISSUE THREAD

**Issue by bimzcy** [gitbobobo/StreamMusic#490]
连接Emby资料库很奇怪，当前分区居然只能选择其中一个文件夹，而我在Emby里是创建了多个文件夹的，比如华语专辑、日韩专辑、欧美专辑等，这就导致要搜索歌曲的时候还需要切换不同的分区，而不能一次搜索全部。

用Symfonium就没有这个烦恼。

**Comment by gitbobobo** [comment]
测试版已经加入全部分区的支持了

**Comment by gitbobobo** [comment]
1.3.1已发布
