### ISSUE TITLE
mac客户端里的本地音乐什么意思

### ISSUE THREAD

**Issue by sky8282** [gitbobobo/StreamMusic#491]
![1](https://github.com/user-attachments/assets/c92974d5-b998-4af3-9694-6a449251d1a5)

播放音乐之后都会在这里产生曲目，是怎么回事？是缓存到本地吗？
我已经在设置里关闭离线模式和关闭了自动下载

**Comment by jibwf** [comment]
有一个播放后缓存功能。如果不需要可以关闭

**Comment by gitbobobo** [comment]
边听边存是控制程序是否保留缓存文件的

**Comment by sky8282** [comment]
> 有一个播放后缓存功能。如果不需要可以关闭

设置里已经关闭，但是还是会出现
