### ISSUE TITLE
歌曲添加到歌单时,歌单中已经存在了，但是会重复添加

### ISSUE THREAD

**Issue by zhiwei1998** [gitbobobo/StreamMusic#494]
**Describe the bug (BUG 描述)**
歌曲添加到歌单时，原来歌单中就已经存在了，但是会重复添加，导致歌单中出来重复的歌曲

**To Reproduce (复现步骤)**

**Expected behavior (期望行为)**
希望在添加歌曲时可以给出重复提示，禁止添加，可以确保歌单的整洁

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 - OS: 安卓14
 - 音流版本: 1.3.0

**Music Server Type (音乐服务器类型)**
e.g. emby 4.8.8.0

**Additional context (额外信息)**

**Comment by zhiwei1998** [comment]
![Uploading Screenshot_2024-08-09-11-26-51-571_cn.aqzscn.stream_music-edit.jpg…]()

**Comment by gitbobobo** [comment]
这个问题无法处理，总不能添加一首歌曲就先向服务端查询一下是否已经在歌单里了，这样效率太低了，要做也是在服务端做
