### ISSUE TITLE
Navidrome stream接口不支持302播放

### ISSUE THREAD

**Issue by yonly1314** [gitbobobo/StreamMusic#495]
**Describe the bug (BUG 描述)**
ios app navidrome stream接口，无法播放302链接，直接访问navidrome站点，stream接口可以正常播放302链接

**Expected behavior (期望行为)**
ios app 能正常播放302链接

**Platform and Device Info (操作系统及设备信息)**
 - OS: ios
 
**Music Server Type (音乐服务器类型)**
navidrome

**Comment by gitbobobo** [comment]
131测试版已修复此问题

**Comment by yonly1314** [comment]
已经发送了邮件申请ios tf版本，辛苦发放一下测试资格

**Comment by yonly1314** [comment]
> 131测试版已修复此问题
ios tf 1.3.1版本，任然无法播放302链接，如有需要可以提供服务器地址和账号供测试
日志如下：
```
DEBUG 🐛 [server_notify]开始缓存：无尽空虚
  DEBUG 15:54:17.218 (+0:00:28.768467)
  DEBUG 🐛 GET:http://IP:PORT/rest/stream?u=dev&t=1bd3a33b8c99a73e1e008b1c8badee98&s=6578c8&f=json&v=1.15.0&c=Stream+Music&id=cd299e40bcd82c2fd0a1a5374be1ec4e&format=raw&maxBitRate=0
  ERROR 15:54:17.219 (+0:00:28.768964)
  ERROR ⛔ 播放异常：Failed to recognize file format.
  DEBUG 15:54:17.594 (+0:00:29.144231)
  DEBUG 🐛 [server_notify]缓存完成：无尽空虚
```

**Comment by gitbobobo** [comment]
那麻烦提供下吧，最近有个用户发我的302直链的navi账号是没有问题了 邮箱 aqzscn@qq.com

**Comment by yonly1314** [comment]
确实是url里面有中文导致的，做了url encode就好了。
