### ISSUE TITLE
为何一张专辑被分割成无数分享

### ISSUE THREAD

**Issue by sky8282** [gitbobobo/StreamMusic#500]
专辑里的艺术家有的是合作的，所以个别曲目的艺术家有2个甚至更多，这样导致导入之后被切割成无数份专辑

![1](https://github.com/user-attachments/assets/d9f95e3d-5e0f-4d3c-add7-64822302a9ad)

**Comment by sky8282** [comment]
![12](https://github.com/user-attachments/assets/2c0c106f-c8f3-4ed9-92af-e4ff5f0f8a9a)

**Comment by gitbobobo** [comment]
这是 Navidrome 的特性，你需要将歌曲标签中的专辑艺术家统一为一个人

**Comment by RuiDSaaCC** [comment]
用 Emby 吧，只要 MusicBrainz 的专辑ID相同就是同专辑，专辑艺术家可以完全不同

**Comment by sky8282** [comment]
这不现实，太多的工作量了，为何不参考下roon对于专辑的管理逻辑，同张专辑roon里就不会被分割

**Comment by sky8282** [comment]
谢谢建议，我尝试一下emby，现在装的Navidrome!

**Comment by sky8282** [comment]
已经编辑歌曲的元数据解决，多谢指导
