### ISSUE TITLE
下载问题

### ISSUE THREAD

**Issue by greatkeke** [gitbobobo/StreamMusic#501]
**Describe the bug (BUG 描述)**
无法下载音乐

**To Reproduce (复现步骤)**
1. 选择音乐
2. 点击下载

**Expected behavior (期望行为)**
可以正常下载歌曲到本地

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 - OS: ios 17.5.1
 - stream music : 1.3

**Music Server Type (音乐服务器类型)**
jellyfin 10.9.9

**Additional context (额外信息)**
批量下载的话，貌似只有第一首歌能下载，而且还删不掉。
已经试过重新安装都不行，安卓的1.3也试了，同样不行。

**Comment by gitbobobo** [comment]
试下131测试版还有没有问题

**Comment by greatkeke** [comment]
哪里有1.3.1版本下载

**Comment by greatkeke** [comment]
进一步发现，原来是部分歌曲下载到100%就卡住了，取消下载后才能继续下载。
仅有少部分歌曲是这样，无法下载。
另外发现听local 的歌曲时如果没有连接到服务器，会存在播完一首歌之后，无法继续播放下一首，需要按一下播放才可以继续。

**Comment by gitbobobo** [comment]
好的，我试试看

**Comment by gitbobobo** [comment]
开启飞行模式后并未复现无法自动切歌的问题。

100%之后还会去缓存歌曲对应的封面和歌词，并非是卡住了。

**Comment by greatkeke** [comment]
更新到1.3.1之后好了
