### ISSUE TITLE
对自签名证书的支持

### ISSUE THREAD

**Issue by RuiDSaaCC** [gitbobobo/StreamMusic#502]
后续是否有计划增加对自签名证书的支持？现在用http根本不敢连公共场所的热点。

**Comment by gitbobobo** [comment]
建议申请 Let's Encrypt 的证书

**Comment by xwyam** [comment]
> 建议申请 Let's Encrypt 的证书

Let's Encrypt的证书有效期要缩短到45天了，大佬有计划支持下自签名证书么。
