### ISSUE TITLE
随机播放最后一首后希望再随机一批

### ISSUE THREAD

**Issue by justyeh** [gitbobobo/StreamMusic#504]
目前使用随机播放，到最后一首后会停止音乐
体验不太好：车机上会中断，手机也会感觉到停顿
希望能继续随机一批，无果不好做到无限加载，覆盖当前播放列表也可以

**Comment by gitbobobo** [comment]
目前播放列表最多500首歌曲，我觉得一次肯定是听不完的。

之后会推出类似电台的功能，即不会预先生成播放列表，而是在播完当前歌曲后重新随机一首歌曲。

**Comment by justyeh** [comment]
我随机的是“我喜欢的”，navidrome音乐源，总数不太多
因为我不太喜欢同一时间都听一个歌手的，所以每次都选随机播放，就导致每次随机播放完了还需要再次随机一下

**Comment by gitbobobo** [comment]
那你需要的可能是 设置 - 循环播放

**Comment by justyeh** [comment]
> 那你需要的可能是 设置 - 循环播放

 原来这个开关是控制这个的，谢谢了
