### ISSUE TITLE
是否可以不校验内网地址的https证书？

### ISSUE THREAD

**Issue by GTX990boom** [gitbobobo/StreamMusic#507]
公网可以正常登录，因为证书是和公网域名对应的，但是内网地址就证书和地址对不上无法正常登录了。
是否可以给一个设置，不验证https的证书，谢谢

**Comment by gitbobobo** [comment]
内网为什么要用https呀

**Comment by GTX990boom** [comment]
> 内网为什么要用https呀
首先感谢回复
Navidrome我设置了https证书之后，就访问不了http了，暂时没搞懂怎么设置http和https共存。
就是想问一下能不能增加一个忽略证书的选项
感谢
