### ISSUE TITLE
windows端只能加载Jellyfin一个音乐库。

### ISSUE THREAD

**Issue by qianyue0317** [gitbobobo/StreamMusic#510]
这更新之后怎么只能选择一个音乐库加载了，之前还是能同时加载所有Jellyfin音乐库的。这怎么还越更新越差。。

**Comment by qianyue0317** [comment]
![QQ_1723871104926](https://github.com/user-attachments/assets/ea0cbcfe-73a2-479d-a847-1faf2b91d70e)
这里能不能添加一个选项： 加载所有分区

**Comment by gitbobobo** [comment]
增加新功能的同时难免有考虑不周的时候，介意就不要用。

测试版已经加上了

**Comment by qianyue0317** [comment]
![QQ_1723996888696](https://github.com/user-attachments/assets/e34374a1-9fce-4251-8a6c-43f250f9e0e5)
zheju这句话惹你不悦了？
