### ISSUE TITLE
希望连接audio station时能够支持显示歌曲自带封面而不仅是专辑封面

### ISSUE THREAD

**Issue by Weixuepiaoyang** [gitbobobo/StreamMusic#512]
**Expected behavior (期望行为)**
因为有些音乐资源不是按照专辑划分，而是包含多位歌手的精选。在这种情况下对接audio station时播放歌曲只能读取专辑封面，就会导致一个文件夹中的歌曲只能加载一首歌的封面。而使用DS audio进行播放时是能够加载每首歌曲自己的封面信息的。
刚用不久，感觉其他体验都很好，就这一点当前非常在意，希望能够落地该需求使音流更加好用～

**Comment by gitbobobo** [comment]
131版本将会切换至你所说的这种逻辑，可以先用测试版体验看看有无问题。github首页有下载地址

**Comment by Weixuepiaoyang** [comment]
> 131版本将会切换至你所说的这种逻辑，可以先用测试版体验看看有无问题。github首页有下载地址

已在尝试了，131版本确实可以了！非常感谢！

**Comment by gitbobobo** [comment]
1.3.1已发布
