### ISSUE TITLE
封面图片尺寸限制问题

### ISSUE THREAD

**Issue by Fsdcgh** [gitbobobo/StreamMusic#513]
**Describe the bug (BUG 描述)**
音流对Emby封面图片尺寸限制在了600*600(似乎)，导致在一些场景下图片有些模糊。

**Expected behavior (期望行为)**
开放图片尺寸限制

**Platform and Device Info (操作系统及设备信息)**
 Windows10 22H2
音流版本1.3.0

**Music Server Type (音乐服务器类型)**
Emby 4.8.8.0

**Additional context (额外信息)**
直接解析Emby服务端的图片链接，发现Emby服务端会对图片文件进行实时的压缩和转换,这点可以从的图片链接中看得出来(http://192.168.152.158:63096/emby/Items/192/Images/Primary?maxWidth=600&tag=31259293e383d8dfc68e392ea3e1fc69&quality=90)
如果更改其Width值和quality值Emby会对图片进行实时压缩和转换，例如原链接为:http://192.168.152.158:63096/emby/Items/192/Images/Primary?maxWidth=600&tag=31259293e383d8dfc68e392ea3e1fc69&quality=90,则图片为
![批注 2024-08-18 144602](https://github.com/user-attachments/assets/fcc5ae06-5df9-4a69-b572-b143b4e48b4f)
若链接为:http://192.168.152.158:63096/emby/Items/192/Images/Primary?maxWidth=100&tag=31259293e383d8dfc68e392ea3e1fc69&quality=10,则图片为
![image](https://github.com/user-attachments/assets/aa916dd7-be8a-42b5-8f6f-cd0d941485c9)
若链接为:http://192.168.152.158:63096/emby/Items/192/Images/Primary?,则图片与原文件几乎无异，为
![image](https://github.com/user-attachments/assets/665176bc-ac7e-4b8e-8910-5e1a86b736f6)

此外，我在音流文档(https://music.aqzscn.cn/docs/notes/services/emby#images-%E5%9B%BE%E7%89%87%E9%93%BE%E6%8E%A5)中发现音流似乎将图片尺寸限制在了600*600，我尝试通过自定义API来更改和取消限制值，但没有生效。

**Comment by gitbobobo** [comment]
尺寸限制固定600x600是为了在大部分情况下兼容清晰度与加载时间，同时减少对同一张图片不同版本的缓存。

一些场景无非是桌面端的全屏模式，可即使全屏模式，封面也不会无限制放大，所以我觉得没有使用全尺寸封面的必要性。
