### ISSUE TITLE
iOS 客户端状态栏字体颜色错误

### ISSUE THREAD

**Issue by nrjycyd** [gitbobobo/StreamMusic#515]
**Describe the bug (BUG 描述)**
iOS 客户端状态栏字体颜色错误

**To Reproduce (复现步骤)**
1.设置-主题-跟随系统-白色；
2. 打开音乐，进入“全部音乐”，“我喜欢的”，“本地音乐”，“文件夹”中任意一个；
3. 进入上述界面，会发现手机的状态栏呈现白色，手机的信号、时间等信息字体颜色与状态栏颜色趋同，不能很好反馈信息；

**Expected behavior (期望行为)**
状态栏字体颜色和主界面颜色形成反差；

**Screenshots (截图)**
![IMG_0714](https://github.com/user-attachments/assets/61e5f615-8f96-4eca-9b4f-74e593a710d6)
![IMG_0715](https://github.com/user-attachments/assets/eeec2609-72f3-4b6a-bfae-1922d4a3426c)
![IMG_0716](https://github.com/user-attachments/assets/b918029e-8ce3-4b52-9819-bd40c7d1840a)
![IMG_0717](https://github.com/user-attachments/assets/3260f638-c851-4596-b07a-12764a7edf1b)
![IMG_0718](https://github.com/user-attachments/assets/4b9e7a45-9168-4f00-8ff2-dc3527e9bfaa)

**Platform and Device Info (操作系统及设备信息)**
 - OS: iOS
 - Version: 18.0

**Music Server Type (音乐服务器类型)**
docker image: deluan/navidrome:latest

**Additional context (额外信息)**
无

**Comment by gitbobobo** [comment]
与此问题重复，暂时没有找到有效的解决方案

https://github.com/gitbobobo/StreamMusic/issues/53
