### ISSUE TITLE
安卓1.2.8版本后播放歌曲有几率出现声音卡顿

### ISSUE THREAD

**Issue by hmhboy** [gitbobobo/StreamMusic#518]
安卓1.2.8版本后播放歌曲有几率出现声音卡顿，卡顿时间很短，类似破音，仔细听可以听出，在听24bitFLAC时出现频率较高，其他FLAC歌曲也有发生（因为本人歌曲都是FLAC，其他格式未进行测试）。

音乐文件均已下载到本地播放，因此可以排除网络或者服务端的原因。更换其他品牌手机故障依旧，但换用其他播放器正常。

在QQ群内询问，也有人有同样的情况，目前无法总结出复现规律，但是发生频率较高。

上述卡顿BUG在尝试更换1.2.7版本后消失，查看1.2.8的更新，发现更换了media_kit解码插件，建议作者测试是否因为此原因造成，如无法解决建议能否在下一版本允许用户选择解码插件。

**Comment by hmhboy** [comment]
这个问题和https://github.com/gitbobobo/StreamMusic/issues/505很类似，估计是同一问题。

**Comment by gitbobobo** [comment]
用测试版试试看呢？

**Comment by hmhboy** [comment]
刚刚下载这个版本：
https://oss.aqzscn.cn/stream-music/versions/1.3.1/app-release.apk
测试问题依旧。

**Comment by gitbobobo** [comment]
又更了个测试版本，再试一下吧

**Comment by hmhboy** [comment]
测试了一下，今天这版本似乎没有卡顿了

**Comment by gitbobobo** [comment]
1.3.1已发布
