### ISSUE TITLE
自定义api歌词收到返回值，但是提示没有歌词。

### ISSUE THREAD

**Issue by vvxu** [gitbobobo/StreamMusic#520]
已经按照api的响应体
[
    {
        "id": "<歌词id，用于与其他歌词去重>",
        "title": "<标题，可能与查询的标题不一致>",
        "artist": "<歌手，可能与查询的歌手不一致>",
        "lyrics": "<歌词文件内容>"
    },
    ...
]
返回数据，请求记录中可以看到响应体内容部分有以上格式的内容，但是歌曲的歌词中提示没有歌词。

**Comment by gitbobobo** [comment]
你可以再确认下响应格式是否正确，或是否设置了content-type,据我所知是有可以正常使用的API的

**Comment by yuygfgg** [comment]
内容好像不需要引号
