### ISSUE TITLE
无法删除本地歌曲

### ISSUE THREAD

**Issue by nballen-tx** [gitbobobo/StreamMusic#522]
**Describe the bug (BUG 描述)**
iOS版 删除本地歌曲 实际上无法删除

**To Reproduce (复现步骤)**
1.在歌曲的菜单中选“删除文件”无法删除
2.在本地音乐中选择歌曲删除（不管是全部还是部分）删除后实际不删除

**Expected behavior (期望行为)**
期望是可以删除歌曲

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 - OS: iOS
 - Version 1.30

**Music Server Type (音乐服务器类型)**
navidrome

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
1.3.1已修复
