### ISSUE TITLE
没法调整排序方式

### ISSUE THREAD

**Issue by ShohanPei** [gitbobobo/StreamMusic#525]
**Describe the bug (BUG 描述)**
用文件夹模式浏览歌曲，发现不是按音轨排序的，也没法改，右上角排序方式是灰色的

**To Reproduce (复现步骤)**

**Expected behavior (期望行为)**

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 安卓

**Music Server Type (音乐服务器类型)**
audiostation

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
132测试版已添加音轨号排序

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布
