### ISSUE TITLE
随机播放歌单时，播放列表有500首的上限

### ISSUE THREAD

**Issue by MegrezZhu** [gitbobobo/StreamMusic#530]
**Describe the bug (BUG 描述)**
后端是Navidrome，我有一个2000+首歌曲的歌单，在手机上我希望随机播放这个歌单（所有歌曲都可以随机到），但点击“随机播放”时播放列表只有500首，而且应该都是前500首，导致排在后面的上千首歌一直没法听到。

**To Reproduce (复现步骤)**
1. 有一个多于500首歌的歌单（btw我用的是Navidrome的smart playlist）
2. 点击“随机播放”

3. 打开播放列表，里面只有500首歌，无论直连或者非直连，里面的歌看起来都是前500首

**Expected behavior (期望行为)**

能够在歌单的所有歌曲里面随机，即歌单里有多少歌曲播放列表里就有多少，行为类似网易云/QQ音乐、或者同样支持navidrome的pc端的Feishin、或者navidrome网页端本身。这个500首歌的限制应该是可选的才对。

**Screenshots (截图)**

![67d1aa0be883f7ccf22e65d3852dff5](https://github.com/user-attachments/assets/5919e077-3d7c-44cb-ad3c-93b650ffe6ba)

![d40d7aa9a1853301d0372c3881559f9](https://github.com/user-attachments/assets/e14a8682-b0f6-4f9d-8bcb-45c0cb6079de)

**Platform and Device Info (操作系统及设备信息)**
 - OS: ios 17.5.1
 - Version: 1.3.0

**Music Server Type (音乐服务器类型)**
Navidrome

**Additional context (额外信息)**

**Comment by tonyzzp** [comment]
正想说呢。另外我想要个全部歌曲随机放的功能。类似电台 。

**Comment by gitbobobo** [comment]
1.3.1已修复随机范围在前500首的问题，但数量上限短期内不会放开

**Comment by CloudDragon3** [comment]
我自己测试，机制好像是这样的。在歌单里面，点封面图下面那个“随机播放”，好像是从所有歌曲里，随机出500个。在播放列表里面点随机，是这500首歌曲重新排序。

**Comment by X-Kay** [comment]
就是因为五百首的问题找到这里来了，希望能够考虑下开放全范围随机播放

**Comment by LeslieLee0420** [comment]
确实，同样因为这个问题困扰。因为我的歌单内数量＞500首，虽然不会一次性连续听500多首歌，但这个限制挺无奈的

**Comment by X-Kay** [comment]
您的邮件我已经收到，我会尽快给您回复。

**Comment by woyuanlongye** [comment]
我也发现了，然后在navidrome网页端试了下，navidrome的播放列表也只显示500首，所以看起来应该是navidrome本身的问题

**Comment by X-Kay** [comment]
您的邮件我已经收到，我会尽快给您回复。

**Comment by MegrezZhu** [comment]
> 我也发现了，然后在navidrome网页端试了下，navidrome的播放列表也只显示500首，所以看起来应该是navidrome本身的问题

我在PC上使用Feishin连Navidrome没有这个问题，所以至少Navidrome后端是不存在这个限制的，可能是它的web端也加了500首限制

**Comment by HoDZadkiel** [comment]
Feishin我測試有時可以加入1000首，有時可以零星加入變成1200等等，但就是沒辦法全部加進去
以前用foobar2000聽歌的習慣是全音樂隨機，並且聽到特喜歡的音樂就拉到播放清單最上方，想聽這些歌時去最上方點選就好
所以才會想要一個有全音樂的播放清單！

**Comment by X-Kay** [comment]
您的邮件我已经收到，我会尽快给您回复。

**Comment by jiandanjian** [comment]
同求，这个咋解决
