### ISSUE TITLE
ios在非直连模式下搜索歌曲出现重复记录

### ISSUE THREAD

**Issue by gaozw1** [gitbobobo/StreamMusic#533]
**Describe the bug (BUG 描述)**
在ios下搜索歌曲，出现多个重复记录，可以确定服务器中只有一个符合搜索的记录

**To Reproduce (复现步骤)**
1. 非直连模式下，点击搜索框
2. 输入 不为谁而作的歌
3. 出现多条重复记录

**Expected behavior (期望行为)**
搜索对应歌曲后，只出现在服务器中匹配的记录

**Screenshots (截图)**
在非直连模式下，搜索歌曲
![09730B40-CEBC-4127-B479-49AB287188A3](https://github.com/user-attachments/assets/5a2e193b-b457-41da-be65-95b92ade22dc)

然而，除了第一首，其他歌曲都不能播放，因为服务器端没有这些资源
![5B30C17C-504F-4B9E-AA5B-E7A6CCF6E948](https://github.com/user-attachments/assets/1ae5548c-6c20-42e1-8101-4581edd0cde7)

将模式切换为直连模式，搜索结果符合预期效果
![D959E587-669D-4AA2-8B08-9D01A83368C2](https://github.com/user-attachments/assets/633aa13a-01a7-4ca6-99c7-ad3b60f9e251)

然而将模式切换为非直连模式，搜索结果又出现上述所描述的问题

以下是播放这几个多余的搜索记录时的报错信息
![74AEE02E-E745-489F-BEE6-9CFB7DD9CAE1](https://github.com/user-attachments/assets/dfcd4f71-4903-4bc4-a74a-391396ed0de9)

**Platform and Device Info (操作系统及设备信息)**
 - OS: iOS
 - Version 1.3.0

**Music Server Type (音乐服务器类型)**
Navidrome

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
1.3.1已修复
