### ISSUE TITLE
仍然是不显示封面的问题（我之前提过的#435）

### ISSUE THREAD

**Issue by YashiroKirara** [gitbobobo/StreamMusic#535]
之前1.3.0版本时提过这个问题：https://github.com/gitbobobo/StreamMusic/issues/435

今天看到1.3.1发布了，但是更新后发现问题貌似更严重了，以前只有播放页面不显示歌曲封面，现在所有歌曲封面都不显示了，只有专辑封面可以显示……

服务器版本还和之前一样，iPhone和iPad都是这样的问题，清空本地缓存重新刷新数据也无法解决

![IMG_5115](https://github.com/user-attachments/assets/c23c5434-66f8-4e5d-8a3d-8229c8314eca)
![IMG_5116](https://github.com/user-attachments/assets/67f56c89-05a8-427e-9d4a-a1ba12f1a067)
![IMG_5117](https://github.com/user-attachments/assets/a0d6835e-6475-4910-8f6a-dec39637cdfb)

**Comment by gitbobobo** [comment]
那还需要麻烦你邮件发我一下测试账号了，之前的邮件已经删掉了。

可以按[此处](https://music.aqzscn.cn/docs/features)要求申请一下TF，方便及时反馈问题

**Comment by YashiroKirara** [comment]
你好，申请TF的邮件发送了，请查收


这是测试账号：
用户名：Test
密码：Qwe12345678@@@###
服务器：http://www.darksiders.top:65432


| |
Yashiro Kirara
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年09月2日 09:24 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [gitbobobo/StreamMusic] 仍然是不显示封面的问题（我之前提过的#435） (Issue #535) |

那还需要麻烦你邮件发我一下测试账号了，之前的邮件已经删掉了。

可以按此处要求申请一下TF，方便及时反馈问题

**Comment by gitbobobo** [comment]
好的感谢🙏

**Comment by gitbobobo** [comment]
测试版已更新，试试看还有问题吗

**Comment by YashiroKirara** [comment]
目前看来封面没有问题了，多谢多谢！！！

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布
