### ISSUE TITLE
1.3.1 切换播放模式后界面未更新

### ISSUE THREAD

**Issue by sjf9179** [gitbobobo/StreamMusic#537]
**Screenshots (截图)**
![image](https://github.com/user-attachments/assets/c3f7e2d5-1ebf-4db2-8074-f861f29652d9)
这里无法点击

曲库数量
![image](https://github.com/user-attachments/assets/a359b7ea-ad16-49bb-883f-337293d1b00c)

**Comment by sjf9179** [comment]
1.3.0是正常的

**Comment by gitbobobo** [comment]
界面没有更新，实际已经切换了，可以从播放列表中看到效果

**Comment by sjf9179** [comment]
> 界面没有更新，实际已经切换了，可以从播放列表中看到效果

噢 明白了 改变了刷新逻辑或者时间间隔是吧

**Comment by gitbobobo** [comment]
132测试版已修复

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布
