### ISSUE TITLE
jellyfin 有声书Book分区Section

### ISSUE THREAD

**Issue by jibwf** [gitbobobo/StreamMusic#539]
我的歌曲放在音乐分区，有声书放在Book分区. Jellyfin对Book和Music的处理是不同的逻辑，有声书不会刮削。音流目前无法识别Book分区的音乐文件，希望可以支持，更好的处理有声书. 

**Platform and Device Info (操作系统及设备信息)**
 - OS: ARM MACOS
 - 音流 1.3.1

**Music Server Type (音乐服务器类型)**
Jellyfin 10.9.10

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
官网已有说明，这个不会支持的。

<img width="984" alt="image" src="https://github.com/user-attachments/assets/5c5218a6-0fe1-4475-b566-91bcfc6aded4">
