### ISSUE TITLE
【需求】切换歌单播放或重新播放整个歌单播放控制会变化， 是否可以有一个可以按个人喜好记录一个状态

### ISSUE THREAD

**Issue by zmquan** [gitbobobo/StreamMusic#541]
现象如下：

https://github.com/user-attachments/assets/03105e39-df02-4cd0-9c33-80b6d1f61cdc

**Comment by gitbobobo** [comment]
https://music.aqzscn.cn/docs/guides/play

请参考此页文档

**Comment by zmquan** [comment]
我研究一下， 多谢

**Comment by zmquan** [comment]
哈哈， 比如很喜欢一首歌， 希望下次打开都是同首歌，像一直听，每次打开都要点击一下`单曲循环` ， 好像那个按钮不是很丝滑，有时候好像到后面就不动， 不会一直loop。  哈哈哈哈

**Comment by gitbobobo** [comment]
单曲循环的切换新版本有点儿问题，点击之后界面不会更新，之后会修复此问题
