### ISSUE TITLE
链接线路无法删除

### ISSUE THREAD

**Issue by justyeh** [gitbobobo/StreamMusic#544]
线路列表中有一个线路无法删除：后面没有...

这个链接已经失效了，摆在那里很别扭

希望改进一下逻辑：所有的线路都可以编辑、删除，即使最后一个也可以删除（允许线路为空的资料库 or 删除最后一个时提示一并删除资料库），总之，把选择的权利交给用户

**Comment by gitbobobo** [comment]
无法编辑的链接一般是服务端返回的，即使删掉也会在下次登录时重新获取到，这会更加令用户困扰。

多几个线路也并不会影响连接速度，应用会使用最先连接成功的备用线路。

至少存在一个线路是资料库存在的根基，若要删除资料库，在上一级删除岂不是更加方便？
