### ISSUE TITLE
鸿蒙4.2.0 无法播放 dsf 等无损格式的文件

### ISSUE THREAD

**Issue by msnake0502** [gitbobobo/StreamMusic#548]
鸿蒙 4.2.0 无法播放 dsf 等无损格式的文件，从苹果IOS转到了华为鸿蒙，之前使用的 ds player 无安卓版（ds player 可以正常播放 dsf 等），很庆幸找到了 音流，正准备付费的时候返回继续尝试，发现 dsf 等无损格式的文件无法播放，不知是需要开通会员才可以还是目前本身不支持（会员功能没有提到），如果本身不支持，希望可以支持。

**Comment by gitbobobo** [comment]
1.3.2最新测试版已修复，可以先试试看有没有问题

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布

**Comment by gitbobobo** [comment]
鸿蒙需要连续点击版本号，在开发者页面启用audioTrack
