### ISSUE TITLE
离线播放版本经常播放完一首或者几首后就不播放了

### ISSUE THREAD

**Issue by TMTBO** [gitbobobo/StreamMusic#550]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
离线播放版本经常播放完一首或者几首后就不播放了.
目前测试了
iOS 1.3.0, 1.3.1: 音乐下载到本地, 锁屏后, 经常出现, 大多数据时候只能播放完一首后就不播放了, 灵动岛上的播放状态没了, 看上去并不是暂停
Android 1.3.0: 在电视上使用, 播放缓存数据的音乐, 也会出现以上情况

看了下日志, 看上去是"Error decoding audio" 有关, 但实际是可以正常decode的, 重新点一下播放就可以正常播放

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**

**Expected behavior (期望行为)**

**Screenshots (截图)**
![Screenshot 2024-09-06 at 18 30 33](https://github.com/user-attachments/assets/882c363f-be41-45bf-8e1d-986e77ce2a43)

**Platform and Device Info (操作系统及设备信息)**
 - OS: iOS
 - Version 17.6.1

**Music Server Type (音乐服务器类型)**
Jellyfin  10.9.7
出现异常时, 服务连无法连接, 但音乐已下载到本地

- [x] Direct Mode（直连模式）
- [ ] Library Mode（媒体库模式）

**Additional context (额外信息)**

**Comment by paysenyu** [comment]
同样的问题

**Comment by TMTBO** [comment]
最新版本已解决

**Comment by TMTBO** [comment]
最新版本已解决
