### ISSUE TITLE
会员的文件夹功能和实际数量对不上

### ISSUE THREAD

**Issue by sjf9179** [gitbobobo/StreamMusic#552]
![image](https://github.com/user-attachments/assets/6bd2efba-f1e0-48f6-acf6-2dd79129c18a)
我文件夹里是32首

![image](https://github.com/user-attachments/assets/2dda4acf-5d15-4b75-92c9-d0da04bed098)
音流里只有27了  而且这个数字会变  有时又是21  有时又是20

很迷

**Comment by sjf9179** [comment]
![Uploading image.png…]()
新的数字出现了

**Comment by sjf9179** [comment]
![image](https://github.com/user-attachments/assets/18ab6848-fba0-4c86-8b14-ec9c12ced59c)
新的数字出现了

**Comment by gitbobobo** [comment]
直连模式下，只有支持文件夹接口的服务可以正常显示

https://music.aqzscn.cn/docs/services#%E5%8A%9F%E8%83%BD%E6%AF%94%E8%BE%83

**Comment by sjf9179** [comment]
明白
但是这个数字也不应该老是变化吧？

**Comment by gitbobobo** [comment]
变化是因为读到了新的音乐

**Comment by sjf9179** [comment]
> 变化是因为读到了新的音乐

![image](https://github.com/user-attachments/assets/70913fbc-46f7-4916-b41e-1795cda75647)
第一 这个文件夹很久没变动了 为啥会读到新音乐
第二 就算读到新的了 也不会突然变少吧(100%肯定没有删除)  这个数字是一会儿大 一会儿小变动的
