### ISSUE TITLE
ios下载的歌曲怎么分享出来呢

### ISSUE THREAD

**Issue by sjf9179** [gitbobobo/StreamMusic#553]
下载好了 然后没有能任何使用的地方

**Comment by gitbobobo** [comment]
分享的话从网页端下载应该更好吧。

目前app内的下载最主要的用途还是保证不被系统自动删掉

**Comment by sjf9179** [comment]
> 分享的话从网页端下载应该更好吧。
> 
> 目前app内的下载最主要的用途还是保证不被系统自动删掉

OK 期待加入分享功能
