### ISSUE TITLE
希望可以支持上下滑动切歌 

### ISSUE THREAD

**Issue by T888T** [gitbobobo/StreamMusic#555]
#### 希望可以支持上下滑动切歌
类似于某音视频的上下滑动来切换视频那样 这样即便在不方便或不看屏幕的情况下也可以盲操切歌 
如果和当前操作逻辑有冲突或可以增加按钮来切换逻辑 感谢大佬！！！

**Comment by gitbobobo** [comment]
没见过支持这种操作方式的音乐app，而且感觉并不合理，抱歉

**Comment by T888T** [comment]
> 没见过支持这种操作方式的音乐app，而且感觉并不合理，抱歉

可以看一下抖音旗下的汽水音乐app就是这种交互逻辑
