### ISSUE TITLE
ios 无法调整播放模式，比如无法调整为单曲循环

### ISSUE THREAD

**Issue by qiniuweihe** [gitbobobo/StreamMusic#556]
如题

**Comment by wangfengyu1999** [comment]
同问题，截图如下：
![3271725722430_ pic](https://github.com/user-attachments/assets/47aa005f-cee8-4068-9561-f2b414be6e40)

**Comment by gitbobobo** [comment]
与此问题 https://github.com/gitbobobo/StreamMusic/issues/537 相同，测试版已修复此问题
