### ISSUE TITLE
iOS在未连接服务器时无法自动切换下一首歌曲播放

### ISSUE THREAD

**Issue by wangfengyu1999** [gitbobobo/StreamMusic#557]
问题如题。
具体情况为歌曲1播放完后，自动切换到歌曲2的末尾并暂停，必须手动点击播放按钮才能播放。

**Comment by paysenyu** [comment]
同样的问题 下载了1000多首歌

飞机上开飞行模式，播放万一首之后就不会自动播放下一首 需要切到前台才可以

软件在后台就不行

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布
