### ISSUE TITLE
1.3.1版本电脑端及app端【文件夹结构无法更新】

### ISSUE THREAD

**Issue by applemomoka** [gitbobobo/StreamMusic#559]
我最近将NAS中得文件夹音乐重新整理了一下文件夹以后，文件夹结构如下图
![微信图片_20240909100422](https://github.com/user-attachments/assets/dda87958-2f5c-4698-8c71-d5ef1e0bb5f9)
但是电脑端及app重新同步文件夹还是显示未整理之前得文件夹结构
![微信图片_20240909100415](https://github.com/user-attachments/assets/9663a9ce-bdfd-438f-ae73-edab9a4d517e)
![微信图片_20240909101243](https://github.com/user-attachments/assets/34f7f2e5-3588-43cf-8b75-98267080f9ad)

导致大量音乐无法播放
我试过删掉资料库、删除app缓存，换低版本app
都没有成功，仍然是没有更新文件夹结构。

**Comment by gitbobobo** [comment]
从音流文件夹里找几首歌曲，看下文件路径

**Comment by applemomoka** [comment]
> 从音流文件夹里找几首歌曲，看下文件路径
比如这首歌
![微信图片_20240909205113](https://github.com/user-attachments/assets/ae037957-0307-426d-ba28-262bbae3d2b5)
它实际路径是下面得
![微信截图_20240909205328](https://github.com/user-attachments/assets/14ad8047-6709-450e-a273-da14b876fb78)
我在navidrome里面是映射到音乐文件夹这里，最近把所有歌手都单独放到人物文件夹里面了，整理了其他文件夹，但是音流app里面得路径无法随着更新，各种同步好几次也没成功更新，导致很多音乐播放不了。

**Comment by gitbobobo** [comment]
如果显示的文件路径都和实际路径对不上的话，鉴于你已经清除过音流的数据，更大的可能是服务端的数据还没更新，而非音流的问题。

**Comment by applemomoka** [comment]
> 如果显示的文件路径都和实际路径对不上的话，鉴于你已经清除过音流的数据，更大的可能是服务端的数据还没更新，而非音流的问题。

我连得是navidrome，那就是说那边没更新吗，但是那边不是自动更新得么，不清楚后续该咋弄了。

**Comment by gitbobobo** [comment]
navi只会自动更新添加的歌曲，如果你修改过歌曲，还是需要手动同步的
