### ISSUE TITLE
安卓上某些音频只能播放一次 app版本 1.3.1

### ISSUE THREAD

**Issue by MoCongxin** [gitbobobo/StreamMusic#561]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
某些音频只能播放一次，切换其他歌曲再切换回来就无法播放了

**Platform and Device Info (操作系统及设备信息)**
 - OS: MIUI 12.5.19
 - Version 1.3.1

**Music Server Type (音乐服务器类型)**
Navidrome Music Server 0.51.1 (6d253225)

- [ ] Library Mode（媒体库模式）

**Additional context (额外信息)**
音频信息
![image](https://github.com/user-attachments/assets/b671737b-3ae9-49ed-be13-e8ea95c6d6f7)

**Comment by gitbobobo** [comment]
可以关掉边听边存试试，目前缓存逻辑还不太完善

**Comment by gitbobobo** [comment]
1.3.2 已发布，对缓存逻辑进行了优化。还有问题可以重新开启此issue
