### ISSUE TITLE
【需求】独立音量控制

### ISSUE THREAD

**Issue by invalidunit** [gitbobobo/StreamMusic#565]
手机版无所谓，但是电脑版应该在播放控制组件旁边增加独立的音量控制吧，因为电脑比手机两个软件同时播放的可能性大一点

**Comment by sabully** [comment]
![image](https://github.com/user-attachments/assets/67e63362-31b6-4d9a-b0fd-5ea33b5ca8b0)
win11系统可以控制各个软件的音量啊

**Comment by invalidunit** [comment]
> ![image](https://private-user-images.githubusercontent.com/41895592/367187762-67e63362-31b6-4d9a-b0fd-5ea33b5ca8b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYyMTQ1MDgsIm5iZiI6MTcyNjIxNDIwOCwicGF0aCI6Ii80MTg5NTU5Mi8zNjcxODc3NjItNjdlNjMzNjItMzFiNi00ZDlhLWIwZmQtNWVhMzNiNWNhOGIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEzVDA3NTY0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5NTAyZWIxZjUzNGQzMmQxYWE3ZjQzNGIxOTZhNjgyZGU1OTM1NjZmMmM2ZTVmMzI0ZWYwNjY1YjEyODgzNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2S7iKnNa0BzRs2fcce1k-kJBc6yEMnBVbBoH5EqrjuQ) win11系统可以控制各个软件的音量啊

虽然，那 mac 呢，而且 qq音乐，网易云，都是控制模块右边有个音量控制，用的比较习惯 emmm

**Comment by gitbobobo** [comment]
音流歌词页面的音量按钮在各个平台都是独立的音量控制。

至于控制栏的音量条，是有计划添加的
