### ISSUE TITLE
「需求」专辑歌曲排序问题

### ISSUE THREAD

**Issue by xiaowu911** [gitbobobo/StreamMusic#569]
专辑里面歌曲的排序目前只有按添加时间、按歌曲名、按专辑名三种排序方式，可以增加按音轨排序（正、倒序）吗？
某些混音专辑里面的歌曲，如果不按音轨顺序播放的话，听起来奇奇怪怪的。
使用环境是Navidrome服务器+免费版客户端（Mac、iOS、Android）

**Comment by gitbobobo** [comment]
按专辑名排序就是按音轨排序（132版本会改为按音轨号排序），倒序我认为没有使用场景。

**Comment by xiaowu911** [comment]
应该说没有按音轨号排序，描述错了，目前按专辑名排序的话，音轨号顺序还是错的
![1726663925069](https://github.com/user-attachments/assets/e48894b8-0c4d-43a9-bafb-24152002ecda)
期待下个版本
