### ISSUE TITLE
使用代理时无法连接服务器

### ISSUE THREAD

**Issue by qu270051387** [gitbobobo/StreamMusic#570]
本人是免流玩家
24＊7使用box4分流国内外
Mihomo+tun+家宽+国外
经测试，当启动代理时，音流无法正常连接navidrome服务器
分流不行  国外全局不行   国内全局不行
因为使用的是家宽  所以当使用家里wifi时 国内全局的ip与不开启代理时ip为同一个

**Comment by qu270051387** [comment]
![Screenshot_20240913-193855_Stream Music](https://github.com/user-attachments/assets/8c665aec-9f44-4bde-89c7-0c86741e2a86)

**Comment by gitbobobo** [comment]
我这里没有对应的网络环境，很难排查出问题所在，抱歉。
