### ISSUE TITLE
【BUG】点击歌单无法切换

### ISSUE THREAD

**Issue by LyleYoung** [gitbobobo/StreamMusic#576]
【我的歌单】下的多个歌单无法切换，点击仍然停留在原来的歌单。如果此时点击任意其他目录，再选歌单，可以成功切换。
![2](https://github.com/user-attachments/assets/cc0d6be9-29f3-43f2-808d-f1029db2351a)

**Comment by gitbobobo** [comment]
我这里没有复现出来，你的服务端和连接模式是什么

**Comment by LyleYoung** [comment]
Audio Station，默认连接模型(没勾选直连

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布
