### ISSUE TITLE
iOS及Windows版本 连接Synology Audio全部歌曲显示100首

### ISSUE THREAD

**Issue by maycyc** [gitbobobo/StreamMusic#580]
### **Describe the bug (BUG 描述，多条问题请分别建立 issue)**

- Windows 1.3.2.2版本与iOS TF版本：1.3.2（93）均有此问题
- 连接Navidrome无此问题
- 媒体库模式扫描出2061首，实际歌曲5040首

### **Screenshots (截图)**
- ![685af6254ce238fbaccde209a017425e](https://github.com/user-attachments/assets/ac746165-6ef1-439c-8ea7-4815b794d450)
- ![image](https://github.com/user-attachments/assets/81085d10-e88c-4418-b89d-ae71b73b73a6)
- ![IMG_4198](https://github.com/user-attachments/assets/3549d97a-310c-403f-b922-986c998d10a0)
- ![屏幕截图 2024-09-18 130245](https://github.com/user-attachments/assets/d024ce63-6582-4eb6-bd85-bfbc2d216daf)

### **Platform and Device Info (操作系统及设备信息)**
 - OS: [e.g. iOS] iOS&Windows
 - Version [e.g. 22]Windows 1.3.2.2版本与iOS TF版本：1.3.2（93）

### **Music Server Type (音乐服务器类型)**
- Synology Audio

- [x] Direct Mode（直连模式）
- [x] Library Mode（媒体库模式）

**Comment by gitbobobo** [comment]
测试版已更新，应该修复了

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布
