### ISSUE TITLE
【需求】安装及缓存路径；点击购买会员无反应（目前是否不支持购买？）。

### ISSUE THREAD

**Issue by LyleYoung** [gitbobobo/StreamMusic#582]
1.发现目前在安装时候没有路径选择，以及在【储存空间管理】内也不能选择缓存到具体的路径以及下载位置。预期是否能添加选择安装+缓存文件到自定义某个路径。
2.点击【音流会员】发现无反应，是否是目前暂时不支持购买？或者有其他购买渠道。
![image](https://github.com/user-attachments/assets/3d81c1dd-80be-4103-9412-639957432a63)

**Comment by gitbobobo** [comment]
桌面端目前使用msix安装包，无法选择安装路径。但似乎可以在系统设置内调整全局msix的安装位置。

软件包解压之后整体也就 100M 左右大小，我觉得没有必要更换安装位置。若实在需要，可以把msix直接解压使用。

目前只有下载位置可以在下载弹框中调整位置。

只有手机端可以购买。
