### ISSUE TITLE
整张专辑无分轨功能

### ISSUE THREAD

**Issue by afeiwuxi** [gitbobobo/StreamMusic#583]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
以果断订购。
但接入Navidrome使用时，服务器保存有的整张CD的WAV和CUE分轨文件，只识别wav整张专辑文件，无法识别分轨CUE文件。
播放时也只能是整张从头至尾的播放，无法选择其中一首歌。

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
-

**Expected behavior (期望行为)**
能否实现读取cue分轨描述文件，使整张CD可以分割成单个歌曲，便于选择其中歌曲来播放。也可以选择其中某首歌放入列表等。

**Screenshots (截图)**
-

**Platform and Device Info (操作系统及设备信息)**
 - iOS14.1

**Music Server Type (音乐服务器类型)**
Navidrome

- [ ] Direct Mode（直连模式）
- [  ] Library Mode（媒体库模式）

**Additional context (额外信息)**
-

**Comment by gitbobobo** [comment]
这个功能需要服务端实现，客户端是无法读取到文件夹内的同名cue文件的
