### ISSUE TITLE
Duplicate song detection doesn't count higher than 9

### ISSUE THREAD

**Issue by Insprill** [gitbobobo/StreamMusic#589]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
When running duplicate song detection on an artist with more than 9 duplicate songs, it only shows 9, even though there are more.

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
1. Get more than 9 duplicate songs from an artist.
2. View duplicate songs.
3. It will show 9 even though there's more.

**Expected behavior (期望行为)**
It should show the actual number of duplicates, or `9+` if the small number is intentional.

**Screenshots (截图)**
All songs in this screenshot are duplicated 100+ times, but it only shows 9 for all of them.
![image](https://github.com/user-attachments/assets/6908090b-3c1b-4bdd-a5de-81c69c572088)

**Platform and Device Info (操作系统及设备信息)**
 - OS: IOS v61.7.10
 - StreamMusic: v1.3.1
 - Navidrome: v0.53.2

**Music Server Type (音乐服务器类型)**
e.g. emby 4.17.

- [ ] Direct Mode（直连模式）
- [x] Library Mode（媒体库模式）

**Comment by gitbobobo** [comment]
fixed on 1.3.2 beta

**Comment by gitbobobo** [comment]
1.3.2 has released
