### ISSUE TITLE
點選流派未顯示任何專輯

### ISSUE THREAD

**Issue by theturtle626** [gitbobobo/StreamMusic#594]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
iOS v1.3.1 點選流派未顯示任何專輯

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
點選流派, 只有出現到底了

**Expected behavior (期望行为)**
1.3.0 版本可正常顯示, 同版本 emby, Windows desktop / Android 1.3.0 版本正常

**Platform and Device Info (操作系统及设备信息)**
 - iOs 18

**Music Server Type (音乐服务器类型)**
emby 4.8.8

- [V] Direct Mode（直连模式）

**Comment by gitbobobo** [comment]
需要在资料库中指定分区后才可以显示。

**Comment by theturtle626** [comment]
已經可以了, 謝謝
