### ISSUE TITLE
是否可以考虑重新开放“实时搜索”的功能，可以做个开关提供选择

### ISSUE THREAD

**Issue by roccox** [gitbobobo/StreamMusic#599]
在前一个版本中，关闭了“实时搜索”的功能。

但是一定要回车后才能出搜索结果，完全失去了那种丝滑的感觉。

能不能把这个功能重新加上，可以默认不打开，提供一个开关供大家自由选择就好。

**Comment by gitbobobo** [comment]
主要是实时搜索会产生多个搜索请求，这样对一些使用 sqlite 数据库的服务端来说，可能会导致最新想要的查询结果需要极长的等待时间才能返回结果。

这样理论上的丝滑，实际表现却并不丝滑，不如用户主动发起搜索。

**Comment by roccox** [comment]
这个功能我理解的不是应该做本地搜索么？服务器的信息应该已经同步到本地了啊

**Comment by gitbobobo** [comment]
对于媒体库模式来说是本地搜索，不过我更倾向于使用直连模式，所以默认是按直连模式的逻辑去考虑问题的。

如果确实需要这个功能的话，那我可以在媒体库模式使用实时搜索，直连模式则需要用户主动发起搜索

**Comment by roccox** [comment]
我自己是觉得很好用，不麻烦的话重新打开吧，大不了加个开关让大家自己选嘛。谢谢

**Comment by gitbobobo** [comment]
最新测试版已添加

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布
