### ISSUE TITLE
mac 打开音流不播放会阻止电脑休眠

### ISSUE THREAD

**Issue by iamckun** [gitbobobo/StreamMusic#600]
能不能在暂停音乐的时候别强制电脑在线

**Comment by gitbobobo** [comment]
好的，之后改一下。

目前需要关掉播放页面来关掉屏幕常亮（沿用手机版逻辑）

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布

**Comment by yuhenghuang** [comment]
macOS更新到15.3之后似乎又有了这个问题.

在暂停播放和关闭窗口后,系统显示因为音频输出被使用而阻止休眠.

希望能在新版中解决.

配图

<img width="687" alt="Image" src="https://github.com/user-attachments/assets/90f45b07-24a5-41c1-8aff-608ba84c6c51" />

<img width="766" alt="Image" src="https://github.com/user-attachments/assets/2cb5e51a-21dd-4721-b9ee-f4bea4d17dc2" />

使用
```sh
pmset -g assertions | grep sleep
```
可以看到以下输出. 其中`pid 166(coreaudiod)`应该就是音流在使用
```
   pid 94(powerd): [0x00001f6c00018fb3] 00:52:16 PreventUserIdleSystemSleep named: "Powerd - Prevent sleep while display is on"  
   pid 166(coreaudiod): [0x00002b5a00019259] 00:01:22 PreventUserIdleSystemSleep named: "com.apple.audio.AppleUSBAudioEngine:EDIFIER:EDIFIER M230:EDI00000X04:2.context.preventuseridlesleep"
```
