### ISSUE TITLE
1.3.2最新的beta版本 发热严重

### ISSUE THREAD

**Issue by TMTBO** [gitbobobo/StreamMusic#601]
最近更新了1.3.2最新的beta版本, 离线播放音乐的时候严重发热. 只播放一首音乐, 手机就烫手.
设备: iphone15 pro

**Comment by gitbobobo** [comment]
嗯，我也遇到了，还在查原因，遇到这种情况可以先杀掉重进。

**Comment by gitbobobo** [comment]
build 96 已修复，可以再试试

**Comment by TMTBO** [comment]
> build 96 已修复，可以再试试

升级完, 连接不上服务(navidrome(0.52.5))了, 本地下载的也无法播放, 点击提示"正在连接服务器"

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布

**Comment by TMTBO** [comment]
之前测试版本正常了, 用了两天, 正式版本发热问题依然存在.
![IMG_9730](https://github.com/user-attachments/assets/ea22e25d-8141-4b2a-b5ed-52114ce8d34a)
![IMG_9731](https://github.com/user-attachments/assets/26ac779c-5655-4a75-b65c-30b6b2d140ca)

**Comment by TMTBO** [comment]
之前测试版本正常了, 用了两天, 正式版本发热问题依然存在.
![IMG_9730](https://github.com/user-attachments/assets/ea22e25d-8141-4b2a-b5ed-52114ce8d34a)
![IMG_9731](https://github.com/user-attachments/assets/26ac779c-5655-4a75-b65c-30b6b2d140ca)

**Comment by TMTBO** [comment]
找到问题了, 自定义api中获取封面接口失败, 导致的, 删除就可以了
