### ISSUE TITLE
音乐名称中存在多个-可能无法播放

### ISSUE THREAD

**Issue by mufengyian** [gitbobobo/StreamMusic#606]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
音乐名称中存在多个-符号可能无法播放

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
例如-遠い空へ-.mp3、1-800-273-8255.mp3这种命名的歌曲，在navidrome中正常播放，在音流中就无法播放。

**Expected behavior (期望行为)**
修复bug
**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
安卓14，小米13
**Music Server Type (音乐服务器类型)**
e.g. emby 4.17.
Navidrome
- [ ] Direct Mode（直连模式）
- [ ] Library Mode（媒体库模式）
媒体库模式
**Additional context (额外信息)**
ERROR ⛔ [play_err]播放异常：Failed to recognize file format.
  ERROR 19:17:35.095 (+0:22:45.898823)
  ERROR ⛔ 封面图片解析失败: Failed to open image file

**Comment by gitbobobo** [comment]
问题肯定和文件名无关，我的曲库中大部分都是以`歌手 - 歌名`命名的歌曲，没有无法播放的情况
