### ISSUE TITLE
Reverse album sort order within a year

### ISSUE THREAD

**Issue by Insprill** [gitbobobo/StreamMusic#607]
Related to #476, since albums are sorted from newest to oldest and then ascending alphabetically, dated albums read backward when scrolling through the list. Feishin sorts are descending by default, while Navidrome sorts ascend, but from oldest to newest, so everything is still in chronological order

For example, scrolling through my library currently looks like this:
- 2024/03/22...
- 2024/04/21...
- 2024/05/12...
- 2023/02/01...
- 2023/03/02...
- 2023/04/09...

This makes it annoying to find an album from a specific date since the years and dates within a year are sorted in two different directions.

**Comment by gitbobobo** [comment]
1.3.3 updated
