### ISSUE TITLE
播放未转码高音质flac文件闪退问题

### ISSUE THREAD

**Issue by kaige1116** [gitbobobo/StreamMusic#608]
手机系统:鸿蒙
服务器前端:navidrome
发现问题:播放第一个文件有时候正常，个别直接闪退。切换歌曲时95%概率闪退。播放文件为flac 4000+k。
navidrome转码320kpbs后正常，未出现闪退情况。

**Comment by gitbobobo** [comment]
连续点击版本号，在开发者页面中启用 AudioTrack 即可修复

**Comment by kaige1116** [comment]
大佬太牛了！成功解决
