### ISSUE TITLE
移动网络后台播放转码音频时候，间歇性会停止播放，音乐无长显示

### ISSUE THREAD

**Issue by paysenyu** [gitbobobo/StreamMusic#609]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**

1. 在线音乐品质-移动网络下播放音质-192K
2. 后台播放时会卡住 （锁屏界面切歌也会） 
3. 打开app 前台播放时几乎不会出现
4. 出现问题后切换下一首再切换回来刚才卡住的音乐也无法播放

**Expected behavior (期望行为)**

**Screenshots (截图)**

![IMG_0619](https://github.com/user-attachments/assets/c6545df8-ebe9-4bad-b956-715d9eb5495d)

**Platform and Device Info (操作系统及设备信息)**
 - OS: 18.1beta6

**Music Server Type (音乐服务器类型)**
e.g. emby 

- [ ] Direct Mode（直连模式）

**Comment by gitbobobo** [comment]
文件格式是什么？清除缓存后是否可以播放

**Comment by paysenyu** [comment]
> 文件格式是什么？清除缓存后是否可以播放

99%的音乐是 flac格式， 不开移动端转码目前就未出现

刚刚清理了缓存，再次尝试还是不行，关闭移动端转码会好很多。

iOS端不知道如何获取日志

**Comment by paysenyu** [comment]
刚看到个设置，我把转码文件从aac 变成mp3 再观察一段时间试试

**Comment by gitbobobo** [comment]
是最新版本了吗？目前我没遇到过无法播放的问题

**Comment by paysenyu** [comment]
已换大容量设备全部音乐离线下载，暂时不会重现条件了
