### ISSUE TITLE
歌词直接写入音乐标签时无法正确读取

### ISSUE THREAD

**Issue by Gabriel-six** [gitbobobo/StreamMusic#617]
封面、歌词等信息直接保存至音乐的标签时，音流无法正确读取歌词，封面可以读取；
但是歌词单独保存成.lrc文件时读取正常。
望改进，个人感觉歌词单独保存为文件会使目录稍显杂乱。
感谢。

**Comment by gitbobobo** [comment]
音乐标签的读取是服务端做的事情，音流只是请求服务端返回的信息。

可以从此页面看你的服务端对内置歌词的支持情况 https://music.aqzscn.cn/docs/services

**Comment by Gabriel-six** [comment]
> 音乐标签的读取是服务端做的事情，音流只是请求服务端返回的信息。
> 
> 可以从此页面看你的服务端对内置歌词的支持情况 https://music.aqzscn.cn/docs/services

感谢解答，我的服务端使用的是audio station，确实是不支持内嵌歌词。
