### ISSUE TITLE
定时停止 不符合预期

### ISSUE THREAD

**Issue by ljcbaby** [gitbobobo/StreamMusic#618]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
倒计时结束后播完当前歌曲不会停止。

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
1. 设置 定时停止 勾选 播完当前歌曲后停止

**Expected behavior (期望行为)**
倒计时结束后播完当前歌曲停止。

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 - OS: Android
 - Version 1.3.2

**Additional context (额外信息)**
可否增加自定义分钟，方便测试以及自由调整。

**Comment by gitbobobo** [comment]
测试版已修复

**Comment by gitbobobo** [comment]
1.3.3已修复
