### ISSUE TITLE
华为平板播放母带，切换到下一首闪退，目前测试必现

### ISSUE THREAD

**Issue by 240722795** [gitbobobo/StreamMusic#619]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**

**Expected behavior (期望行为)**

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 - OS: [e.g. iOS]鸿蒙4.0

**Music Server Type (音乐服务器类型)**
navidrome  0.53.3

- [ ] Direct Mode（直连模式）
- [x] Library Mode（媒体库模式）

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
https://github.com/gitbobobo/StreamMusic/issues/608
