### ISSUE TITLE
MacOS客户端没有内容

### ISSUE THREAD

**Issue by cosmos-lou** [gitbobobo/StreamMusic#621]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
macOS sequoia 15.0.1 打开客户端界面没有内容，只有左上角的全屏、最小化、关闭按钮

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
无法复现，尝试了退出重新打开客户端、卸载重新安装、重启电脑，都不行
现在打开客户端就是没内容的状态

**Expected behavior (期望行为)**
解决问题

**Screenshots (截图)**
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/cde0e776-0576-49ba-8921-1e9b31589804">
**Platform and Device Info (操作系统及设备信息)**
![WX20241015-160034@2x](https://github.com/user-attachments/assets/9d3d5b31-cc24-4053-9769-d872e201115e)

**Music Server Type (音乐服务器类型)**
navidorme 0.53.3 直连模式

**Additional context (额外信息)**
无

**Comment by gitbobobo** [comment]
确认一下是不是最新版本，这个问题解决过的

**Comment by cosmos-lou** [comment]
> 确认一下是不是最新版本，这个问题解决过的

重装最新版，已解决，感谢！
