### ISSUE TITLE
不能通过邮箱恢复购买

### ISSUE THREAD

**Issue by yingwenbo** [gitbobobo/StreamMusic#622]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
1. 进入『通过邮箱恢复购买』
2. 填入邮箱
3. 点击发送验证码
4. 提升『签名信息错误』

**Platform and Device Info (操作系统及设备信息)**
 - OS: ipadOS
 - Version 18.0.1

**Comment by gitbobobo** [comment]
https://music.aqzscn.cn/docs/problems#%E6%81%A2%E5%A4%8D%E8%B4%AD%E4%B9%B0%E6%97%B6%E6%8F%90%E7%A4%BA%E7%AD%BE%E5%90%8D%E4%BF%A1%E6%81%AF%E9%94%99%E8%AF%AF
