### ISSUE TITLE
使用Emby连接时，会一直在Emby上添加账号验证

### ISSUE THREAD

**Issue by byte170202** [gitbobobo/StreamMusic#63]
我的服务端是Emby，有一个音乐媒体库，在使用的时候，会持续往Emby的仪表盘添加已验证信息，这块是因为扫库还是什么原因，是否有可能进行优化。

**Comment by gitbobobo** [comment]
你是说这种信息？
<img width="384" alt="image" src="https://github.com/gitbobobo/StreamMusic/assets/100769410/5c5a5273-7199-447b-9d4c-9223a100c710">

**Comment by code170202** [comment]
> 你是说这种信息？ <img alt="image" width="384" src="https://user-images.githubusercontent.com/100769410/278789406-5c5a5273-7199-447b-9d4c-9223a100c710.png">

是的，会一直加很多很多条，而且实际播放音乐的时候，不会记录播放了什么音乐
