### ISSUE TITLE
不能添加主备用线路

### ISSUE THREAD

**Issue by Lens-lzy** [gitbobobo/StreamMusic#633]
使用环境：iPhone 15 Pro

下载途径：Appstore国区

添加线路的button是灰色的，无法添加。

是否与购买会员有关？但是我看到购买会员也是灰色的！

另外，是否有相关交流群？没有找到！

**Comment by gitbobobo** [comment]
这个是会员功能，杀掉重进就可以购买/恢复购买了。

建议多用几天，基础功能满意之后再考虑付费的事情。

QQ群：851038883
