### ISSUE TITLE
[BUG] 安卓平台无法显示歌词

### ISSUE THREAD

**Issue by CallMe-86** [gitbobobo/StreamMusic#635]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
安卓平台无法显示歌词（悬浮窗）

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
具体设置见截图

**Expected behavior (期望行为)**
通过悬浮窗显示歌词

**Screenshots (截图)**
![app](https://github.com/user-attachments/assets/df4f2a26-6676-40cb-85cd-f3abc83604e4)

**Platform and Device Info (操作系统及设备信息)**
 - OS: 安卓14 小米澎湃os
 - Browser
 - Version 1.3.2

**Music Server Type (音乐服务器类型)**
navidrome（与音乐服务器应该无关）

- [ ] Direct Mode（直连模式）
- [x] Library Mode（媒体库模式）

**Additional context (额外信息)**
一开始用的时候还是可以显示歌词的，后来好像把这个功能关闭了，用了一段时间想再打开这个功能，发现开启不了了。

**Comment by gitbobobo** [comment]
这个是132版本的bug

**Comment by gitbobobo** [comment]
1.3.3已修复
