### ISSUE TITLE
接入Subsonic服务，有的歌曲专辑封面显示错误

### ISSUE THREAD

**Issue by hoyulicn** [gitbobobo/StreamMusic#638]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
1. 接入MUSIC TAG WEB建立的Subsonic服务，有些歌曲会显示错误的专辑封面。
2. 其他的Subsonic客户端如PC端的SONIXD接入此Subsonic服务并不会有此错误。
3. 用同一批音乐文件搭建Navidrome服务，音流在播放中也不会出现这种错误。

**Screenshots (截图)**
![IMG_1307](https://github.com/user-attachments/assets/429a20f6-3784-4f3d-8f51-f14112c63e1b)
![IMG_1308](https://github.com/user-attachments/assets/8ff0e2e1-75d0-4cb5-a773-92c487e3d645)

**Platform and Device Info (操作系统及设备信息)**
 - OS: IOS18.1

**Music Server Type (音乐服务器类型)**
Subsonic

**Comment by jianchen306** [comment]
安卓一样的问题，已经用回Navidrome。

**Comment by hoyulicn** [comment]
Win平台也一样，希望开发者能看到吧。

**Comment by gitbobobo** [comment]
最好能邮件提供一个测试账号

**Comment by hoyulicn** [comment]
> 最好能邮件提供一个测试账号

初学者不懂应该回复到哪个邮件，是streammusic@noreply.github.com吗？

**Comment by gitbobobo** [comment]
aqzscn@qq.com

**Comment by gitbobobo** [comment]
看了下其他软件，歌手图片同样是没有显示的。

歌曲封面确实有问题，下个版本修复

**Comment by gitbobobo** [comment]
1.3.3已更新
