### ISSUE TITLE
iOS 搜索键盘逻辑改进建议

### ISSUE THREAD

**Issue by Sen-Yao** [gitbobobo/StreamMusic#639]
# 环境

- iOS 18.0.1
- 音流 1.3.2

# 改进建议

在使用 iOS 端音流进行搜索时，若没有点击 iOS 键盘的“搜索”按钮确认搜索结果，而是直接点击弹出的歌曲右侧的“三个点”展开详情，会出现歌曲详情 UI 被 iOS 键盘遮挡的情况，如下图所示，歌曲“Only Love”下方的 UI 被键盘遮挡：

![image](https://github.com/user-attachments/assets/ed96f7f6-2671-4233-aaa9-776be8a080e7)

此时除了点击 iOS 键盘的“搜索”按钮之外，没有比较直观的方式收起 iOS 键盘。建议可以优化逻辑，在用户点击“三个点”展开详情时收起 iOS 键盘。

**Comment by gitbobobo** [comment]
1.3.3已更新，点击键盘外区域即可收起键盘
