### ISSUE TITLE
个性化主题设置问题

### ISSUE THREAD

**Issue by xiaowu911** [gitbobobo/StreamMusic#641]
自定义背景设置页面，只有模糊程度可以滑动设置，搜索框无法输入和搜索，显示的也都是专辑的图片。
是功能未完善？还是存在BUG？
顺带问一下，未来有考虑支持鸿蒙吗？

**Comment by gitbobobo** [comment]
中间是个预览卡片。

需要等鸿蒙+flutter的生态成熟一点才会支持。
