### ISSUE TITLE
iOS端移动网络下不能播放歌曲

### ISSUE THREAD

**Issue by hemind** [gitbobobo/StreamMusic#645]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
iOS端使用移动网络时不能播放歌曲

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
仅开移动网络时，iOS音流App点击任何歌曲不能播放。设置里已经打开了“允许移动网络传输歌曲”。
在同样的网络条件下，使用chrome浏览器连接服务器可以播放，说明移动网络连接服务器没问题。

**Expected behavior (期望行为)**

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**
 - OS:  iOS 16.1.1
 - Browser: chrome
 - Version: 音流v1.3.2

**Music Server Type (音乐服务器类型)**
Navidrome v0.53.1

- [ ] Direct Mode（直连模式）
- [ ] Library Mode（媒体库模式）

两种连接模式下都有同样问题

**Additional context (额外信息)**
一个有意思的点，我在WIFI和移动网络都打开的情况下，点击播放某首歌曲，歌曲开始播放，同时进度条也在加载。当歌曲进度条还未加载完成的时候，我关闭WIFI，这时进度停止加载，歌曲还在播放，过几秒后，进度条在移动网络下开始继续加载。进度条会一直加载到歌曲结束，当歌曲播放结束切换到下一首后，进度条不会加载了，也就是移动网络情况下仍不能播放。

总结一下：移动网络下点击新歌曲，不能启动歌曲的进度加载（缓存），但如果是已经在WIFI下启动了进度加载，关闭WIFI后，仅在移动网络下还是可以继续加载进度条的，直到歌曲结束。

**Comment by AndroidOL** [comment]
![Uploading a3999d1936dee0b307caeb47d06d0eee.jpeg…]()

**Comment by hemind** [comment]
> ![a3999d1936dee0b307caeb47d06d0eee](https://private-user-images.githubusercontent.com/3981579/383850297-d2fb48eb-2e67-4c51-8ba2-6273def5090d.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5OTM3NDcsIm5iZiI6MTczMDk5MzQ0NywicGF0aCI6Ii8zOTgxNTc5LzM4Mzg1MDI5Ny1kMmZiNDhlYi0yZTY3LTRjNTEtOGJhMi02MjczZGVmNTA5MGQuanBlZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA3VDE1MzA0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OGZlNWIxODE2YzdhMDJiZmVlNjU0NTA4MjdjNzg4ZTBkNWZlMjk1NGEwYjM2ZjYwOTljMWZhYzk1MTVkMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.g0eHWVEzbc1xT5lq1jCUtBJDuScTJFbfwC9AUy6Fh0M)

移动网络下我用的标准 192K

**Comment by gitbobobo** [comment]
看下是不是同一个问题 #663

**Comment by AndroidOL** [comment]
> 看下是不是同一个问题 #663

我是看见飞牛的群里有人说无法播放是音流的问题，能看见的我都解释了，飞牛这个系统官方基本不回答也不出声，事情没做好结果搞得音流里外不好看，明明不是软件问题。

所以我建议是尽快加一个提示，或者在后续版本更新中重点指出这个问题，他们做的东西一坨屎，可问题是屎能正常跑，音流掉屎坑里了。

**Comment by gitbobobo** [comment]
感谢感谢，可能音乐这块还是太小众了不够重视吧。

**Comment by hemind** [comment]
> 看下是不是同一个问题 #663

感谢，确实是这个问题，移动网络我换无损就能播放
