### ISSUE TITLE
车机端在登录界面没有选择TV版的选项

### ISSUE THREAD

**Issue by ing0928** [gitbobobo/StreamMusic#646]
车机端在登录界面不显示启用TV版的选项，使用手机端UI进入车机，字体显得特别小，不知道这个触发时机是什么，能不能用个开关用户主动控制或者支持用户设置字体大小。其实平板的界面排版没有问题，只不过系统字体太小了导致应用字体很小，能支持自定义最好了

**Comment by AngeCoo** [comment]
确实，我也再车机上重复登录几次，设置页面也仔细看了，没发现怎么切换到TV模式，不知道是不是隐藏在哪个地方了，常规模式字体很小，点选的按钮也很小，不能用方向盘切换上下一首，不过播放什么倒是都正常，但好像没有桌面小组件之类的

**Comment by gitbobobo** [comment]
如果能识别到当前运行在TV上，音流会自动切换为TV模式。

否则需要在首次登录时选择资料库的页面使用方向键来激活切换到TV模式的提示（1.3.2版本这个逻辑出了问题，可以先用旧版本验证）

在不新增额外的安装包的前提下，如果你有更好的方法来手动切换TV模式，也可以提一下。
