### ISSUE TITLE
邮箱格式报错

### ISSUE THREAD

**Issue by thankforcat** [gitbobobo/StreamMusic#648]
刚购买了，输入邮箱的时候不支持. 例如xxx.abc@gmail.com 会被提示格式错误
用xxx@gmail.com 格式就ok。

btw，开个网页支付功能多好🤣
谢谢开发这么好的软件

**Comment by gitbobobo** [comment]
格式错误不是因为.的问题，再找找看有没有其他特殊字符

**Comment by thankforcat** [comment]
> 格式错误不是因为.的问题，再找找看有没有其他特殊字符

我已经注册了, 不知道改怎么测试了.
