### ISSUE TITLE
有代理时，音乐无法播放

### ISSUE THREAD

**Issue by geekidentity** [gitbobobo/StreamMusic#65]
在这里配置代理后，歌曲列表等可以展示出来，但无法播放
![image](https://github.com/gitbobobo/StreamMusic/assets/23332528/4ece3c4e-a77f-4eda-8834-16e314331f19)

**Comment by gitbobobo** [comment]
这个问题短期内解决不了，如果服务器国内可以访问，建议在代理软件内把音流加到白名单
