### ISSUE TITLE
自定义API里获取封面是否可以添加文件路径的参数

### ISSUE THREAD

**Issue by cianyeah** [gitbobobo/StreamMusic#650]
服务端：Navidrome 0.52.5
WEB服务：nginx 1.22.1
手机端：Android 1.3.2

在使用自定义API时，已经实现了用nginx返回lrc歌词的功能，这里借助了请求参数path（文件路径），但在获取封面时不知道该怎样自定义返回。

在自定义API里可以填上封面接口地址，但下面同时有“加载专辑封面”、“加载歌手图片”两个选项，我该如何返回内容，直接返回图片还是json，如果直接返回图片，那下面为什么会有两个选项，专辑封面和歌手图片是两张不同的图片，而如果返回json的话，json格式应该是什么样的。

另外可不可以在请求封面接口地址时同时加上请求参数path（文件路径），就像获取歌词接口那样，因为我有自定义命名专辑封面和歌手图片的习惯，所以我想根据文件路径自定义返回，希望能添加这个功能。

最后非常感谢作者提供这么好用的NAS音乐APP

**Comment by gitbobobo** [comment]
1.3.3已更新
