### ISSUE TITLE
歌曲播放完后闪退

### ISSUE THREAD

**Issue by yanpf1997** [gitbobobo/StreamMusic#651]
https://github.com/user-attachments/assets/7e3c5e95-a760-4f1a-a1f3-3a20ecbc79b8

**Describe the bug (BUG 描述，多条问题请分别建立 issue)**

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**

**Expected behavior (期望行为)**

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**

**Music Server Type (音乐服务器类型)**
e.g. emby 4.17.

- [ ] Direct Mode（直连模式）
- [ ] Library Mode（媒体库模式）

**Additional context (额外信息)**

部分歌曲播放完后，切换到下一首时会闪退

**Comment by gitbobobo** [comment]
#608
