### ISSUE TITLE
1.3.2版本 miui无法打开桌面歌词

### ISSUE THREAD

**Issue by youyi0218** [gitbobobo/StreamMusic#657]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
桌面歌词无法打开

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
我已经打开设置中的音流 后台弹出页面权限 悬浮窗权限 锁屏显示权限 并把音流后台强制关闭后重新打开，但是桌面歌词依然无法打开
**Expected behavior (期望行为)**

**Screenshots (截图)**
![Screenshot_2024-11-03-16-55-27-644_cn aqzscn stre](https://github.com/user-attachments/assets/522d07bd-0248-4a7e-86e0-81ed650cfdef)
![Screenshot_2024-11-03-16-55-42-234_com miui secur](https://github.com/user-attachments/assets/f46e7089-597a-4df2-8fc4-8652ab6d6de2)

**Platform and Device Info (操作系统及设备信息)**
Xiaomi 12s Ultra miui14.0.15 音流1.3.2

**Music Server Type (音乐服务器类型)**
Navidrome
Library Mode（媒体库模式）

**Additional context (额外信息)**
无

**Comment by gitbobobo** [comment]
与 https://github.com/gitbobobo/StreamMusic/issues/615 问题相同，下个版本修复
