### ISSUE TITLE
重启程序才能获取新歌曲

### ISSUE THREAD

**Issue by thankforcat** [gitbobobo/StreamMusic#659]
测试 Mac intel芯片

如果在打开StreamMusic后, Navidrome添加的歌曲并不会同步到 StreamMusic, 按刷新没用, 只有重新启动程序. 可能是程序只有运行时候才会遍历.

iOS 也能复现.

**Comment by gitbobobo** [comment]
数据同步（增量）只会在应用启动后自动触发，也可以手动点击资料库 - 立即同步来同步（全量更新）

曲库较大建议使用直连模式
