### ISSUE TITLE
希望增加播放时提前缓存接下来即将播放的几首歌功能

### ISSUE THREAD

**Issue by BruceSuen720** [gitbobobo/StreamMusic#66]
希望新增plexamp一样的类似功能，在播放歌曲时，自动提前缓存接下来即将播放的歌曲，提前缓存的数量可以自行设置，因为外网播放时有时候免不了服务器网络不好或者当前手机信号不好，例如坐高铁时候手机信号就不是很稳定，如果实现这个功能就可以很好的解决缓冲卡顿的情况。
plexamp的无感切换歌曲功能也十分好用，上一曲结束时，提前播放下一曲渐入，给人一种音乐不间断，连续播放的优雅感觉

**Comment by gitbobobo** [comment]
#58 和这个问题重复了
