### ISSUE TITLE
飞牛应用中默认安装的Navidrome不支持转码，导致移动网络下无法播放

### ISSUE THREAD

**Issue by AndroidOL** [gitbobobo/StreamMusic#663]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
飞牛未预装ffmpeg导致移动网络（音质未选择无损时无法正常播放），为避免被认为是音流问题，建议提供一个说明或主动尝试关闭转码功能。

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
切换移动网络就无法播放。

**Expected behavior (期望行为)**
自动尝试不请求转码，一般内网穿透至少500Kbps带宽是可以提供的。

**Screenshots (截图)**
![6579cc74e85ab3cf317bdf40b856569d](https://github.com/user-attachments/assets/1e0aaaa8-c73f-4c53-a516-c5a72e6e5421)

**Platform and Device Info (操作系统及设备信息)**
 - OS: iOS 18.2b2
 - Browser: N/A
 - Version: 1.3.2

**Music Server Type (音乐服务器类型)**
Navidrome

- [ ] Direct Mode（直连模式）
- [x] Library Mode（媒体库模式）

**Additional context (额外信息)**
对于开发者：
很多人遇到这个问题，自己找原因不适用于新手用户，建议增加简单的引导。

对于飞牛的用户：
apt install ffmpeg ffmpeg-doc

FFmpegPath= "/usr/bin/ffmpeg"
TranscodingCacheSize = "500MB"

**Comment by gitbobobo** [comment]
没用过飞牛，但我认为这个不属于音流的问题。

docker 安装的一般自带ffmpeg，如果是类似群晖套件那种形式的，我觉得套件作者应该一并添加一下ffmpeg的支持，毕竟音乐转码我个人认为是个刚需。

之后我在文档里提一下吧，软件里不太好做这样的引导。

**Comment by AndroidOL** [comment]
> 没用过飞牛，但我认为这个不属于音流的问题。
> 
> docker 安装的一般自带ffmpeg，如果是类似群晖套件那种形式的，我觉得套件作者应该一并添加一下ffmpeg的支持，毕竟音乐转码我个人认为是个刚需。
> 
> 之后我在文档里提一下吧，软件里不太好做这样的引导。

提了也没用，飞牛官方没做引导，和软件没任何问题，只是我认为可以对这个情况增加一个说明，或者在无法播放是弹出一个提示，引导用户禁用转码，特别是wifi成功播放，移动网络播放出错时

**Comment by AndroidOL** [comment]
> 没用过飞牛，但我认为这个不属于音流的问题。
> 
> docker 安装的一般自带ffmpeg，如果是类似群晖套件那种形式的，我觉得套件作者应该一并添加一下ffmpeg的支持，毕竟音乐转码我个人认为是个刚需。
> 
> 之后我在文档里提一下吧，软件里不太好做这样的引导。

为啥转码是刚需，都用1mbps的内网穿透么？那我宁可花点钱加个本地缓存。

**Comment by AndroidOL** [comment]
> 没用过飞牛，但我认为这个不属于音流的问题。
> 
> docker 安装的一般自带ffmpeg，如果是类似群晖套件那种形式的，我觉得套件作者应该一并添加一下ffmpeg的支持，毕竟音乐转码我个人认为是个刚需。
> 
> 之后我在文档里提一下吧，软件里不太好做这样的引导。

issue我是提了，优化不优化我也不在乎，套件作者是飞牛，他们保证的是Navidrome能访问，能播放，而不是音流能正常用，被那些人认作是音流bug你不在乎那也没问题。

**Comment by gitbobobo** [comment]
每个人需求不一样嘛，像我一个月流量才20G，还没有公网只能用内网穿透，肯定想着要节约着用了，毕竟库里存的都是无损。

这个问题确实是最近收到的反馈多一点，但无法播放的原因很多，软件这里暂时没办法判断。

暂时就先这样吧，我在官网文档里提一下，能不能看到全凭缘分了。

**Comment by shen-lan** [comment]
这个日志在哪个界面?
