### ISSUE TITLE
Windows 音乐播放界面音量条点开之后无法退出

### ISSUE THREAD

**Issue by Baiqibushitouxiang** [gitbobobo/StreamMusic#664]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**
Windows 音乐播放界面音量条点开之后无法退出并且点击之后无论鼠标在哪里音量条都是跟随变化的状态

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**
1.播放某个音乐
2.点击音量条

**Expected behavior (期望行为)**
点击音量后自动退出音乐音量条，并且点击之后，只有鼠标指针在音量条上时音量条才会跟随移动

**Screenshots (截图)**
![issue](https://github.com/user-attachments/assets/e46537dc-0825-4292-9fb5-9a0f83dfe6d7)
![issue2](https://github.com/user-attachments/assets/9a9e9697-e6ca-46c1-b0b3-37b823ee33dd)

**Platform and Device Info (操作系统及设备信息)**
 - OS: [Windows 11 23h2]
 - Version [1.3.2.6]

**Music Server Type (音乐服务器类型)**
Navidrome

- [ √] Direct Mode（直连模式）
- [ ] Library Mode（媒体库模式）

**Comment by gitbobobo** [comment]
我这里没有复现
