### ISSUE TITLE
navidrome，本地歌曲删除后，音流并没有更新列表

### ISSUE THREAD

**Issue by Fiend-D** [gitbobobo/StreamMusic#678]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**

**Expected behavior (期望行为)**

**Screenshots (截图)**

**Platform and Device Info (操作系统及设备信息)**

**Music Server Type (音乐服务器类型)**
e.g. emby 4.17.

- [ ] Direct Mode（直连模式）
- [ ] Library Mode（媒体库模式）

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
若使用媒体库模式需要手动同步歌曲数据

**Comment by luojim-cn** [comment]
删除navidrome.db后重新启动。
