### ISSUE TITLE
当音乐数量超过1千时，序号显示为 1.0k

### ISSUE THREAD

**Issue by soxft** [gitbobobo/StreamMusic#679]
**Describe the bug (BUG 描述，多条问题请分别建立 issue)**

RT

**To Reproduce (复现步骤，复现问题是处理问题的必要条件)**

如图 
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/12454dcf-8f43-48c9-9c3f-b4ac6986a7bd">

**Expected behavior (期望行为)**

我认为 音乐列表不应当使用 简写形式 (xxkK  xxM), 此种格式多用于数据统计

**Screenshots (截图)**
<img width="1112" alt="image" src="https://github.com/user-attachments/assets/cafaf390-feb6-4a85-9ffe-2affc45a4992">

**Platform and Device Info (操作系统及设备信息)**
MacOs 1.3.2 build 97

**Music Server Type (音乐服务器类型)**
e.g.jellyfin

- [x ] Direct Mode（直连模式）
- [ ] Library Mode（媒体库模式）

**Additional context (额外信息)**

**Comment by gitbobobo** [comment]
空间所限，若不简写要么数字被遮挡要么排版混乱，这是我觉得目前最好的选择了

**Comment by soxft** [comment]
以这个作为序号，我不认为是一个合适的解决方案,
完全可以模仿 网易云音乐的模式， 为第一列留下固定的 width, 所有数字 右对齐

**Comment by soxft** [comment]
<img width="206" alt="image" src="https://github.com/user-attachments/assets/625923cd-8f90-4df7-aafc-c2daef962e3b">
