### ISSUE TITLE
华为手机随机播放下一曲闪退

### ISSUE THREAD

**Issue by chowy729** [gitbobobo/StreamMusic#682]
播放时，随机播放下一曲直接闪退。华为鸿蒙4.2

**Comment by gitbobobo** [comment]
https://music.aqzscn.cn/docs/problems#%E5%AE%89%E5%8D%93%E6%92%AD%E6%94%BE%E9%AB%98%E7%A0%81%E7%8E%87%E6%AD%8C%E6%9B%B2%E9%97%AA%E9%80%80
