### ISSUE TITLE
【功能建议】随机播放的一点建议

### ISSUE THREAD

**Issue by xiaowu911** [gitbobobo/StreamMusic#683]
<img width="980" alt="image" src="https://github.com/user-attachments/assets/a718460f-47ca-4d1c-a48a-7045db081de4">

播放时设置了随机播放，切换其他专辑或者文件夹，点击全部播放时，又会切换到列表循环。
建议点击全部播放时，保持原来的循环模式，或者新增一个随机播放全部的按钮。

**Comment by gitbobobo** [comment]
参考官网文档https://music.aqzscn.cn/docs/guides/play
