### ISSUE TITLE
miui14，最新版还是打不开桌面歌词

### ISSUE THREAD

**Issue by youyi0218** [gitbobobo/StreamMusic#685]
已更新1.3.3版本，并且打开所有相关权限，还是没发开桌面歌词（
小米12su，miui14.0.15
![Screenshot_2024-11-17-22-29-27-470_com miui securitycenter](https://github.com/user-attachments/assets/651d9588-61c0-434c-a3b0-0ae067ed788f)
![Screenshot_2024-11-17-22-29-22-346_cn aqzscn stream_music](https://github.com/user-attachments/assets/ceec2019-2a27-49ce-8fae-5c9bb8f43da5)
![Screenshot_2024-11-17-22-29-05-353_com miui securitycenter](https://github.com/user-attachments/assets/befc2329-5c83-4164-b72e-31072d1d15ca)

**Comment by gitbobobo** [comment]
灰色是会员功能
