### ISSUE TITLE
听本地音乐的歌会走流量

### ISSUE THREAD

**Issue by ChinaJiuXiang** [gitbobobo/StreamMusic#69]
打开边听边存功能，听本地音乐的歌时会走流量

**Comment by ChinaJiuXiang** [comment]
1.1.7版本，miui14.0.29

**Comment by gitbobobo** [comment]
只是流量监控会显示有流量，实际不消耗流量，你可以关掉网络连接试试

**Comment by coolguy001tv** [comment]
不对，的确会走流量。
> 只是流量监控会显示有流量，实际不消耗流量，你可以关掉网络连接试试

先说我这里的情况：
跟楼主比较像，我也是1.1.7 和 MIUI14.0.7。
我是把我的音乐库全部下载到本地（所有音乐前面都有绿色的小勾勾），关闭了“允许移动网络传输歌曲”，然后我的服务器是使用主线路192.168.101.200:4533和备用线路ipv6的域名(xxx.v6.army:4533)。这周分别测试了用wireguard vpn连接后 播放 和 不使用VPN直接域名方式播放，然后和平时的流量消耗对比，根据电信的详单能够看到的确是有流量问题。
我平时步行+骑车上班，大约从8:25-8:30左右开始听音乐，大约听20-30分钟，然后9:10-20左右到公司会连上WIFI，路上除了听歌主要会浏览知乎一类的偏文字的内容（不看视频）。
下图的图一是11.20，使用vpn后的情况，能看到上班路上大约有100M+的流量；而图二的11.21消耗了160M+。
作为对比的是10.12（还没有使用过音流）大约是40M+，和同时作为对比的11.23也是没有开音流，也是40M+。
![image](https://github.com/gitbobobo/StreamMusic/assets/936825/4dea563e-32f1-4cb2-8510-79fa2f9c26f3)
![image](https://github.com/gitbobobo/StreamMusic/assets/936825/c729df7c-8c62-4677-8650-8fd5e5997a5a)
![image](https://github.com/gitbobobo/StreamMusic/assets/936825/eb00fe20-df40-4b4d-8fa8-2466c7315393)
![image](https://github.com/gitbobobo/StreamMusic/assets/936825/2621dbf8-3473-48ae-89a5-69fb26682ccc)
