### ISSUE TITLE
隐藏文件夹入口能不能改成设置选项，让用户选择是否隐藏

### ISSUE THREAD

**Issue by xiaowu911** [gitbobobo/StreamMusic#693]
### Suggestion(建议)

目前在用的服务器有Jellyfin和Navidrome，设置直连模式时，文件夹入口均隐藏了，只能关闭直连模式。
能不能改成设置选项，让用户选择是否隐藏？

**Comment by gitbobobo** [comment]
没有文件夹的服务只能显示获取过的歌曲的文件结构，一是显示数据不全，使用意义不大，二是会导致用户误以为是音流的bug，导致不断有人来反馈。

个人觉得没有必要为一个有缺陷的功能添加一个开关
