### ISSUE TITLE
Android 1.31 1.32更新1.33时，提示已存在更高版本

### ISSUE THREAD

**Issue by Yeashin-Fu** [gitbobobo/StreamMusic#695]
### Steps to reproduce(重现步骤)

![Screenshot_20241119_092603_com android packageinstaller](https://github.com/user-attachments/assets/6d5f33dc-e18c-4afe-8c23-26e2b04810f1)

### Expected results(预期结果)

升级成功

### Actual results(实际结果)

提示已有更高版本

### Server Type(服务器类型)

Navidrome

### Server Version(服务器版本)

0

### Client Version(客户端版本)

1.31 1.32

### Operating System(操作系统)

Android

### Connection Type(连接类型)

Library Mode(媒体库模式)

### Additional Information(附加信息)

1

**Comment by gitbobobo** [comment]
你可能下载到了缓存版本，可以过段时间重新下载试试，这个问题已经处理过了

**Comment by Yeashin-Fu** [comment]
是的，下午再次下载更新，已经正常了
