### ISSUE TITLE
涉及账号密码的问题，建议公开多余的访问地址用途。或者干脆离线设计，付款可以用永久注册码的方式。

### ISSUE THREAD

**Issue by 1148270327** [gitbobobo/StreamMusic#696]
### Suggestion(建议)

目前可以拦截到除了自己的nas地址外，还会访问aqzscn.cn的域名流量。
<img width="323" alt="image" src="https://github.com/user-attachments/assets/e505a197-2e0a-4290-90ee-a8321e7ad69e">

**Comment by gitbobobo** [comment]
oss用来获取最新版本信息

pay用来查询会员价格及验证会员身份

离线设计需要很强的防盗版措施，这点我做不到。

你既然已经抓包了，就仔细看看请求内容，我可以保证除了订单号和邮箱，别的信息是不会上传到服务器的。

https://music.aqzscn.cn/docs/problems#%E5%AE%89%E5%85%A8%E9%97%AE%E9%A2%98

**Comment by 1148270327** [comment]
> oss用来获取最新版本信息
> 
> pay用来查询会员价格及验证会员身份
> 
> 离线设计需要很强的防盗版措施，这点我做不到。
> 
> 你既然已经抓包了，就仔细看看请求内容，我可以保证除了订单号和邮箱，别的信息是不会上传到服务器的。
> 
> https://music.aqzscn.cn/docs/problems#%E5%AE%89%E5%85%A8%E9%97%AE%E9%A2%98

没有刻意抓包，是mac系统内的底层网络管理防火墙可以看到。小众产品、价格也不高，破解分发的人应该很少很少。
