### ISSUE TITLE
Jump to artist by letter

### ISSUE THREAD

**Issue by logname** [gitbobobo/StreamMusic#698]
### Suggestion(建议)

I searched for a week before I found your app by coincidence. Excellent work! The only thing I am struggling with is finding a specific artist using CarPlay. Scrolling through many pages while driving is risky, so it would be great to have the capability to touch the first letter of the artist name and jump to that section of the artist list, similar to how it is possible to jump to the first letter of a contact I don't know if Apple allows this. I noticed that you have the beginning of this capability in the Folder view.

Also, I would like to suggest you use CarPlay simulator and post screenshots of your CarPlay UI in the Appstore (if Apple allows this). I was frustrated that nobody shows what their app looks like in CarPlay, and ended up just downloading a bunch to try in the CarPlay Simulator before making a decision. Your app is that best I found for use with Synology Audio Station, and very affordable for the added features. Thank you again!

### Usage scenario or reason(使用场景或原因)

<img width="1119" alt="Carplay contacts obfuscated" src="https://github.com/user-attachments/assets/f2857aab-e42c-4984-a417-b41458aa3a22">
<img width="1130" alt="CarPlay contacts search by letter" src="https://github.com/user-attachments/assets/8c1122b3-b0a2-4d4d-b5f5-8a9213703958">
<img width="1121" alt="Steam Music folder list" src="https://github.com/user-attachments/assets/01b4c281-7c59-4f86-9b9f-cc74a8212198">
<img width="1120" alt="Stream Music search by letter" src="https://github.com/user-attachments/assets/f3a1adb7-495d-454a-a62b-d443183ceb65">

**Comment by gitbobobo** [comment]
yes，i can add

**Comment by logname** [comment]
@gitbobobo Thank you so much for adding this!  Eagerly waiting for Apple to publish version 1.3.4 to the app store.
