### ISSUE TITLE
希望新增可以删除源文件的能力

### ISSUE THREAD

**Issue by Canight** [gitbobobo/StreamMusic#699]
### Suggestion(建议)

有时候库内同一首歌有多个音源，对比进行保留的时候希望能删除到源文件

**Comment by gitbobobo** [comment]
可以部署多个服务端，需要删除文件时切换到支持文件删除接口的服务端，正常听歌专门用一个服务端

**Comment by Canight** [comment]
> 可以部署多个服务端，需要删除文件时切换到支持文件删除接口的服务端，正常听歌专门用一个服务端

就是连的 station 删除没生效
