### ISSUE TITLE
Android客户端无法连接使用HTTPS协议的Navidrome音乐服务

### ISSUE THREAD

**Issue by garylavayou** [gitbobobo/StreamMusic#707]
### Steps to reproduce(重现步骤)

1. 打开“设置”页面；
2. 选择“/音乐库/资料库管理/连接线路”；
3. 将连接线路配置为使用HTTPS访问的地址。
4. 返回“设置”页面并选择“更多/网络配置/检查连接”。

### Expected results(预期结果)

检查连接提示“连接成功”。

### Actual results(实际结果)

检查连接提示“连接失败”。

### Server Type(服务器类型)

Navidrome

### Server Version(服务器版本)

0.53.3

### Client Version(客户端版本)

1.3.3

### Operating System(操作系统)

Android

### Connection Type(连接类型)

Library Mode(媒体库模式)

### Additional Information(附加信息)

已知在Android设备上：
- 使用自签名证书部署HTTPS服务，设备上已导入签发该证书的根证书；
- 使用统一服务的HTTP地址端口可正常通过测试和访问媒体库；
- 使用浏览器可通过同一HTTPS域名端口访问Navidrome音乐服务。

**Comment by qq77522980** [comment]
这个严格说来不算是app的bug，因为这涉及到证书问题。自签名证书在android设备上就是会有各种问题，我刚开始也遇到过，后来换成正常签署的证书就正常了。

**Comment by garylavayou** [comment]
> 这个严格说来不算是app的bug，因为这涉及到证书问题。自签名证书在android设备上就是会有各种问题，我刚开始也遇到过，后来换成正常签署的证书就正常了。

这是系统限制吗，因为我用端edge浏览器访问服务是正常的。

**Comment by gitbobobo** [comment]
目前不支持自签名证书
