### ISSUE TITLE
使用音流客户端播放时不能配合Emby的last.fm插件记录下播放记录

### ISSUE THREAD

**Issue by Yuk-0v0** [gitbobobo/StreamMusic#713]
### Steps to reproduce(重现步骤)

使用音流iOS和win客户端听歌

### Expected results(预期结果)

跟使用Emby网页版一样，能在Last.fm留下播放记录

### Actual results(实际结果)

Emby网页版播放音乐能正常在Last.fm留下播放记录
但使用音流客户端就只会显示状态，但播放完毕后不会留下播放记录
![image](https://github.com/user-attachments/assets/9cd6df2d-c59a-45d1-a3d4-aed28ee7f669)

### Server Type(服务器类型)

Emby

### Server Version(服务器版本)

4.8.10.0

### Client Version(客户端版本)

V1.3.3（2024-11-17）

### Operating System(操作系统)

iOS, Windows

### Connection Type(连接类型)

Library Mode(媒体库模式)

### Additional Information(附加信息)

我稍微分析了下emby日志
以下是网页端能正常记录的日志
![image](https://github.com/user-attachments/assets/469b241d-c6b8-4968-afe9-c684393bcd90)
以下是使用音流客户端不能正常记录的日志
![image](https://github.com/user-attachments/assets/7bf5d8b3-88bd-47e2-85c4-cd5732055e4d)

两者都是处于听完一首歌后切换到下一首的状态log
初步判断是缺少了SessionManager的Playback stopped相关状态，导致没能触发Last.fm插件记录

如需更多日志，请和我说

**Comment by gitbobobo** [comment]
好的，应该就是这个问题，我没有安装lastfm这个插件，以为上报播放进度就够了。。。

**Comment by LINKlang** [comment]
![image](https://github.com/user-attachments/assets/5267726d-d8a4-495e-86b5-46ee96a2f1a8)
应该是这个，因为我也有一样问题

**Comment by Yuk-0v0** [comment]
> 好的，应该就是这个问题，我没有安装lastfm这个插件，以为上报播放进度就够了……这个插件直接在emby里可以搜到吗

可以的，在元数据那一类

**Comment by gitbobobo** [comment]
测试版已修复

**Comment by Yuk-0v0** [comment]
> 测试版已修复

感谢付出，测试已修复

**Comment by yiyule10** [comment]
> 测试版已修复

安卓端 音流 V1.3.7（2025-04-28），后端emby 4.8.11.0，Library Mode(媒体库模式)。emby安卓端播放可正常在last.fm记录。音流 播放音乐，emby控制台可以看到正在播放音乐，但是last.fm并没有记录。音乐为生成的strm文件。
