### ISSUE TITLE
Emby转码后无法正常加载音频

### ISSUE THREAD

**Issue by LINKlang** [gitbobobo/StreamMusic#714]
### Steps to reproduce(重现步骤)

1. 开启转码
2. 播放音乐
3. 出现问题

### Expected results(预期结果)

服务端转换完后，音流客户端正常加载

### Actual results(实际结果)

emby日志提示转码，然后音流客户端卡在0：00总时长

### Server Type(服务器类型)

Emby

### Server Version(服务器版本)

4.8.10.0

### Client Version(客户端版本)

1.3.3

### Operating System(操作系统)

Android, iOS, Windows

### Connection Type(连接类型)

Library Mode(媒体库模式)

### Additional Information(附加信息)

[ffmpeg-transcode-76fde7a2-2520-404b-97e7-b2c588eb4e81_1.txt](https://github.com/user-attachments/files/17902174/ffmpeg-transcode-76fde7a2-2520-404b-97e7-b2c588eb4e81_1.txt)
![image](https://github.com/user-attachments/assets/412fb0f5-3135-4fed-bfb4-7c4b50ccdfd8)

**Comment by gitbobobo** [comment]
emby的转码有问题，检查是否安装ffmpeg，或用docker部署emby

**Comment by LINKlang** [comment]
ffmpeg emby默认调用自己的，暂时没找到办法让emby调用系统环境变量里的ffmpeg

**Comment by gitbobobo** [comment]
总之这个不属于音流的问题，建议用docker部署emby
