### ISSUE TITLE
车机上安装音流显示的名字是stream music，而不是中文的音流，是车机问题还是什么问题？

### ISSUE THREAD

**Issue by kqwkn** [gitbobobo/StreamMusic#715]
### Steps to reproduce(重现步骤)

首先非常感谢作者能提供这么优秀的app。我用音流连接家里NAS上的Navidrome音乐库，非常爽，刚买了台车子，吉利星愿，可以安装APP，我通过官方的方式安装好后显示的是英文名字stream music，而不是中文的音流，不是太方便通过语音来打开，不知道是是车机问题还是哪里问题，希望可以帮忙排查解决问题，万分感谢！

### Expected results(预期结果)

1

### Actual results(实际结果)

1

### Server Type(服务器类型)

Navidrome

### Server Version(服务器版本)

Navidrome 0.52.5

### Client Version(客户端版本)

1.3.2

### Operating System(操作系统)

Android

### Connection Type(连接类型)

Library Mode(媒体库模式)

### Additional Information(附加信息)

首先非常感谢作者能提供这么优秀的app。我用音流连接家里NAS上的Navidrome音乐库，非常爽，刚买了台车子，吉利星愿，可以安装APP，我通过官方的方式安装好后显示的是英文名字stream music，而不是中文的音流，不是太方便通过语音来打开，不知道是是车机问题还是哪里问题，希望可以帮忙排查解决问题，万分感谢！

**Comment by gitbobobo** [comment]
应用名称是跟随系统语言显示的

**Comment by kqwkn** [comment]
关键是车机系统确实是中文，魅族那个什么flyme auto，还有我安装其他app也可以显示中文，所以问问，感谢回复，估计还是车机这边问题



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月26日 14:21 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [gitbobobo/StreamMusic] 车机上安装音流显示的名字是stream music，而不是中文的音流，是车机问题还是什么问题？ (Issue #715) |

应用名称是跟随系统语言显示的
