### ISSUE TITLE
ios 1.3.3 flac格式无法播放

### ISSUE THREAD

**Issue by zeno980** [gitbobobo/StreamMusic#717]
### Steps to reproduce(重现步骤)

IOS18 音流1.3.3 版本 搭配navidrome，mp3格式正常播放，flac无法播放，但其他数据都能加载出来，包括封面等

### Expected results(预期结果)

正常播放

### Actual results(实际结果)

元数据加载正常，但无法播放，进度条一直为0

### Server Type(服务器类型)

Navidrome

### Server Version(服务器版本)

0.53.3

### Client Version(客户端版本)

1.3.3

### Operating System(操作系统)

iOS

### Connection Type(连接类型)

Direct Mode(直连模式)

**Comment by gitbobobo** [comment]
请提供测试账号，正常来说不会有这个问题
