### ISSUE TITLE
网络问题

### ISSUE THREAD

**Issue by 1368129224** [gitbobobo/StreamMusic#720]
### Steps to reproduce(重现步骤)

浏览器能够正常访问navidrome和jellyfin，但是在Windows客户端中无法连接，配置代理后也无法链接
![Snipaste_2024-11-27_11-18-26](https://github.com/user-attachments/assets/a07c9f64-9c5b-42f9-8bf6-188bfbd6eebc)

### Expected results(预期结果)

能够正常连接

### Actual results(实际结果)

不能链接

### Server Type(服务器类型)

Navidrome, Jellyfin

### Server Version(服务器版本)

Navidrome:0.53.3 (13af8ed4)/Jellyfin: 10.10.3

### Client Version(客户端版本)

windows1.3.3

### Operating System(操作系统)

Windows

### Connection Type(连接类型)

Direct Mode(直连模式)

**Comment by 1368129224** [comment]
补充：通过浏览器使用该代理，可以正常使用navidrome和jellyfin

**Comment by gitbobobo** [comment]
需要开启tun模式，否则无法代理音流的部分请求
