### ISSUE TITLE
希望在ios端中添加小组件功能

### ISSUE THREAD

**Issue by KatoMegumii** [gitbobobo/StreamMusic#726]
### Suggestion(建议)

希望尽快在ios端中添加小组件功能，安卓那边早就有了，我为了避免苹果抽成专门用安卓购买的会员，理直气壮催更

**Comment by gitbobobo** [comment]
桌面小组件已于1.3.2推出，若你的系统无法显示，可能是系统版本问题导致的

**Comment by KatoMegumii** [comment]
能麻烦适配ios17.0吗，舍不得15pm的巨魔，绝唱了
