### ISSUE TITLE
希望PC端可选缓存位置，或者自动下载每一首播放的歌

### ISSUE THREAD

**Issue by KatoMegumii** [gitbobobo/StreamMusic#728]
### Suggestion(建议)

手机上直接把缓存拉满就能把听过的歌都下载了，但电脑上缓存默认在c盘，下载选项也不能选下载每一首播放的歌

**Comment by gitbobobo** [comment]
下载可以批量下载，目前没有觉得下载每一首播放过的歌曲有什么特别的用处

**Comment by KatoMegumii** [comment]
反复缓存大容量歌曲很耗流量，又不想缓存拉满占太多c盘

**Comment by gitbobobo** [comment]
不想缓存，完全可以用下载功能解决。
