### ISSUE TITLE
emby服务器不显示歌词

### ISSUE THREAD

**Issue by mysll** [gitbobobo/StreamMusic#73]
使用emby服务器,安卓手机.emby客户端能正常显示歌词,音流里提示没有歌词
emby客户端
![微信图片_20231107145436](https://github.com/gitbobobo/StreamMusic/assets/3783323/f4365e50-68c8-4ef8-aa4a-818ef782110f)
音流客户端
![微信图片_20231107145440](https://github.com/gitbobobo/StreamMusic/assets/3783323/fed0d140-be1c-4816-9939-c3c65325d9d5)

**Comment by gitbobobo** [comment]
试试先在emby服务器上获取到歌词，然后在音流刷新下数据，再看下有没有歌词。

现在没走获取歌词的接口，而是直接读取的歌曲信息里的歌词，可能是这个原因导致的。你试下如果这样操作之后音流是否能显示歌词

**Comment by mysll** [comment]
> 试试先在emby服务器上获取到歌词，然后在音流刷新下数据，再看下有没有歌词。
> 
> 现在没走获取歌词的接口，而是直接读取的歌曲信息里的歌词，可能是这个原因导致的。你试下如果这样操作之后音流是否能显示歌词

是说要把歌词嵌入到音乐文件中么?我现在的歌词是单独的文件

**Comment by gitbobobo** [comment]
不是嵌入，不确定emby是不是可以在线搜索歌词

**Comment by gitbobobo** [comment]
1.2.2已支持
