### ISSUE TITLE
缓存的歌曲为什么名称是乱码的? 希望缓存时根据歌曲的实际名称进行缓存

### ISSUE THREAD

**Issue by dengshenkk** [gitbobobo/StreamMusic#730]
### Steps to reproduce(重现步骤)

设置了缓存,在线听歌后缓存的歌曲名称变成 navidrome_1732863898508_af59677d4696708d8e56b25639351e8f.flac  去缓存路径里面可以找到这个文件, 但是名称是错乱的啊

<img width="1154" alt="image" src="https://github.com/user-attachments/assets/d2751be2-bb49-46a7-adf7-ade76cd39643">

### Expected results(预期结果)

缓存和实际的名称一致

### Actual results(实际结果)

歌曲名称变成 navidrome_1732863898508_af59677d4696708d8e56b25639351e8f.flac

### Server Type(服务器类型)

Navidrome

### Server Version(服务器版本)

1.0.0

### Client Version(客户端版本)

版本1.3.3 (104)

### Operating System(操作系统)

macOS

### Connection Type(连接类型)

Library Mode(媒体库模式)

**Comment by gitbobobo** [comment]
缓存的目的是让app去读取的，如需保持原文件名，需要使用下载功能

**Comment by dengshenkk** [comment]
哦, 下载是付费功能
