### ISSUE TITLE
存储占用大且无法清理

### ISSUE THREAD

**Issue by iLovEing** [gitbobobo/StreamMusic#733]
### Steps to reproduce(重现步骤)

iphone14， ios18.1.1，后台开zerotier，使用app串流nas navidrome服务， 正常使用app一段时间

### Expected results(预期结果)

1. 手机温度正常
2. 存储占用可控且可以正常清理

### Actual results(实际结果)

1. 关于发热
清空后台，重启手机只使用app，灭屏状态+蓝牙连接听歌，一段时间后手机明显感觉发烫。如果边充电边听，也是灭屏状态，一段时间后会出现高温无法充电提示。
3. 关于存储
系统显示其他数据占用高，且无法清理，具体如图：
![97067c825fc9d746741920753de596a](https://github.com/user-attachments/assets/1494a39c-1f5b-4b19-aa0a-318c68150cec)
我的关于存储的设置：
![9c6315477a09164fe681701dbfcd3dc](https://github.com/user-attachments/assets/95012fe4-35bb-4b2b-81d7-e9cf4af298f2)

### Server Type(服务器类型)

Navidrome

### Server Version(服务器版本)

latest

### Client Version(客户端版本)

latest

### Operating System(操作系统)

iOS

### Connection Type(连接类型)

Direct Mode(直连模式)

### Additional Information(附加信息)

这两个问题困扰我很厉害，有需要可以安装debug版本，提供日志。

**Comment by iLovEing** [comment]
nas为威联通，Navidrome服务的基本信息：
![image](https://github.com/user-attachments/assets/d06cbf41-1aa4-4178-9055-52f933f5d338)

**Comment by gitbobobo** [comment]
如果曲库较大，建议使用直连模式，不然会把服务端的数据完全同步到本地数据库，存储空间自然就会很大
