### ISSUE TITLE
新增全局快捷键控制和全局歌词显示

### ISSUE THREAD

**Issue by Aftnos** [gitbobobo/StreamMusic#737]
### Suggestion(建议)

新增
1.全局快捷键控制
2.全局歌词显示

### Usage scenario or reason(使用场景或原因)

1.可以在其他任意工作中快速切歌
2.可以托盘软件后仍然看到歌词
更像音乐软件了不是？（bush）

**Comment by gitbobobo** [comment]
已有功能
