### ISSUE TITLE
Android歌词时间错误

### ISSUE THREAD

**Issue by MyEnergyFiled** [gitbobobo/StreamMusic#739]
### Steps to reproduce(重现步骤)

安装最新和前两个一共三个旧版均发现问题，再久远未尝试
歌词未LRC内嵌，查看歌曲详情，时间都被加上了30分钟
iPhone下正常

### Expected results(预期结果)

歌词时间恢复正常

### Actual results(实际结果)

歌词时间错误

### Server Type(服务器类型)

Navidrome

### Server Version(服务器版本)

0.52.5

### Client Version(客户端版本)

1.3.3

### Operating System(操作系统)

Android

### Connection Type(连接类型)

Direct Mode(直连模式), Library Mode(媒体库模式)

**Comment by MyEnergyFiled** [comment]
![android](https://github.com/user-attachments/assets/a9e80e71-93c0-4b31-b653-4b264728c527)
![iphone](https://github.com/user-attachments/assets/c3874719-83a7-49ce-86a1-6fdbbbd1ffa4)

**Comment by gitbobobo** [comment]
软件不可能自动加上歌词偏移，检查下你的歌词来源

**Comment by MyEnergyFiled** [comment]
不好意思说错了，歌词是LRC内嵌，写入到标签中的

**Comment by MyEnergyFiled** [comment]
重新添加资料库也这样错误，删除重新安装后同样问题。所有歌词都有偏移，而且不记得做过调整歌词操作。有没有办法来提取日志查看问题。
![Johnny](https://github.com/user-attachments/assets/36cabdb1-22b7-45ef-b02c-3f0aae08cd41)

**Comment by Austinwenyz** [comment]
subsonic模式下没问题

**Comment by MyEnergyFiled** [comment]
安卓目前使用1.3.5 正常

**Comment by gitbobobo** [comment]
看下你的系统时间和时区，有可能是这里的问题

**Comment by MyEnergyFiled** [comment]
是有手动设置时区。目前使用的自动设置正常。看样子是手动设置的问题

**Comment by wolfling45** [comment]
我也遇到了此问题，一台miui，设置自动时区可以解决，另外一台澎湃os也有此问题，但是这个系统没有自动时区这个选项。。。只能手动，尝试了设置不同时区，均无法解决，版本1.3.5.
