### ISSUE TITLE
希望增加小组件的支持

### ISSUE THREAD

**Issue by wangzan200808** [gitbobobo/StreamMusic#74]
可以增加安卓版本的小组件吗？

**Comment by gitbobobo** [comment]
会增加的

**Comment by cwycool** [comment]
订阅了~ 这个功能很想要~

**Comment by justyeh** [comment]
**强烈需求小组件**
1.3发布后，完成度算是比较高了，就差一个桌面小组件就齐全了

**Comment by justyeh** [comment]
> 快了，等dlna功能修复之后就会开始

订阅支持了一波，qq音乐的小组件样式可以参考一下

**Comment by gitbobobo** [comment]
1.3.2测试版已经添加了播放控制组件，可以先试试看兼容性如何

**Comment by gitbobobo** [comment]
1.3.2 正式版已发布

**Comment by justyeh** [comment]
> 1.3.2 正式版已发布

ios16.6 找不到要添加的小组件

**Comment by gitbobobo** [comment]
可以尝试重启手机，看会不会出现

**Comment by justyeh** [comment]
> 可以尝试重启手机，看会不会出现

重启后依旧找不到小组件
![WechatIMG706](https://github.com/user-attachments/assets/1f217d1b-a760-45e0-bb50-0a79357b8517)
