### ISSUE TITLE
几点优化建议

### ISSUE THREAD

**Issue by zjyg1993** [gitbobobo/StreamMusic#740]
### Suggestion(建议)

目前在用mac客户端，有几点问题可以改进下，
1.每次从正常窗口切换到迷你模式，位置都是不固定的，希望可以记忆上一次的屏幕位置；迷你模式下的关闭按钮，可以换成切换按钮，还以为是关闭软件，容易误解
2.自定义主题色，貌似没有生效，软件自带的毛玻璃效果貌似不是很干净，可以优化下

**Comment by gitbobobo** [comment]
切换到迷你模式，位置就是当前窗口左上角。

主题色在侧边栏有效果的
