### ISSUE TITLE
播放周杰伦新专辑最伟大的作品，会闪退

### ISSUE THREAD

**Issue by sgf2013sdo** [gitbobobo/StreamMusic#741]
### Steps to reproduce(重现步骤)

歌曲信息：周杰伦最伟大作品整个专辑
例如：最伟大的作品
文件大小：161.58MB
文件格式：flac
时长：4:04
比特率：5551kbps

再此专辑里，切换几次歌曲；不切换可正常播放，正常跳转下一首

### Expected results(预期结果)

音流app崩溃，闪退

### Actual results(实际结果)

音流app闪退

### Server Type(服务器类型)

AudioStation

### Server Version(服务器版本)

7.2.0-5516

### Client Version(客户端版本)

1.3.3

### Operating System(操作系统)

Android

### Connection Type(连接类型)

Library Mode(媒体库模式)

**Comment by gitbobobo** [comment]
#682
