### ISSUE TITLE
期望支持Audiobookshelf有声书的支持

### ISSUE THREAD

**Issue by maycyc** [gitbobobo/StreamMusic#744]
### Suggestion(建议)

期望支持Audiobookshelf有声书的支持
自建的Docker服务  没有一款好用的软件适配
同时也购买了有声书架的服务，但是现有的软件只有网页版、plappa、prologue这几款软件，使用起来都差强人意
期待大佬会考虑支持（同时也使用emby创建媒体库再连接音流，但是emby效果不太满意，还是Audiobookshelf这个服务器比较适合有声书

**Comment by gitbobobo** [comment]
Audiobookshelf有什么功能是有声书比较需要的吗？我觉得服务端只要能记录播放进度就挺适合存有声书的了

**Comment by maycyc** [comment]
> Audiobookshelf有什么功能是有声书比较需要的吗？我觉得服务端只要能记录播放进度就挺适合存有声书的了

- 首先，我购买的有声书就类似emby服，它是使用Audiobookshelf创建的服务器，所以只能找支持连接Audiobookshelf的App
- 再有，Audiobookshelf可以类似刮削影视一样去刮削有声书，匹配有声书的信息及封面等等
- 其它...我也说不上为啥用这个服务了，但是对于有声书来说，Audiobookshelf的刮削功能真是好用

**Comment by maycyc** [comment]
https://github.com/user-attachments/assets/8051a694-ea1a-437d-a7c6-15ca5d1a8655

**Comment by maycyc** [comment]
有个录的音流添加的emby有声书，但是视频上传一直报错

**Comment by maycyc** [comment]
音流连接自建emby服务器

**Comment by maycyc** [comment]
https://github.com/user-attachments/assets/a43901f1-0339-4aa7-b96b-2a51d7f9b3dc

Emby的有声读物媒体库排序有问题，也没有好用的刮削功能。

**Comment by maycyc** [comment]
还有官网的Windows开发版本1.3.3.5版本一直无法下载，已经持续好久了。
链接应该是失效了
![image](https://github.com/user-attachments/assets/b5fc1aa3-04c0-4a4a-92b1-f9610c8fe194)

**Comment by CallMe-86** [comment]
> > Audiobookshelf有什么功能是有声书比较需要的吗？我觉得服务端只要能记录播放进度就挺适合存有声书的了
> 
> * 首先，我购买的有声书就类似emby服，它是使用Audiobookshelf创建的服务器，所以只能找支持连接Audiobookshelf的App
> * 再有，Audiobookshelf可以类似刮削影视一样去刮削有声书，匹配有声书的信息及封面等等
> * 其它...我也说不上为啥用这个服务了，但是对于有声书来说，Audiobookshelf的刮削功能真是好用

只能找支持连接Audiobookshelf的App——Audiobookshelf不是有自己的app吗

**Comment by maycyc** [comment]
> 只能找支持连接Audiobookshelf的App——Audiobookshelf不是有自己的app吗


Audiobookshelf还在测试中，体验效果都不太理想

**Comment by gitbobobo** [comment]
从我自己的实线来看，有声书的刮削根本不算大的痛点。

有声书不像音乐一样每首歌曲都需要专门刮削，选好一本有声书，用mp3tag 批量加上艺术家、专辑、标题、音轨号的标签，网上找张这本书的图片，嵌入到它的元数据中，之后放到 emby 也好，navidrome 也好。

音流连接之后按专辑查看，按音轨号排序，就可以很好的听书了。

**Comment by maycyc** [comment]
之前听书只用听书Audiobookshelf服了
现在找到有声书下载网站了，回来自己下载整理下
看来Audiobookshelf协议不是大众需求，issue可以关闭了🫡

**Comment by 1115919577** [comment]
@gitbobobo 现在陆续出来很多提供Audiobookshelf的服务了，不用自己麻烦建emby或navidrome，建议增加Audiobookshelf支持，谢谢。

**Comment by wuleimo** [comment]
> 从我自己的实线来看，有声书的刮削根本不算大的痛点。
> 
> 
> 
> 有声书不像音乐一样每首歌曲都需要专门刮削，选好一本有声书，用mp3tag 批量加上艺术家、专辑、标题、音轨号的标签，网上找张这本书的图片，嵌入到它的元数据中，之后放到 emby 也好，navidrome 也好。
> 
> 
> 
> 音流连接之后按专辑查看，按音轨号排序，就可以很好的听书了。

navidrome能识别有声书嘛？，比如网易云音乐里面的有声书，我只能在网易云下载有声书，而一些下载音频的edge音频插件上都搜不到网易云有声书的音频。
audiobookshelf，它好像直接用文件名称和图片识别，而navidrome是识别音乐的元数据的

**Comment by wolaijiuni** [comment]
> 之前听书只用听书Audiobookshelf服了 现在找到有声书下载网站了，回来自己下载整理下 看来Audiobookshelf协议不是大众需求，issue可以关闭了🫡

老哥 能分享下有声书下载网站吗
