### ISSUE TITLE
大佬考虑优化下对平板以及车机歌词显示的优化吗？

### ISSUE THREAD

**Issue by yylike-code** [gitbobobo/StreamMusic#745]
### Suggestion(建议)

大佬可否设置歌词大小可调？已阅读之前issues里面的回复（会影响ui）。但感觉可以考虑隐藏封面，把歌词置中，这样调整字体大小时就不会影响ui了？
ps:尝试在车机上开启tv模式，在绑定服务器界面使用方向盘按键，无法切换，希望可以加一个按钮。

### Usage scenario or reason(使用场景或原因)

在使用车机听歌中，歌词较小
感谢大佬的付出！

**Comment by braxiong** [comment]
同，本想上来提这个问题，没想到已经有人先发了
不过不知道你的车机是竖板还是横版的，我的竖板，UI非常小，选歌非常不方便，而且播放界面下歌曲封面非常大，感觉占了有60%的界面，剩下一点给歌词显示小小的字  TAT 
二人血书跪求作者优化   QAQ

**Comment by gitbobobo** [comment]
个性化 - 主题 - 歌词 中可设置歌词大小

竖屏就是平板的竖屏界面，目前感觉没有优化空间

**Comment by yylike-code** [comment]
> 个性化 - 主题 - 歌词 中可设置歌词大小
> 
> 竖屏就是平板的竖屏界面，目前感觉没有优化空间

感谢大佬的回复！很惭愧因为没有购买完整版，导致误以为没有该功能。不知道通过主题可不可以同步修改ui的大小。在搜索歌曲或者是加入喜爱歌单的时候，2k屏幕下按钮都比较小。

**Comment by gitbobobo** [comment]
并不能修改UI大小
