### ISSUE TITLE
华为mated  pro使用过程经常闪退

### ISSUE THREAD

**Issue by Jeffwongchina** [gitbobobo/StreamMusic#748]
### Steps to reproduce(重现步骤)

通常在第一首歌完毕后切换第二首歌就闪退

### Expected results(预期结果)

不闪退

### Actual results(实际结果)

不闪退

### Server Type(服务器类型)

Plex

### Server Version(服务器版本)

最新

### Client Version(客户端版本)

最新

### Operating System(操作系统)

Android

### Connection Type(连接类型)

Library Mode(媒体库模式)

**Comment by gitbobobo** [comment]
https://music.aqzscn.cn/docs/problems
