### ISSUE TITLE
linux平台的开发请求

### ISSUE THREAD

**Issue by Hansetar** [gitbobobo/StreamMusic#749]
### Suggestion(建议)

其实三端主流平台都有大厂做了app,但linux平台是真的几乎没有，如果可以的话，开发以下linux端的，适配debian ，arch版本的

**Comment by gitbobobo** [comment]
没有肯定是因为用户量少。

可以先用 feishin 代替

与问题 #503 重复

**Comment by gitbobobo** [comment]
🏷️ **Priority: P0** - 无法播放的基础功能问题，用户反馈详细且复现条件明确。
