### ISSUE TITLE
能否添加安卓手机开启USB独占的功能

### ISSUE THREAD

**Issue by 3031887094** [gitbobobo/StreamMusic#757]
### Suggestion(建议)

因为音流支持播放无损音乐，但是安卓手机自带SRC会自动转码，所以能否添加一下这个功能呢，这样就能很好解决在外播放无损音乐的需求

### Usage scenario or reason(使用场景或原因)

安卓设备

**Comment by gitbobobo** [comment]
与问题 #36 重复
