### ISSUE TITLE
navidrome客户端搜索速度慢

### ISSUE THREAD

**Issue by sjz008** [gitbobobo/StreamMusic#759]
### Steps to reproduce(重现步骤)

我音乐库有7万多首歌曲，用的直连模式，搜索要五六秒返回结果。

### Expected results(预期结果)

网页端的navidrome搜索东西几乎秒开

### Actual results(实际结果)

音流搜索歌曲要五六秒才能返回结果

### Server Type(服务器类型)

Navidrome

### Server Version(服务器版本)

0.53.3

### Client Version(客户端版本)

1.3.3

### Operating System(操作系统)

Android

### Connection Type(连接类型)

Direct Mode(直连模式)

**Comment by gitbobobo** [comment]
音流搜索时不止会搜索歌曲，还会同时搜索专辑和歌手，这可能是导致搜索变慢的原因，耗时其实还是在服务端的处理上
