### ISSUE TITLE
支持增強LRC格式

### ISSUE THREAD

**Issue by San-sec** [gitbobobo/StreamMusic#762]
### Suggestion(建议)

希望大大可以添加**_LRC增强格式_**的支持。。

### Usage scenario or reason(使用场景或原因)

本人使用的FB2K在播放歌曲時會自動搜刮genius，azlyrics等網站的LRC并同時寫入tag，有時搜刮到的是&lt;mm:ss.xx>增强格式的LRC，所以會在SM上遇到無法正確識別的問題。

**Comment by gitbobobo** [comment]
如果你说的是逐字歌词，目前不打算支持。

**Comment by San-sec** [comment]
> 如果你说的是逐字歌词，目前不打算支持。

好叭╮(╯-╰)╭
