### ISSUE TITLE
ARTIST未按照ARTISTSORT排序

### ISSUE THREAD

**Issue by San-sec** [gitbobobo/StreamMusic#763]
### Suggestion(建议)

如題，本人使用mp3tag搜刮，其中ARTISTSORT正常寫入。Navidrome重新讀取后，SM并未按其排序，而是用
![2024-12-21_15-06-06_Mp3tag v3 23  -  XMusic#Pop_#Indie_宇多田ヒカル](https://github.com/user-attachments/assets/55b714ef-8d9f-4323-80c0-1c03a0261255)
ARTIST排序。

### Usage scenario or reason(使用场景或原因)

NAVIDROME VERSION : v0.53.2(3910e77a)
SM VERSION : 1.2.8

**Comment by gitbobobo** [comment]
没见过用这个字段的，而且这同样是服务端的工作，客户端无法处理
