### ISSUE TITLE
multi-value fields suppport

### ISSUE THREAD

**Issue by San-sec** [gitbobobo/StreamMusic#764]
### Suggestion(建议)

如題，希望可以支持多個tag

想法來源:
https://community.mp3tag.de/t/how-to-separate-multiple-artist/52232/10

### Usage scenario or reason(使用场景或原因)

![2024-12-21_16-02-58_Mp3tag v3 23  -  XMusicQobuzHarlem YuHarlem No 1 G](https://github.com/user-attachments/assets/8399bca4-2811-45c3-bded-f03da893d47b)

**Comment by gitbobobo** [comment]
音流不负责组织元数据，这些信息都来自服务端，也就是说你的服务端支持，音流就支持
