### ISSUE TITLE
wire guard下使用公网，转码判断（流量/WiFi）似乎有问题

### ISSUE THREAD

**Issue by tty228** [gitbobobo/StreamMusic#85]
客户端：安卓1.1.7
服务端：Navidrome 0.50 on OpenWrt 二进制文件运行

公网下听歌，开启了流量下转码，但是在进程中没有看到 ffmpeg，打开 WiFi 下转码的话，是可以看到进程的
从流量消耗上也能看到不太正常
作者有时间的话测试一下看看能不能复现，如果没有 wire guard 环境的话，需要什么日志我再提供一下
![IMG_20231121_002705](https://github.com/gitbobobo/StreamMusic/assets/33397881/4d301dad-bc53-4adf-8c89-0b167a40d14f)
![Screenshot_2023-11-21-00-21-07-33_94747945fb87ce2cf0fa6ae879e973c4](https://github.com/gitbobobo/StreamMusic/assets/33397881/711a42a9-0001-4f1e-bdc5-f0b316f1861b)

**Comment by gitbobobo** [comment]
wire guard是VPN？VPN目前是会识别为Wi-Fi网络

**Comment by tty228** [comment]
嗯，是 VPN
