### ISSUE TITLE
连续播放5、6首歌曲后就停止播放

### ISSUE THREAD

**Issue by victorli-cn** [gitbobobo/StreamMusic#86]
版本：ios TestFlight 1.1.7

**Comment by WYithal** [comment]
同有这个问题，要大退重进才正常，还有就是经常主备线路无限切换卡死

**Comment by gitbobobo** [comment]
1.2.8已更换新的播放插件，可以再看看这样的问题还会不会出现。

**Comment by WYithal** [comment]
> 1.2.8已更换新的播放插件，可以再看看这样的问题还会不会出现。

用了2天多，没有这个问题了
