### ISSUE TITLE
navidrome智能歌单排序错误

### ISSUE THREAD

**Issue by AshinLin** [gitbobobo/StreamMusic#89]
**服务端：navidrome[0.49.3]**
**客户端：安卓1.1.7**

**在navidrome建立智能歌单，比如最多播放.nsp：**
{
  "all": [
    {"gt": {"playcount": 0}}
  ],
  "sort": "playcount",
  "order": "desc",
  "limit": 100
}
**在网页端正常按播放次数排序**
![image](https://github.com/gitbobobo/StreamMusic/assets/13843885/77218c0d-c120-4746-9de7-4db050e1b057)
**但在音流APP中为倒序**
![817ec95def20070bc6683eca98e7bec](https://github.com/gitbobobo/StreamMusic/assets/13843885/491cb4b5-ae5a-44f0-af6f-65b8f333eed7)

**Comment by gitbobobo** [comment]
右上角改下排序方式看看是否可以，目前不确定是否能识别出智能歌单和普通歌单的区别，默认还是按添加时间倒序排列的

**Comment by AshinLin** [comment]
> 右上角改下排序方式看看是否可以，目前不确定是否能识别出智能歌单和普通歌单的区别，默认还是按添加时间倒序排列的

手动排序可以，能按navidrome默认排序就更好了
