### ISSUE TITLE
专辑内每个歌曲因为服务端改名原因全部重复一遍

### ISSUE THREAD

**Issue by ranlychan** [gitbobobo/StreamMusic#91]
系统：android
客户端版本：1.1.7
服务器程序与版本：Jellyfin 10.8.12
问题描述：与服务器同步以后，某个专辑内的所有单曲全部重复了一遍，Jellyfin网页端显示只有有16首，但音流app显示有32首。此外，多出来的一部分虽然可以点进去但无法正常播放，进度条静止。
截图：
![b15da19805fcb31e8c8f41d5ffcca55](https://github.com/gitbobobo/StreamMusic/assets/56482592/e93be558-574c-4127-b4aa-803a36f2d77e)
![2eb5782dde1368336d839636f2249b6](https://github.com/gitbobobo/StreamMusic/assets/56482592/39303cd6-a9d4-4bdb-a762-3d1dcb3f19d3)
![1701002237829](https://github.com/gitbobobo/StreamMusic/assets/56482592/a3a0dc51-ae80-4dff-a926-01214401306a)

**Comment by ranlychan** [comment]
问题补充：此前服务端有相似专辑，两个专辑内有同名音乐，但两个专辑互换名字后，音流app再次同步时无法识别此操作，从而出现上述重复单曲问题。

**Comment by gitbobobo** [comment]
试试手动同步数据后可以恢复吗

**Comment by ranlychan** [comment]
> 试试手动同步数据后可以恢复吗
无法恢复

**Comment by gitbobobo** [comment]
那可能就是服务器上有数据残留，手动同步数据会把旧的数据删掉的。

方便的话可以提供个测试账号，发到我邮箱aqzscn@qq.com，我看看怎么回事
