### ISSUE TITLE
建议和反馈

### ISSUE THREAD

**Issue by cfandora** [gitbobobo/StreamMusic#95]
开门见山，直接说吧：

服务端：Navidrome
客户端平台：Android

### 转码格式

舍弃早就被淘汰的mp3，替换成低码率模式下编码效益最高的opus，Navidrome支持这种编码的转码。

### 服务端在国外的情况

日常直接使用浏览器访问自带的webui听歌的话问题不大，但使用音流的时候(特别是WSA上，手机上最近比较稳定了)，不管是直连还是代理，不管是原文件还是开了转码，经常性的一首歌只缓冲前几秒，播完这几秒后音流再次尝试缓冲，尝试了几秒就变成暂停状态，就不做任何缓冲的尝试了。

### WSA才有的问题

在WSA上经常是封面缓存好了以后，过几天再打开，封面又丢失了，但存储空间占用还在，必须删了才能重新缓存
另外，WSA上流畅度也比手机低很多(因为win端目前确实找不到好用的客户端，只能用这个)

### 播放列表加载这一块不稳定

同样也是服务器在国外，虽然库的加载在手机上比较正常了，但播放列表的加载通常很慢甚至加载不出来(都是Navidrome的智能列表)

**Comment by happyTonakai** [comment]
似乎不支持opus，我的库全是opus，几乎不能正常播放……

**Comment by gitbobobo** [comment]
1.2.8已支持opus转码
