### ISSUE TITLE
专辑功能无法使用

### ISSUE THREAD

**Issue by dayvight** [gitbobobo/StreamMusic#96]
音流的专辑功能显示暂无数据
使用的服务端是Emby
![IMG_0390](https://github.com/gitbobobo/StreamMusic/assets/69447314/70fd981f-2231-402c-9bfc-d859e0771285)
![IMG_0391](https://github.com/gitbobobo/StreamMusic/assets/69447314/8898004b-2ed6-426a-bc5c-24d3afbebe81)

**Comment by gitbobobo** [comment]
1.10这个问题应该解决了，可以试试手动同步下数据

**Comment by dayvight** [comment]
使用的是1.10版本，手动同步了依旧是暂无数据，emby版本是4.7.14.0

**Comment by gitbobobo** [comment]
1.2.2初步处理了艺术家名下找不到专辑的问题，但目前还存在一些问题

音流目前和Navidrome的艺术家处理逻辑是一致的，即只支持一个专辑艺术家，这会导致在支持多艺术家的音乐服务上，只有第一个艺术家会拥有这个专辑/歌曲，之后的艺术家则查询不到这个专辑/歌曲
