### ISSUE TITLE
通过quick connect id 在公网上无法登录audio station

### ISSUE THREAD

**Issue by MentorDonald** [gitbobobo/StreamMusic#98]
排除是nas或服务端问题，群晖自带的audio station 能登陆。
1.19版本，安卓/鸿蒙4.0

**Comment by MentorDonald** [comment]
1.10

**Comment by twister3344** [comment]
最后是怎么解决的呀？我最近把ddns关了，改用quickconnect，群晖的app都能正常登录，包括DS audio，但是在音流上用qc登录失败，提示请检查网络或者账号密码是否正确。

**Comment by twister3344** [comment]
> 如果还无法登录，可以邮箱或加群私发我一个测试账号，我看看什么原因
冒昧问下  怎么加群
