### ISSUE TITLE
可以增加http的basic auth认证功能吗

### ISSUE THREAD

**Issue by YosenFree** [gitbobobo/StreamMusic#99]
我的音乐库服务是内网穿透的，为了安全起见，内网服务都加了个http的basic 鉴权，需要鉴权才能使用服务，否则访问就会401。大佬可否考虑加上一个auth的账号密码的全局设置，仅设置一次就行，保存在客户端，后续的请求头都带上。

我想很多人都是自拓管在本地的音乐库，目前app已经非常好用和美观了，期待大佬能添加，感谢！！！

**Comment by gitbobobo** [comment]
我感觉大部分人自己部署之后不会设置鉴权吧，反正我是没有。。
